client/javascripts/app.js
client/stylesheets/app.scss
lib/transport_web/templates/layout/_navigation.html.eex
lib/transport_web/templates/layout/app.html.eex
lib/transport_web/templates/page/index.html.eex
test/transport_web/controllers/page_controller_test.exs

Use main tag for elm

---

client/tests/TransportTest.elm

Format multiline comment properly

---

.circleci/Dockerfile
.circleci/config.yml

Continuous Delivery on Heroku

---

.editorconfig
.eslintignore
client/javascripts/app.js
client/javascripts/components/map/map.js
client/javascripts/components/map/map.tag
client/javascripts/components/organization/organization-search.tag
client/javascripts/components/organization/organization.tag
client/package.json
client/stylesheets/_transitional.scss
client/stylesheets/app.scss
client/stylesheets/components/_map.scss
client/stylesheets/components/_organization.scss
client/webpack.config.js
client/yarn.lock
lib/transport_web/controllers/page_controller.ex
lib/transport_web/controllers/session_controller.ex
lib/transport_web/router.ex
lib/transport_web/templates/page/index.html.eex
lib/transport_web/templates/page/search_organizations.html.eex
test/transport_web/controllers/page_controller_test.exs

Add organization search prototype

---

Procfile
client/package.json
client/yarn.lock
compile
config/prod.exs
elixir_buildpack.config
lib/transport_web/router.ex
mix.exs
phoenix_static_buildpack.config

Fixes #20 
**Definition of done:**

Deploy to heroku

---

priv/static/json/datasets.json

Add shortlist of transport datasets

---

.circleci/config.yml
config/dev.exs
lib/transport_web/router.ex
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/fr/LC_MESSAGES/default.po
test/transport_web/solutions/login_test.exs

Set french as default language

---

priv/static/json/datasets.json

Add logo to datasets.json

---

priv/static/json/datasets.json

Add spatial in datasets.json

---

client/javascripts/components/map/map.tag
client/stylesheets/components/_map.scss

To add consistency with the rest of components.

Add simpler map component syntax

---

client/javascripts/components/map/map.js
client/javascripts/components/map/map.tag
client/stylesheets/_mixins.scss
client/stylesheets/_variables.scss
client/stylesheets/app.scss
client/stylesheets/components/_map.scss
client/stylesheets/contexts/_landing.scss
client/webpack.config.js
lib/transport_web/templates/page/index.html.eex
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/fr/LC_MESSAGES/default.po
test/transport_web/solutions/reuse_data_test.exs

Let reuse data in landing page

---

client/javascripts/components/shortlist/shortlist.tag
client/stylesheets/_variables.scss
client/stylesheets/components/_shortlist.scss
client/stylesheets/contexts/_landing.scss
lib/transport_web/controllers/page_controller.ex
lib/transport_web/router.ex
lib/transport_web/templates/page/index.html.eex
lib/transport_web/templates/page/shortlist.html.eex
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/fr/LC_MESSAGES/default.po
test/transport_web/controllers/page_controller_test.exs
test/transport_web/solutions/reuse_data_test.exs

Partial solution for #22 
Preview:

Add front shortlist

---

client/stylesheets/contexts/_landing.scss
lib/transport_web/templates/page/index.html.eex
test/transport_web/solutions/login_test.exs
test/transport_web/solutions/reuse_data_test.exs

Better landing button handling

---

.circleci/config.yml
client/stylesheets/components/_shortlist.scss

Fix CircleCI deployment

---

client/stylesheets/_base.scss
client/stylesheets/_mixins.scss
client/stylesheets/components/_list.scss
client/stylesheets/components/_logo.scss
client/stylesheets/components/_navigation.scss
client/stylesheets/layouts/_footer.scss
client/stylesheets/layouts/_header.scss
client/webpack.config.js
lib/transport_web/templates/page/login.html.eex
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/fr/LC_MESSAGES/default.po
test/transport_web/solutions/login_test.exs

Explain the log in / sign up process

---

lib/transport_web/controllers/session_controller.ex
test/fixture/cassettes/session/create-2.json
test/transport_web/controllers/page_controller_test.exs
test/transport_web/controllers/session_controller_test.exs

Redirect to /user/organizations after login

---

lib/transport/datagouvfr/client.ex
lib/transport_web/controllers/user_controller.ex
lib/transport_web/router.ex
lib/transport_web/templates/user/add_badge_dataset.html.eex
lib/transport_web/templates/user/organization_datasets.html.eex
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/fr/LC_MESSAGES/default.po

Add a GTFS tag to a dataset

---

lib/transport_web/controllers/user_controller.ex
lib/transport_web/templates/user/add_badge_dataset.html.eex
lib/transport_web/templates/user/organization_datasets.html.eex
lib/transport_web/templates/user/organizations.html.eex
priv/gettext/alert.pot
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/alert.po
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/en/LC_MESSAGES/user.po
priv/gettext/fr/LC_MESSAGES/alert.po
priv/gettext/fr/LC_MESSAGES/default.po
priv/gettext/fr/LC_MESSAGES/user.po
priv/gettext/user.pot

Add domain to user translations

---

client/stylesheets/base/_buttons.scss
client/stylesheets/base/_layout.scss
client/stylesheets/base/_typography.scss

Add data.gouv.fr base style

---

.circleci/Dockerfile
.circleci/config.yml
lib/transport/data_validator/server.ex
lib/transport_web/controllers/user_controller.ex
mix.exs
mix.lock
test/transport/data_validator/server_test.exs

We need to add a backend compatibility to be able to ask for the status of a task.

Add celery compatibility

---

lib/transport_web/controllers/session_controller.ex
priv/gettext/alert.pot
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/alert.po
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/fr/LC_MESSAGES/alert.po

Add domain to alert translations

---

lib/transport_web/templates/layout/_footer.html.eex
lib/transport_web/templates/layout/_header.html.eex
lib/transport_web/templates/layout/app.html.eex
lib/transport_web/templates/page/index.html.eex
lib/transport_web/templates/page/login.html.eex
lib/transport_web/templates/page/shortlist.html.eex
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/en/LC_MESSAGES/page-index.po
priv/gettext/en/LC_MESSAGES/page-login.po
priv/gettext/en/LC_MESSAGES/page-shortlist.po
priv/gettext/fr/LC_MESSAGES/default.po
priv/gettext/fr/LC_MESSAGES/page-index.po
priv/gettext/fr/LC_MESSAGES/page-login.po
priv/gettext/fr/LC_MESSAGES/page-shortlist.po
priv/gettext/page-index.pot
priv/gettext/page-login.pot
priv/gettext/page-shortlist.pot

Add domain to page translations

---

client/stylesheets/base/_typography.scss

Add heading font-size

---

client/stylesheets/_states.scss
client/stylesheets/app.scss
client/stylesheets/base/_buttons.scss
client/stylesheets/base/_layout.scss
client/stylesheets/components/_header.scss
client/stylesheets/components/_message.scss
client/stylesheets/components/_navigation.scss
client/stylesheets/globals/_variables.scss
client/stylesheets/layouts/_container.scss

partial_fix #76
Before:
After:

Update theme colours

---

config/staging.exs

Add staging environment

---

client/package.json
client/stylesheets/base/_typography.scss
client/stylesheets/components/_cards.scss
client/stylesheets/components/_footer.scss
client/stylesheets/components/_header.scss
client/stylesheets/components/_hero.scss
client/stylesheets/components/_list.scss
client/stylesheets/components/_map.scss
client/stylesheets/components/_shortlist.scss
client/stylesheets/globals/_externals.scss
client/stylesheets/globals/_mixins.scss
client/stylesheets/layouts/_column.scss
client/stylesheets/layouts/_container.scss
client/yarn.lock
lib/transport_web/templates/user/organizations.html.eex

Add css grid

---

client/javascripts/components/footer/footer-help.tag
client/stylesheets/base/_form.scss
client/stylesheets/components/_footer-help.scss
client/stylesheets/globals/_variables.scss
config/config.exs
config/mailgun.exs
lib/transport/mailgun/client.ex
lib/transport_web.ex
lib/transport_web/controllers/contact_controller.ex
lib/transport_web/router.ex
lib/transport_web/templates/layout/_footer.html.eex
lib/transport_web/templates/layout/app.html.eex
lib/transport_web/views/contact_view.ex
priv/gettext/alert.pot
priv/gettext/en/LC_MESSAGES/alert.po
priv/gettext/fr/LC_MESSAGES/alert.po
test/transport_web/solutions/contact_test.exs

We add a contact button on every page
When you click the button a messaging box appears:
When you click the button a email is sent to contact@transport.beta.gouv.fr, and you're informed about it.
Then it goes back to normal.
fixes #99

Add contact form

---

client/stylesheets/components/_cards.scss

Fix img card size

---

client/stylesheets/components/_dataset-details.scss
client/stylesheets/components/_documentation.scss
client/stylesheets/components/_shortlist.scss
lib/transport/reusable_data/dataset.ex
lib/transport/reusable_data/reusable_data.ex
lib/transport_web/controllers/dataset_controller.ex
lib/transport_web/router.ex
lib/transport_web/templates/dataset/details.html.eex
lib/transport_web/templates/dataset/index.html.eex
priv/gettext/alert.pot
priv/gettext/en/LC_MESSAGES/alert.po
priv/gettext/en/LC_MESSAGES/page-dataset-details.po
priv/gettext/en/LC_MESSAGES/page-shortlist.po
priv/gettext/fr/LC_MESSAGES/alert.po
priv/gettext/fr/LC_MESSAGES/default.po
priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
priv/gettext/fr/LC_MESSAGES/page-shortlist.po
priv/gettext/page-dataset-details.pot
priv/gettext/page-shortlist.pot

partial_fix #26 
partial_fix #112 
Discussions:

Dataset page

---

client/javascripts/components/discussions/discussions.tag
client/stylesheets/components/_discussions.scss
lib/transport_web/templates/dataset/details.html.eex
priv/gettext/alert.pot
priv/gettext/en/LC_MESSAGES/alert.po
priv/gettext/en/LC_MESSAGES/page-dataset-details.po
priv/gettext/fr/LC_MESSAGES/alert.po
priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
priv/gettext/page-dataset-details.pot

partial_fix #112 
The post comment button was always activated.

Fix not connected discussions

---

lib/transport_web/controllers/page_controller.ex
lib/transport_web/controllers/session_controller.ex
lib/transport_web/router.ex
lib/transport_web/templates/layout/_header.html.eex
lib/transport_web/views/layout_view.ex
priv/gettext/en/LC_MESSAGES/page-dataset-details.po
priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
priv/gettext/page-dataset-details.pot
test/transport_web/controllers/session_controller_test.exs
test/transport_web/controllers/user_controller_test.exs
test/transport_web/integrations/login_test.exs

partial_fix #44
You are now redirected to the page you were previously visiting.

Redirect to previous page after login

---

lib/transport/datagouvfr/client/organizations.ex
lib/transport_web/controllers/user_controller.ex
lib/transport_web/router.ex
lib/transport_web/templates/user/organization_datasets.html.eex
lib/transport_web/templates/user/organization_form.html.eex
lib/transport_web/templates/user/organizations.html.eex
priv/gettext/alert.pot
priv/gettext/en/LC_MESSAGES/alert.po
priv/gettext/en/LC_MESSAGES/organization-form.po
priv/gettext/en/LC_MESSAGES/user.po
priv/gettext/fr/LC_MESSAGES/alert.po
priv/gettext/fr/LC_MESSAGES/organization-form.po
priv/gettext/fr/LC_MESSAGES/user.po
priv/gettext/user.pot
test/fixture/cassettes/user/organization-create-4.json
test/fixture/cassettes/user/user-without-organization-3.json
test/transport_web/controllers/user_controller_test.exs

If you don't have an organisation yet when you click on "Open my data" you'll be directly redirected to the organisation form.
If you already have an organisation you'll see a button above the organisation list
The organisation form : 
partial_fix #44

Allow AOs to create their organisation

---

lib/transport_web/controllers/page_controller.ex
lib/transport_web/controllers/session_controller.ex
priv/gettext/en/LC_MESSAGES/user.po
priv/gettext/fr/LC_MESSAGES/user.po
priv/gettext/user.pot
test/transport_web/controllers/session_controller_test.exs
test/transport_web/integration/login_test.exs

Whitelist user attributes

---

lib/transport/datagouvfr/client.ex

Set data.gouv.fr client connection timepout to 15s

---

lib/transport_web/templates/layout/_footer.html.eex
lib/transport_web/templates/layout/_header.html.eex
lib/transport_web/templates/layout/app.html.eex
lib/transport_web/templates/page/index.html.eex
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/en/LC_MESSAGES/page-index.po
priv/gettext/fr/LC_MESSAGES/default.po
priv/gettext/fr/LC_MESSAGES/page-index.po
priv/gettext/page-index.pot
test/fixture/cassettes/session/create-2.json
test/transport_web/solutions/reuse_data_test.exs

en fait votre fwk est bizarre, le même texte est présent dans plusieurs fichiers ... je crains de ne pas intervenir au(x ??) bon endroit.

Change transport.beta.gouv.fr to transport.data.gouv.fr

---

client/javascripts/components/map/map.js
client/webpack.config.js
test/transport_web/solutions/reuse_data_test.exs

Fix double marker issue

---

priv/gettext/fr/LC_MESSAGES/page-index.po

Change wording on data publishing

---

lib/transport/datagouvfr/authentication.ex
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/fr/LC_MESSAGES/default.po

Update login timeout

---

lib/transport/reusable_data/dataset.ex
lib/transport/reusable_data/licence.ex
lib/transport/reusable_data/reusable_data.ex
lib/transport_web/templates/dataset/details.html.eex
lib/transport_web/templates/dataset/index.html.eex
lib/transport_web/views/dataset_view.ex
test/transport/reusable_data/reusable_data_test.exs
test/transport_web/api/controllers/dataset_controller_test.exs
test/transport_web/solutions/reuse_data_test.exs

Filter not validated and invalid datasets

---

lib/transport/reusable_data/dataset.ex
lib/transport/reusable_data/reusable_data.ex
lib/transport_web/api/serializers/dataset_serializer.ex
lib/transport_web/controllers/dataset_controller.ex
test/transport/reusable_data/reusable_data_test.exs
test/transport_web/api/controllers/dataset_controller_test.exs
test/transport_web/solutions/reuse_data_test.exs

https://github.com/etalab/transport-validator/pull/4 needs to be merge
before

Use validations of datasets object

---

client/javascripts/components/validation/validation.tag
client/stylesheets/components/_validation.scss
lib/transport/reusable_data/dataset.ex
lib/transport/validation/validation.ex
lib/transport_web/api/controllers/dataset_controller.ex
lib/transport_web/api/views/dataset_view.ex
lib/transport_web/router.ex
lib/transport_web/templates/dataset/details.html.eex
priv/gettext/alert.pot
priv/gettext/en/LC_MESSAGES/alert.po
priv/gettext/en/LC_MESSAGES/page-dataset-details.po
priv/gettext/en/LC_MESSAGES/reusable_data.po
priv/gettext/en/LC_MESSAGES/validations.po
priv/gettext/fr/LC_MESSAGES/alert.po
priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
priv/gettext/fr/LC_MESSAGES/reusable_data.po
priv/gettext/fr/LC_MESSAGES/validations.po
priv/gettext/page-dataset-details.pot
priv/gettext/reusable_data.pot
priv/gettext/validations.pot

Add validation messages to dataset details

---

.circleci/config.yml
lib/mix/tasks/transport/validate_data.ex
lib/transport/validation/validation.ex
lib/transport_web/api/controllers/dataset_controller.ex
test/support/database_case.ex
test/support/external_case.ex
test/support/user_facing_case.ex
test/test_helper.exs
test/transport/data_improvement/repositories/dataset_repository_test.exs
test/transport/data_validator/celery_task_test.exs
test/transport/data_validator/server_test.exs
test/transport/datagouvfr/client/datasets_test.exs
test/transport/datagouvfr/client/organizations_test.exs
test/transport/datagouvfr/client_test.exs
test/transport/reusable_data/reusable_data_test.exs
test/transport_web/api/controllers/dataset_controller_test.exs
test/transport_web/controllers/dataset_controller_test.exs
test/transport_web/controllers/page_controller_test.exs
test/transport_web/controllers/session_controller_test.exs
test/transport_web/controllers/user_controller_test.exs
test/transport_web/integrations/contact_test.exs
test/transport_web/integrations/login_test.exs
test/transport_web/solutions/data_reuse/using_list_test.exs
test/transport_web/solutions/data_reuse/using_map_test.exs
test/transport_web/solutions/data_sharing_test.exs
test/transport_web/solutions/login_test.exs
test/transport_web/views/error_view_test.exs
test/transport_web/views/layout_view_test.exs
test/transport_web/views/page_view_test.exs

Apparently, some tests are failing due to concurrency issues.

Fix failing tests on CircleCI

---

lib/transport/reusable_data/dataset.ex

This can happen when validations is not set yet.

Fix lib/transport/reusable_data/dataset.ex:assign

---

lib/transport/datagouvfr/client/resources.ex

Add organization to community resources

---

client/javascripts/components/community_resources/community_resources.tag
client/stylesheets/components/_community-resources.scss
lib/transport_web/templates/dataset/details.html.eex
priv/gettext/dataset.pot
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/dataset.po
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/en/LC_MESSAGES/page-dataset-details.po
priv/gettext/en/LC_MESSAGES/page-shortlist.po
priv/gettext/fr/LC_MESSAGES/dataset.po
priv/gettext/fr/LC_MESSAGES/default.po
priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
priv/gettext/fr/LC_MESSAGES/page-shortlist.po
priv/gettext/page-dataset-details.pot
priv/gettext/page-shortlist.pot

Add community resources to dataset details

---

client/javascripts/components/community_resources/community_resources.tag
lib/transport/reusable_data/reusable_data.ex
lib/transport_web/templates/dataset/details.html.eex
priv/gettext/en/LC_MESSAGES/page-dataset-details.po
priv/gettext/en/LC_MESSAGES/page-shortlist.po
priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
priv/gettext/fr/LC_MESSAGES/page-shortlist.po
priv/gettext/page-dataset-details.pot
priv/gettext/page-shortlist.pot

Add a text when there is no community resources

---

lib/transport/datagouvfr/client.ex
lib/transport_web/controllers/session_controller.ex
lib/transport_web/router.ex

there is a lot of private values in here.
It might be exposed during a failure.

Remove client from assigns

---

client/javascripts/components/discussions/discussions.tag

Add connection needed information on discussions

---

lib/transport/import_data_service.ex

Fetch logo at organization.logo_thumbnail

---

priv/gettext/fr/LC_MESSAGES/page-dataset-details.po

Fix speling mistake

---

lib/transport_web/templates/dataset/details.html.eex
lib/transport_web/templates/dataset/index.html.eex
priv/gettext/en/LC_MESSAGES/page-dataset-details.po
priv/gettext/en/LC_MESSAGES/page-shortlist.po
priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
priv/gettext/fr/LC_MESSAGES/page-shortlist.po
priv/gettext/page-dataset-details.pot
priv/gettext/page-shortlist.pot

Do not display territory badge when there is no territory

---

lib/transport/import_data_service.ex

Add "Fichier" in possible CSV headers for udata

---

client/javascripts/components/dataset-followers/dataset-followers.tag
client/stylesheets/base/_buttons.scss
lib/transport/datagouvfr/client.ex
lib/transport/datagouvfr/client/datasets.ex
lib/transport/reusable_data/reusable_data.ex
lib/transport_web/api/controllers/follower_controller.ex
lib/transport_web/api/views/discussion_view.ex
lib/transport_web/api/views/follower_view.ex
lib/transport_web/api/views/json_view.ex
lib/transport_web/router.ex
lib/transport_web/templates/dataset/details.html.eex
priv/gettext/alert.pot
priv/gettext/dataset.pot
priv/gettext/en/LC_MESSAGES/alert.po
priv/gettext/en/LC_MESSAGES/dataset.po
priv/gettext/en/LC_MESSAGES/page-dataset-details.po
priv/gettext/en/LC_MESSAGES/page-index.po
priv/gettext/en/LC_MESSAGES/page-shortlist.po
priv/gettext/fr/LC_MESSAGES/alert.po
priv/gettext/fr/LC_MESSAGES/dataset.po
priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
priv/gettext/fr/LC_MESSAGES/page-shortlist.po
priv/gettext/page-dataset-details.pot
priv/gettext/page-shortlist.pot
test/transport_web/solutions/data_reuse/using_list_test.exs
test/transport_web/solutions/data_reuse/using_map_test.exs

The page that show the details of a dataset now has this button
When you click on it you will receive notifications about this dataset, and then you'll have the possibility to unsubscribe:
fix #198

Add subscription button

---

lib/mix/tasks/transport/import_data.ex
lib/transport/import_data_service.ex
lib/transport/reusable_data/reusable_data.ex
priv/repo/datasets.json

Update curated list of datasets

---

lib/transport/datagouvfr/client/datasets.ex
priv/gettext/dataset.pot
priv/gettext/en/LC_MESSAGES/dataset.po
priv/gettext/fr/LC_MESSAGES/dataset.po
test/fixture/cassettes/client/datasets/organization-datasets-6.json
test/transport/datagouvfr/client/datasets_test.exs

Add compatibility with new datagouv API

---

client/javascripts/components/map/map.js

Center the map on France by default

---

client/stylesheets/components/_header.scss
lib/transport/datagouvfr/client/user.ex
lib/transport_web/controllers/session_controller.ex
lib/transport_web/templates/layout/_header.html.eex
priv/gettext/default.pot
test/transport_web/views/avatar_view_test.exs

Show username

---

priv/repo/datasets.json

Didn't change the ```catalogue_id```, I imagine it won't work automatically ?

Update GTFS Angers and Royan + AOM in Open License

---

README.md

Reset should be run before seed.

Fix mix task order

---

priv/repo/datasets.json

Fix changed slug of STAN network (Nancy)

---

.circleci/config.yml
lib/transport/import_data_service.ex

What do you think ? @Tristramg

Import data on deploy

---

priv/repo/datasets.json

Fix IRIGO and Transpole

---

lib/transport/import_data_service.ex

Give a log on importing status, and error logs when something fails.

Improve import data task logs

---

.circleci/config.yml
README.md
config/datagouvfr.exs
config/test.exs
lib/transport/import_data_service.ex
lib/transport/reusable_data/dataset.ex
priv/repo/datasets.json
test/test_helper.exs
test/transport/import_data_service_test.exs

This we'll help us to be extremely reactive to changes on datagouv's datasets.

Check external links on CircleCI before deployment

---

lib/transport/import_data_service.ex
priv/repo/datasets.json

Fix import of cara'bus network

---

lib/transport/import_data_service.ex
priv/repo/datasets.json

Log when dataset download uri not found

---

README.md
lib/mix/tasks/transport/fetch_validation_results.ex
lib/mix/tasks/transport/validate_data.ex
lib/transport/data_validation/aggregates/feed_source.ex
lib/transport/data_validation/aggregates/feed_version.ex
lib/transport/data_validation/aggregates/project.ex
lib/transport/data_validation/data_validation.ex
lib/transport/data_validation/queries/find_feed_version.ex
lib/transport/data_validation/queries/list_feed_sources.ex
lib/transport/data_validation/repository/feed_source_repository.ex
lib/transport/data_validation/repository/feed_version_repository.ex
lib/transport/datagouvfr/client.ex
priv/repo/datasets.json
test/fixture/cassettes/data_validation/find_feed_version-ok.json
test/fixture/cassettes/data_validation/list_feed_sources-ok.json
test/transport/data_validation/data_validation_test.exs
test/transport/data_validation/queries/find_feed_source_version.exs
test/transport/data_validation/queries/list_feed_sources_test.exs

Validate with datatools

---

test/fixture/cassettes/data_validation/find_project-not_found.json
test/transport/data_validation/aggregates/project_test.exs
test/transport/data_validation/repository/project_repository_test.exs

Add project repository tests

---

client/javascripts/components/validation/catalogueerrors.tag

Use https for catalogue

---

priv/repo/datasets.json

Add datasets

---

client/stylesheets/components/_mailing-list.scss
lib/transport_web/templates/page/index.html.eex
priv/gettext/en/LC_MESSAGES/page-index.po
priv/gettext/fr/LC_MESSAGES/page-index.po
priv/gettext/page-index.pot

Add link to connect to slack

---

.circleci/config.yml

Let CircleCI provide mongo and phantom for CI

---

mix.exs

Fix faker start error

---

.circleci/config.yml
lib/transport/data_validation/data_validation.ex
lib/transport/data_validation/repository/feed_version_repository.ex
test/transport/data_validation/data_validation_test.exs

Connected to #184 
Depends on etalab/transport-ops#5

Add integration testing for data validation

---

.circleci/config.yml

This was accidentaly removed in f8132f6cd781

Fix deployment to heroku by Circle-Ci

---

priv/repo/datasets.json

Test which GTFS will appear...

Add Le Mans

---

lib/transport/reusable_data/dataset.ex
lib/transport/reusable_data/reusable_data.ex
lib/transport_web/templates/dataset/details.html.eex
priv/gettext/en/LC_MESSAGES/page-dataset-details.po
priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
priv/gettext/page-dataset-details.pot

Present validation results in front

---

lib/transport_web/templates/dataset/details.html.eex
priv/gettext/en/LC_MESSAGES/page-shortlist.po
priv/gettext/fr/LC_MESSAGES/page-shortlist.po
priv/gettext/page-shortlist.pot

Make download more visible

---

.circleci/config.yml

On n’utilisait pas le cache nécessairement comme prévu https://discuss.circleci.com/t/saving-cache-stopped-working-warning-skipping-this-step-disabled-in-configuration/24423/17
J’en profite pour refactorer et simplifier

Circleci: use workspaces instead of cache

---

lib/transport_web/templates/page/faq.html.eex

Ajustement de la FAQ (exemple ODbL)

---

client/stylesheets/main.scss
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/en/LC_MESSAGES/reusable_data.po
priv/gettext/fr/LC_MESSAGES/default.po
priv/gettext/fr/LC_MESSAGES/reusable_data.po
priv/gettext/reusable_data.pot

fix wrong navigation class

---

lib/transport_web/templates/page/index.html.eex

Correct typo

---

lib/transport/reusable_data/dataset.ex
lib/transport_web/api/controllers/stats_controller.ex
lib/transport_web/controllers/stats_controller.ex
lib/transport_web/templates/stats/index.html.eex

Ajout de 3 cartes de statistiques

More stats please

---

lib/transport_web/controllers/backoffice_controller.ex
lib/transport_web/router.ex
lib/transport_web/templates/backoffice/index.html.eex
priv/gettext/alert.pot
priv/gettext/backoffice.pot
priv/gettext/en/LC_MESSAGES/alert.po
priv/gettext/en/LC_MESSAGES/backoffice.po
priv/gettext/fr/LC_MESSAGES/alert.po
priv/gettext/fr/LC_MESSAGES/backoffice.po

Add delete dataset

---

.gitignore
lib/transport_web/templates/dataset/_description_transport-statique.html.eex
lib/transport_web/templates/dataset/_sidebar_common.html.eex
lib/transport_web/templates/dataset/_sidebar_transport-statique.html.eex
lib/transport_web/templates/dataset/details.html.eex
lib/transport_web/views/dataset_view.ex
priv/gettext/backoffice.pot
priv/gettext/en/LC_MESSAGES/backoffice.po
priv/gettext/en/LC_MESSAGES/page-dataset-details.po
priv/gettext/en/LC_MESSAGES/page-shortlist.po
priv/gettext/fr/LC_MESSAGES/backoffice.po
priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
priv/gettext/fr/LC_MESSAGES/page-shortlist.po
priv/gettext/page-dataset-details.pot
priv/gettext/page-shortlist.pot

Template type dataset

---

lib/transport_web/templates/page/index.html.eex

Rework landing page

---

lib/transport_web.ex
lib/transport_web/controllers/backoffice_controller.ex
lib/transport_web/templates/backoffice/_dataset.html.eex
lib/transport_web/templates/backoffice/_form_dataset.html.eex
lib/transport_web/templates/backoffice/index.html.eex
lib/transport_web/templates/dataset/index.html.eex
lib/transport_web/templates/page/index.html.eex
lib/transport_web/views/input_helpers.ex
priv/gettext/backoffice.pot
priv/gettext/en/LC_MESSAGES/backoffice.po
priv/gettext/en/LC_MESSAGES/page-index.po
priv/gettext/en/LC_MESSAGES/page-shortlist.po
priv/gettext/fr/LC_MESSAGES/backoffice.po
priv/gettext/fr/LC_MESSAGES/page-index.po
priv/gettext/fr/LC_MESSAGES/page-shortlist.po
priv/gettext/page-index.pot
priv/gettext/page-shortlist.pot

Ajoute aussi des fonctions pour faire des templates compatibles avec template.data.gouv.fr
fixes #406

Add search backoffice

---

client/javascripts/components/footer/footer-help.tag
client/stylesheets/components/_footer-help.scss
client/stylesheets/components/_icons.scss

Rends plus visible le bouton de fermeture du formulaire de contact

---

lib/transport_web/controllers/stats_controller.ex
lib/transport_web/templates/stats/index.html.eex

Ajoute cette carte à la page /stats
fixes #405

Ajout stat population couverte

---

lib/transport_web/templates/page/index.html.eex

Retravail de quelques phrases pour réduire la taille des textes

Small rework landing page

---

lib/transport_web/templates/stats/index.html.eex

Ça donne ça: 
C'est pas encore terrible, mais c'est mieux qu'avant.

Fix affichage des stats

---

lib/transport/import_data_service.ex

Meilleure "détection" du GTFS

---

lib/transport/mailjet/client.ex
lib/transport_web/controllers/contact_controller.ex
lib/transport_web/templates/layout/_footer.html.eex
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/fr/LC_MESSAGES/default.po

Add topic to contact email

---

lib/transport_web/templates/dataset/details.html.eex
priv/gettext/en/LC_MESSAGES/page-dataset-details.po
priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
priv/gettext/page-dataset-details.pot

Fix text starting new discussion

---

lib/transport/dataset.ex
lib/transport_web/controllers/dataset_controller.ex
test/transport_web/solutions/data_reuse/using_list_test.exs

Redirection quand un seul résultat

---

client/javascripts/map.js
lib/transport/aom.ex
lib/transport_web/api/controllers/stats_controller.ex
lib/transport_web/controllers/stats_controller.ex
priv/repo/migrations/20181204093045_add_included_in_dataset_to_datasets.exs

Included in datasets

---

lib/transport_web/controllers/backoffice_controller.ex
priv/gettext/backoffice.pot
priv/gettext/en/LC_MESSAGES/backoffice.po
priv/gettext/fr/LC_MESSAGES/backoffice.po

Ajout référentiel points d'arrêts

---

lib/transport_web/controllers/backoffice_controller.ex
lib/transport_web/templates/backoffice/_dataset.html.eex
lib/transport_web/views/backoffice_view.ex

Add link to dataset on backoffice

---

lib/transport/datagouvfr/client/datasets.ex
lib/transport/dataset.ex
lib/transport_web/controllers/backoffice_controller.ex

Ça ne fonctionnait pas lorsque l'adresse finissait par un #

Fix extract slug

---

lib/transport/commune.ex
priv/repo/migrations/20181210164424_insee_aom_table.exs

Ajout des communes

---

lib/transport_web/api/controllers/aom_controller.ex
lib/transport_web/router.ex

Allow to search aom by insee code

---

lib/transport_web/api/controllers/aom_controller.ex
lib/transport_web/api/views/aom_view.ex
lib/transport_web/router.ex
priv/repo/migrations/20181204093045_add_included_in_dataset_to_datasets.exs
priv/repo/migrations/20181205134354_aom_postgis_geometry.exs
priv/repo/migrations/20181205164605_migrate_validations.exs
priv/repo/migrations/20181210164424_insee_aom_table.exs
priv/repo/migrations/20181212091910_commune_to_aom.exs

Export aom as geojson

---

config/datagouvfr.exs
config/mailjet.exs
config/staging.exs
config/test.exs
lib/datagouvfr.ex
lib/datagouvfr/authentication.ex
lib/datagouvfr/client.ex
lib/datagouvfr/client/datasets.ex
lib/datagouvfr/client/discussions.ex
lib/datagouvfr/client/user.ex
lib/mailjet.ex
lib/mailjet/client.ex
lib/transport/import_data_service.ex
lib/transport/partner.ex
lib/transport_web/controllers/backoffice_controller.ex
lib/transport_web/controllers/contact_controller.ex
lib/transport_web/controllers/dataset_controller.ex
lib/transport_web/controllers/discussion_controller.ex
lib/transport_web/controllers/follower_controller.ex
lib/transport_web/controllers/session_controller.ex
lib/transport_web/templates/dataset/details.html.eex
test/datagouvfr/client/datasets_test.exs
test/datagouvfr/client/discussions_test.exs

Pour mieux respecter les standards elixir et rendre le tout plus idiomatique

Move mailjet datagouvfr

---

lib/transport_web/controllers/backoffice_controller.ex

Il y a eu un problème de résolution de conflit …

Fix validation

---

lib/transport/dataset.ex
lib/transport_web/templates/dataset/_sidebar_transport-statique.html.eex
test/transport/dataset_test.exs

Fix add national

---

config/config.exs

Enable tags in markdown

---

priv/static/demo_rt.html

need https://github.com/etalab/transpo-rt/pull/54

update to the new transpo_rt routes

---

lib/transport/resource.ex

Only try to validate GTFS files

---

priv/repo/migrations/20190130145745_rename_transit_types.exs

Migrate dataset types enum in database

---

config/prod.exs
lib/transport/import_data.ex
lib/transport_web/controllers/backoffice/dataset_controller.ex
test/transport/import_data_doc_test.exs
test/transport/import_data_service.exs
test/transport/import_data_service_doc_test.exs

There are three things here.
* A Rename of `ImportDataService` to `ImportData` since it's not a service 
* Every day we import & validate (we were just importing before).
* To avoid problems we are replacing every resources

Fix import validate

---

config/config.exs
config/prod.exs
lib/datagouvfr/client/datasets.ex
lib/transport/helpers.ex
lib/transport/import_data.ex
lib/transport_web/templates/layout/_header.html.eex
test/transport/helpers.exs

Use resource’s filename as title if it isn’t set

---

lib/transport_web/router.ex
lib/transport_web/templates/error/internal_server_error.html.eex
lib/transport_web/views/error_view.ex
priv/gettext/en/LC_MESSAGES/errors.po
priv/gettext/errors.pot
priv/gettext/fr/LC_MESSAGES/errors.po

Render 404 when the template is not found

---

lib/transport/dataset.ex
lib/transport_web/controllers/discussion_controller.ex
lib/transport_web/templates/backoffice/page/_dataset.html.eex
lib/transport_web/templates/dataset/details.html.eex
lib/transport_web/templates/dataset/index.html.eex
lib/transport_web/views/backoffice/page_view.ex

Fix discussions

---

lib/transport_web/views/dataset_view.ex

Fix datasets/regions pagination

---

lib/transport/dataset.ex
lib/transport_web/controllers/dataset_controller.ex
lib/transport_web/controllers/pagination_helpers.ex
lib/transport_web/templates/dataset/index.html.eex
lib/transport_web/views/dataset_view.ex
priv/gettext/en/LC_MESSAGES/page-shortlist.po
priv/gettext/fr/LC_MESSAGES/page-shortlist.po
priv/gettext/page-shortlist.pot

Add ordering on results 
fix #622

Add ordering in datasets

---

lib/transport_web/controllers/atom_controller.ex
lib/transport_web/templates/atom/index.html.eex
lib/transport_web/templates/atom/index.xml.eex

Improve atom

---

lib/transport/dataset.ex
lib/transport_web/controllers/backoffice/page_controller.ex
lib/transport_web/controllers/dataset_controller.ex
lib/transport_web/templates/dataset/index.html.eex
lib/transport_web/views/dataset_view.ex
priv/gettext/en/LC_MESSAGES/page-shortlist.po
priv/gettext/fr/LC_MESSAGES/page-shortlist.po
priv/gettext/page-shortlist.pot

Add filter per type menu on /datasets

---

lib/transport/dataset.ex
lib/transport_web/controllers/dataset_controller.ex

Empty search

---

lib/datagouvfr/client.ex
lib/datagouvfr/client/reuses.ex
lib/transport_web/controllers/dataset_controller.ex
lib/transport_web/templates/dataset/details.html.eex
priv/gettext/en/LC_MESSAGES/page-dataset-details.po
priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
priv/gettext/page-dataset-details.pot

Adds section in details of dataset this is quite ugly, but this page needs a complete rewrite

Show reuse

---

lib/transport_web/controllers/backoffice/page_controller.ex
lib/transport_web/templates/backoffice/page/_dataset.html.eex
lib/transport_web/views/backoffice/page_view.ex
lib/transport_web/views/dataset_view.ex

A dataset is considered outdated if the max end_date of its resources is outdated

Fix outdated

---

lib/transport/dataset.ex
lib/transport_web/controllers/backoffice/dataset_controller.ex
lib/transport_web/controllers/backoffice/page_controller.ex
lib/transport_web/router.ex
lib/transport_web/templates/backoffice/page/_dataset.html.eex
lib/transport_web/templates/backoffice/page/_form_dataset.html.eex
lib/transport_web/templates/backoffice/page/index.html.eex
priv/gettext/backoffice.pot
priv/gettext/backoffice_dataset.pot
priv/gettext/dataset.pot
priv/gettext/en/LC_MESSAGES/backoffice.po
priv/gettext/en/LC_MESSAGES/backoffice_dataset.po
priv/gettext/en/LC_MESSAGES/dataset.po
priv/gettext/fr/LC_MESSAGES/backoffice.po
priv/gettext/fr/LC_MESSAGES/backoffice_dataset.po
priv/gettext/fr/LC_MESSAGES/dataset.po
test/transport/dataset_test.exs
test/transport_web/controllers/backoffice_controller_test.exs

Adds a edit button in /backoffice

Dataset edition

---

Dockerfile.dev
README.md
docker-compose.yml
restore_db.sh

@thimy can you try this out branch ?

Add docker-compose to make development easier

---

lib/transport_web/controllers/atom_controller.ex

It now takes between 300 and 700 ms to load

Do not load validations for /atom.xml

---

.circleci/config.yml
README.md
config/test.exs

PhantomJS is now deprecated, we had a bugs, so we move to selenium
instead

Use selenium instead of phantomjs

---

.circleci/config.yml
client/stylesheets/components/_pagination.scss
client/stylesheets/components/_shortlist.scss
client/stylesheets/globals/_mixins.scss
client/stylesheets/home.scss
client/stylesheets/main.scss
lib/transport_web/templates/dataset/index.html.eex
lib/transport_web/templates/page/index.html.eex
priv/gettext/fr/LC_MESSAGES/page-shortlist.po
test/transport_web/solutions/data_reuse/using_list_test.exs

Improve dataset list for a minimalist and more consistent look.

Rework results page

---

config/prod.exs
lib/mailjet/client.ex
lib/transport/data_checker.ex
lib/transport/resource.ex
lib/transport_web/controllers/contact_controller.ex

That will notice us on expiring data every day.

Send email expiring data

---

client/stylesheets/components/_validation.scss
lib/transport/validation.ex
lib/transport_web/controllers/resource_controller.ex
lib/transport_web/templates/resource/details.html.eex
lib/transport_web/views/resource_view.ex
priv/gettext/en/LC_MESSAGES/page-index.po
priv/gettext/en/LC_MESSAGES/page-shortlist.po
priv/gettext/en/LC_MESSAGES/validations.po
priv/gettext/fr/LC_MESSAGES/page-index.po
priv/gettext/fr/LC_MESSAGES/validations.po
priv/gettext/page-index.pot
priv/gettext/page-shortlist.pot
priv/gettext/validations.pot

Group the issues labels

---

lib/transport_web/templates/resource/_coordinates_issue.html.eex
lib/transport_web/templates/resource/_duplicate_stops_issue.html.eex
lib/transport_web/templates/resource/_extra_file_issue.html.eex
lib/transport_web/templates/resource/_generic_issue.html.eex
lib/transport_web/templates/resource/_missing_file_issue.html.eex
lib/transport_web/templates/resource/_speed_issue.html.eex
lib/transport_web/templates/resource/_unused_stop_issue.html.eex
lib/transport_web/templates/resource/details.html.eex
lib/transport_web/views/resource_view.ex
priv/gettext/en/LC_MESSAGES/page-dataset-details.po
priv/gettext/en/LC_MESSAGES/validations-explanations.po
priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
priv/gettext/fr/LC_MESSAGES/validations-explanations.po
priv/gettext/page-dataset-details.pot
priv/gettext/validations-explanations.pot

https://screenshots.firefox.com/67jPi0kJEILlWFT0/localhost
Pour les détails longs, j’ai préféré utiliser des clefs et mettre le texte en anglais dans le .po. Il y aura bien trop de fautes, ça évitera de se planter.
Le dispatch pourrait être un peu plus magique, mais je me dis que c’est finalement pas plus mal d’être explicite.

Rework validation details

---

lib/transport/aom.ex
lib/transport/dataset.ex
lib/transport/region.ex
priv/repo/migrations/20190506153738_add_dataset_document.exs

Add a search_vector and feed it with triggers...
The code is simpler in the elixir part, and is faster this way.

Search region directly

---

priv/repo/migrations/20190516142725_search_commune.exs

Lines to look at are 28 to 34.

Search per commune

---

Dockerfile.dev
apps/gbfs/lib/gbfs/controllers/velomagg_controller.ex

small updates after validating feeds with https://gbfs-validator.netlify.com/

nest status in 'feeds' and add last reported

---

apps/transport/lib/transport_web/templates/validation/index.html.eex
apps/transport/lib/transport_web/templates/validation/show.html.eex
apps/transport/lib/transport_web/views/validation_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/validations.pot

Noicer validation

---

apps/gbfs/config/config.exs
apps/gbfs/lib/gbfs/controllers/jcdecaux_controller.ex
apps/gbfs/lib/gbfs/controllers/toulouse_controller.ex
apps/gbfs/lib/gbfs/router.ex
apps/gbfs/lib/gbfs/views/error_view.ex
config/config.exs

with the precious help of @antoine-de

Add jcdecaux controller

---

apps/transport/lib/transport_web/templates/layout/_footer.html.eex
apps/transport/lib/transport_web/templates/page/guide.html.md
apps/transport/priv/gettext/default.pot
apps/transport/priv/gettext/en/LC_MESSAGES/default.po
apps/transport/priv/gettext/fr/LC_MESSAGES/default.po

Add a link to the validation tool

---

apps/transport/lib/transport_web/views/backoffice/page_view.ex

Fix pagination in backoffice when querying

---

apps/transport/lib/transport_web/templates/layout/_footer.html.eex
apps/transport/lib/transport_web/templates/validation/index.html.eex
apps/transport/lib/transport_web/templates/validation/show.html.eex
apps/transport/priv/gettext/default.pot
apps/transport/priv/gettext/en/LC_MESSAGES/default.po
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/default.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/validations.pot

fixes https://github.com/etalab/transport-site/issues/750
par contre j'ai pas fixé l'alignement de https://github.com/etalab/transport-site/issues/750#issuecomment-503503408 car ça dépasse mes compétences :stuck_out_tongue_winking_eye:

minor change of wording

---

apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/templates/dataset/index.html.eex
apps/transport/lib/transport_web/templates/layout/_footer.html.eex
apps/transport/priv/gettext/default.pot
apps/transport/priv/gettext/en/LC_MESSAGES/default.po
apps/transport/priv/gettext/en/LC_MESSAGES/page-shortlist.po
apps/transport/priv/gettext/fr/LC_MESSAGES/default.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-shortlist.po
apps/transport/priv/gettext/page-shortlist.pot

Add realtime links

---

apps/transport/priv/static/demo_rt.html

Rework demo rt

---

apps/transport/lib/opendatasoft/url_extractor.ex
apps/transport/lib/transport/import_data.ex

Déjà on va y voir un peu plus clair…

ImportData: move opendatasoft logic somewhere else

---

apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
apps/transport/lib/transport_web/templates/backoffice/page/index.html.eex

add the start of the validity period, the type of the dataset ('public-transport', 'bike-sharing', ...) and the format of the resource

 add some fields to the api

---

apps/gbfs/lib/gbfs/controllers/jcdecaux_controller.ex
apps/gbfs/lib/gbfs/controllers/vcub_controller.ex

add the station capacity for jcdecaux and vcub (it was already done for smoove)

GBFS: add capacity

---

apps/transport/lib/transport/dataset.ex
apps/transport/priv/gettext/dataset.pot
apps/transport/priv/gettext/en/LC_MESSAGES/dataset.po
apps/transport/priv/gettext/fr/LC_MESSAGES/dataset.po

I did not know whether to put `train` or `long-distance-train` since I don't know the extend of what we'll put in this category
closes #784

add a train category

---

apps/transport/lib/transport_web/templates/layout/_footer.html.eex
apps/transport/lib/transport_web/templates/layout/_header.html.eex
apps/transport/lib/transport_web/templates/page/index.html.eex
apps/transport/priv/gettext/default.pot
apps/transport/priv/gettext/en/LC_MESSAGES/default.po
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/default.po

Fix some links on the home page

---

.circleci/config.yml
apps/transport/lib/datagouvfr/client.ex
apps/transport/lib/datagouvfr/client/api.ex
apps/transport/lib/datagouvfr/client/community_resources.ex
apps/transport/lib/datagouvfr/client/datasets.ex
apps/transport/lib/datagouvfr/client/discussions.ex
apps/transport/lib/datagouvfr/client/http_poison.ex
apps/transport/lib/datagouvfr/client/oauth.ex
apps/transport/lib/datagouvfr/client/resources.ex
apps/transport/lib/datagouvfr/client/reuses.ex
apps/transport/lib/datagouvfr/client/user.ex
apps/transport/lib/transport/data_checker.ex
apps/transport/lib/transport/partner.ex
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/controllers/discussion_controller.ex
apps/transport/lib/transport_web/controllers/follower_controller.ex
config/datagouvfr.exs

This push to pre-production platform for testing purposes before pushing it to production
fix #656

Post comment outdated data

---

apps/transport/lib/datagouvfr/client/datasets.ex

that function is used by `TransportWeb.Backoffice.ResourceController.resources_list`

Re-introduce  Datagouvfr.Client.API.get function

---

apps/transport/lib/datagouvfr/client/api.ex
apps/transport/lib/datagouvfr/client/discussions.ex
apps/transport/lib/datagouvfr/client/reuses.ex
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/templates/dataset/details.html.eex

We were displaying a link to the api
fix #811

Display page reuse

---

apps/transport/client/stylesheets/components/_choose_file.scss
apps/transport/lib/datagouvfr/client/oauth.ex
apps/transport/lib/datagouvfr/client/resources.ex
apps/transport/lib/transport_web/controllers/resource_controller.ex
apps/transport/lib/transport_web/templates/resource/choose_file.html.eex
apps/transport/lib/transport_web/views/input_helpers.ex
apps/transport/priv/gettext/en/LC_MESSAGES/resource.po
apps/transport/priv/gettext/fr/LC_MESSAGES/resource.po
apps/transport/priv/gettext/resource.pot

The form might be a bit confusing now. Should I had a step?

Replace file url

---

README.md
apps/transport/client/stylesheets/components/_shortlist.scss
apps/transport/lib/transport/dataset.ex
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/lib/transport_web/templates/dataset/index.html.eex
apps/transport/test/transport_web/solutions/data_reuse/using_list_test.exs

new PR because I cannot change #814 
closes #759

Better dataset title

---

apps/transport/client/stylesheets/components/_dataset-details.scss

Fix dataset logo on chrome

---

apps/transport/lib/transport/dataset.ex
apps/transport/lib/transport/resource.ex
apps/transport/lib/transport_web/controllers/backoffice/dataset_controller.ex

Validate dataset when it's added

---

apps/transport/lib/transport/import_data.ex

We were just importing logo when the user is ana organization, not a
user.
fix #822

Import logo when author is a user

---

apps/transport/lib/transport/resource.ex
apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex

Do not show dataset without end_date as outdated

---

apps/transport/lib/datagouvfr/client.ex
apps/transport/lib/datagouvfr/client/oauth.ex
apps/transport/lib/datagouvfr/client/resources.ex
apps/transport/lib/transport_web/controllers/resource_controller.ex

So the change can be seen immediatly
fix #817

Import dataset after resource upload

---

apps/transport/client/stylesheets/main.scss
apps/transport/lib/transport_web/templates/layout/_header.html.eex

It doesn't change on desktop.
On mobile it was:
Now it looks like:
And when clicked:

Hide by default menu on mobile

---

apps/transport/lib/hasher.ex
apps/transport/lib/http_stream.ex
apps/transport/lib/transport/data_checker.ex
apps/transport/lib/transport/resource.ex
apps/transport/mix.exs
apps/transport/priv/repo/migrations/20190911085235_add_resource_content_hash.exs
mix.lock

J'ai du ajouter une nouvelle librairie parce que hackney (la lib erlang derrière httpoison) a un bug dans un cas étrange qui forcément nous arrivait avec toutes nos URLs...
Les redirects ne sont pas gérés, mais on en a pas pour l'instant !

Add resource sha256

---

apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/lib/transport/dataset.ex
apps/transport/lib/transport/history.ex
apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/mix.exs
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot
config/prod.exs
mix.lock

port https://github.com/etalab/transport-history/ to elixir
add a daily cron job that backup every GTFS/Netex (for the moment) to S3.

Backup cron

---

apps/transport/lib/transport_web/controllers/resource_controller.ex

should fix https://sentry.data.gouv.fr/etalab/site/issues/1859478/

fix sentry 1859478

---

apps/transport/lib/transport_web/templates/page/faq.html.md
apps/transport/lib/transport_web/templates/page/partners.html.md
apps/transport/lib/transport_web/templates/stats/_other.html.md
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/dataset.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-index.po

rename "Aires de covoiturage" to "Lieux de covoiturage"

---

apps/transport/priv/real_time_providers.csv

fix mistake from #861

---

apps/transport/lib/transport/application.ex
apps/transport/lib/transport/search_communes.ex
apps/transport/test/transport/search_communes_test.exs

It will search on normalized names and insee codes

Add search on communes

---

apps/db/lib/db/dataset.ex
apps/transport/lib/transport/search_communes.ex
apps/transport/lib/transport_web/live/commune_field.ex
apps/transport/lib/transport_web/templates/backoffice/page/_form_dataset.html.eex
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po

Add commune search field

---

apps/transport/priv/real_time_providers.csv

for the next departure I'm a bit confused.
There is no link that I can find on opendatasoft.
So the "best" thing I can find is to directly give the url of the webservice, but so there are no explanation.
They have a demo site for their webservices, but I cannot give a precise url for this...
poke @sabinesafi

add bordeaux realtime

---

apps/db/lib/db/dataset.ex
apps/transport/lib/transport_web/templates/dataset/index.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-shortlist.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-shortlist.po
apps/transport/priv/gettext/page-shortlist.pot

Add intercities/cities filter

---

apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
apps/transport/lib/transport_web/api/schemas.ex

It can be usefull for automated interraction with the resources

add the content-hash in the api

---

apps/transport/lib/transport/import_data.ex

for idfm there is a GTFS.pdf that was taken as a GTFS.
check the extension never to import GTFS

Do not import pdf

---

apps/transport/lib/transport_web/controllers/aoms.ex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/aoms/index.html.eex
apps/transport/lib/transport_web/views/aoms_view.ex

This adds (for now hidden) page /aoms to list them all for reporting purpose.
The design is a bit rough for now, but it will allow us to validate the needs.

Add a list off all AOMs for reporting

---

apps/transport/lib/transport_web/templates/layout/app.html.eex

https://www.youtube.com/watch?v=33ovVKiV6e0

Add strike banner

---

apps/transport/lib/transport/import_data.ex

this makes it possible to reference lyon's netex

improve the netex discovery

---

apps/transport/lib/transport_web/controllers/session_controller.ex

This should fix https://sentry.data.gouv.fr/etalab/site/issues/1864762/

fix sentry 36

---

apps/transport/lib/transport_web/templates/layout/_header.html.eex
apps/transport/priv/gettext/default.pot
apps/transport/priv/gettext/en/LC_MESSAGES/default.po
apps/transport/priv/gettext/fr/LC_MESSAGES/default.po

Add a link to the blog in the headers

---

restore_db.sh

now we don't need to be logged as postgres, and the DB is not deleted and recreated

simplify restore_db.sh

---

apps/transport/lib/transport_web/templates/layout/app.html.eex

Reverts of the revert, it's strike day etalab/transport-site#917

Revert "Revert "Add strike banner""

---

apps/transport/lib/transport_web/templates/stats/index.html.eex

fixes #941
Is the wording ok for you @be-mercier?

Change wording of /stats realtime and add link

---

apps/transport/client/javascripts/map.js
apps/transport/client/stylesheets/components/_map.scss
apps/transport/lib/transport_web/controllers/stats_controller.ex
apps/transport/lib/transport_web/templates/stats/_maps.html.eex
apps/transport/lib/transport_web/templates/stats/index.html.eex

Display oversea regions

---

apps/transport/lib/transport_web/templates/layout/app.html.eex

Reverts etalab/transport-site#943

Revert "Revert "Revert "Add strike banner"""

---

apps/transport/client/javascripts/map.js
apps/transport/lib/transport_web/api/controllers/stats_controller.ex

For Public transport we were considering all the datasets...
we for example now have no more datasets on clermont (there is only a bise sharing dataset here)
poke @antoine-martin-ponts

fix wrong base schedule stats

---

apps/transport/lib/transport_web/controllers/aoms.ex

reorder csv column

---

apps/transport/lib/transport_web/templates/aoms/index.html.eex

add missing td

---

apps/transport/client/stylesheets/components/_map.scss

Corrige l'affichage pour petits écrans

---

apps/db/lib/db/dataset.ex
apps/transport/lib/transport_web/controllers/backoffice/dataset_controller.ex

The solution is not perfect, but at least we get a message…

Improve error handling in the backoffice

---

apps/transport/client/images/icons/sorted_asc.svg
apps/transport/client/images/icons/sorted_desc.svg
apps/transport/client/images/icons/unsorted.svg
apps/transport/client/stylesheets/components/_aom_table.scss
apps/transport/lib/transport_web/templates/aoms/index.html.eex

Better aom table

---

apps/transport/client/stylesheets/components/_shortlist.scss
apps/transport/lib/transport_web/templates/dataset/index.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex

close #545 
Note: for review there is a separate commit with the html file formating

Add dataset's type icon on dataset list

---

apps/db/priv/repo/migrations/20200110124026_unaccent.exs

for clever cloud we install them manually

do not install extension if exists

---

apps/db/lib/db/dataset.ex
apps/db/priv/repo/migrations/20200114101848_change_search_conf.exs

else we don't have the permissions to modify 'simple' on clever-cloud

use custom postgres text configuration

---

README.md

small fixes in readme

---

apps/db/lib/db/dataset_geographic_view.ex
apps/db/priv/repo/migrations/20200114143832_add_dataset_view.exs
apps/transport/lib/transport_web/api/controllers/stats_controller.ex
apps/transport/lib/transport_web/controllers/dataset_controller.ex

for the moment the ergonomics are not that better, but it will not
change much when we'll make it possible to associate a Dataset with a
list of geometry.
I did not change the text search query as I think we still want some
custom things for it.

Add a dataset view to ease the geographic association

---

apps/db/lib/db/dataset.ex
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/lib/transport_web/templates/dataset/index.html.eex
apps/transport/lib/transport_web/templates/page/index.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex

Now most filters can be combined.
It is still work in progress, but this PR can be merged already to avoid the next one to be too large.

Improve search logic

---

apps/db/lib/db/dataset.ex
apps/db/lib/db/resource.ex
apps/transport/lib/transport/import_data.ex
apps/transport/lib/transport_web/controllers/aoms.ex
apps/transport/lib/transport_web/controllers/page_controller.ex
apps/transport/lib/transport_web/templates/dataset/_licence.html.eex
apps/transport/lib/transport_web/templates/page/index.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex

Better tiles

---

apps/db/priv/repo/migrations/20200116163306_more_pt.exs

should fix https://sentry.data.gouv.fr/etalab/site/issues/1872558/

no more 'long-distance-coach' or 'train' type, all is 'public-transit'

---

apps/db/lib/db/dataset.ex
apps/db/priv/gettext/dataset.pot
apps/db/priv/gettext/en/LC_MESSAGES/dataset.po
apps/db/priv/gettext/fr/LC_MESSAGES/dataset.po
apps/transport/client/images/icons/addresses.svg
apps/transport/lib/transport_web/templates/page/index.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/priv/gettext/dataset.pot
apps/transport/priv/gettext/en/LC_MESSAGES/dataset.po
apps/transport/priv/gettext/en/LC_MESSAGES/page-index.po
apps/transport/priv/gettext/fr/LC_MESSAGES/dataset.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-index.po
apps/transport/priv/gettext/page-index.pot

closes #928
looks like:
I took the icon from https://feathericons.com/

Add dataset type "Addresses"

---

apps/transport/lib/transport_web/templates/layout/_footer.html.eex

J'imagine que c'est ça le bon lien...à confirmer
closes #1006

fix API broken link

---

apps/transport/priv/gettext/en/LC_MESSAGES/validations-explanations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations-explanations.po

change warning message for extra files in GTFS

---

apps/transport/lib/transport/import_data.ex
apps/transport/lib/transport_web/controllers/backoffice/dataset_controller.ex

This PR contains 2 changes:
* it adds a big catch to display errors instead of a 500.
This is a bit uggly, but this makes it possible to display an error in the backoffice. It's still a very technical error, but it will makes the diagnostic easier:
* change unicity constraint on resource url
before we were using the url of the resource to get it's id. This was done in order to properly update the resource when reimporting an existing dataset.
But this was causing a problem (a 500) when a resource was referenced in 2 different datasets.

better handling of resource url unicity

---

apps/db/lib/db/validation.ex

closes  #1001
Ca faisait longtemps que je ne m'étais pas autant creusé la tête sur une seule ligne de code :smile:

Show by default issues with higher severities

---

apps/transport/client/stylesheets/home.scss
apps/transport/lib/transport_web/templates/page/index.html.eex

closes #973 
I chose a little bouncing and fading chevron, to give a hint but without  staying in the way after.
Let me know what you think about it.
It only appears if the page height is < 910px, because if it's higher you can probably see there is content below.

Add a little bouncing chevron to show there is more below

---

apps/gbfs/lib/gbfs/controllers/index_controller.ex
apps/gbfs/lib/gbfs/controllers/jcdecaux_controller.ex
apps/gbfs/lib/gbfs/controllers/smoove_controller.ex
apps/gbfs/lib/gbfs/controllers/vcub_controller.ex

I only annotated the controllers. Not views, router etc. I’m not sure it’s worth.

Dialyzer: anotate gbfs controllers

---

apps/db/lib/db/resource.ex
apps/db/lib/db/validation.ex
apps/db/priv/gettext/en/LC_MESSAGES/validations.po
apps/db/priv/gettext/fr/LC_MESSAGES/validations.po
apps/db/priv/gettext/validations.pot
apps/transport/client/javascripts/utils.js
apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/client/stylesheets/components/_validation.scss
apps/transport/client/webpack.config.js
apps/transport/lib/transport_web/controllers/pagination_helpers.ex
apps/transport/lib/transport_web/controllers/resource_controller.ex
apps/transport/lib/transport_web/controllers/validation_controller.ex
apps/transport/lib/transport_web/templates/dataset/_resource.html.eex
apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/lib/transport_web/templates/resource/_validation_summary.html.eex
apps/transport/lib/transport_web/templates/resource/details.html.eex
apps/transport/lib/transport_web/templates/validation/show.html.eex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/page-dataset-details.pot
apps/transport/priv/gettext/validations.pot

closes #1018 
Un nouveau look pour la page de présentation d'une ressource.
Ajout des metadatas
nouvelle présentation
Quelques petites corrections de bug au passage (suppression de la pagination quand il n'y a qu'une page, et une string manquante)

Resource page

---

apps/transport/lib/transport_web/templates/stats/index.html.eex

fix car sharing urls

---

apps/db/lib/db/commune.ex
apps/db/lib/db/dataset.ex
apps/db/priv/repo/migrations/20200217142350_add_commune_region.exs
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/router.ex
apps/transport/priv/gettext/en/LC_MESSAGES/errors.po
apps/transport/priv/gettext/errors.pot
apps/transport/priv/gettext/fr/LC_MESSAGES/errors.po

closes #1026 
Add a page for each city at `/datasets/commune/:insee`
This page reference all the dataset linked either directly to this city or to an AO/region covering this city
For the moment this page is not referenced anywhere.
Also add a 404 on `/datasets/region/<unknown_region>`, `/datasets/aom/<unknown_aom>`, `/datasets/commune/<unknown_insee>`

Add commune page

---

apps/transport/lib/transport_web/controllers/dataset_controller.ex

Ma PR #1061 a créé des 404 indues sur les urls du type :
* https://transport.data.gouv.fr/datasets/region/2
* https://transport.data.gouv.fr/datasets/aom/322

fix 404 bug for region and aom urls

---

apps/db/priv/repo/migrations/20200220141013_fuzzystrmatch.exs
apps/transport/lib/transport_web/api/controllers/places_controller.ex
apps/transport/lib/transport_web/api/router.ex
apps/transport/lib/transport_web/api/schemas.ex
apps/transport/lib/transport_web/api/views/places_view.ex
apps/transport/test/support/database_case.ex
apps/transport/test/transport_web/controllers/places_controller_test.exs

je rouvre #1064, j'ai l'impression que sinon github se prend les pieds dans le tapis...
add a /places api
for the moment it is not used, but the plan is to use it in the search bar

Add a /places api for autocomplete on places

---

apps/db/lib/db/dataset.ex

In an AOM page, display the parent dataset

---

apps/db/priv/gettext/dataset.pot
apps/db/priv/gettext/en/LC_MESSAGES/dataset.po
apps/db/priv/gettext/fr/LC_MESSAGES/dataset.po
apps/transport/client/javascripts/dataset-map.js
apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/client/webpack.config.js
apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
apps/transport/lib/transport_web/api/router.ex
apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot

Ajout d'une jolie petite carte sur la page des datasets

---

apps/transport/client/javascripts/map-csv.js
apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex

Ajout d'une carte sur la page dataset de la BNS

---

apps/transport/client/stylesheets/components/_shortlist.scss
apps/transport/client/stylesheets/components/_stats.scss
apps/transport/client/yarn.lock
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/dataset/index.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-index.po
apps/transport/priv/gettext/en/LC_MESSAGES/page-shortlist.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-index.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-shortlist.po
apps/transport/priv/gettext/page-index.pot
apps/transport/priv/gettext/page-shortlist.pot
apps/transport/test/transport_web/controllers/dataset_controller_test.exs
apps/transport/test/transport_web/controllers/dataset_search_test.exs
apps/transport/test/transport_web/solutions/data_reuse/using_list_test.exs

À merger après #1146 et #1147 (ça les contient).
Enlever un peu d'espace blanc, mieux voir quand on est sur la page d'une région / AOM / commune
Avant :
Après :
Avant :
Après :

Résultats de recherche => coup de pinceau

---

apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex

fixes https://sentry.data.gouv.fr/etalab/site/issues/1880127/

fix nil error on dataset without any csv

---

apps/transport/client/javascripts/dataset-map.js
apps/transport/client/javascripts/map-csv.js
apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex

J'ai voulu rajouter une carte au dataset des bornes de stations rechargeables.
/datasets/fichier-consolide-des-bornes-de-recharge-pour-vehicules-electriques/
Ce qui m'a amener à corriger plusieurs choses en passant :
- les "autres ressources" n'étaient pas triées par date, ce qui rendait difficile de repérer les plus récentes.
- il y a une petite erreur dans la ressource (une ligne est décalée d'une colonne). On évite que ça rende la visualisation de tout le fichier impossible.
- nous avions une erreur 500 en appelant l'api pour récuperer le geojson d'un dataset national (il n'y a pas de géométrie en base). On retourne un geojson vide à la place. (exemple : /api/datasets/5448d3e0c751df01f85d0572/geojson)
- quelques modifs dans le code js pour éviter des erreurs potentielles

IRVE map and corrections

---

apps/transport/lib/transport_web/api/controllers/datasets_controller.ex

* display all the datasets in the API, not only the pt
* display the resource metadata when available (this way we can have the
networks, the modes, ...)
* add a `covered_area` section like:
```json
"covered_area": {
"type": "aom",
"name": "CC du Territoire de Lunéville à Baccarat",
"aom": {
"siren": "200070324",
"name": "CC du Territoire de Lunéville à Baccarat"
}
},
```
or
```json
"covered_area": {
"type": "region",
"region": {
"name": "Grand Est"
},
"name": "Grand Est"
},
```
or
```json
"covered_area": {
"type": "country",
"name": "France",
"country": {
"name": "France"
}
```
or for cities
```json
"covered_area": {
"type": "cities",
"name": "Sel et Vermois",
"cities": [
{
"name": "Saint-Nicolas-de-Port",
"insee": "54483"
},
{
"name": "Rosières-aux-Salines",
"insee": "54462"
},
{ …
```

update the API

---

apps/transport/client/stylesheets/components/_backoffice.scss
apps/transport/lib/transport_web/controllers/backoffice/dataset_controller.ex
apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.eex
apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po

ajout d'un lien vers le backoffice depuis la page d'un dataset :
et d'actions dans le backoffice plus facilement accessibles :

Add backoffice actions

---

apps/transport/lib/transport_web/templates/page/real_time.html.md

Fix broken link

---

apps/transport/lib/transport/data_checker.ex

désactivation temporaire des commentaires auto sur la péremption des données

désactivation temporaire des commentaires auto

---

apps/transport/lib/transport_web/api/controllers/datasets_controller.ex

les contours ne s'affichaient plus, sûrement du à un pb de merge

fix geojson

---

apps/transport/lib/transport/import_data.ex
apps/transport/lib/transport/import_data_worker.ex

Aprés le merge je regarderais comment ca remonte dans sentry (et si il y a besoin de plus d'info)

Ajout d'erreur sentry lors de l'import des données

---

apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/templates/dataset/_parkings.html.eex
apps/transport/priv/gettext/en/LC_MESSAGES/page-shortlist.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-shortlist.po
apps/transport/priv/gettext/page-shortlist.pot

Ajout d'un edito pour la stationnement.
Ca donne ca en francais:
en en anglais:
(je pense qu'il faudrait faire une passe sur le design de l'edito, mais on peut séparer le travail)
closes #1185

Ajout d'une section d'editorialisation pour le stationnement

---

apps/db/lib/db/resource.ex
apps/db/priv/repo/migrations/20200616101043_add_resource_filesize.exs
apps/transport/client/javascripts/map-geojson.js
apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/lib/transport/import_data.ex
apps/transport/lib/transport_web/templates/resource/details.html.eex
apps/transport/priv/gettext/en/LC_MESSAGES/page-shortlist.po
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-shortlist.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/page-shortlist.pot
apps/transport/priv/gettext/validations.pot

Si un geojson est trop gros, l'utilisateur doit confirmer qu'il veut le voir. J'ai mis la limite à 2Mo, ça te parait correct ?

Confirm for big geojson display

---

.circleci/config.yml

j'ai espoir que ça puisse accéler notre CI.

change circleCI MIX_ENV variable to use the PLT cache

---

apps/db/lib/db/resource.ex
apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/lib/transport_web/controllers/resource_controller.ex
apps/transport/lib/transport_web/templates/dataset/_resource.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot

il y a 3 états maintenant : 
closes #1213

Ne pas dire que des données sont à jour si on n'a pas de dates

---

apps/db/priv/repo/migrations/20200623112618_import_logs_unlimited_text_length_logs_table.exs

Il y a des erreurs qui ne se font pas logger parce que leur message est trop long.

change varchar(255) to text

---

apps/db/lib/db/logs_validation.ex
apps/db/lib/db/resource.ex
apps/db/priv/repo/migrations/20200623134041_create_validation_logs_table.exs

création d'une table de logs pour les taches de validation.

validation logs table creation

---

apps/db/lib/db/dataset.ex
apps/db/lib/db/resource.ex
apps/transport/client/stylesheets/components/_backoffice.scss
apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.eex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po

Ajout dans le backoffice des imports et des validations faites sur un dataset.

Add backoffice import validation logs

---

apps/transport/lib/transport/log_cleaner.ex
config/prod.exs

On ne garde qu'un mois de log d'import/validation

Nettoyage des anciens log

---

apps/transport/lib/transport_web/views/resource_view.ex

same bug as in the conversion, we could match the associated NeTEx...
And remove the old way of matching a geojson, as all has been regenerated

fix geojson association

---

apps/db/lib/db/resource.ex

fix nil error when no validation

---

apps/db/lib/db/resource.ex
apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/lib/transport_web/templates/dataset/_resources_container.html.eex
apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/lib/transport_web/views/resource_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot

Gtfs real time display category

---

apps/transport/client/yarn.lock

To resolve the security warning concerning serialize-javascript
https://github.com/etalab/transport-site/network/alert/apps/transport/client/yarn.lock/serialize-javascript/open

update yarn lockfile

---

apps/db/lib/db/dataset.ex
apps/db/test/test_db_dataset.ex

Je rajoute quelques tests sur la fonction changeset des datasets.
J'ai aussi fait apparaître dans le code que datagouv_id est attendu dans les clés des paramêtres passés à la fonction.

Add dataset changeset tests

---

apps/gbfs/lib/gbfs/controllers/vlille_controller.ex

J'avais aussi inversé les coordonnées des vlilles...

coordinates inversion

---

apps/db/lib/db/dataset.ex
apps/transport/lib/transport_web/controllers/page_controller.ex
apps/transport/lib/transport_web/templates/page/index.html.eex

Oups j'avais juste mis à jour le lien, mais pas le compteur.

Correct real time count

---

apps/transport/lib/transport_web/api/controllers/datasets_controller.ex

Ajout du champ `page_url` (url de la page transport.data.gouv.fr correspondante) et slug
l'ajout de ces champs va rendre plus simple l'industrialisation autour de l'api (notamment pour le temps réel)

Api: ajout du champ page_url et slug

---

apps/transport/lib/transport_web/templates/stats/index.html.eex

En travaillant sur #1355 j'ai vu cette petite faute de frappe, je corrige.

Correction typo

---

apps/transport/lib/mix/tasks/transport/import_aom.ex

increase the aom integration timeout
seems the prod server is way slower than my machine

Edit aom transaction timeout

---

apps/db/lib/db/dataset.ex
apps/transport/lib/transport_web/controllers/page_controller.ex
apps/transport/lib/transport_web/templates/page/index.html.eex

broken by #1246
I had forgotten there was those filters...
There was a confusion between `features` and `modes`.

repair the count by modes

---

apps/transport/lib/transport_web/controllers/stats_controller.ex

fix realtime count

---

apps/transport/lib/transport_web/controllers/resource_controller.ex
apps/transport/lib/transport_web/templates/error/internal_server_error.html.eex
apps/transport/test/transport_web/controllers/resource_controller_test.exs

J'ai tenté de rajouter des petits tests sur le controller des ressources.
Je me suis du coup rendu compte que l'on renvoyait des pages avec "404" marqué dessus, mais qui étaient en 200.
J'ai aussi enlevé l’élément dans la view de l'erreur 500 qui faisait qu'on avait des pages blanches. closes #1383

Resource controller test

---

apps/db/lib/db/stats_history.ex
apps/db/priv/repo/migrations/20201214163517_stats_history.exs
apps/transport/lib/transport/stat_handler.ex
apps/transport/lib/transport/stats_handler.ex
apps/transport/lib/transport_web/controllers/stats_controller.ex
apps/transport/lib/transport_web/templates/stats/index.html.eex
config/prod.exs

stocke les stats globale de la page /stats en base
pour le moment on ne stocke que les stats globales

Stock les stats en base

---

apps/transport/lib/transport_web/templates/page/producteurs.html.eex
apps/transport/priv/gettext/en/LC_MESSAGES/page-producteurs.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-producteurs.po
apps/transport/priv/gettext/page-producteurs.pot

unify transport.data.gouv.fr brand on producteurs page

---

apps/transport/test/transport_web/controllers/page_controller_test.exs

Séance sympathique de pairing avec @thbar pour une discussion autour des tests et des bonnes pratiques.

Ajout d'un test sur le controlleur de la page producteurs

---

blog/content/billets/la-production-des-données-temps-réel-interview-avec-différents-producteurs-de-données.md

Link 'API open data bar de Kisio Digital' is bad formed and gives a 404
Merci

[Bug] Post 'la-production-des-données-temps-réel...' link resolution

---

apps/db/priv/gettext/fr/LC_MESSAGES/dataset.po
apps/transport/client/images/icons/charge-station.svg
apps/transport/lib/transport_web/templates/page/index.html.eex
apps/transport/priv/gettext/en/LC_MESSAGES/page-index.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-index.po
apps/transport/priv/gettext/page-index.pot

close #1553 
ça te va comme picto @NicolasBerthelot ?
stp dis oui parce que je galère trop avec Inkscape :rofl:

Créer une catégorie "réapprovisonnement de véhicules"

---

apps/transport/lib/transport_web/templates/stats/index.html.eex

lié à #1541 
Mais ne clôture pas tout à fait la question, car je n'ai pas ajouté de carte sur les IRVE et les lieux de covoiturage (voir discussion en cours dans l'issue).

Petite mise à jour des textes dans la page stats

---

apps/db/lib/db/dataset.ex
apps/db/priv/gettext/dataset.pot
apps/db/priv/gettext/en/LC_MESSAGES/dataset.po
apps/db/priv/gettext/fr/LC_MESSAGES/dataset.po
apps/transport/client/images/icons/bike-path.svg
apps/transport/lib/transport_web/templates/page/index.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-index.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-index.po
apps/transport/priv/gettext/page-index.pot

Ajout de la categorie aménagement cyclable

---

apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex

Add counter for each sections from the dataset details page.
Close #1453

Add counters for datasets details sections

---

config/dev.secret.template.exs

Une virgule en trop

---

apps/transport/lib/transport_web/api/controllers/places_controller.ex
apps/transport/test/transport_web/controllers/places_controller_test.exs

...pour les communes.
closes #1535

Ajout du code insee dans les résultats de recherche

---

apps/transport/lib/transport_web/templates/layout/app.html.eex

Change la valeur de l'attribut `lang` en fonction de la langue utilisée

Set html lang according to session

---

apps/transport/client/javascripts/map.js
apps/transport/lib/transport/stats_handler.ex
apps/transport/lib/transport_web/templates/stats/index.html.eex

Ajout d'une section "Format de données" pour le temps réel

---

apps/transport/client/package.json

Durant mon travail sur #1875, j'ajoute des logs selon qu'on est en mode "worker only", "webserver only", ou les deux. 
Ces logs (ainsi que d'autres) étaient un peu perdus dans la masse du `--progress` fourni par webpack. Je supprime ce flag qui n'apporte pas une grosse plus-value aujourd'hui.
```
> @0.0.1 watch /Users/thbar/git/transport/transport-site/apps/transport/client
> webpack --watch-options-stdin --color --config webpack.dev.js
webpack dev configuration is used
assets by path ../images/ 5.18 MiB 106 assets
assets by path *.js 2.55 MiB 9 assets
assets by path ../fonts/ 1.29 MiB
assets by path ../fonts/*.otf 532 KiB 3 assets
assets by path ../fonts/*.ttf 417 KiB 3 assets
asset ../fonts/fa-solid-900.eot 198 KiB [compared for emit] [from: …
```

Réduction des logs webpack en développement

---

apps/transport/lib/transport_web/controllers/page_controller.ex
apps/transport/lib/transport_web/router.ex
apps/transport/test/transport_web/controllers/page_controller_test.exs
config/config.exs

Fixes https://github.com/etalab/transport-site/issues/1879
Voir https://securitytxt.org/

Ajout page security.txt

---

apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/lib/transport_web/templates/resource/details.html.eex

Fixes https://github.com/etalab/transport-site/issues/1897

Ajustement couleur pour données présentes

---

config/dev.exs
config/prod.exs

C'était dans `config :transport, TransportWeb.Endpoint` par mégarde

Move s3_buckets config

---

config/runtime.exs

Pendant qu'on clarifie la situation

No cronjob for ResourceHistoryDispatcherJob

---

.formatter.exs
apps/shared/lib/application.ex
apps/shared/lib/data_visualization.ex
apps/shared/lib/hasher.ex
apps/shared/test/data_visualization_test.exs
apps/shared/test/http_stream_v2_test.exs
apps/shared/test/validation/gbfs_validator_test.exs
apps/shared/test/validation/gtfs_validator_test.exs
apps/unlock/lib/config.ex
apps/unlock/lib/controller.ex
apps/unlock/lib/router.ex
apps/unlock/test/config_fetcher_test.exs
apps/unlock/test/controllers/unlock_controller_test.exs

Formatte `shared` et `unlock`.
J'ai l'habitude d'écrire du code pas beau et laisser faire les algos ensuite :)

Formatte shared et unlock

---

.github/CODEOWNERS

Pour ne pas avoir à choisir qui doit review pour chaque PR.
Voir https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
À faire en même temps :
- mettre @AntoineAugusti maintainer dans https://github.com/orgs/etalab/teams/transport/members et https://github.com/orgs/etalab/teams/transport-tech/members
- mettre la team transport-tech admin de ce dépôt

Ajout fichier CODEOWNERS

---

apps/transport/client/javascripts/map.js
apps/transport/lib/transport/stats_handler.ex
apps/transport/lib/transport_web/api/controllers/stats_controller.ex
apps/transport/lib/transport_web/templates/stats/index.html.eex
apps/transport/test/transport_web/controllers/stats_controller_test.exs

Avec la publication récente de JDD VLS, on se retrouve à avoir plusieurs JDD dans une même ville. Dans ce cas, notre carte n'affiche qu'un seul JDD.
J'ai adapté le code pour pouvoir avoir plusieurs liens.

Affichage de plusieurs JDD VLS par commune

---

config/runtime.exs

Une fois toutes les 6 heures, et non toutes les minutes toutes les 6h 🤦 
Merci @fchabouis. Le unique nous a protégé ! https://github.com/etalab/transport-site/blob/f28a6f79b779a5f3beb3eb802a474baee7a8f026/apps/transport/lib/jobs/resource_history_job.ex#L5

Fix cron frequency for ResourceHistoryDispatcherJob

---

apps/gbfs/lib/gbfs/controllers/vlille_controller.ex

Nous avons une exception récurrente dans notre GBFS des VLille : https://sentry.io/share/issue/e318a199a5ac4fce8f260c25fe5d30d7/
Je soupçonne que de temps en temps le champ `datemiseajour` soit absent.
J'ajoute donc une information en extra à l'exception sentry pour m'assurer que c'est ça le problème et pouvoir le faire remonter.

Ajout d'infos Sentry à une exception récurrente

---

apps/transport/lib/jobs/gtfs_converter.ex
apps/transport/lib/jobs/gtfs_to_geojson_converter_job.ex

Les jobs de conversions GTFS -> GeoJSON et GTFS -> NeTEx vont être très similaires, je prépare un peu le terrain en extrayant les fonctions pour les rendre génériques et pouvoir les réutiliser pour le NeTEx. Cette PR est juste un refactoring de l'existant.

Preparation de la conversion NeTEx

---

.formatter.exs
scripts/hash_compute_experiment.exs
scripts/internal_zip_checksum_experiment.exs

Aucun changement dans cette PR à part le lancement du "formateur".
J'ai séparé de #2063 comme mentionné avec @AntoineAugusti, pour que ça soit moins sujet à confusion.

Formattage automatique du code de tous les "scripts" 

---

.vscode/launch.json

J'ai eu à nouveau l'utilité aujourd'hui de faire du débuggage pas-à-pas, pour aller creuser assez loin.
Vu que ça m'arrive de temps en temps, je propose de stocker la configuration (un peu difficile à trouver) pour que chacun puisse lancer ça.
Ca fonctionne conjointement avec l'extension https://marketplace.visualstudio.com/items?itemName=JakeBecker.elixir-ls.
Ce n'est pas parfait, il y a des déconnections etc, mais ça m'a aidé au moins un peu.
À discuter !

Ajout configuration débuggage pas-à-pas pour VSCode

---

apps/db/lib/db/resource.ex
apps/transport/lib/jobs/resource_history_job.ex
apps/transport/test/transport/jobs/resource_history_job_test.exs

Suite de https://github.com/etalab/transport-site/pull/2123
J'ai sans faire exprès historisé quelques ressources qui sont en temps réel. Cette PR répare le bug et le test qui était mal écrit.

Répare bug historisation real time

---

apps/transport/lib/transport_web/templates/page/infos_producteurs.html.eex

Suite à demande de @Benoit-MINT

Mise à jour lien "vos obligations" dans espace producteur

---

.gitignore
README.md

J'ai voulu faire tourner les outils en local pour reviewer #2197, et il me manquait ça.

Documentation pour installer facilement les validateurs Java en local

---

apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/test/transport_web/controllers/backoffice/page_controller_test.exs

Suite de #2199 , j'avais oublié de ne sélectionner que les datasets actifs dans ma requête !

Oups : oubli de filtrer les datasets inactifs

---

config/runtime.exs

Voir #2227 et en particulier https://github.com/etalab/transport-site/issues/2227#issuecomment-1068191743, il y a je pense des processus annexe et il faut prévoir un peu de marge.

Réduction de la taille du pool Ecto

---

config/runtime.exs

This reverts commit c4e9f84590ccf2f02549f867acd7e09c71f15215.
Je repars en arrière car 1/ j'ai augmenté la taille du plan en prod et 2/ ça semble poser un souci sur staging.

Revert "Réduction de la taille du pool Ecto (voir #2227)"

---

apps/transport/lib/transport_web/templates/layout/_header.html.eex
apps/transport/priv/gettext/default.pot
apps/transport/priv/gettext/en/LC_MESSAGES/default.po
apps/transport/priv/gettext/fr/LC_MESSAGES/default.po

Ajout d'un lien vers normes.data.gouv.fr

---

apps/transport/lib/jobs/gtfs_rt_validation_job.ex
apps/transport/lib/jobs/on_demand_validation_job.ex
apps/transport/test/transport/jobs/gtfs_rt_validation_job_test.exs
apps/transport/test/transport/jobs/on_demand_validation_job_test.exs
apps/transport/test/transport_web/controllers/validation_controller_test.exs

Fixes https://github.com/etalab/transport-site/issues/2255

Gestion File.Error pour validation GTFS-RT

---

apps/transport/client/javascripts/map-geojson.js

closes #2259 
Merci @AntoineAugusti d'avoir repéré le problème !

Réparer la cartes des geojsons pour les points

---

apps/transport/lib/data_screens/data_screens.ex
apps/transport/lib/transport_web/plugs/health_check.ex

Suppression de warnings de compilation :broom: 

---

apps/shared/lib/date_time_display.ex

Support des locales exotiques

---

apps/transport/lib/transport_web/templates/resource/gtfs_details.html.eex
apps/transport/lib/validators/gtfs_transport_validator.ex
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/validations.pot

suite à #2371 , correction suite à une erreur sur le site remontée par @ChristinaLaumond

Correction multi validation, lorsque la validation est sans erreur

---

.circleci/config.yml
.tool-versions
Dockerfile
Dockerfile.dev
apps/transport/lib/transport_web/views/dataset_view.ex

Voir https://github.com/etalab/transport-ops/releases/tag/elixir-1.13.4-erlang-24.3.4-ubuntu-focal-20211006-transport-tools-1.0.3

Mise à jour Elixir/Erlang/NodeJS

---

apps/transport/lib/transport/stats_handler.ex
apps/transport/test/transport/stats_handler_test.exs

Réparation de la fonction count_dataset_with_format.
closes #2441

Modification of the count dataset function for validated data.

---

apps/transport/lib/db/resource_unavailability.ex
apps/transport/test/db/resource_unavailability_test.exs

Fixes #2484
Adapte le code SQL pour que le dernier jour de la période ne compte pas forcément 24h et qu'un éventuel downtime en cours soit borné jusqu'à l'heure courante. Ajoute un test.

Répare bug calcul de disponibilité pour dernier jour

---

.gitignore
.miniorc.template
config/dev.secret.template.exs

Dans cette PR je documente comment travailler avec un bucket local, pour pouvoir travailler de façon isolée (et accessoirement, hors ligne).

Setup S3 local avec Minio

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/db/gettext.ex
apps/transport/lib/db/validation.ex
apps/transport/lib/validators/gtfs_transport_validator.ex

Suppression warning DB.Gettext

---

apps/transport/lib/transport/import_data.ex

C'est pas le fix du siècle, mais ça permet de close #2513 pour le jeu de données [Ilévia](https://transport.data.gouv.fr/datasets/localisation-des-arrets-ilevia-bus-metro-et-tram-gtfs-pictogrammes-du-reseau-ilevia/).

Ne pas nettoyer les "[" et "]" lors de l'import.

---

apps/transport/lib/db/multi_validation.ex
apps/transport/test/db/multi_validation_test.exs

Répare jointure entre MultiValidation et ResourceMetadata

---

apps/shared/test/validation/gbfs_validator_test.exs

closes #2633 
En fait l'erreur n'était pas intermittente, c'est moi qui la voyait de manière intermittente je pense :laughing:

Nettoyage output de test GBFS

---

apps/transport/lib/jobs/gtfs_multi_validation_job.ex
apps/transport/lib/jobs/resource_history_validation_job.ex
apps/transport/lib/validators/validator_selection.ex
apps/transport/test/transport/jobs/resource_history_validation_job_test.exs
apps/transport/test/transport/validators/validator_selection_test.exs
config/runtime.exs

Comme discuté hier avec @AntoineAugusti, il est possible de simplifier et de rendre plus explicite cette partie du code.

Simplification de validator_selection.ex

---

scripts/gtfs_diff.exs

Je préfère mettre le code au chaud sur le repo pour ne pas risquer de le perdre.
L'idée derrière cette tentative est de tester la possibilité de générer des fichiers de diff entre GTFS, selon un schéma simple, avec un nombre fixe de colonnes et qui permet d'exprimer toutes les modifications que peut subir un GTFS.
Exemple de output pour un panel de modification aux niveau des fichiers (ajout/suppression), des colonnes (ajout/suppression) et des lignes (ajout/édition/suppression).
file | action | target | identifier | arg
-- | -- | -- | -- | --
levels.txt | add | file | {"file_name":"levels.txt"} | null
agency.txt | delete | file | {"file_name":"agency.txt"} | null
stops.txt | add | column | {"column_name":"new_column"} | null
stops.txt | delete | column | {"column_name":"stop_lon"} | null …

Ajout d'un script de diff GTFS

---

apps/transport/priv/zfe_ids.csv

Avec les données transmises par la DGEC

Mise à jour identifiants ZFE

---

apps/transport/lib/transport/import_data.ex

Fixes https://github.com/etalab/transport-site/issues/2695
Voir aussi [sur Mattermost](https://mattermost.incubateur.net/betagouv/pl/dmndriht33865qomy9x4riqdww).

Meilleure détection des ressources GTFS-RT

---

.stylelintrc.json
apps/transport/client/javascripts/explore.js
apps/transport/client/javascripts/map.js
apps/transport/client/javascripts/resource-viz.js
apps/transport/client/package.json
apps/transport/client/stylesheets/components/_aom_table.scss
apps/transport/client/stylesheets/components/_autocomplete.scss
apps/transport/client/stylesheets/components/_backoffice.scss
apps/transport/client/stylesheets/components/_blog.scss
apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/client/stylesheets/components/_discussions.scss
apps/transport/client/stylesheets/components/_download_availability.scss
apps/transport/client/stylesheets/components/_error.scss
apps/transport/client/stylesheets/components/_explore.scss
apps/transport/client/stylesheets/components/_icons.scss
apps/transport/client/stylesheets/components/_mail.scss
apps/transport/client/stylesheets/components/_mailing-list.scss
apps/transport/client/stylesheets/components/_shortlist.scss
apps/transport/client/stylesheets/components/_stats.scss
apps/transport/client/stylesheets/components/_tooltip.scss
apps/transport/client/stylesheets/components/_validation.scss
apps/transport/client/stylesheets/espace_producteur.scss
apps/transport/client/stylesheets/home.scss
apps/transport/client/stylesheets/main.scss
apps/transport/client/stylesheets/producteurs.scss
apps/transport/client/webpack.common.js
apps/transport/client/yarn.lock

Ca n'a pas été de la tarte de mettre à jour css-loader !
Ca cassait un peu tout : les images, les fonts et leaflet :crying_cat_face: 
J'ai mis des commentaires dans le code pour expliquer certains points.
Les 2 upgrades les pus impactantes ont été css-loader et stylelint (linter scss), le reste ça va.

JS maj majeures

---

apps/transport/lib/transport_web/templates/dataset/_resource.html.heex
apps/transport/lib/transport_web/templates/dataset/details.html.heex
apps/transport/lib/transport_web/templates/resource/details.html.heex
apps/transport/lib/transport_web/views/resource_view.ex

Ajout message "data vis disponible" pour les geojsons

---

apps/transport/priv/search_custom_messages.yml

Ajout rubrique air-transport pour préciser que le format attendu est le GTFS

Ajout message pour la rubrique air-transport

---

apps/transport/lib/transport_web/controllers/resource_controller.ex
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Voir:
- #2738 
Curieux que ça plante chez moi, l'ordre semble différent. Postgres 14 en prod, CI et en local pourtant.

Correctif pour test fragile

---

apps/transport/lib/transport_web/live/siri_querier_live.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/explore.po
apps/transport/priv/gettext/explore.pot
apps/transport/priv/gettext/fr/LC_MESSAGES/explore.po

Suite de https://github.com/etalab/transport-site/pull/2704
Des traductions étaient incohérentes en FR

Traductions SIRI requête/réponse

---

apps/transport/lib/transport_web/templates/dataset/index.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/page-shortlist.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-shortlist.po
apps/transport/priv/gettext/page-shortlist.pot

suite à discussion avec Benoit.
https://mattermost.incubateur.net/betagouv/pl/cxyqp9u7qjdi9njh47ghyztb6y

"Ajouté le ..." devient "créé le ..."

---

apps/transport/lib/jobs/resource_history_job.ex
apps/transport/test/transport/jobs/resource_history_job_test.exs

Fixes #2812
#2811 corrige le bug qui a engendré l'historisation de ressources communautaires et cette PR ajoute des sécurités supplémentaires pour éviter que ça survienne à nouveau.

ResourceHistoryJob : ne pas historiser certaines ressources

---

apps/transport/lib/transport_web/controllers/page_controller.ex
apps/transport/lib/transport_web/endpoint.ex
apps/transport/lib/transport_web/router.ex
apps/transport/priv/static/robots.txt
apps/transport/test/transport_web/controllers/page_controller_test.exs

Fixes #1701
Le contenu du `robots.txt` sera différent en staging.

Adapte robots.txt en staging

---

apps/transport/lib/transport/stats_handler.ex
apps/transport/test/support/factory.ex
apps/transport/test/transport/stats_handler_test.exs

Nous enregistrons des stats sur la qualité des données, j'ai réécrit la fonction pour qu'elle aille chercher les infos dans la multi validation.
Ajout de 2 tests au passage, ce qui  m'a permis de trouver un bug :v:

Stats handler : utilisation des resources metadatas et de la multi validation

---

apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/lib/transport_web/templates/backoffice/page/index.html.heex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po

Ne plus lire les resource.end_date depuis le backoffice

---

apps/transport/lib/transport/data_checker.ex
apps/transport/test/transport/data_checker_test.exs

Adapte l'envoi de notifications concernant les GTFS périmés  :
- si les données n'ont pas été mises à jour 3 jours et 7 jours après la date de péremption
- dans l'e-mail adressé aux bizdevs, indique pour chaque JDD si une notification a été envoyée ou pas
Utile pour la période charnière de début d'année 2023.

DataChecker : envoi des notifications si les données restent périmés

---

apps/transport/lib/transport_web/router.ex

Implémente la suggestion faites dans https://github.com/etalab/transport-site/pull/2868#discussion_r1057595453

Router: scope pour OpenApi

---

apps/datagouvfr/lib/datagouvfr/client/api.ex
apps/datagouvfr/test/datagouvfr/client/api_test.exs

Il se trouve que data.gouv.fr fait des redirections avec le code 308 (voir https://github.com/opendatateam/udata/pull/2706) mais que HTTPoison ne gère pas ça... https://github.com/etalab/transport-site/issues/1801
Le code introduit dans https://github.com/etalab/transport-site/pull/2826 ne fonctionne donc pas, car il repose sur le bon fonctionnement de la redirection. On a déjà `follow_redirect: true`, mais ce n'est pas suffisant.
J'ajoute donc du code temporaire pour gérer ça, et j'ai [relancé côté Hackney](https://github.com/benoitc/hackney/pull/692#issuecomment-1366060493).

API data.gouv.fr : gère redirection 308

---

apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

suite à #2862 , correction d'un bug d'affichage de la période de validité

Fix validity period display

---

apps/transport/lib/transport/history_fetcher.ex
apps/transport/test/transport/history_fetcher_test.exs

fix : Afficher les ressources historisées triées par date d'historisation

---

apps/unlock/mix.exs
mix.exs
mix.lock

Voir https://github.com/qcam/saxy/blob/master/CHANGELOG.md
et https://github.com/qcam/saxy/issues/116

Mise à jour de Saxy

---

apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/lib/transport_web/templates/backoffice/page/_dataset.html.heex
apps/transport/lib/transport_web/templates/backoffice/page/index.html.heex

Backoffice : ajout organisation avec possibilité de trier

---

apps/transport/lib/transport_web/live/backoffice/cache_live.ex
apps/transport/lib/transport_web/live/backoffice/cache_live.html.heex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/backoffice/page/index.html.heex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po
apps/transport/test/transport/cache_cachex_test.exs
apps/transport/test/transport_web/live_views/cache_live_test.exs
apps/transport/test/transport_web/live_views/gbfs_live_test.exs
apps/transport/test/transport_web/live_views/proxy_config_live_test.exs

Fixes #2893
https://user-images.githubusercontent.com/295709/210545673-5192a4ff-b7b1-4e0e-8689-51df9457d4de.mov

Ajout page de debug du cache dans le backoffice

---

apps/transport/priv/repo/migrations/20230103165252_validation_v1_shutdown.exs

"The final shutdown"
Je supprime les champs et les tables en base, suite à #2807 #2808 #2880 #2882 #2889 #2892 et #2894

Suppression des tables et champs de validation V1

---

apps/transport/priv/repo/migrations/20230120093740_dataset_add_unique_datagouv_id.exs
apps/transport/test/support/factory.ex
apps/transport/test/transport/data_checker_test.exs

Ajout index unique sur dataset.datagouv_id

---

apps/transport/test/transport_web/controllers/backoffice/page_controller_test.exs

J'ai un test récent qui échoue chez moi *parfois*

Test fragile

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/transport/gbfs_metadata.ex
apps/transport/lib/transport/import_data.ex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/priv/search_custom_messages.yml

Fixes #2989
- Détection du format `gbfs` lors de l'import
- Affichage d'une carte
- Calcul de métadonnées
- Ne pas historiser
J'ai fait une recherche sur `bike-scooter-sharing` dans `lib/transport`. J'espère ne rien avoir oublié. On pourra revenir dessus sinon 👍

Adaptation suite publication dans car-motorbike-sharing

---

.circleci/config.yml
.tool-versions
Dockerfile
Dockerfile.dev

- Patchs sécurité au niveau de l'OS (ma première motivation pour faire ça)
- Elixir 1.14.1 -> 1.14.3 (https://github.com/elixir-lang/elixir/releases)
- OTP
- NodeJS

Mises à jour techniques

---

apps/transport/lib/transport_web/templates/backoffice/contact/form.html.heex

Fixes #3000
Le HTML n'était pas le bon !

Contacts : job_title n'est pas requis

---

apps/datagouvfr/lib/datagouvfr/client/api.ex
apps/datagouvfr/test/datagouvfr/client/api_test.exs

closes #3016 
[Voir Sentry](https://transport-data-gouv-fr.sentry.io/issues/3987059322/?environment=prod&project=6197733&referrer=issue-stream)

Gestion d'une redirection 308 avec un redirect relatif

---

apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.heex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po

Répare mauvaise interpolation dans traduction

---

apps/transport/lib/transport_web/live/backoffice/cache_live.html.heex
apps/transport/lib/transport_web/live/backoffice/edit_dataset_live.ex
apps/transport/lib/transport_web/live/siri_querier_live.html.heex

Je pense que suite à #3029 des warnings étaient apparus quand on lance les tests.
J'ai appliqué les suggestions.

Suppressions de warnings dans les tests

---

apps/transport/mix.exs
apps/unlock/mix.exs
mix.lock

https://github.com/ufirstgroup/ymlr/releases
RAS

Mise à jour majeure ymlr

---

apps/transport/mix.exs
mix.lock

En fait elle m'a l'air plutôt mineure...
https://github.com/akash-akya/unzip/releases

Mise à jour "majeure" unzip 0.8

---

apps/shared/lib/validation/tableschema_validator.ex
apps/shared/test/validation/tableschema_validator_test.exs

Mise à jour URL Validata

---

.circleci/config.yml
Dockerfile
Dockerfile.dev

Pour intégrer https://github.com/hove-io/transit_model/pull/891 dans notre convertisseur GTFS2NeTEx !

Maj de transport-tools v1.0.7

---

config/config.exs

Voir [leur JDD](https://www.data.gouv.fr/fr/datasets/reseau-de-transport-en-commun-lia-siri/) + [Mattermost](https://mattermost.incubateur.net/betagouv/pl/rc9ci4zs4ibcixat1aw7yebo9y)

Ajout requestor_ref SIRI pour Lia

---

blog/themes/mediumish/layouts/partials/_shared/head.html
blog/themes/mediumish/layouts/partials/_shared/matomo.html

En lien avec #3123
Ajout le tracking Matomo pour le blog.

Ajout code tracking Matomo

---

apps/transport/lib/jobs/resource_history_validation_job.ex
apps/transport/test/transport/jobs/resource_history_validation_job_test.exs

closes #3134 
Le code appelé par le BO quand on force la validation ne prenait pas en compte l'argument `force_validation`. J'en profite pour rajouter un test et pour DRY un peu le code.

Backoffice : Réparation de la validation forcée

---

restore_db.sh

Suppression "set -e"

---

apps/transport/lib/transport/history_fetcher.ex

En regardant le temps de réponse pour `dataset#details` j'ai remarqué qu'une requête assez simple mettait régulièrement 700ms, en passant en sous-requête on passe à 70ms. Je comprends pas tout ce qui se passe sur PostgreSQL mais bon !
Voir [sur Mattermost](https://mattermost.incubateur.net/betagouv/pl/z9xbh3h9kfbmbgrknmg9nsncsw)

HistoryFetcher : accélère requête SQL

---

apps/transport/lib/transport_web/live/backoffice/edit_dataset_live.ex
apps/transport/test/transport_web/live_views/edit_dataset_live_test.exs

closes #3192 
Il faut en fait sauvegarder l'état des champs du formulaire dans les assigns de la view pour qu'en cas de re-render ils ne soient pas remis à leur état initial. Le fait d'ajouter un représentant légal déclenche un render de la view, d'où le bug.

Backoffice : correction bug

---

apps/transport/lib/db/multi_validation.ex

Je réécris la query qui permet d'aller chercher les multivalidations et métadonnées associées à un dataset. Au lieu d'utiliser des join, j'utilise des lateral joins, et le résultat est...comment dire, meilleur.
Ca devrait bien accélerer le chargement des pages datasets qui sont lentes actuellement.
Avant : [debug] QUERY OK source="resource" **db=911.4ms** idle=1067.8ms
SELECT r0."id", s2."id", s2."validation_timestamp", s2."validator", s2."validator_version", s2."command", s2."result", s2."data_vis", s2."max_error", s2."oban_args", s2."resource_id", s2."resource_history_id", s2."validated_data_name", s2."secondary_resource_id", s2."secondary_resource_history_id", s2."secondary_validated_data_name", s2."inserted_at", s2."updated_at", r3."id", r3."resource_id", r3."resource_history_id", …

Perf sur query des multivalidations

---

apps/transport/priv/facilitators.csv
apps/transport/priv/search_custom_messages.yml

Mise à jour URL Géovélo

---

apps/transport/lib/opendatasoft/url_extractor.ex
apps/transport/lib/transport/import_data.ex

Suppression gestion format Neptune

---

learning_track.md
scripts/debugging.livemd

Suite à discussion avec @vdegove ce jour, je note tout ça.

Amélioration des tutoriels pour débugger l'application

---

apps/datagouvfr/lib/datagouvfr/client.ex
apps/transport/lib/transport/data_checker.ex
apps/transport/test/transport/data_checker_test.exs

Archive les datasets passés en privé sur data.gouv

---

apps/transport/lib/transport_web/controllers/session_controller.ex
apps/transport/test/transport_web/controllers/session_controller_test.exs

Fixes #3308, voir l'issue pour toute l'histoire

Rattachement de contact : comparaison minuscules pour email

---

apps/transport/client/javascripts/explore.js
apps/transport/client/stylesheets/components/_explore.scss
apps/transport/lib/transport_web/api/controllers/geo_query_controller.ex
apps/transport/lib/transport_web/controllers/explore_controller.ex
apps/transport/lib/transport_web/templates/explore/explore.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/explore.po
apps/transport/priv/gettext/explore.pot
apps/transport/priv/gettext/fr/LC_MESSAGES/explore.po
apps/transport/test/transport_web/controllers/api/geo_query_controller_test.exs
apps/transport/test/transport_web/controllers/explore_controller_test.exs

Rajout des IRVE à la carte d’exploration

---

apps/transport/client/javascripts/explore.js

Suite au retour de @cyrilmorin
closes #3330

Wording dans la carte IRVE

---

apps/transport/test/transport_web/controllers/backoffice/notification_subscription_controller_test.exs

Répare test instable NotificationSubscriptionController

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/db/notification.ex
apps/transport/lib/db/notification_subscription.ex
apps/transport/lib/jobs/periodic_reminder_producers_notification_job.ex
apps/transport/lib/transport_web/templates/email/producer_with_subscriptions.html.md
apps/transport/lib/transport_web/templates/email/producer_without_subscriptions.html.md
apps/transport/priv/gettext/en/LC_MESSAGES/notification_subscription.po
apps/transport/priv/gettext/fr/LC_MESSAGES/notification_subscription.po
apps/transport/priv/gettext/notification_subscription.pot
apps/transport/test/db/notification_test.exs
apps/transport/test/transport/jobs/periodic_reminder_producers_notification_job_test.exs
config/runtime.exs

Fixes #3337 
Voir l'issue pour le détail de la fonctionnalité, il y a pas mal de documentation dans le code !
[Un exemple d'e-mail](https://app.frontapp.com/open/cnv_yxagi1i?key=dgoxfiv-eweWxQy6lTbxnsF101JVuBZz) pour quelqu'un sans notifications
[Un autre exemple](https://app.frontapp.com/open/cnv_yxag1zq?key=NWVDwd4WNx_r0f3n-TTgLlvhEM_ypsLk) avec des notifications

Notifications : rappels périodiques pour les producteurs

---

apps/shared/lib/gbfs_metadata.ex

https://github.com/MobilityData/gbfs/pull/522 va ajouter la possibilité d'exprimer les timestamps avec un format différent (préalablement uniquement UNIX).
Adapte notre code pour gérer ce cas.
Lecture utile [What's the difference between ISO 8601 and RFC 3339 Date Formats?](https://stackoverflow.com/q/522251). Il n'y a pas de méthodes spécifiques dans Elixir il me semble.

Métadonnées GBFS : parsing du timestamp en RFC 3339

---

apps/transport/priv/real_time_providers.csv

Merci Vincent Leblond de [Tellae](https://tellae.fr/) d'avoir remonté la nécessité de mettre à jour ces données !
[Voir conversation interne](https://app.frontapp.com/open/cnv_z14bj2u?key=L8NvEl7XGiBrQ81EQKB6Vuc4kC67fdWJ)

Mise à jour données temps réel non standardisées

---

apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex

Fixes #3467
Va chercher les données dans `dataset_region_legal_owner` en plus de `dataset_aom_legal_owner` pour avoir les régions + les AOMs.

Export de JDDs : ajout des régions pour représentants légaux

---

scripts/pagination_example.exs

Session coaching avec @vdegove, je stocke le résultat à titre de référence, ça peut aider.

Exemples d'usage de `Stream.resource/3` et `Stream.unfold` pour paginer des ressources

---

apps/transport/lib/transport/climate_resilience_bill.ex
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/templates/dataset/details.html.heex
apps/transport/lib/transport_web/templates/email/datasets_switching_climate_resilience_bill.html.md
apps/transport/lib/transport_web/templates/page/future_loi_climat_resilience.html.heex
apps/transport/lib/transport_web/templates/page/loi_climat_resilience.html.heex
apps/transport/priv/gettext/dataset.pot
apps/transport/priv/gettext/en/LC_MESSAGES/dataset.po
apps/transport/priv/gettext/fr/LC_MESSAGES/dataset.po
apps/transport/test/transport/jobs/datasets_switching_climate_resilience_bill_job_test.exs
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

Fixes #3149
Tire les conséquences de l'annulation du décret d'application de l'article 122 de la loi climat et résilience.
Voir [tâches identifiées](https://github.com/etalab/transport-site/issues/3149#issuecomment-1740933756).
Je vois avec @Benoit-MINT quand on envoie ceci en production. Surement faire quelques actions de communication avant.

Adaptations article 122 loi climat et résilience

---

apps/transport/lib/jobs/consolidate_bnlc_job.ex
apps/transport/test/transport/jobs/consolidate_bnlc_job_test.exs

Fixes #3511
Tout est dans le titre et dans l'issue :)

Consolidation BNLC : ignore colonnes non présentes dans schéma

---

apps/transport/lib/jobs/database_backup_replication_job.ex

En lien avec https://github.com/etalab/transport-site/issues/3529#issuecomment-1759653073
Voir la discussion sur le ticket pour plus de contexte.

DatabaseBackupReplicationJob : ajuste timeout upload

---

apps/transport/lib/transport_web/api/controllers/aom_controller.ex
apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
apps/transport/lib/transport_web/api/controllers/places_controller.ex
apps/transport/lib/transport_web/api/controllers/stats_controller.ex

Fix pour:
- #3539
J'ai été charger la page Swagger sans constater d'erreur.

Suppression des alias dans les définitions de réponses OpenAPI

---

.gitignore
livebook/irve-total.livemd

Ça a été rapide à faire et je trouve l'outil de plus en plus productif pour creuser les données.
Voir:
- #3544 
Je partage une copie d'écran car on ne se rend pas trop compte sinon ; les smart cells sont très pratiques pour configurer la connection à la DB ou faire un graphique.

Suivi du nombre de points de charge IRVE (via Livebook)

---

apps/transport/lib/jobs/dataset_quality_score.ex
apps/transport/test/transport/jobs/dataset_quality_score_test.exs

Fixes #3628. Voir le ticket pour le détail du problème et le périmètre. Je ferai un ticket bizdev pour essayer d'améliorer la qualité de ces ressources.

DatasetQualityScore : gère validation non effectuée

---

apps/transport/lib/db/organization.ex
apps/transport/lib/transport_web/templates/dataset/_discussion.html.heex
apps/transport/test/db/contact_test.exs

Organisation datagouv : logo peut ne pas exister

---

apps/transport/test/transport_web/controllers/api/geo_query_controller_test.exs

Répare test instable dans TransportWeb.API.GeoQueryControllerTest

---

apps/transport/test/transport/jobs/import_dataset_monthly_metrics_job_test.exs

Fixes https://github.com/etalab/transport-site/issues/3672
Il y avait déjà une tentative pour éviter un test instable mais ça ne fonctionne pas selon les identifiants qui ont été donnés pour `datagouv_id` et le fait que ce soit du tri alphanumérique et non du "natural sort".
```elixir
iex> Enum.sort(["dataset_datagouv_id_106", "dataset_datagouv_id_92"])
["dataset_datagouv_id_106", "dataset_datagouv_id_92"]
iex> Enum.sort(["dataset_datagouv_id_93", "dataset_datagouv_id_92"]) 
["dataset_datagouv_id_92", "dataset_datagouv_id_93"]
```

ImportDatasetMonthlyMetricsTestJob: répare test instable

---

apps/transport/lib/jobs/update_contacts_job.ex
apps/transport/test/transport/jobs/update_contacts_job_test.exs

Fixes https://github.com/etalab/transport-site/issues/3680
Gère le cas où l'utilisateur a été supprimé sur data.gouv.fr. Voir le détail de la situation et la solution proposée sur l'issue.

UpdateContactsJob : gère cas où user datagouv a été supprimé

---

apps/transport/lib/transport_web/controllers/resource_controller.ex

Je propose un déploiement temporaire de cette branche (sans la merger), qui conjointement avec les logs AppSignal:
- https://github.com/etalab/transport-site/issues/3440
vont nous permettre de faire une recherche par mot clé "PROBE" et d'itérer jusqu'à comprendre ce qui se passe, directement sur la production (ou prochainement mais à première vue la data n'est pas assez à jour).
Pourquoi cette démarche ? Parce qu'on n'a pour l'instant pas de repro en local, et que ça pourrait être lié à quelque chose de spécifique à l'environnement de prod à première vue etc.
- https://mattermost.incubateur.net/betagouv/pl/izhwfb39dirk7qdmz1fc6bqgxh
> Si vous avez une idée, je suis sur un os. Sur [cette méthode](https://github.com/etalab/transport-site/blob/268510fcc34a08ac1070302dc284757b291d6aa4/apps/tra …

Ajout d'une "probe" temporaire de débuggage

---

docs/contacts.md

Fixes #3850
Documente le fonctionnement des contacts en suivant le plan suivant.
```
```

Documente le fonctionnement des contacts

---

apps/transport/lib/jobs/new_datagouv_datasets_job.ex
apps/transport/test/transport/jobs/new_datagouv_datasets_job_test.exs
config/runtime.exs

Je ne vois pas quoi rajouter par rapport à la description de l'issue :grimacing: 
Closes #3856.

NewDatagouvDatasetsJob: pas le weekend

---

apps/transport/test/transport/jobs/new_datagouv_datasets_job_test.exs

Meilleur fix que #3869.
Closes #3868.

3868: test email un lundi et un mercredi

---

apps/gbfs/lib/gbfs/controllers/vlille_controller.ex
apps/gbfs/test/gbfs/controllers/vlille_controller_test.exs

Fixes https://github.com/etalab/transport-site/issues/3873
Voir le ticket pour le détail du problème

GBFS Lille : répare source des données

---

apps/transport/lib/jobs/geo_data/irve_to_geo_data.ex
apps/transport/test/transport/jobs/geo_data/irve_to_geodata_test.exs

Toujours utiliser le dernier IRVE statique

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/transport_web/live/reuses_live.ex

Difficile de faire une démo. Le changement était simple et bien décrit dans l'issue d'origine.
Closes #3876

"Voir sur data.gouv.fr" dans un nouvel onglet

---

apps/transport/priv/repo/migrations/20240418140451_resource_url_size.exs

Fixes https://github.com/etalab/transport-site/issues/3882

resource.url : augmente taille du champ

---

apps/transport/lib/transport_web/templates/page/infos_reutilisateurs.html.heex
apps/transport/lib/transport_web/templates/reuser_space/index.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/reuser-space.po
apps/transport/priv/gettext/fr/LC_MESSAGES/reuser-space.po
apps/transport/priv/gettext/reuser-space.pot

Fixes #3924
Ajuste quelques phrases sur l'Espace réutilisateur conformément aux instructions dans le ticket.

Espace réutilisateur : JDD suivi 👉 favori

---

apps/transport/priv/gettext/fr/LC_MESSAGES/reuser-space.po

Suite de #3928, corrige une répétition d'un mot. On est 3 à ne pas avoir vu ça immédiatement 🙈

Espace réutilisateur : corrige typo

---

apps/transport/lib/transport_web/live/follow_dataset_live.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot
apps/transport/test/transport_web/live_views/follow_dataset_live_test.exs

Dernière partie, fixes #3908
Implémente ce qui a été décidé ici https://github.com/etalab/transport-site/issues/3908#issuecomment-2112053389
https://github.com/etalab/transport-site/assets/295709/83bbd5c7-06cb-4967-beb1-3eccb7f06ca5

Coeur de suivi JDD : mode déconnecté

---

apps/transport/lib/db/dataset_history_resources.ex
apps/transport/lib/jobs/dataset_history_job.ex
apps/transport/priv/repo/migrations/20240520130507_add_datagouv_id_to_dataset_history_resources.exs
apps/transport/test/transport/jobs/dataset_history_job_test.exs

Historisation de resource.datagouv_id

---

apps/transport/lib/jobs/promote_producer_space_job.ex
apps/transport/lib/jobs/warn_user_inactivity_job.ex
apps/transport/lib/mailer/user_notifier.ex

En lien avec #3951
Réintègre les derniers e-mails vers `UserNotifier` qui a été introduit récemement.

Migrer dernières notifications vers UserNotifier

---

apps/transport/lib/transport_web/templates/backoffice/contact/_notification_subscriptions.html.heex
apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.heex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po

En éditant un dataset :
En éditant un contact :
Voir #3970

Notifications: afficher le rôle d'un abonnement

---

apps/transport/lib/db/contact.ex
apps/transport/lib/jobs/dataset_quality_score.ex
apps/transport/lib/jobs/expiration_notification_job.ex
apps/transport/lib/jobs/import_dataset_followers_job.ex
apps/transport/lib/transport/cache.ex
apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
apps/transport/lib/transport_web/api/controllers/geo_query_controller.ex
apps/transport/lib/transport_web/api/controllers/stats_controller.ex
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/controllers/page_controller.ex
apps/transport/lib/transport_web/controllers/resource_controller.ex
apps/transport/lib/transport_web/controllers/stats_controller.ex
apps/transport/lib/transport_web/live/on_demand_validation_live.ex
apps/transport/test/transport_web/controllers/api/stats_controller_test.exs

Renommer le helper de Cache

---

apps/transport/lib/transport_web/templates/layout/_header.html.heex
apps/transport/priv/gettext/default.pot
apps/transport/priv/gettext/en/LC_MESSAGES/default.po
apps/transport/priv/gettext/fr/LC_MESSAGES/default.po

Voir:
- https://github.com/etalab/transport-site/issues/3802
Phrasé précis validé avec Jorge
Pour info @jthiard

Ajout lien vers Accèslibre Mobilités

---

apps/transport/lib/transport_web/templates/page/index.html.heex

Correction URL "En savoir plus" page d‘accueil

---

apps/transport/lib/db/dataset.ex
apps/transport/test/db/db_dataset_test.exs

DB.Dataset.formats/1 : ignore nil

---

apps/transport/lib/mailer/user_notifier.ex
apps/transport/lib/transport_web/templates/email/new_dataset.html.heex
apps/transport/lib/transport_web/views/email_view.ex
apps/transport/test/transport/data_checker_test.exs
apps/transport/test/transport/jobs/new_dataset_notifications_job_test.exs

Fixes #4038
Passe le template en HEEX de manière à avoir une véritable liste HTML et des liens classiques.

Emails : améliore template new_dataset

---

apps/transport/lib/mailer/admin_notifier.ex
apps/transport/test/transport/data_checker_test.exs
apps/transport/test/transport/jobs/datasets_without_gtfs_rt_related_resources_notification_job_test.exs
apps/transport/test/transport/jobs/new_datagouv_datasets_job_test.exs

Fixes #4044
Améliore les liens vers les JDDs dans ce module pour avoir de véritables liens et améliorer la lisibilité des e-mails envoyés à notre équipe.

AdminNotifier : passage à de véritables liens

---

apps/transport/lib/transport/data_checker.ex
apps/transport/test/transport/data_checker_test.exs

Fixes #4090
Gère le cas où un JDD perd son producteur (`owner` ou `organization`).

DataChecker : gère JDD sans producteur

---

apps/transport/lib/jobs/dataset_quality_score.ex
apps/transport/test/transport/jobs/dataset_quality_score_test.exs

Fixes #4084
Cette PR ajoute `today_score`, le score du jour dans la colonne `details` de la table `dataset_score`.
On aura alors :
- `dataset_score.score` : le score intégrant le passé + le score calculé du jour
- `dataset_score.details` : qui contiendra `previous_score` et `today_score` (🆕)

DatasetQualityScore : ajout today_score à details

---

apps/transport/lib/transport_web/templates/page/espace_producteur.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/espace-producteurs.po
apps/transport/priv/gettext/espace-producteurs.pot
apps/transport/priv/gettext/fr/LC_MESSAGES/espace-producteurs.po

Espace producteur : mise à jour d'une traduction

---

apps/transport/lib/jobs/database_backup_replication_job.ex
apps/transport/test/transport/jobs/database_backup_replication_job_test.exs

En lien avec #4111
Vérifie que le dernier dump de base de données a une taille comprise entre 90% et 110% du dump précédent. Si ce n'est pas le cas, `raise`, ce qui aura pour effet de nous prévenir par e-mail (voir https://github.com/etalab/transport-site/issues/3395 pour le mécanisme, pour être certain de ne pas rater un job `state = discarded` pour ce job)

DatabaseBackupReplicationJob : vérification taille du dump

---

README.md

Voir:
- #4108 
@AntoineAugusti et @ptitfred sont maintenant dans les destinataires email, et j'ajoute également ici les urls de suivi qui seront pratiques en cas d'incident.

Documente le monitoring Updown.io

---

apps/transport/priv/gettext/fr/LC_MESSAGES/espace-producteurs.po
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Espace producteur : mise à jour traductions FR

---

apps/transport/lib/jobs/resource_history_job.ex

En lien avec #4118
Similaire à #4136, ajout de compteurs pour suivre de potentiels problèmes dans l'historisation de fichiers et détecter en particulier des fichiers ZIP invalides.
Dans un premier temps on pourra suivre le volume/avoir des alertes et en fonction de ça on verra si il est nécessaire d'automatiser des notications à notre équipe/aux producteurs.

ResourceHistoryJob : ajout de compteurs AppSignal

---

apps/transport/lib/transport/import_data.ex

Fixes #4149
Certaines URLs de ressources OpenDataSoft sont encore avec l'ancien format, ou au moins contiennent un paramètre `?use_labels=(true|false)`, ce qui n'était pas autorisé par le code précédemment et causait des détections de mauvais formats.
J'en profite pour ajouter l'exclusion de ressources ODS à `gbfs?`, qui était le seul format bien typé qui ne contenait pas cette clause.
J'envisage de faire un job Oban pour vérifier que les ressources avec une URL ODS-like ont bien certains formats et à l'exécuter régulièrement en prod… :alarm: Peut-être dans un ticket/PR à créer ?

ImportData : ajuste détection ressource ODS

---

apps/transport/lib/transport_web/templates/dataset/_dataset_resources_history.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot

Fixes #4154
Invite à nous contacter pour accéder aux données historisées anciennes. Ouvre la popup de contact au clic.

Historisation : message invitant à nous contacter

---

apps/transport/test/build_test.exs

Voir https://github.com/etalab/transport-site/pull/4177#issuecomment-2355474967

Silence des warnings du mix.lock

---

apps/transport/lib/transport_web/templates/resource/gtfs_details.html.heex
apps/transport/lib/transport_web/views/resource_view.ex

Fait récemment pour le validateur NeTEx. J'en profite pour le faire sur la page de détail GTFS aussi.

Ressource GTFS : Localisation d'une durée

---

apps/transport/lib/transport_web/templates/dataset/_resource_validation_summary_netex.html.heex

Follow-up malheureux de #4227.

Dataset : supporter les ressources NeTEx sans validation

---

apps/transport/lib/transport_web/templates/dataset/_resource_validation_summary_gtfs.html.heex
apps/transport/lib/transport_web/templates/dataset/_resource_validation_summary_netex.html.heex
apps/transport/lib/transport_web/templates/resource/_validation_summary.html.heex
apps/transport/lib/validators/gtfs_transport_validator.ex
apps/transport/lib/validators/netex_validator.ex
apps/transport/priv/gettext/en/LC_MESSAGES/gtfs-transport-validator.po
apps/transport/priv/gettext/en/LC_MESSAGES/netex-validator.po
apps/transport/priv/gettext/fr/LC_MESSAGES/gtfs-transport-validator.po
apps/transport/priv/gettext/fr/LC_MESSAGES/netex-validator.po
apps/transport/priv/gettext/gtfs-transport-validator.pot
apps/transport/priv/gettext/netex-validator.pot
apps/transport/test/transport_web/controllers/dataset_controller_test.exs
apps/transport/test/transport_web/controllers/validation_controller_test.exs

Pluriel des résumés de validation

---

apps/transport/lib/validators/gtfs_transport_validator.ex
apps/transport/lib/validators/netex_validator.ex
apps/transport/priv/gettext/fr/LC_MESSAGES/gtfs-transport-validator.po

En lien avec #3025 
Avec des tests plus complets.
A noter que les tests ne savent pas tester toutes les locales.
Voir https://github.com/etalab/transport-site/pull/4238/files#r1784517926.

Mauvaise traduction

---

apps/transport/lib/transport_web/templates/backoffice/page/index.html.heex

BO exports : ajouter export des contacts

---

apps/shared/lib/gbfs_metadata.ex
apps/shared/test/gbfs_metadata_test.exs

GBFSMetadata : mise à jour logique pour languages

---

apps/shared/lib/validation/gbfs_validator.ex
apps/shared/test/validation/gbfs_validator_test.exs

Validateur GBFS : définit un timeout HTTP

---

apps/transport/lib/db/dataset.ex
apps/transport/test/db/db_dataset_test.exs

Vérification de la présence du nom custom de dataset avant insertion en base de données

---

apps/transport/lib/transport/gbfs_metadata.ex
apps/transport/test/transport/gbfs_metadata_test.exs

Ajout de cache pour les requêtes HTTP effectuées pour calculer des métadonnées sur les flux GBFS. Il est possible que nous ayons besoin de plusieurs flux pour calculer un ensemble d'indicateurs. Il n'est pas nécessaire de faire plusieurs fois la même requête HTTP.
On peut (discuté précédemment https://github.com/etalab/transport-site/pull/4298#issuecomment-2476903051) :
- tout requêter au début et passer plein de réponses aux sous-méthodes
- cacher les réponses HTTP
Je choisis la seconde option où le diff est minime.

GBFSMetadata : ajout de cache HTTP

---

apps/transport/lib/transport_web/controllers/backoffice/contact_controller.ex
apps/transport/test/transport_web/controllers/backoffice/contact_controller_test.exs
docs/inventaire_donnees_geographiques_septembre_2023.md

J'observe en local que ce test n'est pas stable.
Mon fix n'est peut-être pas le bon ; peut-être faut-il corriger le comporter du contrôleur. N'étant pas familier du sujet je choisis l'option prudente.

Stabilisation d'un test unitaire

---

apps/transport/lib/jobs/consolidate_lez_job.ex
apps/transport/test/transport/jobs/consolidate_lez_job_test.exs

Adapte le job en charge de la consolidation des ZFE pour ignorer les ressources qui n'ont aucune `resource_history` valide.
Ceci peut survenir quand on vient de référencer un JDD, la ZFE publiée n'est pas encore valide, le producteur est en train de corriger sa publication. On veut pouvoir continuer à consolider les ZFE, en n'incluant pas encore cette ressource.
La version existante du job forçait la présence d'une historisation valide par ressource, ce qui n'est pas toujours le cas et bloque donc la consolidation.
```
** (MatchError) no match of right hand side value: nil
(transport 0.0.1) lib/jobs/consolidate_lez_job.ex:138: Transport.Jobs.ConsolidateLEZsJob.content_features/1
(elixir 1.16.2) lib/enum.ex:4326: Enum.flat_map_list/2
(transport 0.0.1) lib/jobs/consolidate_lez_job.ex:133: …
```

ConsolidateLEZsJob : ignore ressources sans historisation valide

---

apps/transport/lib/jobs/database_backup_replication_job.ex
apps/transport/test/transport/jobs/database_backup_replication_job_test.exs

Fixes #4379
Compare la taille du dump d'hier et d'aujourd'hui et non des "2 derniers dumps" pour gérer le cas où il y a plusieurs dumps pour une même journée (crash, backup manuel etc.)

DatabaseBackupReplicationJob : compare taille d'hier et d'aujourd'hui

---

apps/transport/lib/transport_web/templates/resource/_gtfs_unusable_trip.html.heex
apps/transport/lib/transport_web/views/resource_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/validations-explanations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations-explanations.po
apps/transport/priv/gettext/validations-explanations.pot

See [UnusableTrip](https://github.com/etalab/transport-validator/pull/211).

Support new GTFS validation rule

---

apps/transport/priv/gbfs_operators.csv
apps/transport/test/transport/csv_documents_test.exs

[Voir alerte sur Front](https://app.frontapp.com/open/cnv_19tnln4m?key=b-TWswRlCgjBmYUA5MpOFviSA3aMax__)
Similaire à #4414

Mise à jour opérateurs GBFS

---

apps/transport/lib/jobs/new_datagouv_datasets_job.ex

Suppression mot clef electrique

---

apps/transport/lib/transport_web/live/gtfs_diff_select_live.ex
apps/transport/lib/transport_web/live/gtfs_diff_select_live.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/validations.pot
apps/transport/test/transport_web/live_views/gtfs_diff_select_live_test.exs

- traduction (i18n) de l'objet concerné par un changement (fichier, ligne ou
colonne)
- ordre des résumés : ajoutés, modifications puis suppressions
- légère amélioration de l'affichage des changements
Aperçu:

GTFS diff: changement dans la section "Résumé"

---

apps/transport/priv/gettext/fr/LC_MESSAGES/page-index.po

Fixes https://github.com/etalab/transport-site/issues/4457

Accueil : correction traduction

---

apps/transport/lib/transport/gtfs_diff.ex
apps/transport/test/transport/gtfs_diff_test.exs

GTFS diff: agency_id comme clef primaire

---

apps/transport/lib/transport_web/templates/backoffice/page/index.html.heex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po

BO : supprimer bouton Carte nationale des arrêts GTFS

---

apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/test/gtfs_diff_explain_test.exs

gtfs-diff: URL de l’exploitant -> URL de l’entité

---

apps/transport/lib/transport_web/live/gtfs_diff_select_live/differences.ex
apps/transport/priv/gettext/en/LC_MESSAGES/gtfs-diff.po
apps/transport/priv/gettext/fr/LC_MESSAGES/gtfs-diff.po
apps/transport/priv/gettext/gtfs-diff.pot

Version FR manquante, et en attente de review par Cyril.

GTFS diff: aide en ligne pour les comparaisons

---

apps/transport/lib/transport_web/live/followed_datasets_live.ex
apps/transport/priv/gettext/en/LC_MESSAGES/reuser-space.po
apps/transport/priv/gettext/fr/LC_MESSAGES/reuser-space.po
apps/transport/priv/gettext/reuser-space.pot

Espace réutilisateurs : Gérer -> Préférences

---

apps/transport/lib/transport/application.ex
apps/transport/lib/transport/preemptive_api_cache.ex
apps/transport/lib/transport/preemptive_home_stats_cache.ex
apps/transport/lib/transport_web/controllers/page_controller.ex

Cache préemptif des stats de la home page

---

apps/transport/lib/transport_web/templates/reuse/index.html.heex

Réutilisations : liens dans nouvel onglet

---

apps/transport/lib/transport_web/views/reuser_space_view.ex

[Voir Front](https://app.frontapp.com/open/cnv_1ah40cra?key=2RTlv_MI2GRER9NlQxGts-ZRLykDIAEF)

Éligibilité token : ajout Futureco

---

apps/transport/lib/transport_web/live/gtfs_diff_select_live/results.ex
apps/transport/test/transport_web/live_views/gtfs_diff_select_live_test.exs

GTFS-diff: tri des fichiers conforme à la spec

---

apps/transport/lib/transport/gtfs_diff.ex

GTFS-diff: support fare_products & booking_rules

---

apps/transport/lib/db/reuse.ex
apps/transport/test/db/reuse_test.exs
apps/transport/test/transport_web/controllers/reuse_controller_test.exs

Fixes #4659
Tri par date de création la plus récente des réutilisations

Reuse : tri pour la recherche

---

config/dev.exs

Ajout datagouvfr en app reloadable

---

apps/transport/lib/jobs/dataset_quality_score.ex

DatasetQualityScore : répare test fragile

---

apps/transport/lib/transport_web/templates/email/dataset_with_error_producer.html.md
apps/transport/test/transport_web/controllers/discussion_controller_test.exs
apps/transport/test/transport_web/controllers/validation_controller_test.exs

MAJ texte dataset_with_error_producer.html.md

---

apps/transport/client/stylesheets/reuses.scss
apps/transport/lib/transport_web/templates/reuse/index.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/reuses.po
apps/transport/priv/gettext/fr/LC_MESSAGES/reuses.po

Fixes https://github.com/etalab/transport-site/issues/4857#issuecomment-3370523883

Réutilisations : lien vers Espace réutilisateur
