apps/transport/lib/db/notification_subscription.ex
apps/transport/test/db/notification_subscription_test.exs
scripts/contacts/insert_contacts.exs
scripts/contacts/insert_notification_subscriptions.exs

Suite de https://github.com/etalab/transport-site/pull/2981
Cette PR ajoute :
- un script d'import de contacts à partir d'un fichier CSV, pour alimenter notre base de données pour ~130 contacts
- un script d'import d'abonnements à des notifications, pour les contacts précédemment importés
C'est une étape de migration de la [configuration YAML](https://github.com/etalab/transport-notifications) vers l'import en base de données

Ajout scripts pour insérer contacts et abonnements

---

apps/transport/lib/transport_web/views/markdown_handler.ex
apps/transport/test/transport_web/views/markdown_handler_test.exs

Fixes #3005
Earmark ne supporte pas les tableaux avec la syntaxe "GitHub Flavored Markdown" https://github.com/pragdave/earmark/issues/278, qui était la syntaxe pour ce jeu de données. C'est [le format qui est retourné par l'API de data.gouv.fr](https://www.data.gouv.fr/api/1/datasets/liste-des-passages-a-niveau/).
J'ajoute donc l'option qui permet de gérer cette syntaxe ainsi que l'ajout de la classe `.table` qui permet d'avoir un rendu convaincant.

Rendu de tables en Markdown

---

apps/transport/lib/jobs/new_datagouv_datasets_job.ex
apps/transport/lib/transport/data_checker.ex
apps/transport/lib/transport/import_data.ex
apps/transport/test/transport/jobs/new_datagouv_datasets_job_test.exs

Data.gouv.fr vient de modifier le comportement de son API et ne renvoie plus de datetimes naives. Sauf que nous nous étions préparés à avoir des dates au format "2022-09-28T03:08:59.782000**Z**" et que c'est finalement des dates au format "2022-09-28T03:08:59.782000 **+00:00** " qui sont renvoyées.
J'ai pu reproduire en local et vérifier que le fix corrigeait bien le problème d'import.

S'adapter au changement d'API côté data.gouv.fr

---

apps/transport/lib/db/contact.ex
apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/lib/transport_web/templates/backoffice/contact/form.html.heex
apps/transport/lib/transport_web/templates/backoffice/contact/index.html.heex
apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.heex
apps/transport/lib/transport_web/views/backoffice/page_view.ex
apps/transport/priv/repo/migrations/20230309102424_add_mailing_list_title_contact.exs
apps/transport/priv/repo/migrations/20230309102424_add_title_contact.exs
apps/transport/test/db/contact_test.exs
apps/transport/test/transport_web/controllers/backoffice/contact_controller_test.exs

Ajout d'une colonne `mailing_list_title` pour les contacts qui ne sont pas des personnes mais plutôt des alias/listes de diffusion comme `service-sig@example.fr`.
Adapte les formulaires, tableaux et interfaces où prénom + nom étaient présents.

Contacts : ajout colonne pour titre

---

apps/transport/lib/transport_web/router.ex

Notre page swagger est actuellement blanche car une bonne partie de son contenu est bloqué par nos headers CSP.
Malheureusement, cela semble concerner directement la lib [swagger-ui](https://github.com/swagger-api/swagger-ui) et le problème a déjà été remonté.
https://github.com/swagger-api/swagger-ui/issues/7540
https://github.com/swagger-api/swagger-ui/issues/5817
On dirait qu'il n'y a pas de possibilité d'injecter des nonce.
Plutôt que d'autoriser le CSS inline partout à cause de swagger, je préfère ne pas appliquer de CSP à cette page là uniquement.
In english: I now serve the swagger page without CSP headers, because I don't want to weaken the CSP policy on the whole website just for this page.

Plus de CSP pour la page swagger

---

apps/transport/lib/db/contact.ex
apps/transport/lib/transport_web/templates/backoffice/contact/index.html.heex
apps/transport/test/db/contact_test.exs

Fixes #3031
Recherche par prénom, nom, titre (avec `ts_query`) ou organisation (stricte) de contacts.

Recherche de contacts par prénom

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/transport/comments_checker.ex
apps/transport/test/transport/comments_checker_test.exs

Fixes #3051
Il semblerait que l'API de data.gouv.fr puisse renvoyer un datetime sans microsecondes, ce fait hurler Ecto quand le type indiqué est `:utc_datetime_usec`, [voir doc](https://hexdocs.pm/ecto/Ecto.Schema.html#module-primitive-types).
> For calendar types with and without microseconds, the precision is enforced when persisting to the DB. For example, casting ~T[09:00:00] as :time_usec will succeed and result in ~T[09:00:00.000000], but persisting a type without microseconds as :time_usec will fail. Similarly, casting ~T[09:00:00.000000] as :time will succeed, but persisting will not. This is the same behaviour as seen in other types, where casting has to be done explicitly and is never performed implicitly when loading from or dumping to the database.
En attendant que l'équipe …

latest_data_gouv_comment_timestamp: pas besoin de usec

---

apps/transport/lib/db/dataset.ex

je mets le coalesce car certaines populations ne sont pas remplies et le NULL fait un peu n'importe quoi dans le tri.
Je vais faire une autre PR pour régler le problème des populations non renseignées / fausses.
ça fait remonter IDFm en page 1 mais toujours derrière 2 autres jeux qui ont des populations fausses.

Recherche par région : tri par population descendante

---

apps/shared/lib/helpers.ex
apps/shared/test/helpers/helpers_test.exs

Corrige un bug introduit dans #3059, qui ne gère pas le cas d'une liste vide. Voir [sur Sentry](https://transport-data-gouv-fr.sentry.io/issues/4046454967/?environment=prod&project=6197733&query=is%3Aunresolved&referrer=issue-stream&stream_index=0)

Helpers : corrige fonction last_updated

---

apps/transport/lib/transport_web/templates/resource/_validation_report_schema.html.heex
apps/transport/lib/transport_web/views/resource_view.ex
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Fixes #3063
`schema_type` n'est pas renseigné directement dans la multi-validation, j'adapte donc le code et les tests à la réalité. `schema_type` est déterminé à partir du `schema_name`.
En production.
```sql
select validator, rh.payload->>'schema_name', count(1)
from multi_validation mv
join resource_history rh on rh.id = mv.resource_history_id
where mv.inserted_at >= '2023-03-01'
group by 1, 2
```
|Validator|schema_name|count|
|--- | --- | ---|
|GTFS transport-validator |  | 1992|
|validata-api | etalab/schema-stationnement-cyclable | 624|
|EXJSONSchema | etalab/schema-zfe | 41|
|Validata JSON | etalab/schema-zfe | 39|
|Validata JSON | etalab/schema-amenagements-cyclables | 33|
|EXJSONSchema | etalab/schema-amenagements-cyclables | 32|
|validata-api | etalab/schema-irve-dynamique | 30| …

Fix : schema_type n'est pas renseigné dans la multi-validation

---

apps/transport/test/transport_web/controllers/backoffice/broken_urls_controller_test.exs

Dans certains cas les urls remontaient dans un ordre inversé, je corrige ça ici.

Correctif test fragile

---

apps/transport/lib/db/notification_subscription.ex
apps/transport/lib/transport/comments_checker.ex
apps/transport/test/db/notification_subscription_test.exs
apps/transport/test/transport/comments_checker_test.exs

Fixes #3070
- Ajout d'un motif de notification `:daily_new_comments`
- Adapte `Transport.CommentsChecker` pour utiliser ce nouveau motif
- Adapte les tests
:warning: Il faudra inscrire notre équipe + l'ART à ce nouveau motif une fois que ce sera déployé en production.

Notification : abonnements au récap des commentaires postés

---

apps/transport/lib/transport_web/live/backoffice/proxy_config_live.ex
apps/transport/test/transport_web/controllers/backoffice/broken_urls_controller_test.exs
apps/transport/test/transport_web/live_views/proxy_config_live_test.exs
apps/unlock/lib/config.ex
apps/unlock/lib/controller.ex
apps/unlock/test/config_fetcher_test.exs
apps/unlock/test/controllers/unlock_controller_test.exs
apps/unlock/test/enforce_ttl_test.exs
apps/unlock/test/github_config_test.exs
scripts/http_generic_testing.exs

:warning: attention à l'ordre de déploiement. Si on veut tester sur prochainement, il faudrait une autre PR à déployer en production pour ignorer les éléments avec une configuration "http-generic", sinon le proxy plantera en production.
Cette PR introduit un nouveau "type" de configuration YAML pour le proxy: "generic-http".
Voir plus bas, elle ne fait en fait (actuellement en tout cas) qu'exactement la même chose que le "gtfs-rt" (qui permet déjà de retourner les headers HTTP requis), mais en dissociant le nom pour qu'on garde bien en configuration les "gtfs-rt" marqués comme tels, et que cette information soit remontée via une variable `subtype` dans la configuration, pour permettre une customisation pas trop compliquée si besoin de la faire plus tard.
Cette approche a permis d'éviter …

Introduction Generic.HTTP pour le proxy

---

apps/transport/lib/db/contact.ex
apps/transport/lib/transport_web/templates/backoffice/contact/form.html.heex
apps/transport/priv/repo/migrations/20230412080437_contact_add_secondary_phone_number.exs
apps/transport/test/db/contact_test.exs

Fixes #3076
Ajoute une nouvelle colonne `:secondary_phone_number` pour les contacts, afin de gérer le cas fixe + portable.
Je n'ai pas cherché à attribuer le fixe ou le portable à une colonne en particulier, pas sûr que ce soit un véritable besoin. Si on a vraiment besoin de trouver que des numéros fixes ou portables à un moment, on _devrait_ pouvoir le faire à l'aide de libraries/simplement étant donné qu'on gère quasi exclusivement des numéros de téléphones FR.
La donnée est stockée chiffré en BDD, comme pour `:phone_number`.

Contacts : ajout 2nde colonne pour téléphone

---

apps/transport/lib/transport/import_data.ex

Fixes #3083
Détecte le format `NeTEx` dans la catégorie `locations` avec le mécanisme étendu, pas uniquement en regardant le format renseigné sur data.gouv.fr.
Démo avec un fichier ZIP et une description qui contient le mot clé "netex"

Possibilité d'avoir des NeTEx dans locations

---

apps/transport/lib/db/dataset.ex
apps/transport/priv/gettext/db-dataset.pot
apps/transport/priv/gettext/en/LC_MESSAGES/db-dataset.po
apps/transport/priv/gettext/fr/LC_MESSAGES/db-dataset.po
apps/transport/priv/search_custom_messages.yml

Lié à #3083
Pour la catégorie `locations` :
- adapte le titre
- adapte la description de la catégorie

Renomme titre catégorie locations

---

config/config.exs

Suite de https://github.com/etalab/transport-site/pull/3080, le requestor ref a changé.

Mise à jour requestor ref Lia Le Havre

---

apps/transport/lib/jobs/datasets_without_gtfs_rt_related_resources_notification_job.ex
apps/transport/test/transport/jobs/datasets_without_gtfs_rt_related_resources_notification_job_test.exs
config/runtime.exs

En lien avec #3035, voir #3072 pour la PR précédente et le contexte.
Cette PR ajoute un job hebdomadaire (le lundi) qui identifie les JDD où un lien GTFS-RT -> GTFS est nécessaire et n'est pas renseigné.
Si on reçoit cet e-mail, on devra ajouter quelques lignes dans la table `resource_related`.

Ajout d'une notification pour les JDD avec liens GTFS-RT manquants

---

apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/client/stylesheets/components/_icons.scss
apps/transport/client/stylesheets/main.scss
apps/transport/lib/db/dataset.ex
apps/transport/lib/transport_web/templates/dataset/_resource.html.heex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

En lien avec #3035.
Cette PR adapte la page de détails d'un jeu de données, `dataset#details` pour afficher la ressource GTFS à utiliser pour un GTFS-RT quand il n'est pas évident de savoir quelle ressource utiliser et qu'on a eu un lien entre ressources renseigné.
Ceci est représenté par "🔗 GTFS" avec un lien vers la page `resource#details` du GTFS associé.
On peut discuter de l'interface !
cc @cyrilmorin

Affiche GTFS pertinent pour GTFS-RT sur dataset#details

---

apps/transport/lib/transport/comments_checker.ex
apps/transport/test/transport/comments_checker_test.exs

Fixes #3110
Adapte le code pour ne pas stocker de logs d'envoi de notifications par e-mail quand il n'y a pas eu de nouveau commentaire et donc pas d'e-mail envoyé.
C'est une méprise de ma part, je pensais qu'on avait qu'une liste de données avec des JDD ayant eu de nouveaux commentaires, ce qui n'est pas le cas.
ℹ️ J'irai nettoyer les données en BDD en prod ensuite.

CommentsChecker : ne pas stocker notification quand pas de comms

---

apps/transport/lib/db/data_conversion.ex
apps/transport/lib/jobs/gtfs_to_netex_converter_job.ex
apps/transport/lib/transport_web/live/force_netex_conversion.ex
apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.heex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po
apps/transport/test/db/data_conversion_test.exs

Suite à une mise à jour du convertisseur NeTEx, il est pour le moment fastidieux de relancer les conversions NeTEx existantes, car il faut à la fois nettoyer la base et supprimer les fichiers du S3. Je rajoute la possibilité de le faire depuis notre Backoffice pour un dataset donné.

Permettre de rafraichir les conversions NeTEx

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/transport_web/templates/dataset/_licence.html.heex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

Fixes #3114
Ajoute un message mentionnant les règles de la communauté OSM pour les JDD avec licence ODbL venant d'OSM.
Un JDD est considéré comme tel
- quand il a le tag `openstreetmap` indiqué sur data.gouv.fr
- OU quand notre équipe a mis le tag `licence-osm` sur le backoffice

Adapte message pour licence ODbL provenant d'OSM

---

apps/transport/lib/db/resource_related.ex
apps/transport/lib/transport_web/controllers/resource_controller.ex
apps/transport/lib/transport_web/templates/resource/_related_resources.html.heex
apps/transport/lib/transport_web/templates/resource/details.html.heex
apps/transport/priv/gettext/db-resource-related.pot
apps/transport/priv/gettext/en/LC_MESSAGES/db-resource-related.po
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/db-resource-related.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot
apps/transport/test/db/resource_related_test.exs
apps/transport/test/transport_web/controllers/resource_controller_test.exs

En lien avec #3035.
Affiche une liste de ressources associées sur la page affichant les détails d'une ressource, lorsque des ressources associées existent.
Merci @fchabouis pour les échanges que nous avons eu à propos de l'interface :pray:

Affiche ressources associées sur resource#details

---

apps/transport/lib/transport_web/views/dataset_view.ex

Répare un bug introduit dans https://github.com/etalab/transport-site/pull/3116
Ne gère pas le cas où `custom_tags = nil`, visiblement la valeur par défaut mis dans le modèle Ecto n'est pas suffisant :cry:.
Voir [erreurs](https://transport-data-gouv-fr.sentry.io/issues/4135720909/?environment=prod&project=6197733&query=is%3Aunresolved&referrer=issue-stream&stream_index=0) sur Sentry, déjà près de 4k exceptions.

Licence ODbL : gère nil pour custom_tags

---

apps/shared/lib/validation/jsonschema_validator.ex
apps/shared/test/validation/jsonschema_validator_test.exs
apps/transport/lib/jobs/resource_history_job.ex
apps/transport/test/transport/jobs/resource_history_job_test.exs

lié à https://github.com/etalab/transport-site/issues/2428
Pour l'instant la validation des [aménagements cyclables nationaux](https://transport.data.gouv.fr/datasets/amenagements-cyclables-france-metropolitaine#dataset-top) échoue pour 2 raisons : l'historisation de la ressource échoue lors du téléchargement, à cause du timeout par défaut de HTTPoison, puis la validation échoue pour la même raison. J'augmente ces 2 timeouts à 3 minutes, comme c'est déjà fait ailleurs dans le code.

Augmenter le timeout pour historisation des ressources et validation jsonschema

---

apps/transport/lib/jobs/datasets_without_gtfs_rt_related_resources_notification_job.ex
apps/transport/lib/validators/gtfs_rt_validator.ex
apps/transport/test/support/factory.ex
apps/transport/test/transport/jobs/datasets_without_gtfs_rt_related_resources_notification_job_test.exs
apps/transport/test/transport/validators/gtfs_rt_validator_test.exs

Fixes #3117
Adapte le job pour ignorer les GTFS qui sont périmés, sans ceci on envoyait une notification pour un JDD qui ne requiert pas notre attention en réalité.
Dans une logique "boy scout", adapte le validateur GTFS-RT pour éliminer expliciter les ressources `is_community_resource = true` (pas un bug, mais vaut mieux se prémunir).

Notification GTFS-RT vers GTFS : prend en compte JDD à jour

---

apps/datagouvfr/lib/datagouvfr/client/user.ex
apps/transport/lib/db/contact.ex
apps/transport/lib/transport_web/controllers/session_controller.ex
apps/transport/lib/transport_web/templates/backoffice/contact/form.html.heex
apps/transport/lib/transport_web/views/backoffice/contact_view.ex
apps/transport/priv/repo/migrations/20230427083218_contact_add_datagouv_user_id_last_login_at.exs
apps/transport/test/transport_web/controllers/backoffice/contact_controller_test.exs
apps/transport/test/transport_web/controllers/session_controller_test.exs

Cette PR permet d'associer un utilisateur data.gouv.fr à un `DB.Contact` dans notre base de données, lors de la connexion. Si un contact n'existe pas, le contact est créé à partir des informations récupérées depuis data.gouv.fr.
- 2 colonnes sont ajoutées à `contact`
- `datagouv_user_id` identifiant data.gouv.fr d'un contact
- `last_login_at` dernier datetime de connexion
- l'association d'un utilisateur à un contact est fait lors de la connexion
- en cherchant en priorité à retrouver un contact déjà associé à l'aide de son identifiant
- avec l'adresse e-mail renseignée sur data.gouv.fr
- les infos sur data.gouv.fr sont utilisées pour mettre à jour les données ou créer un contact si on n'a pas pu trouver de contact
- dans tous les cas la date de dernière connexion est enregistrée
La …

Associe un utilisateur à un contact ou crée un contact lors de la connexion

---

apps/datagouvfr/lib/datagouvfr/client.ex
apps/datagouvfr/lib/datagouvfr/client/datasets.ex
apps/transport/lib/transport/data_checker.ex
apps/transport/test/transport/data_checker_test.exs

Fixes #3112
Gère les erreurs HTTP dans le job quotidien qui active/désactive les JDD et les ignore : ne fait rien (surtout pas désactiver le JDD, qui était le comportement précédent).

Gère erreurs HTTP pour DataChecker

---

apps/transport/lib/transport_web/templates/layout/app.html.heex

En lien avec #3123
Adapte le code Matomo pour les propriétés `setCookieDomain` et `setDomains`.
Lien [vers la documentation](https://developer.matomo.org/guides/tracking-javascript-guide#tracking-one-domain-and-its-subdomains-in-the-same-website), "Tracking one domain and its subdomains in the same website"

Mise à jour code Matomo

---

apps/transport/client/stylesheets/espace_producteur.scss
apps/transport/lib/transport_web/templates/resource/form.html.heex
apps/transport/test/transport_web/routing/headers_and_cookies_test.exs

Ajout de règles CSS manquantes sur l'espace producteur, lors de l'ajout d'une ressource.

Espace producteur : ajout CSS pour filler

---

apps/shared/lib/gbfs_metadata.ex
apps/shared/test/gbfs_metadata_test.exs

Pour un futur calcul de score de fraicheur, on va avoir besoin de l'information

Metadata GBFS : ajout info "fraicheur" du flux

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/transport/climate_resilience_bill.ex
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/templates/dataset/_climate_resilience_bill_panel.html.heex
apps/transport/lib/transport_web/templates/dataset/index.html.heex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/priv/gettext/dataset.pot
apps/transport/priv/gettext/en/LC_MESSAGES/dataset.po
apps/transport/priv/gettext/en/LC_MESSAGES/page-shortlist.po
apps/transport/priv/gettext/fr/LC_MESSAGES/dataset.po
apps/transport/priv/gettext/fr/LC_MESSAGES/explore.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-shortlist.po
apps/transport/priv/gettext/page-shortlist.pot
apps/transport/test/transport_web/controllers/dataset_controller_test.exs
apps/transport/test/transport_web/controllers/dataset_search_test.exs
apps/transport/test/transport_web/controllers/dataset_view_test.exs

Lié à #3149
- Ajoute un filtre pour n'afficher que les JDD concernés par l'article 122 de la loi climat et résilience
- Adapte le panel "climat et résilience" quand ce filtre est présent

Ajout d'un filtre pour JDD loi climat et résilience

---

apps/transport/lib/transport_web/controllers/page_controller.ex
apps/transport/lib/transport_web/templates/page/loi_climat_resilience.html.heex

En lien avec #3149
Ajout de tuiles, comme sur la page d'accueil, sur la page "Loi climat et résilience" indiquant le nombre de JDDs concernés par l'article 122 pour chaque type de données et renvoie vers la liste à l'aide du filtre spécifique ajouté dans #3180

Page loi climat et résilience : ajout tuiles

---

apps/transport/lib/db/notification_subscription.ex
apps/transport/lib/jobs/dataset_now_on_nap_notification_job.ex
apps/transport/lib/transport_web/controllers/notification_controller.ex
apps/transport/lib/transport_web/live/send_now_on_nap_notification_view.ex
apps/transport/lib/transport_web/live/validate_dataset_view.ex
apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.heex
apps/transport/lib/transport_web/templates/email/dataset_now_on_nap.html.md
apps/transport/priv/gettext/backoffice_dataset.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice_dataset.po
apps/transport/priv/gettext/en/LC_MESSAGES/notification_subscription.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice_dataset.po
apps/transport/priv/gettext/fr/LC_MESSAGES/notification_subscription.po
apps/transport/priv/gettext/notification_subscription.pot
apps/transport/test/transport/jobs/dataset_now_on_nap_notification_job_test.exs

Fixes #3184
- Ajout d'un bouton permettant d'envoyer un e-mail de bienvenue aux contacts ajoutés à un JDD sur le backoffice. Ce bouton n'est présent que si le JDD a été référencé récemment (< 30 jours) et qu'un e-mail n'a pas encore été envoyé
- Ajout d'un job envoyant cet e-mail aux contacts déjà associés à ce JDD

Backoffice : envoi e-mail lors du référencement d'un JDD

---

apps/transport/lib/transport_web/templates/stats/index.html.heex

Lien mort, déplacé ailleurs. [Voir Mattermost](https://mattermost.incubateur.net/betagouv/pl/x47puq7rxj873qm6mpp3k3hfma)

Page stats : suppression mention covoit FabMob

---

apps/transport/client/javascripts/gtfs.js

J'avais fait une petite erreur pour attraper la bonne couleur dans la palette, parce que j'ai pris une palette à 9 couleurs et pas à 10 couleurs.
C'est pour ça que là ou on a le pus d'arrêts, ça s'affiche en bleu au lieu de rouge.
devient
je me demandais pourquoi on avait toujours un point bleu au milieu de Paris...

Carte des arrêts GTFS : correction couleur

---

apps/transport/lib/jobs/gtfs_import_stops_job.ex
apps/transport/test/transport/jobs/gtfs_import_stops_job_test.exs

Voir:
- #3179
- https://github.com/etalab/transport-site/issues/3178
Fait passer le nombre de `data_import` de 544 à 435, et le nombre de `gtfs_stops` de 890344 à 670898.
Donc on devrait voir un certain nombre de doublons supprimés, ainsi que des soucis comme #3178 réglés.

Amélioration du nettoyage import carte nationale (890k points à 670k)

---

apps/transport/lib/db/dataset.ex
apps/transport/test/db/db_dataset_test.exs

On ne peut actuellement pas passer d'un jeu de donnée associé à une région à un jeu de données national, à cause d'un bug dans le code du changeset.
Je rajoute un test + la correction.
Je me rends aussi compte que deux `cast_assoc` n'ont à priori rien à faire dans le changeset du dataset. De ce que je comprend cette fonction est utile pour mettre à jour les associations enfants d'un schéma, par exemple les `Comments` depuis le changeset d'un `Post`. Mais ici le dataset `belongs_to` une Région, dont il faut juste mettre à jour le `region_id`, pas besoin de `cast_assoc` quoi que ce soit, on ne veut pas modifier la région depuis le changeset du dataset.
closes #3202

Backoffice : fix bug changement région

---

apps/transport/test/transport_web/controllers/resource_controller_test.exs

Vous aviez peut-être vu passer ça dans les logs des tests
ça faisait pas joli :man_artist: 
J'ai eu du mal à localiser le test :hot_face:

Nettoyage des logs d'un test

---

apps/transport/lib/jobs/dataset_quality_score.ex
apps/transport/test/transport/jobs/dataset_quality_score_test.exs

J'avais un trou dans la raquette pour les ressources qu'on ne sait pas noter pour le moment. Ca fait que les jobs correspondants étaient en erreur au lieu de sauvegarder en base des scores `nil`

Correction calcul fraicheur

---

apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/lib/db/notification.ex
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/templates/dataset/_notifications_sent.html.heex
apps/transport/lib/transport_web/templates/dataset/details.html.heex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/lib/validators/gtfs_rt_validator.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot
apps/transport/test/db/notification_test.exs
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

Affiche les notifications envoyées par le PAN lors des 90 derniers jours sur la page de détails d'un jeu de données.
Objectif :
- être transparent sur le fait que le PAN agit pour la qualité des données
- faire découvrir la fonctionnalité des notifications
Voir [la discussion sur Mattermost](https://mattermost.incubateur.net/betagouv/pl/1gjkp6d1cpnztg9xs1unsrkoew)
ℹ️  Il faut la v14 de PostgreSQL en local pour la fonction `date_bin`

Jeu de données : affichage des notifications envoyées

---

apps/shared/lib/gbfs_metadata.ex

Parfois il retournait `61` au lieu de 60 quand le serveur était fatigué.

Test instable

---

apps/transport/lib/transport_web/controllers/resource_controller.ex
apps/transport/lib/transport_web/endpoint.ex
apps/transport/lib/transport_web/plugs/head.ex
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Gère la méthode `HEAD` explicitement pour le téléchargement de ressources diffusées en HTTP. Dans ces cas, on fait "relai" et on rediffuse les données du producteur.
Il arrive que la réponse soit lente (téléchargement long/réponse lente) de notre côté, alors qu'une requête `HEAD` à la source est rapide. Ceci est susceptible de porter préjudice au producteur, par exemple avec une indisponibilité de la ressource suite à une réponse trop lente (voir [sur Mattermost](https://mattermost.incubateur.net/betagouv/pl/or4rbmt4r7yg5my7s5a59yx59r)).

Resource#download : ajout méthode HEAD explicite

---

apps/transport/lib/jobs/on_demand_validation_job.ex
apps/transport/lib/transport_web/live/on_demand_validation_live.html.heex
apps/transport/lib/transport_web/templates/resource/_validation_report_gtfs_rt.html.heex
apps/transport/lib/transport_web/views/resource_view.ex
apps/transport/lib/validators/gtfs_rt_validator.ex
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/validations.pot
apps/transport/test/transport/jobs/on_demand_validation_job_test.exs
apps/transport/test/transport/validators/gtfs_rt_validator_test.exs
apps/transport/test/transport_web/controllers/resource_controller_test.exs
apps/transport/test/transport_web/controllers/validation_controller_test.exs

Fixes #3206
Fixes #2832
Pour le validateur GTFS-RT + la validation à la demande :
- Gère le cas où on a une erreur `OutOfMemory` lors d'une validation GTFS-RT, qui survient lorsqu'on essaie d'analyser les shapes d'un GTFS avec les flux. Dans ce cas la validation est réessayée, en ignorant le traitement des shapes
- Affiche un message pour informer que certaines règles n'ont pas été vérifiées
- Les métadonnées de validation renseignent sur le fait que cette option a été activée `"ignore_shapes": true`

Validateur GTFS-RT : possibilité d'ignorer les shapes

---

apps/datagouvfr/lib/datagouvfr/client/oauth.ex

Fixes #3216
Notre librairie OAuth permet de passer des paramètres au client HTTP, qui est Hackney.
https://github.com/ueberauth/oauth2/blob/7589795f0ef30bc63da7789b924f67e82471c0c4/lib/oauth2/client.ex#L96-L98
Il se trouve que le paramètre de timeout qu'on passait n'était pas le bon.
- `timeout` is the time we keep the connection alive in the pool https://github.com/benoitc/hackney/blob/d6d075f9edcbb7e0b5c9418dba5dd34f2c95bc21/README.md?plain=1#L368
- `recv_timeout` timeout used when receiving data over a connection. Default is 5000 https://github.com/benoitc/hackney/blob/d6d075f9edcbb7e0b5c9418dba5dd34f2c95bc21/doc/hackney.md?plain=1#L364
En utilisant la bonne variable et en faisant x3 par rapport à ce qu'on avait avant, j'espère qu'on dira au revoir aux problèmes constatés.

Client OAuth datagouv : réglage du timeout

---

apps/transport/lib/validators/gtfs_rt_validator.ex
apps/transport/test/transport/jobs/on_demand_validation_job_test.exs
apps/transport/test/transport/validators/gtfs_rt_validator_test.exs

Suite de https://github.com/etalab/transport-site/pull/3209
L'argument était mal passé à l'exécutable java :cry:
Ça donnait
```
Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -ignoreShapes yes
```
J'adapte comment cet argument est donné (et cette fois j'ai bien testé en local :angel:).

Validateur GTFS-RT : option ignoreShapes

---

apps/transport/test/transport_web/live_views/proxy_requests_count_live_test.exs

Ajout de tests pour la LiveView ajoutée dans https://github.com/etalab/transport-site/pull/3220

Ajout tests pour ProxyRequestsCount

---

apps/transport/test/transport_web/live_views/discussions_live_test.exs

Tout est là https://medium.com/elixir-learnings/testing-a-phoenix-liveview-that-does-an-async-operation-after-mount-b8ec27e6c167
Le fait d'appeler `render` envoie un  message à la mailbox de la LiveView, qui arrive après le message envoyé par la fonction `mount` de la LiveView pour faire la requête chez data.gouv. Donc le fait d'appeler `render` dans le test nous assure que l'appel asynchrone dans la LiveView est fait d'abord (mailbox FIFO)

Réparation de test sur DiscussionsLive

---

apps/datagouvfr/lib/datagouvfr/client/user.ex
apps/transport/lib/db/dataset.ex
apps/transport/lib/transport/import_data.ex
apps/transport/lib/transport_web/controllers/notification_controller.ex
apps/transport/lib/transport_web/controllers/page_controller.ex
apps/transport/lib/transport_web/controllers/resource_controller.ex
apps/transport/lib/transport_web/templates/resource/list.html.heex
apps/transport/priv/repo/migrations/20230609122110_dataset_add_organization_id.exs
apps/transport/test/support/factory.ex
apps/transport/test/transport/import_data_test.exs
apps/transport/test/transport_web/controllers/notification_controller_test.exs
apps/transport/test/transport_web/controllers/page_controller_test.exs
apps/transport/test/transport_web/controllers/resource_controller_test.exs
apps/transport/test/transport_web/live_views/discussions_live_test.exs

Le retour de #3216
Problème : pour certains utilisateurs qui sont membre d'une organisation sur data.gouv.fr avec beaucoup de JDD (> 250), l'API `/user/org_datasets` peut avoir des temps de réponse > 15s ([voir Mattermost](https://mattermost.incubateur.net/betagouv/pl/67ec6b1j6pn63bpf7gcrfp8uur)), ce qui empêche le chargement de pages comme l'Espace producteur / gestion des notifications.
L'idée est de retrouver les organisations dont est membre l'utilisateur (avec `/api/me`) et d'utiliser ces identifiants d'organisations pour retrouver les JDD correspondants.
- Ajout de `organization_id` sur `dataset`
- Faire en sorte que ce soit rempli lors de l'import
- Supprime l'ancien code/utilise l'endpoint `me` pour retrouver les JDD pertinents
En mergeant, on va ajouter une colonne …

Récupérer JDD pour un utilisateur

---

apps/transport/lib/jobs/datasets_climate_resilience_bill_not_lo_licence_job.ex
apps/transport/lib/transport_web/templates/email/datasets_climate_resilience_bill_inappropriate_licence.html.heex
apps/transport/lib/transport_web/views/email_view.ex
apps/transport/test/transport/jobs/datasets_climate_resilience_bill_not_lo_licence_job_test.exs
config/runtime.exs

En lien avec #3228
Détecte les JDD article 122 qui passe à une licence différente de la LO, retire le tag `loi-climat-resilience` et prévient notre équipe bizdev pour prendre contact avec les producteurs.
Le job est planifié du lundi au vendredi.

Job quotidien identifiant JDD article 122 avec licence non LO

---

apps/transport/lib/jobs/datasets_climate_resilience_bill_not_lo_licence_job.ex
apps/transport/test/transport/jobs/datasets_climate_resilience_bill_not_lo_licence_job_test.exs

Suite de https://github.com/etalab/transport-site/pull/3229
Inutile d'envoyer un e-mail quand il y a 0 JDD concernés, sinon on envoie un corps vide. Je gère donc ce cas, et j'ajoute un test.
Navré !

Article 122 avec mauvaise licence : gère cas sans JDD

---

apps/transport/lib/db/dataset_score.ex
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/templates/dataset/details.html.heex
apps/transport/test/db/dataset_score_test.exs

je rajoute sur chaque page dataset le score de fraicheur du dataset, uniquement pour les membre de l'équipe lorsqu'ils sont connectés.

Score de fraicheur sur le site pour l'équipe PAN

---

apps/transport/lib/transport_web/controllers/page_controller.ex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/layout/app.html.heex
apps/transport/test/transport_web/controllers/page_controller_test.exs

Ajout d'une page [humans.txt](https://humanstxt.org/) pour rendre hommage aux personnes qui font/ont fait le PAN. Utilise [l'API de beta.gouv.fr](https://github.com/betagouv/beta.gouv.fr/tree/master/api)

Ajout page humans.txt

---

apps/transport/lib/transport_web/views/markdown_handler.ex
apps/transport/test/transport_web/views/markdown_handler_test.exs

Cette MR utilise une option de EarmarkParser, ici https://github.com/RobertDober/earmark_parser#breaks sur laquelle s’appuie le wrapper Earmark que l’on utilise, qui permet de gérer les retours à la ligne simple de Markdown sans créer de nouveau paragraphe. Un simple `\n` dans le markdown va donc créer un line break html `<br \>` au lieu d’être ignoré.
J’en profite pour rajouter de nouveaux tests.
Fixes #3163

Gestion des retours à la ligne simples dans les commentaires datagouv

---

apps/transport/client/javascripts/dataset-map.js
apps/transport/client/javascripts/explore.js
apps/transport/client/javascripts/gtfs.js
apps/transport/client/javascripts/map-geojson.js
apps/transport/client/javascripts/map.js
apps/transport/client/javascripts/mapbox-credentials.js
apps/transport/client/javascripts/resource-viz.js
apps/transport/client/javascripts/validation-map.js

closes #2214 
Ne pas merger tout de suite, on va attendre de mettre la carte de Pathtech sur le nouveau compte Mapbox
Mais je pense qu'on va peut être plus devoir payer, parce qu'on peut demander des tuiles de 512*512 au lieu de 256*256 et donc en consommer 4 fois moins ! Il y a moyen qu'on revienne dans le free tier avec ça.

Update mapbox vector tiles url and key

---

apps/transport/lib/transport_web/templates/backoffice/page/index.html.heex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po

Rajout d’un lien vers le dashboard d’ouverture des données par AOM dans le backoffice

---

apps/datagouvfr/lib/datagouvfr/client/user.ex
apps/transport/lib/db/contact.ex
apps/transport/lib/db/organization.ex
apps/transport/lib/transport_web/controllers/notification_controller.ex
apps/transport/lib/transport_web/controllers/session_controller.ex
apps/transport/priv/repo/migrations/20230630074914_add_organization.exs
apps/transport/test/db/contact_test.exs
apps/transport/test/transport_web/controllers/notification_controller_test.exs
apps/transport/test/transport_web/controllers/session_controller_test.exs

Ajout d'une nouvelle table `organization` contenant les données des organisations data.gouv.fr. Ces données sont remplies pour le moment par le biais de la connexion des utilisateurs, plus tard il faudra mettre à jour ces données plus fréquemment et avoir un many-to-many avec `dataset`

Ajout table organization

---

scripts/irve/dynamic-irve.exs
scripts/irve/req_custom_cache.exs

En lien avec:
- https://github.com/etalab/transport-site/issues/3219
Cela permet d'afficher l'url du dataset et aussi le nombre de lignes dans la ressource CSV, ça nous a servi avec @cyrilmorin aujourd'hui.

Amélioration du script d'analyse des IRVE dynamiques

---

apps/gbfs/mix.exs
apps/unlock/mix.exs

Ils consomment l'essentiel des events et on va dépasser le quota rapidement au final.
Voir:
- #3274 
Je propose de déployer en l'état et de vérifier que ça suffit (sachant qu'on a une application umbrella).

Tentative de suppression de l'instrumentation AppSignal sur les proxies

---

apps/transport/lib/transport_web/controllers/aoms.ex
apps/transport/test/transport_web/controllers/aoms_controller_test.exs

Fixes #3276
J'ai retravaillé le controller pour éviter de faire 2 fois une requête. Je rends la première requête légèrement plus générique et j'utilise `Enum.group_by` pour assembler les bouts nécessaires.
En local, avec un dump de prod du jour je suis sous les 2s.

Améliore les performances pour /aoms

---

apps/transport/lib/db/contact.ex
apps/transport/test/db/contact_test.exs
apps/transport/test/support/factory.ex

Fixes #3281
Bug constaté : quand on crée/met à jour un contact, le code actuel tente dans tous les cas de créer une organisation, même si celle-ci existe.
Cette  PR adapte le code pour gérer le cas. Doc pertinente, [Constraints and Upserts](https://hexdocs.pm/ecto/constraints-and-upserts.html)

Contact et organisations : ne pas créer de doublons

---

apps/gbfs/lib/gbfs/router.ex
apps/gbfs/mix.exs
apps/shared/lib/appsignal_filter.ex
apps/shared/mix.exs
apps/unlock/lib/router.ex
apps/unlock/mix.exs
config/config.exs

~~:warning: ce n'est pas bon, je ne reçois plus aucune donnée (EDIT: tout agrégé sous `[GET /*_path](https://appsignal.com/transport-dot-data-dot-gouv-dot-fr/sites/64a294f583eb67b60f035246/actions/web/GET%20%2F*_path)`) sur le staging après réactivation de la clé d'API, donc la PR semble poser un problème quelque part~~
Dans cette PR:
- Je tente de réduire l'utilisation du quota en filtrant les requêtes proxy et GBFS (https://github.com/etalab/transport-site/issues/3274, https://github.com/appsignal/appsignal-elixir/issues/865)
- Je supprime les données de session et les paramètres de ce qui est envoyé, car cela contient de la donnée sensible (https://github.com/etalab/transport_deploy/issues/64) - mais ça ne purgera pas ce qui a déjà été envoyé (je verrai avec le support si on peut faire …

Ajustements pour AppSignal

---

apps/transport/lib/transport/import_data.ex

Fixes #3277
Je suis **hyper** étonné que le code utilise actuellement uniquement le `format` pour le nettoyer alors qu'on a plein de logique qui utilise d'autres signaux dans le même code (titre, URL, description) ! 😱 
https://github.com/etalab/transport-site/blob/10ef2e8862015ae1411eb915f0f9afd88b784d7b/apps/transport/lib/transport/import_data.ex#L665-L675
Je change donc le code actuel où il est important de pouvoir se rattraper à d'autres signaux.

ImportData : utilisation des infos de la ressource

---

apps/transport/lib/transport/availability_checker.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/test/transport/availability_checker_test.exs

Il arrive que des endpoints SIRI répondent des 405 en HEAD ou en GET, ce qui n'est pas si étonnant que ça.
Pour ne pas les pénaliser pour le moment, on accepte ces réponses, uniquement pour des ressources SIRI.
Il faudra supprimer l'indisponibilité de [la ressource SIRI](https://transport.data.gouv.fr/resources/81029)
```sql
delete from resource_unavailability where resource_id = 81029;
```

AvailabilityChecker : accepte réponse 405 pour SIRI

---

apps/transport/lib/db/contact.ex
apps/transport/lib/transport_web/controllers/session_controller.ex
apps/transport/test/db/contact_test.exs
apps/transport/test/transport_web/controllers/session_controller_test.exs

Corrige un bug lié aux organisations des contacts : quand les infos sur les organisations n'étaient pas passées, le contact n'était plus associé aux organisations.
J'adapte le code pour mettre à jour les infos sur ses organisations uniquement quand on passe les clés pertinentes, le reste du temps on n'y touche pas.
En regardant [put_assoc/4](https://hexdocs.pm/ecto/Ecto.Changeset.html#put_assoc/4)
> This function is used to work with associations as a whole. For example, if a Post has many Comments, it allows you to add, remove or change all comments at once.
Le code précédent donnait `[]` à `put_assoc` quand la clé était absente, supprimant les associations existantes.
À noter que le bug n'était pas si voyant car https://github.com/etalab/transport-site/pull/3271 met à jour les …

Contact : mise à jour des organisations explicite

---

apps/transport/lib/transport/data_checker.ex
apps/transport/test/transport/data_checker_test.exs

Indique si un JDD est soumis à l'article 122 pour l'e-mail adressé à notre équipe pour faciliter le suivi de la péremption des JDDs.
[Exemple d'un e-mail existant](https://app.frontapp.com/open/cnv_xrpw1ue?key=IIwRSvbyroXRloYRL8Dj9aU32nEWuIL7)

Data checker : indique si JDD est soumis à l'article 122

---

apps/transport/lib/transport_web/live/backoffice/custom_tags_live.ex

Documente les valeurs de `custom_tags` qui ont un effet en terme de fonctionnalités.

Backoffice : ajout documentation pour custom_tags

---

apps/datagouvfr/lib/datagouvfr/client/api.ex
apps/shared/lib/gbfs_metadata.ex
apps/shared/lib/hasher.ex
apps/transport/lib/db/dataset.ex
apps/transport/lib/jobs/oban_logger.ex
apps/transport/lib/mix/tasks/transport/import_epci.ex
apps/transport/lib/opendatasoft/url_extractor.ex
apps/transport/lib/transport/community_resource_cleaner.ex
apps/transport/lib/transport/import_data.ex
apps/unlock/lib/controller.ex

Lié à #3307, [gère la hard deprecation de Elixir 1.15](https://hexdocs.pm/elixir/1.15/changelog.html#4-hard-deprecations)

Logger.warn est déprécié

---

apps/transport/lib/jobs/geo_data/base.ex
apps/transport/lib/jobs/geo_data/bnlc_to_geo_data.ex
apps/transport/lib/jobs/geo_data/irve_to_geo_data.ex
apps/transport/lib/jobs/geo_data/parkings_relais_to_geo_data.ex
apps/transport/test/transport/jobs/dataset_history_job_test.exs
apps/transport/test/transport/jobs/geo_data/bnlc_to_geodata_test.exs
apps/transport/test/transport/jobs/geo_data/irve_to_geodata_test.exs
apps/transport/test/transport/jobs/geo_data/lez_to_geo_data_test.exs
apps/transport/test/transport/jobs/geo_data/parkings_relais_to_geo_data_test.exs
config/runtime.exs

Cette PR rajoute un job Oban pour importer la base de donnée consolidée des IRVE dans la table GeoData. Cela permettra par la suite d’afficher ces IRVE dans la carte d’exploration (voir #3246).

3246 Rajout des IRVE dans les GeoData

---

apps/transport/lib/jobs/gtfs_rt_metadata.ex
apps/transport/test/transport/jobs/gtfs_rt_entities_test.exs
apps/transport/test/transport/jobs/gtfs_rt_metadata_test.exs

Ajout d'un mécanisme pour ne pas garder le nombre d'entités GTFS-RT tout le temps, ne garder que 3 mois d'historique détaillé parait approprié.

GTFSRTEntitiesDispatcherJob : suppression de métadonnées anciennes

---

config/runtime.exs

Le tracking de déploiement est utile pour détecter plus facilement les régressions (erreurs / performance) ou à l'inverse les améliorations.

Suivi des déploiements applicatifs avec AppSignal

---

apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/backoffice/page/index.html.heex
apps/transport/test/transport_web/controllers/backoffice/page_controller_test.exs

Fixes #3321
Ajout d'un bouton pour télécharger un CSV depuis le backoffice qui contient les données décrites par @cyrilmorin dans l'issue. L'échelle est celui des ressources mais on va remonter au JDD, validations, métadonnées etc.
La requête SQL est "assez moche" mais elle fait le travail et s'exécute en 250ms en production. Elle n'est pas testée vu l'usage beta actuel et le fait que c'est réservé à notre équipe. Une review est bienvenue pour autant !

Backoffice : ajout d'un export général

---

apps/transport/client/javascripts/explore.js
apps/transport/lib/transport_web/templates/layout/app.html.heex

Enregistre des événements dans Matomo lorsqu'un utilisateur choisit d'afficher un layer sur la carte d'exploration. Juste pour avoir des chiffres :wink:

Carte d'exploration : tracking au clic par layer

---

apps/transport/lib/db/dataset.ex
apps/transport/priv/repo/migrations/20230719124102_dataset_legal_owner_company_siren_type.exs
apps/transport/test/db/db_dataset_test.exs
apps/transport/test/transport_web/controllers/backoffice/dataset_controller_test.exs
apps/transport/test/transport_web/live_views/edit_dataset_live_test.exs

Fixes #3338
- Passe de integer à string
- Vérifie que le SIREN a le bon format lors de l'insertion

Change type pour dataset.legal_owner_company_siren

---

apps/transport/lib/transport_web/api/controllers/datasets_controller.ex

Cette PR met en cache les opérations suivantes:
- `/api/datasets` (index de l'API)
- `/api/datasets/:id` (détail API d'un dataset, avec ses ressources et history)
Car, comme vu dans :
- #3302 
- #3334
ces deux opérations comptent parmi les plus utilisées (même si le débit total est faible actuellement), et les plus longues à calculer.
L'objectif de la PR n'est pas tant d'accélérer le comportement pour les utilisateurs (ça ne sera que peu le cas je pense, même si je vérifierai après coup avec AppSignal), que de nous protéger contre un traffic un peu plus poussé qui ferait planter les connections à la base de données.

Mise en cache `/api/datasets` et `/api/datasets:id`

---

apps/transport/lib/db/notification_subscription.ex
apps/transport/lib/jobs/resources_changed_notification_job.ex
apps/transport/lib/transport_web/templates/email/resources_changed.html.md
apps/transport/priv/gettext/en/LC_MESSAGES/notification_subscription.po
apps/transport/priv/gettext/fr/LC_MESSAGES/notification_subscription.po
apps/transport/priv/gettext/notification_subscription.pot
apps/transport/test/transport/jobs/resources_changed_notification_job_test.exs

Ajoute une nouvelle notification envoyée quand les ressources d'un JDD ont changé. Les cas identifiés :
- une ressource a été supprimée
- une ressource a été ajoutée
- une URL de téléchargement a été modifiée
On envoie du texte assez simple
```
Sujet : $NOM_JDD : ressources modifiées
Bonjour,
Les ressources du jeu de données URL + TITRE viennent d'être modifiées (ajout/suppression de ressources ou modification d'URLs de téléchargement).
L’équipe du PAN
```
Pour l'instant il est impossible de s'inscrire à cette notification, elle aura sa place dans un futur espace réutilisateur #3231. À voir si on montre le détail des notifications qu'on a ou si on inscrit à un package de notifications, sans détailler.

Ajout d'une notification quand les ressources ont changé

---

apps/transport/lib/db/contact.ex
apps/transport/lib/transport_web/controllers/backoffice/contact_controller.ex
apps/transport/lib/transport_web/templates/backoffice/contact/index.html.heex
apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.heex
apps/transport/lib/transport_web/views/backoffice/contact_view.ex
apps/transport/lib/transport_web/views/backoffice/page_view.ex
apps/transport/test/db/contact_test.exs
apps/transport/test/transport_web/controllers/backoffice/contact_controller_test.exs
apps/transport/test/transport_web/views/backoffice/page_view_test.exs

Fixes #3344
- Permet de rechercher des noms de famille de manière partielle et non sensible à la casse sur `/backoffice/contacts` (c'était possible auparavant, mais la comparaison était effectuée avec des `ts_vector`, il y a du `ilike` en plus maintenant)
- Génération des versions non accentuées en plus (quand nécessaire) dans les `datalist` qui aident à trouver les contacts existants (partie recherche de contact dans la section Contacts + depuis un JDD)

Amélioration de la recherche de contacts dans le backoffice

---

apps/transport/lib/transport_web/controllers/backoffice/contact_controller.ex
apps/transport/lib/transport_web/views/backoffice/page_view.ex
apps/transport/test/transport_web/controllers/backoffice/contact_controller_test.exs

Répare un bug introduit dans https://github.com/etalab/transport-site/pull/3348 : on avait une exception pour les contacts qui ont `last_name = null` provoqué par `unaccent`.
```
:unicode.characters_to_nfd_binary/1 at line 895
errors were found at the given arguments:
* 1st argument: not valid character data (an iodata term)
```
- ignore les valeurs nulles
- gère `nil` pour `unaccent`

Contacts : ignorer valeurs nulles

---

apps/transport/lib/transport/availability_checker.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/test/transport/availability_checker_test.exs

Similaire à https://github.com/etalab/transport-site/pull/3287
Autorise les réponses 401 ou 405 pour les flux SIRI Lite, ce qu'on autorise déjà pour les flux SIRI. Ces 2 fluxs ont souvent des authentifications, on ne souhaite pas considérer ces ressources comme indisponibles.
[Voir ticket](https://app.frontapp.com/open/cnv_xm25uc6?key=jKJI2Biljhp1W1pzz8GLNt8JCACa20oV)

AvailabilityChecker : autorise 401 ou 405 pour SIRI Lite

---

apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/lib/transport_web/live/discussions_live.ex
apps/transport/lib/transport_web/templates/dataset/_dataset_resources_history.html.heex
apps/transport/lib/transport_web/templates/dataset/_notifications_sent.html.heex
apps/transport/lib/transport_web/templates/dataset/details.html.heex

Il y a intérêt d’après @AntoineAugusti d’avoir l’historique de toutes les resources liées à un dataset sur une même liste, sur la page du dataset, pour comprendre si ils ont changé le nom des fichiers par exemple. Du coup cette PR laisse le code tel quel et rajoute juste un addseemore, tout en bougeant vers son propre template.
Avec 3 resources historiques / avec plus de 3 :

Ne montrer que les 3 plus récentes resources historisées

---

apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/client/stylesheets/components/_discussions.scss

Corrige un bug introduit dans https://github.com/etalab/transport-site/pull/3358, les sélecteurs CSS n'étaient pas bon : on ciblait par exemple `.discussion` au lieu `.discussion .displayMore`. Résultat : tous les commentaires étaient centrés, et non seulement le bouton "voir plus".
J'en profite pour corriger un padding-left.

Correction bug CSS text-align

---

apps/transport/lib/jobs/new_datagouv_datasets_job.ex
apps/transport/test/transport/jobs/new_datagouv_datasets_job_test.exs

Ignore certains jeux de données publiés de manière quotidienne par une organisation spécifique. [Exemple d'un JDD](https://www.data.gouv.fr/fr/datasets/bdtopo-c-terrains-de-sport-pour-le-departement-de-lindre-et-loire/)

Nouveaux JDD à référencer : ignore BDTOPO

---

apps/transport/lib/transport_web/templates/resource/_coordinates_issue.html.heex

Fixes #3357
Les erreurs `InvalidCoordinates` et `MissingCoordinates` peuvent concerner stops OU shapes, adapte le template en conséquence.

Validation GTFS : erreur coordonnées pour shapes

---

apps/shared/lib/validation/tableschema_validator.ex
apps/shared/test/validation/tableschema_validator_test.exs

Voir [Désactiver la sensibilité à la casse dans l'en-tête](https://git.opendatafrance.net/validata/validata-core/-/issues/25) côté Validata.
Désactive la sensibilité à la casse des en-têtes pour la validation des schémas TableSchema, pour se conformer à ce que constatent les producteurs sur publier.etalab.studio et sur l'interface web de Validata.

Validation TableSchema : ignore casse des headers

---

apps/transport/lib/transport_web/controllers/session_controller.ex
apps/transport/test/transport_web/controllers/session_controller_test.exs

Fixes #3367
N'enregistre pas toutes les organisations dans le cookie de session, les utilisateurs avec trop d'organisations ont alors un cookie trop gros.
Les organisations ne sont pas récupérées directement en lisant la session plus, on repasse par l'API data.gouv.fr pour l'utilisateur en cas de besoin.

SessionController : filtre les organisations

---

apps/transport/lib/db/dataset.ex
apps/transport/test/db/db_dataset_test.exs

J'ai remarqué que des espaces étaient souvent ajoutés en fin de valeur, rempli par notre équipe dans le backoffice.

Dataset : suppression espaces pour custom_title

---

apps/transport/lib/db/dataset_score.ex
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/templates/dataset/_dataset_scores.html.heex
apps/transport/lib/transport_web/templates/dataset/details.html.heex
apps/transport/test/db/dataset_score_test.exs
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

- Affiche le score de disponibilité (introduit dans #3333) sur la page `dataset#details` pour les admins
- Ajoute les méthodes requises
- Couverture de tests adéquate

Affiche score de disponibilité

---

config/runtime.exs

Comme indiqué dans https://github.com/etalab/transport-site/pull/3347#issuecomment-1650201467, planifie l'exécution du job en charge de prévenir des réutilisateurs si il y a des modifications de ressources. Personne ne peut s'inscrire à ce motif pour l'instant, ce sera dans l'espace réutilisateurs.
Le job d'avant est planifié à 21h, les différents jobs exécutés ensuite ont terminé hier à 21:01:08, ça me parait donc assez large.

Planifie ResourcesChangedNotificationJob

---

apps/transport/client/javascripts/vega.js
apps/transport/client/package.json
apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/client/webpack.common.js
apps/transport/client/yarn.lock
apps/transport/lib/db/dataset_score.ex
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/templates/dataset/_dataset_resources_history.html.heex
apps/transport/lib/transport_web/templates/dataset/_dataset_scores.html.heex
apps/transport/lib/transport_web/templates/dataset/_dataset_scores_chart.html.heex
apps/transport/lib/transport_web/templates/dataset/details.html.heex
apps/transport/mix.exs
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot
apps/transport/test/db/dataset_score_test.exs
apps/transport/test/transport_web/controllers/dataset_controller_test.exs
mix.lock

- Ajout de [Vega Lite](https://vega.github.io/vega-lite/) pour afficher des graphiques sur le site web
- Permet de récupérer les scores d'un JDD au cours des _n_ derniers jours
- Affiche les scores d'un JDD sur `dataset#details` uniquement pour les admins

Affichage d'un graphique pour les scores d'un JDD

---

apps/transport/test/documentation_links_test.exs
apps/transport/test/test_helper.exs

Ajoute un test à notre suite, qui ne sera exécuté qu'en CI. J'ai repris une bonne partie du code dans https://github.com/etalab/transport-site/issues/2579#issuecomment-1667451745, merci @thbar !
C'est l'occasion de voir quelques surprises :grimacing:

Ajout test liens valides pour la documentation

---

apps/transport/lib/transport_web/plugs/custom_secure_browser_headers.ex
apps/transport/lib/transport_web/templates/dataset/_dataset_scores_chart.html.heex

#3375 n'était pas suffisant, j'adopte une des solutions proposée dans https://github.com/vega/vega-embed/issues/1214#issuecomment-1670812445. Peut-être qu'on pourra spécifier le `nonce` dans Vega Embed plus tard.

Adapte CSP pour style sur Vega Embed

---

apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/dataset/_community_resources.html.heex
apps/transport/lib/transport_web/templates/dataset/_notifications_sent.html.heex
apps/transport/lib/transport_web/templates/email/dataset_now_on_nap.html.md
apps/transport/lib/transport_web/templates/email/producer_with_subscriptions.html.md
apps/transport/lib/transport_web/templates/email/producer_without_subscriptions.html.md
apps/transport/lib/transport_web/templates/layout/_footer.html.heex
apps/transport/lib/transport_web/templates/notification/index.html.heex
apps/transport/lib/transport_web/templates/page/index.html.heex
apps/transport/lib/transport_web/templates/page/infos_producteurs.html.heex
apps/transport/lib/transport_web/templates/stats/index.html.heex

Remplace les liens avec ceux indiqués dans https://github.com/etalab/transport-site/issues/2579#issuecomment-1669710754
`mix test apps/transport/test --only documentation_links` passe sur ma machine ensuite

Mise à jour liens documentation

---

apps/transport/lib/db/dataset_score.ex
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/templates/dataset/_dataset_scores.html.heex
apps/transport/test/db/dataset_score_test.exs
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

#3382 n'était pas aussi anecdotique que ça, ça engendre des 500 quand `score: nil`.
J'améliore le code et ajoute pas mal de tests.
[Voir Sentry](https://transport-data-gouv-fr.sentry.io/issues/4382715635/)

Gère DB.DatasetScore.score nil pour affichage

---

apps/transport/lib/transport_web/live/backoffice/custom_tags_live.ex
apps/transport/test/transport_web/live_views/custom_tags_live_test.exs

Mauvaise nouvelle, certains systèmes demandent un requestor ref SIRI en majuscules.
On peut les renseigner à l'aide d'un tag dans notre backoffice https://github.com/etalab/transport-site/pull/3291 mais notre système lowercase chaque tag.
Cette PR ne lowercase pas automatiquement un tag de requestor ref SIRI.

CustomTagsInput : ne pas lowercase un tag requestor_ref

---

apps/transport/client/javascripts/utils.js
apps/transport/lib/transport_web/live/discussions_live.ex
apps/transport/lib/transport_web/templates/dataset/_dataset_resources_history.html.heex
apps/transport/lib/transport_web/templates/dataset/_notifications_sent.html.heex
apps/transport/lib/transport_web/templates/resource/gtfs_details.html.heex

Similaire à ce qui a été fait dans #3343
On a ajouté à plusieurs endroits récemment des éléments d'interface pour déplier/replier. Le code de tracking permettra de voir à quel point ceci est utilisé, en groupant par fonctionnalité : ressources historisées / commentaires / notifications envoyées etc.

AddSeeMore : tracking JS au clic

---

apps/transport/lib/jobs/multi_validation_with_error_notification_job.ex
apps/transport/lib/jobs/resource_unavailable_notification_job.ex
apps/transport/test/support/factory.ex
apps/transport/test/transport/jobs/multi_validation_with_error_notification_job_test.exs
apps/transport/test/transport/jobs/resource_unavailable_notification_job_test.exs

Ajuste le délai d'envoi minimum pour un jeu de données : on passe de 15 jours à 7 jours.
Ceci s'applique aux motifs :
- erreurs sur un JDD (erreur + fatal pour GTFS)
- ressource indisponible pendant au moins 6h consécutives
ces 2 événements sont assez rares et importants, ne pas envoyer un e-mail parce que c'est déjà survenu au cours des 15 derniers jours parait un peu trop.

Ajuste délai minimum entre 2 notifications : 7 jours

---

apps/transport/lib/jobs/datasets_switching_climate_resilience_bill_job.ex
apps/transport/lib/transport_web/templates/email/dataset_with_error_producer.html.md
apps/transport/lib/transport_web/templates/email/dataset_with_error_reuser.html.md
apps/transport/lib/transport_web/templates/email/datasets_climate_resilience_bill_inappropriate_licence.html.heex
apps/transport/lib/transport_web/templates/email/datasets_switching_climate_resilience_bill.html.md
apps/transport/lib/transport_web/templates/email/producer_with_subscriptions.html.md
apps/transport/lib/transport_web/templates/email/producer_without_subscriptions.html.md
apps/transport/lib/transport_web/templates/email/resource_unavailable_producer.html.md
apps/transport/lib/transport_web/templates/email/resource_unavailable_reuser.html.md
apps/transport/lib/transport_web/templates/email/resources_changed.html.md
apps/transport/lib/transport_web/views/email_view.ex
apps/transport/test/transport/jobs/datasets_switching_climate_resilience_bill_job_test.exs

Convertit une notification envoyée (JDD qui deviennent soumis à l'article 122 ou qui ne le sont plus) au format Markdown pour une meilleure expérience pour les destinataires.

DatasetsSwitchingClimateResilienceBillJob : conversion e-mail en Markdown

---

apps/transport/lib/jobs/database_backup_replication_job.ex
apps/transport/lib/jobs/oban_logger.ex
apps/transport/lib/transport/application.ex
apps/transport/test/transport/jobs/database_backup_replication_job_test.exs
apps/transport/test/transport/jobs/oban_logger_test.exs
config/config.exs

Adapte le logger Oban pour permettre d'envoyer un e-mail à notre équipe tech en cas d'échec sur certains jobs.
Applique ce nouveau mécanisme à `DatabaseBackupReplicationJob`, job dont l'exécution est importante.

ObanLogger : email en cas d'erreur pour certains jobs

---

apps/transport/lib/transport/data_checker.ex

Adapte le texte envoyé en fin de notification pour les notifications `:expiration` et `:new_dataset`.
Le précédent texte était "ancien", avant qu'on ait un espace producteur et la doc associée.
Dans un monde idéal (et un refactor à suivre un jour je l'espère) on aurait une meilleure gestion des templates de notifications pour mettre ça au même endroit.

DataChecker : adapte footer gérer les notifications

---

apps/transport/lib/transport/data_checker.ex
apps/transport/lib/transport_web/templates/email/expiration_producer.html.md
apps/transport/test/transport/data_checker_test.exs

Retravaille https://github.com/etalab/transport-site/pull/3403, les templates n'étaient pas encore en HTML il n'était donc pas possible d'utiliser le code.
Passe le template envoyé aux producteurs pour une notification `:expiration` en HTML et adapte les tests.

DataChecker : passe email expiration en HTML

---

apps/transport/lib/transport_web/templates/email/expiration_producer.html.md
apps/transport/test/transport/data_checker_test.exs
apps/transport/test/transport_web/views/no_html_in_markdown_templates.exs

Répare un bug introduit dans https://github.com/etalab/transport-site/pull/3409, qui tentait déjà de corriger un autre bug :grimacing:
Mon erreur était de mettre des liens en HTML dans un template Markdown `.html.md`. Le moteur de template a (trop sympa) transformé les `<a href="">` en `<a href=””>` (_smart quotes_) ce qui n'est plus du code HTML valide.
Corrige ce bug et ajoute un test pour vérifier qu'on n'essaie pas de mettre des liens HTML dans du `*.html.md`

Corrige liens HTML pour e-mail :expiration

---

apps/transport/lib/transport/import_data.ex

Regarde description, titre et URL comme pour pas mal d'autres formats. Malheureusement regarder uniquement le format n'est pas suffisant pour les ressources qui proviennent de plateformes tierces où le format n'est pas controlé par l'utilisateur ([voir discussion](https://mattermost.incubateur.net/betagouv/pl/bhnh4auxn3n5fxgonywt5gt9ic)).

ImportData : détection plus large du SIRI

---

apps/transport/lib/transport/import_data.ex
apps/transport/test/transport/import_data_test.exs

Suite de #3415
La détection SIRI / SIRI Lite était ok, mais plus loin dans le process d'import, `formated_format` se base uniquement sur le format pour garder en SIRI :cry: (`is_siri?(format) -> "SIRI"`).
Fait comme pour le NeTEx, change le format lorsqu'on a bien détecté que c'était une ressource NeTEx. Ce n'était pas si bête que ça.
Bref, encore une suite de PRs qui montre que `Transport.ImportData` est fragile et mérite un refactor pour assurer plus de sécurité/stabilité.

ImportData: changement format pour SIRI et SIRI Lite

---

apps/transport/lib/transport/import_aom.ex
apps/transport/priv/repo/migrations/20230828142610_aom_trim_departement.exs

Fixes #3423
- migration de BDD pour supprimer les espaces dans `aom.departement`
- modification du code d'import pour `trim` plusieurs champs (pas vu d'autres écarts)

AOMs : pas d'espaces pour les départements

---

docs/scaleway/README.md
docs/scaleway/bucket_lifecycle_configuration_production.json
docs/scaleway/bucket_lifecycle_configuration_staging.json

Fixes https://github.com/etalab/transport-site/issues/3406
- Adapte les lifecycle rules de nos 2 buckets contenant une réplication de nos sauvegardes de bases de données afin de supprimer les uploads incomplets au bout d'1 jour. J'ai suivi [la configuration](https://www.scaleway.com/en/docs/storage/object/api-cli/lifecycle-rules-api/#setting-rules-for-incomplete-multipart-uploads).
- Ajoute un README de documentation générale présentant le contenu de ce dossier
Ceci a déjà été appliqué en staging et production, exemple de commande
```
aws --endpoint-url "https://s3.fr-par.scw.cloud" --region fr-par s3api put-bucket-lifecycle-configuration --lifecycle-configuration file://$(pwd)/docs/scaleway/bucket_lifecycle_configuration_production.json --bucket transport-prod-backups
```
J'ai vérifié …

Buckets Scaleway : ajuste lifecycle rules

---

apps/transport/lib/jobs/database_backup_replication_job.ex
apps/transport/test/transport/jobs/database_backup_replication_job_test.exs

Détecté suite à [ce ticket dans Front](https://app.frontapp.com/open/msg_1qn80tue?key=8gPjICa3JQ_nqAm9uaJweY-Vv_czc0xg)
On dépasse ce jour la taille de 1 GB pour le backup de notre base de données en production.
Le code actuel lève une erreur dans ce cas (l'objectif était de nous alerter sur un dump potentiellement faux/nous inviter à revoir notre stratégie).
Comme on est OK avec la croissance de la taille de ce fichier, adapte la taille max à 10 GB.

Mise à jour taille max backup de base de données

---

apps/transport/lib/transport_web/live/discussions_live.ex

fixes #3436 
Plutôt que prendre l’ordre des commentaires dans le retour API pour connaître le dernier commentaire, on s’appuie sur les dates de publication.

Répare discussions repliées

---

apps/transport/lib/transport_web/live/discussions_live.ex
scripts/req_stream.exs

Pour en discuter entre dévs:
- #3446 
- #3447
J'ai fait un test de streaming avec Req, ça fonctionne pas mal. Ca pose des questions sur est-ce qu'on décode ou pas le body, compression etc.
J'ai pensé notamment à ces bouts de code:
https://github.com/etalab/transport-site/blob/2ccb1ed1e58e5c4889d28453f285dc434fd49110/apps/transport/lib/jobs/resource_history_job.ex#L245-L250
Le body est conservé en RAM car il est ensuite passé comme argument à l'upload S3:
https://github.com/etalab/transport-site/blob/2ccb1ed1e58e5c4889d28453f285dc434fd49110/apps/transport/lib/jobs/resource_history_job.ex#L140
Qui actuellement ne fait pas de streaming:
https://github.com/etalab/transport-site/blob/2ccb1ed1e58e5c4889d28453f285dc434fd49110/apps/transport/lib/S3/s3.ex#L35-L46
Mais cela est supporté: …

Exemple de script qui fait du streaming direct vers le disque

---

apps/transport/priv/repo/migrations/20230913130308_metrics_gbfs_target_name.exs

Fixes https://github.com/etalab/transport-site/issues/3458
Une migration changeant le nom des mauvaises valeurs des événements devrait être suffisant.
En plusieurs étapes :
- correction du nom de l'événement innaproprié pour avoir le bon nom (`gbfs:besancon/` vers `gbfs:besancon`)
- https://github.com/etalab/transport-site/blob/e25f9c70641063a5152201fdef87ce60fa97c395/apps/transport/lib/jobs/archive_metrics_job.ex#L81, `Transport.Jobs.ArchiveMetricsJob` est en charge de consolider les metrics au bout d'un moment (90 jours) qui se base sur des doublons de date/event/target (qui vont être présents étant donné qu'on va avoir changé la valeur de `target`).
On aura donc une correction automatique au bout d'un minimum de 90 jours. L'issue indiquant qu'on a quelques lignes mauvaises dès le …

Corrige valeurs de metrics.target pour certains GBFS

---

apps/transport/lib/transport/availability_checker.ex
apps/transport/test/transport/availability_checker_test.exs

Fixes https://github.com/etalab/transport-site/issues/3463
Voir le détail dans l'issue et l'approche suivie.
Ce fix est attendue par un client, [Twisto Caen la mer](https://transport.data.gouv.fr/datasets/caen-la-mer-reseau-twisto-gtfs-siri). [Voir Front](https://app.frontapp.com/open/msg_1qtpzxue?key=5oSuYWMp-F7u2impB_9lvmwnvMk6LD4c).

AvailabilityChecker : accepte réponse 303 suite à GET pour SIRI

---

apps/transport/test/transport_web/controllers/conversion_controller_test.exs

Fixes https://github.com/etalab/transport-site/issues/3434 (or at least attempts to).
- je tente de démarrer Ecto avec un owner clair
- j'attends plus longtemps avant de requêter en base, on pouvait voir avant qu'on avait un array vide alors qu'on attendait une ligne dans `metrics`
@thbar si tu vois une meilleure manière. Je n'arrive pas à répliquer à 100% en local.
```
mix test apps/transport/test --seed 317213
````
passe chez moi alors que ça a [fail ce matin en CI](https://app.circleci.com/pipelines/github/etalab/transport-site/8419/workflows/d6e9736a-50bb-4815-9df0-95df44f47cbb/jobs/41633) avec ce seed.

ConversionController : répare test instable

---

apps/transport/lib/jobs/resource_unavailable_job.ex
apps/transport/lib/transport/import_data.ex
apps/transport/test/transport/jobs/resource_unavailable_job_test.exs

En lien avec 
- #3463
- https://github.com/opendatateam/udata-ods/issues/250
Concerne principalement l'URL SIRI de [Twisto Caen](https://transport.data.gouv.fr/datasets/caen-la-mer-reseau-twisto-gtfs-siri). Pour ce cas, l'URL donnée par l'API ODS v1 (et donc qui remonte dans l'API data.gouv.fr) est `https://twisto.opendatasoft.com/api/datasets/1.0/fichier-gtfs-du-reseau-twisto/alternative_exports/https_api_okina_fr_gateway_cae_realtime_anshar_ws_services` qui répond une 303.
Côté transport.data.gouv.fr, on souhaite avoir l'URL finale (ce qu'attend le producteur, son industriel et le réutilisateur).
Plusieurs possibilités :
- attendre une évolution sur le moissonneur ODS côté data.gouv.fr
- adapter notre code d'import `ImportData` pour transformer les données là
- adapter le job qui …

ResourceUnavailableJob : teste 1 fois URL finale

---

apps/transport/lib/siri_queries.ex
apps/transport/test/transport/siri_queries_test.exs

En lien avec
- #3462
Cette issue met en évidence que l'on ne respecte pas le XSD de SIRI, l'ajout de `<RequestExtension/>` est attendu dans les différentes requêtes, ce qui est fait dans cette PR.
J'ai pu tester en local ensuite que le requêteur web fonctionnait avec le réseau de Toulon.

Transport.SIRI : ajout RequestExtension aux requêtes

---

apps/transport/lib/jobs/resource_unavailable_job.ex
apps/transport/test/transport/jobs/resource_unavailable_job_test.exs

Issue liée https://github.com/etalab/transport-site/issues/3470
Suite de #3466
La précédente PR ne règle pas totalement le problème : on a bien la logique de "follow" pour garder l'URL finale dans notre base de données mais le check ne réussit pas. L'URL finale renvoie une 405 en réponse à une requête HTTP `GET`, ce qui n'est pas bon dans le code existant. Ce serait ok selon `Transport.AvailabilityChecker.available?` (car ressource au format SIRI) mais impossible de déléguer la tâche à cette classe à cause du rate limiting en place (1 req/sec). On consomme ceci en faisant du "follow" puis avec un appel `Transport.AvailabilityChecker.available?`.
Je me résigne à ajouter une variable d'env temporaire permettant de bypass le check de disponibilité pour certaines ressources étant donné que : …

ResourceUnavailableJob : permet d'ignorer certaines ressources

---

apps/transport/lib/http/utils.ex
apps/transport/lib/transport_web/live/siri_querier_live.ex
apps/transport/test/transport_web/controllers/siri_querier_test.exs

Fixes #3469
Ajoute du code qui détecte le `charset` dans `content-type` et qui réencode vers de l'UTF-8 pour éviter les erreurs de rendering dans la LiveView.
Pour tester en local, avec le serveur de Toulon qui répond en `ISO-8859-1` : http://localhost:5000/tools/siri-querier?endpoint_url=https%3A%2F%2Fsaes.ratpdev.com%2Frdtpm&requestor_ref=OPENDATA&query_template=GetStopMonitoring&stop_ref=TOGR09

Requêteur SIRI : décode response.body non utf-8

---

scripts/notion_link_databases.exs

Notion permet d’avoir des tables liées par des identifiants, sur un schéma belongs-to et has-many, mais ne permet pas d’importer et faire fonctionner des références déjà existantes. Ce script permet de le faire, à partir de colonnes d’identifiants préexistants.

Ajout d’un script pour lier des tables Notion

---

apps/transport/lib/transport_web/templates/backoffice/page/_dataset.html.heex
apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.heex

Ne passer pas `locale` dans la session du `mount/3` des LiveViews, ceci est déjà présent dans la session générale de l'application.
https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#module-life-cycle
> When LiveView is first rendered, the mount/3 callback is invoked with the current params, the current session and the LiveView socket.

LiveView : ne pas passer locale

---

apps/transport/lib/transport_web/controllers/explore_controller.ex
apps/transport/test/transport_web/controllers/explore_controller_test.exs

Voir https://transport-data-gouv-fr.sentry.io/issues/4207628748

Résolution de l’erreur 500 sur /explore/gtfs-stops/data

---

apps/transport/lib/jobs/consolidate_bnlc_job.ex
apps/transport/test/transport/jobs/consolidate_bnlc_job_test.exs

En lien avec #3419
Adapte le job de consolidation de la BNLC (qui est toujours en cours de développement, usage interne uniquement, sans impact en prod/remplacement de fichiers sur data.gouv.fr).
- Ajoute un lien de téléchargement du fichier consolidé dans l'e-mail de rapport qui est généré, envoyé aux bizdevs
- Ce fichier consolidé est mis sur notre S3 bucket temporaire (le même que validation à la demande) et supprimé au bout de 4 semaines
J'ai suivi cette approche pour ne pas avoir à envoyer de pièce jointe dans des e-mails.

Consolidation BNLC : téléchargement du fichier consolidé dans e-mail interne

---

apps/shared/lib/validation/tableschema_validator.ex
apps/shared/test/validation/tableschema_validator_test.exs

Fixes #3487
Le certificat du nom de domaine a expiré, on remplace le domaine pour Validata API.

Validation TableSchema : remplacement du domaine

---

apps/transport/lib/jobs/resource_history_validata_json_job.ex
config/runtime.exs

Fixes #3492
Voir issue pour le détail.
Ceci ajoute des jobs dans Oban qui ne finissent jamais car le validateur n'effectue pas de validation, on poll l'API en attente d'un résultat qui n'arrive pas et le job finit par timeout. Ceci survient pour plusieurs centaines de ressources chaque jour.

Désactiver job quotidien Validata JSON

---

apps/transport/lib/db/organization.ex
apps/transport/lib/jobs/periodic_reminder_producers_notification_job.ex
apps/transport/test/transport/jobs/periodic_reminder_producers_notification_job_test.exs

Fixes #3494
Identifie les membres de l'organisation du PAN, ignore ces contacts quand on indique les autres producteurs étant inscrits aux notifications d'un jeu de données.
Quand on s'inscrit depuis le BO on est considéré comme un `:producer` quand il y aura un espace réutilisateur ce sera `:reuser` (mais pas dispo maintenant !).
Bref, une bonne sécurité.

Rappels périodiques aux producteurs : ignore membres du PAN

---

apps/datagouvfr/lib/datagouvfr/client/datasets.ex

Fixes #3431
Je cherche à identifier la fréquence où on va devoir paginer, aller chercher sur une page suivante pour avoir l'info "est-ce que l'utilisateur suit ce JDD".
J'ai parcouru l'API de data.gouv.fr pour tout notre catalogue avec
```
curl -s https://www.data.gouv.fr/api/1/datasets/5f727b957ba624d0618021e6/ | jq ".metrics.followers"
```
et je trouve une écrasante majorité de 0, 1, 2. 98% en-dessous de 10.
Max :
- 63 pour la BAN
- 50 pour IRVE
J'en déduis qu'en mettant un `page_size` "élevé", autour de 100, on ne va jamais paginer actuellement et on est pas trop mals pour le futur.
J'ai vérifié qu'en mettant un `page_size` élevé la réponse n'était pas trop lente.
Je ne pense pas que ce soit utile maintenant, l'usage est faible : proposer de s'abonner sur la page d'un JDD chez nous. On …

Abonnements aux JDD : répare next_page

---

apps/transport/lib/jobs/consolidate_bnlc_job.ex
apps/transport/test/transport/jobs/consolidate_bnlc_job_test.exs

Fixes #3505
- Ajuste le sujet de l'e-mail de rapport en fonction de la présence d'erreurs ou pas
- Ajouter une ligne vide avant le lien vers le fichier à télécharger

Consolidation BNLC : adapter sujet e-mail selon statut

---

apps/transport/lib/siri_queries.ex
apps/transport/test/transport/siri_queries_test.exs

Corrige #3508
Les `LineRef` doivent être dans un `LineDirection` à chaque fois. Pas plusieurs `LineRef` dans un bloc `LineDirection`.
https://github.com/etalab/transport-normes/issues/38#issuecomment-1748903936

Requêteur SIRI : ajuste requête EstimatedTimetable

---

apps/transport/client/javascripts/app.js
apps/transport/lib/transport_web/templates/resource/delete_resource_confirmation.html.heex

Répare code introduit dans #3504
Il y avait vraiment peu de code JavaScript mais c'était suffisant pour faire une erreur. Ça m'apprendra à faire des tests plus poussés en local. Un event ne donne pas la `target` directement donc `event.dataset` est `undefined` et le listener avait une erreur. Faut activer Matomo en local, [c'est désactivé d'habitude](https://github.com/etalab/transport-site/blob/99a2bb63d21a01a7b33b73f5f2dfc3b020fd5e14/apps/transport/lib/transport_web/templates/layout/app.html.heex#L30-L39).
L'event est bien envoyé ensuite, vérifié en local.
Je déplace en plus des balises de tracking car c'était mis sur un `<button>`, sur le `<a>` englobant c'est plus approprié.

Event tracking Matomo : répare listener

---

apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/backoffice/page/index.html.heex
apps/transport/test/transport_web/controllers/backoffice/page_controller_test.exs
config/config.exs
config/dev.exs
config/test.exs

Fixes #3522
Permet de télécharger "l'export général des ressources" proposé depuis notre backoffice aux membres du PAN depuis une URL incluant un token unique, pour pouvoir donner accès à ceci à des partenaires.
J'ai déjà renseigné la variable d'env `EXPORT_SECRET_KEY` chez Clever Cloud.

Télécharger export général des ressources avec URL privée

---

apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.heex

Fixes #3510
Affiche si l'abonnement a été créé par un admin du PAN (source `admin`) ou par l'utilisateur (source `user`).

Notifications backoffice : affichage source abonnement

---

apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex

Répare un bug introduit dans #3473. On avait des doublons dans l'export pour les JDD qui ont des représentants légaux dans 2 tables `dataset_aom_legal_owner` et `dataset_region_legal_owner`.
La requête SQL précédente donnait 2 lignes par JDD dans ce cas, on ne souhaite qu'une seule ligne par `dataset_id` incluant AOMs + régions, sinon on a "un doublon par JDD" avec une ligne incluant uniquement la région et l'autre ligne incluant uniquement les AOMs.
Remarque sur les tests de ce controller https://github.com/etalab/transport-site/pull/3473#discussion_r1330266141

Export ressources BO : 1 ligne par JDD

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/jobs/resource_history_job.ex
apps/transport/lib/transport_web/live/backoffice/custom_tags_live.ex
apps/transport/test/transport/jobs/resource_history_job_test.exs
config/config.exs

#3527 a montré tout son intérêt en production en permettant d'éviter des reboots. Cette PR est un refactor pour conserver le mécanisme et le solidifier (les tags sont gardés tous les jours dans `DatasetHistory` et il y avait des slugs de JDD qui étaient indiqués en dur).
J'ai ajouté les tags `skip_history` sur les JDD des prix de carburant en production déjà.

Dataset : permet d'ignorer historisation avec un tag

---

apps/transport/lib/db/resource_history.ex
apps/transport/lib/jobs/resource_history_validation_job.ex
apps/transport/lib/transport_web/controllers/resource_controller.ex
apps/transport/lib/transport_web/templates/resource/details.html.heex
apps/transport/lib/transport_web/templates/resource/gtfs_details.html.heex
apps/transport/lib/transport_web/templates/validation/show.html.heex
apps/transport/lib/transport_web/views/resource_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/validations.pot
apps/transport/test/db/resource_history_test.exs
apps/transport/test/transport/jobs/resource_history_validation_job_test.exs

Fixes #3058, voir [ce qui est prévu](https://github.com/etalab/transport-site/issues/3058#issuecomment-1768355590).
Cette PR :
- permet de détecter qu'une `ResourceHistory` est un fichier GTFS Flex (en détectant la présence de fichiers caractéristiques)
- de ne pas valider un GTFS avec notre validateur GTFS (de manière à ne pas afficher des erreurs erronnées)
- afficher la page de détails d'une ressource GTFS Flex qu'on a bien détecté que c'était un GTFS Flex mais qu'on ne sait pas encore le valider
- indique sur la validation à la demande GTFS qu'on ne sait pas valider les extensions Flex et Fares v2
Pour les devs : 
- pour le déploiement il faudra supprimer la validation existante de l'unique GTFS Flex en base de données
- les validations concernant des GTFS Flex seront bien lancées …

Détecte et ne valide pas les fichiers GTFS Flex

---

apps/datagouvfr/lib/datagouvfr/client/organization.ex

Résout l’erreur Sentry https://transport-data-gouv-fr.sentry.io/issues/4558606484 qui survient quand on essaye d’accéder à une page d’un dataset qui n’appartient à aucune organisation. On tente alors, pour afficher les discussions, d’accéder via le client API data.gouv, à l’organisation, ce qui provoque une erreur puisque l’identifiant d’organisation fourni au client est `nil`. 
J’ai choisi la solution «simple» : gérer le cas dans le client data.gouv, mais en réalité on ne devrait même pas l’appeler. Dites-moi si vous pensez qu’il faudrait plutôt gérer ça dans discussions_live.ex – en fait, on a déjà un `case`, je voulais pas rajouter un `cond` par dessus.

Gérer l’affichage des discussions pour les datasets qui n’ont pas d’organisation

---

apps/shared/test/validation/gbfs_validator_test.exs
apps/transport/test/transport/data_checker_test.exs
apps/transport/test/transport/jobs/consolidate_bnlc_job_test.exs
apps/transport/test/transport/jobs/dataset_now_on_nap_notification_job_test.exs
apps/transport/test/transport/jobs/datasets_climate_resilience_bill_not_lo_licence_job_test.exs
apps/transport/test/transport/jobs/datasets_switching_climate_resilience_bill_job_test.exs
apps/transport/test/transport/jobs/datasets_without_gtfs_rt_related_resources_notification_job_test.exs
apps/transport/test/transport/jobs/multi_validation_with_error_notification_job_test.exs
apps/transport/test/transport/jobs/new_datagouv_datasets_job_test.exs
apps/transport/test/transport/jobs/new_dataset_notifications_job_test.exs
apps/transport/test/transport/jobs/oban_logger_test.exs
apps/transport/test/transport/jobs/periodic_reminder_producers_notification_job_test.exs
apps/transport/test/transport/jobs/resource_unavailable_notification_job_test.exs
apps/transport/test/transport/jobs/resources_changed_notification_job_test.exs
apps/transport/test/transport_web/controllers/contact_controller_test.exs
apps/transport/test/transport_web/live_views/feedback_live_test.exs
config/config.exs

Passe les adresses `@transport.beta.gouv.fr` en `@transport.data.gouv.fr`.
Ceci impacte :
- l'envoi des e-mails transactionnels (notifications et formulaire de contact)
- ce qui est affiché sur notre site web quand on indique notre adresse de contact
- restera à effectuer des changements sur notre documentation à terme cc @etalab/transport-bizdev 
Côté Front les e-mails envoyés à ces adresses [arrivent dans la même boite](https://app.frontapp.com/settings/tim:7861846/channels).
Le faible volume d'envoi d'e-mails (< 200 / semaine) fait qu'on devrait pouvoir changer de domaine sans faire ceci graduellement en étalant sur plusieurs jours. On gardera un oeil attentif côté Mailjet tout de même évidemment.
Je n'ai pas fait de changement de configuration sur Mailjet/AlwaysData/Front. Tout était …

E-mails : passage à @transport.data.gouv.fr

---

apps/datagouvfr/lib/datagouvfr/client/organization.ex
apps/transport/lib/transport_web/live/discussions_live.ex
apps/transport/test/transport_web/live_views/discussions_live_test.exs

Cette PR traite[ ce commentaire](https://github.com/etalab/transport-site/pull/3548#issuecomment-1771182840) de @AntoineAugusti pour un fix plus durable.

Gérer (mieux) le cas des discussions sans organisation productrice de la donnée

---

apps/transport/lib/mix/tasks/transport/import_communes.ex
config/dev.exs

Le diff a l’air important parce que j’ai déplacé des fonctions pour les remettre dans l’ordre du script, mais en fait, comme changements, il n’y a pas grand chose :
- Passage de HTTPoison à Req. HTTPoison me crachait une erreur avec un simple `HTTPoison.get!`.
- Pas mal de commentaires pour comprendre le code (en fait, c’est ce qui m’a pris le plus de temps, comprendre ce qui était fait)
- Je retourne les clefs du changeset de chaque commune pour avoir une idée de ce qui est modifié – surtout de la géométrie, donc, mais quand même 22 changements de nom
- Et si un changeset change autre chose que la géométrie ou la population, j’outpute les changements dans les logs pour analyse.
Tl;dr : **on aurait dû retrouver 10 suppressions de communes et zéro nouvelles communes, d’après [le fichier de …

Mise à jour de la base de données de communes (millésime 2023)

---

apps/transport/test/documentation_links_test.exs

Nous [avons constaté](https://mattermost.incubateur.net/betagouv/pl/s88dq6fan3rw7dok6z1kwag87c) que ces tests ont fail plusieurs fois aujourd'hui en CI et l'output des tests ne permet pas de savoir la cause du problème.
Cette PR ajoute plus de détails pour comprendre le problème, qui n'a pas été reproduit localement.

DocumentationLinksTest : facilite le debug

---

apps/transport/lib/converters/converter.ex
apps/transport/lib/db/data_conversion.ex
apps/transport/lib/db/resource.ex
apps/transport/lib/jobs/gtfs_generic_converter.ex
apps/transport/lib/jobs/gtfs_to_geojson_converter_job.ex
apps/transport/lib/jobs/gtfs_to_netex_converter_job.ex
apps/transport/priv/repo/migrations/20231019121309_data_conversion_add_columns.exs
apps/transport/test/db/data_conversion_test.exs
apps/transport/test/db/db_dataset_test.exs
apps/transport/test/db/resource_test.exs
apps/transport/test/support/factory.ex
apps/transport/test/transport/jobs/gtfs_to_geojson_converter_job_test.exs
apps/transport/test/transport/jobs/single_gtfs_to_geojson_converter_job_test.exs
apps/transport/test/transport/jobs/transport_tools_test.exs
apps/transport/test/transport_web/controllers/api/datasets_controller_test.exs
apps/transport/test/transport_web/controllers/conversion_controller_test.exs
apps/transport/test/transport_web/controllers/dataset_controller_test.exs
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Suivre la vision générale dans https://github.com/etalab/transport-site/issues/3427.
Cette PR permet d'avoir plusieurs convertisseurs pour les conversions de données (cas d'usage actuel GTFS vers GeoJSON et NeTEx). On a besoin de ce changement pour pouvoir convertir en NeTEx avec notre convertisseur actuel et celui d'EnRoute.
Ajoute 3 colonnes dans `data_conversion` :
- suivre l'avancement de la conversion. On va changer d'état pour EnRoute au fur et à mesure mais pour les convertisseurs actuels l'insertion se fera uniquement quand la conversion est terminée, donc `status = success`
- le nom du convertisseur
- sa version
c'est similaire à ce qu'il y a dans `multi_validation`.
Adapte le code existant pour s'assurer qu'on utilise uniquement des conversions terminées et avec un convertisseur …

DataConversion : gère plusieurs convertisseurs

---

apps/transport/lib/db/data_conversion.ex
apps/transport/lib/jobs/gtfs_to_netex_converter_job.ex
apps/transport/test/db/data_conversion_test.exs
apps/transport/test/transport/jobs/single_gtfs_to_netex_converter_job_test.exs
config/runtime.exs

Répare un bug introduit dans #3549, un job a été renommé et ceci n'a pas été répliqué dans la configuration runtime de la crontab.
On obtient l'erreur suivante en production au boot.
```
2023-10-23T17:59:45+02:00 [os_mon] memory supervisor port (memsup): Erlang has closed
2023-10-23T17:59:45+02:00 (oban 2.15.4) lib/oban/config.ex:88: Oban.Config.new/1
2023-10-23T17:59:45+02:00 ** (ArgumentError) Transport.Jobs.GtfsToGeojsonConverterJob not found or can't be loaded
2023-10-23T17:59:45+02:00 (oban 2.15.4) lib/oban.ex:226: Oban.start_link/1
```
Je fais un fix rapide avec un check en utilisant [Code.ensure_compiled!](https://hexdocs.pm/elixir/Code.html#ensure_compiled!/1) mais je pense regarder un peu plus ensuite, voir demander conseil côté Oban.

Crontab Oban : vérifie que les modules existent

---

apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.heex
apps/transport/test/transport_web/controllers/backoffice/page_controller_test.exs

Répare un bug introduit dans #3525, il y a 2 semaines !?! 🤔
[Voir Sentry](https://transport-data-gouv-fr.sentry.io/issues/4570684508/?environment=prod&project=6197733&query=is%3Aunresolved&referrer=issue-stream&stream_index=1)
```
lib/transport_web/templates/backoffice/page/form_dataset.html.heex in anonymous fn/2 in TransportWeb.Backoffice.PageView."form_dataset.html"/1 at line 1
lib/phoenix_live_view/engine.ex in Phoenix.HTML.Safe.Phoenix.LiveView.Rendered.to_iodata/1 at line 137
lib/phoenix_live_view/engine.ex in Phoenix.HTML.Safe.Phoenix.LiveView.Rendered.to_iodata/3 at line 153
lib/phoenix/controller.ex in Phoenix.Controller.render_and_send/4 at line 772
lib/transport_web/controllers/backoffice/page_controller.ex in TransportWeb.Backoffice.PageController.action/2 at line 1 …
```

Backoffice : répare 500 sur dataset#new

---

apps/transport/lib/transport_web/endpoint.ex
apps/transport/lib/transport_web/plugs/block_user_agent.ex
apps/transport/lib/transport_web/router.ex
apps/transport/test/transport_web/plugs/block_user_agent_test.exs
apps/transport/test/transport_web/routing/canonical_host_redirect_test.exs
config/config.exs

Cette PR ajoute un plug permettant de :
- logger path et user-agent associé quand on le souhaite
- bloquer des requêtes sur `transport_web` avec une liste de mots clés
Ceci est configurable par variables d'environnement, de manière à pouvoir faire évoluer ceci rapidement
- `LOG_USER_AGENT`
- `BLOCK_USER_AGENT_KEYWORDS`, une liste de mots clés à séparer avec des pipes `|`

Ajout Plug pour logger et bloquer user-agent

---

apps/transport/lib/transport_web/endpoint.ex
apps/transport/lib/transport_web/plugs/block_user_agent.ex
apps/transport/test/transport_web/plugs/block_user_agent_test.exs
apps/transport/test/transport_web/routing/canonical_host_redirect_test.exs
apps/transport/test/transport_web/routing/proxy_routing_test.exs

Retravaille https://github.com/etalab/transport-site/pull/3572 pour pouvoir configurer le Plug au runtime et permettre de changer les options avec seulement un reboot et non une compilation.
[Voir Mattermost](https://mattermost.incubateur.net/betagouv/pl/xh4kcfmr93fot8hgyw5mfseufa)

BlockUserAgent : permet d'utiliser les envs au runtime

---

apps/transport/lib/transport_web/plugs/block_user_agent.ex
apps/transport/test/transport_web/plugs/block_user_agent_test.exs

Suite de #3572 #3574
Voir [Sentry](https://transport-data-gouv-fr.sentry.io/issues/4586926444/?referrer=alert_email&alert_type=email&alert_timestamp=1698686327344&alert_rule_id=12100279&notification_uuid=a1521a84-9ba9-4cb2-b06a-5e8d7316b6f4&environment=prod)
Gère le cas où la requête HTTP ne contient pas de header `user-agent`, on autorise ceci pour le moment.

BlockUserAgent : ne crashe pas quand pas de user-agent

---

config/config.exs

Ajout de variables d'environnement pour pouvoir gérer la safelist/blocklist de [`phoenix_ddos`](https://github.com/xward/phoenix_ddos) et réagir en cas de besoin.

Phoenix DDOS : ajout config pour safelist et blocklist

---

apps/transport/lib/jobs/periodic_reminder_producers_notification_job.ex
apps/transport/test/transport/jobs/periodic_reminder_producers_notification_job_test.exs

Fixes https://github.com/etalab/transport-site/issues/3583
Évite de sélectionner plusieurs fois un contact qui est éligible à cet envoi.
Un double fix
- `Enum.uniq()` en sélectionnant les contacts (suffisant pour corriger le problème)
- Ajout d'un [`unique`](https://hexdocs.pm/oban/Oban.html#module-unique-jobs) au job

PeriodicReminders : évite de programmer des doublons

---

apps/transport/lib/jobs/conversions/gtfs_to_netex_enroute_converter_job.ex

Répare un bug introduit dans #3560, il n'y avait pas de clause quand on arrive au 12ème _attempt_ :sob:
**Note :** j'ai reenqueue le stock avec cette requête
```sql
update oban_jobs set args = jsonb_set(args, '{attempt}', '13'::jsonb), errors = '{}'::jsonb[], attempt = 1, state = 'available'
where queue = 'enroute_conversions' and state = 'discarded' and args->>'attempt' = '12'
```

GTFSToNeTExEnRouteConverterJob : gère tous les cas pour next_polling_attempt

---

apps/transport/lib/jobs/conversions/gtfs_to_netex_enroute_converter_job.ex

#3588 ne passe pas en CI, mais passait bien en local avec `mix test apps/transport/test/transport/jobs/conversions/gtfs_to_netex_converter_job_test.exs` ! J'avais un doute de pouvoir utiliser un module attribute dans un doctest, c'est de toute évidence une mauvaise idée.

GTFSToNeTExEnRouteConverterJob : pas de module attribute dans doctest

---

apps/transport/lib/transport_web/templates/backoffice/contact/_notification_subscriptions.html.heex

Similaire à ce qui avait été fait dans https://github.com/etalab/transport-site/pull/3524 (pour la partie JDD), effectue la même chose partie fiche individuelle d'un contact dans le backoffice.
cc @cyrilmorin

Backoffice contacts : affichage de la source d'un abonnement

---

apps/transport/lib/jobs/conversions/gtfs_to_netex_enroute_converter_job.ex

Il y a un bracket en trop dans le nom du fichier temporaire.
Exemple en production :
```
/tmp# ls
appsignal                             enroute_conversion_gtfs_netex_14391}  enroute_conversion_gtfs_netex_2976}   enroute_conversion_gtfs_netex_63145}
appsignal-agent-e8207c1.tar.gz        enroute_conversion_gtfs_netex_14531}  enroute_conversion_gtfs_netex_3292}   enroute_conversion_gtfs_netex_64289}
appsignal.log                         enroute_conversion_gtfs_netex_166}    enroute_conversion_gtfs_netex_3583}   enroute_conversion_gtfs_netex_82783}
core-js-banners                       enroute_conversion_gtfs_netex_16847}  enroute_conversion_gtfs_netex_42986}  enroute_conversion_gtfs_netex_871}
enroute_conversion_gtfs_netex_10152}  enroute_conversion_gtfs_netex_17337} …
```

GTFSToNeTExEnRouteConverterJob : répare tmp_path

---

apps/transport/lib/transport_web/templates/resource/_subfolder_issue.html.heex
apps/transport/lib/transport_web/views/resource_view.ex
apps/transport/lib/validators/gtfs_transport_validator.ex
apps/transport/priv/gettext/en/LC_MESSAGES/gtfs-transport-validator.po
apps/transport/priv/gettext/en/LC_MESSAGES/validations-explanations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/gtfs-transport-validator.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations-explanations.po
apps/transport/priv/gettext/gtfs-transport-validator.pot
apps/transport/priv/gettext/validations-explanations.pot

Fixes https://github.com/etalab/transport-site/issues/3540. Similaire à la PR de ce matin #3593 qui ajoute la gestion d'une autre nouvelle erreur.
Prend en compte la nouvelle erreur ajoutée dans https://github.com/etalab/transport-validator/pull/176, `SubFolder`. Ajoute une vue et des messages pertinents pour cette erreur.

Validateur GTFS : message quand fichiers dans un sous-dossier

---

apps/transport/lib/transport_web/templates/resource/_subfolder_issue.html.heex

Revoit ce qui a été fait dans https://github.com/etalab/transport-site/pull/3595
En réalité la structure que l'on a n'est pas une liste mais dans [une structure `Scrivener.Page`](https://hexdocs.pm/scrivener/Scrivener.Page.html). J'ai été induit en erreur car on a des boucles `for issue <- @issues` qui [utilise `entries` en fait](https://github.com/drewolson/scrivener/blob/09ab5c2b2b474bd1dca71723274b674a1f1805f3/lib/scrivener/page.ex#L31)
[Voir Sentry](https://transport-data-gouv-fr.sentry.io/issues/4629310368/?environment=prod&project=6197733&query=is%3Aunresolved&referrer=issue-stream&stream_index=2)

subfolder_issue : les issues sont en Scrivener

---

apps/transport/lib/jobs/consolidate_bnlc_job.ex
apps/transport/test/transport/jobs/consolidate_bnlc_job_test.exs

En lien avec #3419
Répare un bug introduit en voulant traiter https://github.com/etalab/transport-site/pull/3563#discussion_r1375925884
En consolidant la BNLC, avec le code précédent on ignore la colonne `id_lieu` dans `bnlc_csv_headers/0`. Par la suite, la ligne `|> CSV.decode!(field_transform: &String.trim/1, headers: bnlc_headers)` fait qu'on utilise les header qu'on passe (en ignorant ceux présents en ligne 1) pour le fichier [`bnlc-.csv`](https://github.com/etalab/transport-base-nationale-covoiturage/blob/main/bnlc-.csv). On a ainsi un décalage des colonnes qui [se répercute dans le fichier consolidé](https://app.frontapp.com/open/cnv_zqmgj2u?key=qqu9ccVAHfhUVyjfOoxmlYSWDCHOcfo7), uniquement pour la BNLC sur GitHub et pas des fichiers provenant de data.gouv.fr.
On arrête d'ignorer …

ConsolidateBNLCJob : répare décodage fichier BNLC

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/transport_web/live/backoffice/custom_tags_live.ex
apps/transport/test/db/db_dataset_test.exs

Fixes #3490
Adapte `DB.Dataset.get_resources_related_files` pour ne pas renvoyer une conversion NeTEx quand une ressource NeTEx est déjà présente dans le JDD.
L'ajout notable est la méthode `DB.Dataset.target_conversion_formats` qui détermine les formats de conversion que l'on souhaite.
Démo : pour le JDD IC SNCF on ne propose plus de conversion NeTEx pour leur GTFS.
- J'ai fait en sorte qu'on puisse conserver les conversions NeTEx automatiques si on met un tag `keep_netex_conversions` dans le backoffice (pour certains cas bizarres).
- `get_resources_related_files` est utilisé par l'UI (`dataset#details`) et l'API `/api/datasets/:id`, c'est donc bien répercuté aux 2 endroits
- on continuera à convertir automatiquement ces GTFS, on se contente uniquement de ne pas exposer ces conversions

Ne pas proposer de conversion NeTEx quand une ressource existe

---

apps/transport/lib/transport_web/controllers/page_controller.ex

Voir:
- #3609
Testé en dév via le backoffice:

Hot-fix - passage du TTL de cache de la home-page à 15 minutes

---

apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/test/support/factory.ex
apps/transport/test/transport_web/controllers/backoffice/page_controller_test.exs

Suite de #3614. J'avais oublié un pattern matching pour éviter `org = nil` 🙄.
J'en profite pour ajouter des tests, bien nécessaires.
Navré.

Backoffice : corrige contacts_in_orgs

---

config/runtime.exs

En voulant nettoyer `configs.exs` et `runtime.exs` https://github.com/etalab/transport-site/pull/3607#discussion_r1398959374 j'ai cassé des choses.
`runtime.exs` écrasait complètement la clé de consolidation et il manquait en conséquence `bnlc`. Le job crashait en production.
```
** (KeyError) key :bnlc not found in: %{
zfe: %{
dataset_id: \\\"625438b890bf88454b283a55\\\",
resource_ids: %{
\\\"aires\\\" => \\\"673a16bf-49ec-4645-9da2-cf975d0aa0ea\\\",
\\\"voies\\\" => \\\"3a5d0c66-aef9-4d68-841f-4fe81c9de980\\\"
}
}
}
:erlang.map_get(:bnlc, %{zfe: %{dataset_id: \\\"625438b890bf88454b283a55\\\", resource_ids: %{\\\"aires\\\" => \\\"673a16bf-49ec-4645-9da2-cf975d0aa0ea\\\", \\\"voies\\\" => \\\"3a5d0c66-aef9-4d68-841f-4fe81c9de980\\\"}}})
(transport 0.0.1) …
```

Correction configuration consolidation BNLC runtime

---

apps/transport/lib/converters/converter.ex
apps/transport/lib/converters/gtfs_to_netex_enroute.ex
apps/transport/lib/db/data_conversion.ex
apps/transport/lib/jobs/conversions/gtfs_to_geojson_converter_job.ex
apps/transport/lib/jobs/conversions/gtfs_to_netex_converter_job.ex
apps/transport/lib/jobs/conversions/gtfs_to_netex_enroute_converter_job.ex
apps/transport/test/db/data_conversion_test.exs
apps/transport/test/transport/jobs/conversions/gtfs_to_netex_converter_job_test.exs
apps/transport/test/transport/jobs/conversions/single_gtfs_to_netex_converter_job_test.exs

Utilise le convertisseur EnRoute comme convertisseur par défaut pour le format `NeTEx`.
Les conversions du stock passé est quasiment terminé (reste très peu d'anciens fichiers en cours de conversion) et le flux est bien converti au fur et à mesure.
```sql
select status, count(1)
from data_conversion dc
where dc.converter = 'enroute/gtfs-to-netex'
group by 1;
```
On pourra prochainement supprimer la conversion en parallèle qui est toujours effectuée avec Hove.

Conversions NeTEx : changement de convertisseur par défaut

---

apps/transport/lib/transport/availability_checker.ex
apps/transport/test/transport/availability_checker_test.exs

Fixes #3612
Retravaille `AvailabilityChecker` pour ne plus accepter des statuts HTTP `2xx` mais uniquement `200` pour la plupart des ressources.
Je me demandais s'il fallait accepter du `204 No Content` pour des ressources GTFS-RT mais il ne me semble pas avoir vu des serveurs répondre ceci, ce n'est pas indiqué dans la spec/best practices.
Ne change pas le fonctionnement du reste de ce module
- SIRI/SIRI Lite est traité à part (401 et 405 sont valides)
- teste `HEAD` et fallback en `GET` si non supporté

AvailabilityChecker : accepte uniquement statut 200

---

apps/transport/lib/db/dataset_score.ex
apps/transport/lib/jobs/dataset_quality_score.ex
apps/transport/lib/transport_web/templates/dataset/_dataset_scores.html.heex
apps/transport/test/transport/jobs/dataset_quality_score_test.exs
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

Fixes #3579
PR précédente faisant quelque chose de similaire #3333
Calcule et stocke un nouveau score d'un JDD, le score de conformité.
- concerne les ressources qui sont actuellement validées (GTFS, GBFS et ressources avec un schéma associé)
- ignore les ressources GTFS-RT (pour le moment !)
- pour GTFS ne s'intéresser qu'aux erreurs de type `Error` et `Fatal` (comme ce qui est fait pour la notification d'erreurs de validation)
- le score vaut 0 (si au moins une erreur en GBFS/schémas et si `max_error` est `Error` ou `Fatal` en GTFS) ou 1 sinon
- Le score vaut `nil` si le JDD ne contient aucune ressource pour laquelle on peut attribuer un score
- pour un JDD, faire la moyenne des scores des ressources prises en compte
Rien de visible pour les utilisateurs finaux.
Le nouveau score de …

Calcule et stocke un score de conformité

---

apps/transport/lib/jobs/dataset_quality_score.ex
apps/transport/test/transport/jobs/dataset_quality_score_test.exs

Fixes #3626, voir l'issue pour le détail du problème.
J'ai découpé mes commits pour ajouter un test qui échoue puis le corriger.
Cette exception est visiblement actuellement en prod pour [le JDD Vélib](https://transport.data.gouv.fr/datasets/508) et dans [le dashboard des jobs](https://transport.data.gouv.fr/backoffice/jobs?worker=DatasetQualityScore).

DatasetQualityScore : corrige bug de calcul de score avec nil

---

apps/transport/priv/gettext/en/LC_MESSAGES/gtfs-transport-validator.po

Corrige une petite erreur de traduction ajoutée dans https://github.com/etalab/transport-site/pull/3595/files#diff-3ea1bdfeaea8fd0b507c47429ae38a45bec3aec648c440e189bed8794d0702b6
Une traduction FR est présente dans un fichier `EN` à tort.

Trad EN validateur GTFS : enlève traduction FR

---

apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex

Fixes #3634 suite à l'ajout de ce score récemment. En exécutant la requête complète en prod, celle-ci est toujours exécutée en moins d'1s. L'usage est toujours interne (bizdevs) + ART.
PR similaire à d'autres effectuées précédemment (par exemple #3620)

Export ressources BO : ajout score de conformité

---

apps/transport/lib/jobs/periodic_reminder_producers_notification_job.ex
apps/transport/lib/transport_web/templates/email/producer_with_subscriptions.html.md
apps/transport/lib/transport_web/templates/email/producer_without_subscriptions.html.md
apps/transport/test/transport/jobs/periodic_reminder_producers_notification_job_test.exs

Fixes #3567
Gère les 2 derniers templates à traiter pour la revue du contenu des notifications https://github.com/etalab/transport-site/issues/3567#issuecomment-1833475278, les rappels périodiques envoyés aux producteurs faisant la promotion des notifications.
Les modifications de contenu ont été effectuées suite [aux consignes données](https://www.notion.so/Gestion-des-notifications-externes-3e43125a9e6c41309fa72082c2008945) par @ChristinaLaumond. Le contenu est simplifié en enlevant le bloc sur la partie gestion des membres de l’organisation pour ne pas complexifier le message. Les méthodes inutilisées sont supprimées.

Notifications : ajuste le contenu du rappel périodique des notifs aux producteurs

---

apps/transport/lib/transport_web/live/backoffice/rate_limiter_live.ex
apps/transport/lib/transport_web/live/backoffice/rate_limiter_live.html.heex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/backoffice/page/index.html.heex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po
apps/transport/test/transport_web/live_views/rate_limiter_live_test.exs

Ajoute une nouvelle LiveView dans le backoffice permettant à notre équipe tech de savoir quelle est la configuration actuelle du rate limiter, quelles sont les adresses IPs bloquées (et permettre de débloquer une IP depuis le dashboard).
Il y a une utilité en terme de documentation et pour faciliter l'action en cas de trafic HTTP important.

Backoffice : ajout doc/config pour plug rate limiter

---

apps/transport/lib/transport/import_data.ex

En lien avec #3647
Les ressources ODS ne seront plus nommées "Export au format XXX" avec le changement de moissonneur DCAT. Adapte la logique en conséquence.
Ceci est actuellement utilisé pour ne pas catégoriser des ressources "Export CSV" contenant des liens vers des GTFS / GTFS-RT comme étant du GTFS / GTFS-RT. On lit alors le contenu du CSV (avec `Opendatasoft.UrlExtractor`) pour créer de fausses ressources. Ceci doit être arrêté car on peut désormais référencer des "liens distants" sur OpenDataSoft, mais il faut que les producteurs migrent vers cette solution.
> [!IMPORTANT]  
> Ceci peut être mergé dès à présent car on garde l'ancien comportement et on gère le futur comportement

ImportData : mise à jour logique détection ressource ODS

---

apps/transport/lib/transport/import_data.ex
apps/transport/test/support/factory.ex
apps/transport/test/transport/import_data_test.exs

Fixes https://github.com/etalab/transport-site/issues/3657, voir le détail du problème là-bas.
Le retour de l'API data.gouv.fr a changé [pour une commune](https://www.data.gouv.fr/api/1/spatial/zones/fr:commune:38185/), il n'y a plus la clé `keys` mais on retrouve le même format que pour les EPCI avec la clé `code` qui contient le code INSEE.
Ajoute des tests pour cette méthode, qui n'était pas couverte auparavant.

ImportData : adapte lecture des zones datagouv

---

apps/transport/lib/db/dataset_monthly_metric.ex
apps/transport/lib/jobs/import_dataset_monthly_metrics_job.ex
apps/transport/priv/repo/migrations/20231214145408_dataset_monthly_metrics.exs
apps/transport/test/db/dataset_monthly_metric_test.exs
apps/transport/test/support/factory.ex
apps/transport/test/transport/jobs/import_dataset_monthly_metrics_job_test.exs
config/runtime.exs

Importe les statistiques mensuelles data.gouv.fr pour les JDDs : téléchargements et vues.
Cette PR traite :
- la migration (création de la table `dataset_monthly_metrics`)
- le modèle
- le job Oban d'import, exécuté de manière quotidienne
Il n'affiche pas ces valeurs, ce travail sera mené avec @etalab/transport-bizdev plus tard. En effet les statistiques de téléchargements provenant de data.gouv.fr ne font sens que pour les données hébergées par data.gouv.fr (ce n'est pas valide pour les ressources qui sont hébergées hors data.gouv.fr).
J'ai exécuté le job d'import en local pour vérifier que l'import fonctionne bien. Le premier import, passant de 0 rows à 15 200 lignes a pris 45s.
```elixir
iex> Transport.Jobs.ImportDatasetMonthlyMetricsJob.new(%{}) |> Oban.insert!()
```

Import des stats mensuelles data.gouv.fr pour les JDDs

---

README.md

Quelques améliorations :
- Clarification de l’installation de Yarn
- Instructions d’installation remises dans l’ordre chronologique
- Niveau d’indentation corrigé pour une bonne partie du document.
Pour Docker, je ne l’ai jamais installé, j’ai l’impression qu’avec le docker-compose.yml on s’évite l’installation sur son propre système de postgresql (qui est du coup contenerisé) mais pas la création de la base de données et les migrations, j’ai écrit la doc dans ce sens là.
Voir [le rendu](https://github.com/etalab/transport-site/blob/improve-readme-yarn/README.md) Astuce : bouton en haut à droite pour afficher le menu et vérifier que l’arborescence est logique.

Amélioration du readme

---

apps/transport/lib/S3/s3.ex
apps/transport/lib/jobs/consolidate_bnlc_job.ex
apps/transport/lib/jobs/conversions/gtfs_generic_converter.ex
apps/transport/lib/jobs/gtfs_diff_job.ex
apps/transport/lib/transport/gtfs_diff.ex
apps/transport/lib/transport_web/controllers/validation_controller.ex
apps/transport/lib/transport_web/live/gtfs_diff_select_live.ex
apps/transport/lib/validators/gtfs_rt_validator.ex
apps/transport/test/support/s3_test_utils.ex
apps/transport/test/transport/jobs/consolidate_bnlc_job_test.exs
apps/transport/test/transport/jobs/conversions/single_gtfs_to_geojson_converter_job_test.exs
apps/transport/test/transport/jobs/conversions/single_gtfs_to_netex_converter_job_test.exs
apps/transport/test/transport/validators/gtfs_rt_validator_test.exs
apps/transport/test/transport_web/controllers/validation_controller_test.exs
scripts/download_resource_history_files.exs

Fixes #2067
Adapte le code de toute la codebase pour passer à de l'upload en streaming pour Cellar. J'en ai profité pour changer le client HTTP de `Transport.Validators.GTFSRT` et passer à du streaming avec `Req`.

S3 : migration vers de l'upload en streaming

---

apps/transport/lib/transport/gtfs_diff.ex
apps/transport/test/transport/gtfs_diff_test.exs

Répare un bug introduit dans #3666, [ici](https://github.com/etalab/transport-site/pull/3666/files#diff-8447a6cd2b7fa16ca30e0b99f967cdd9c2783bb0f4543f4725f151111bdd49ca).
Le passage a la sauvegarde sur disque par le biais d'un stream a introduit un bug, ce n'était pas exécuté.
Comme le dit bien [la doc](https://hexdocs.pm/elixir/Stream.html#into/3)
> This function is often used with run/1 since any evaluation is delayed until the stream is executed. 
:angel:
Bref, un `Stream` ça s'exécute.
C'était passé sous silence car il n'y avait pas de tests. Il y en a désormais !

Répare GTFSDiff.dump_diff

---

apps/transport/lib/jobs/consolidate_bnlc_job.ex
apps/transport/test/transport/jobs/consolidate_bnlc_job_test.exs

En lien avec #3419. Discuté [dans Front](https://app.frontapp.com/open/cnv_16n2m1na?key=ZTkFyOix4G-PGnrW2Q2NyytcW9iksF7A).
Met de véritables retours à la ligne dans le rapport de consolidation envoyé par e-mail. Le rapport est envoyé en HTML, il faut donc du `<br/>` et non du `\n`.

ConsolidateBNLCJob : retours à la ligne dans rapport de consolidation

---

apps/transport/lib/jobs/geo_data/bnlc_to_geo_data.ex
apps/transport/test/transport/jobs/consolidate_bnlc_job_test.exs
apps/transport/test/transport/jobs/consolidate_lez_job_test.exs
apps/transport/test/transport/jobs/geo_data/bnlc_to_geodata_test.exs
config/test.exs

Traite ce qui a été mis en évidence dans https://github.com/etalab/transport-site/issues/3419#issuecomment-1864138833
Le job d'import de la BNLC chez nous doit être adapté pour utiliser la nouvelle ressource data.gouv.fr qui contient la BNLC consolidée. On réutilise les paramètres de la consolidation pour sélectionner la ressource pertinente.
J'en profite pour override les paramètres de consolidation de la ZFE dans l'environnement de test.

BNLCJobToGeoData : utilise nouvelle BNLC

---

Dockerfile
config/runtime.exs

J'ai fait une erreur dans mon refactoring de config dans https://github.com/etalab/transport-site/pull/3681 :cry:
`cloak_key` avait été définie dans `config :transport, DB.Repo,` et non dans `config :transport`.
Clever [n'arrivait pas à démarrer l'app](https://console.clever-cloud.com/organisations/orga_f33ebcbc-4403-4e4c-82f5-12305e0ecb1b/applications/app_04f647ef-4a10-4021-a04b-fe510e6cd003/logs) en conséquence.
```
2023-12-26T14:59:40+01:00 14:59:39.182 [notice] Application transport exited: Transport.Application.start(:normal, []) returned an error: shutdown: failed to start child: Transport.Vault
2023-12-26T14:59:40+01:00 ** (EXIT) an exception was raised:
2023-12-26T14:59:40+01:00 ** (MatchError) no match of right hand side value: {:error, {%ArgumentError{message: "could not fetch …
```

Configuration : cloak_key doit être pour :transport

---

Dockerfile
config/config.exs
config/prod.exs
config/runtime.exs

Correction suite à la mise à jour de Sentry en v10, https://github.com/etalab/transport-site/pull/3685 et https://github.com/etalab/transport-site/pull/3681
`RUN mix app.config` produit une erreur dans le Dockerfile étant donné qu'on n'a pas toutes les variables d'environnement attendues lors du build du Dockerfile.
Je retravaille la configuration de Sentry pour [éviter le runtime configuration](https://github.com/getsentry/sentry-elixir/blob/f62d10150a3532ce16e7d45815623b71acc9e2ee/lib/mix/tasks/sentry.package_source_code.ex#L36-L44) en déplaçant la configuration de prod vers `prod.exs` au lieu de `runtime.exs`.
J'en profite pour corriger le packaging du code source, la clé de config n'était pas la bonne (`root_source_code_path` VS `root_source_code_paths` (`s` à la fin), [c'était un …

Déplace la config Sentry v10 vers prod.exs

---

apps/transport/lib/jobs/import_dataset_monthly_metrics_job.ex
apps/transport/test/transport/jobs/import_dataset_monthly_metrics_job_test.exs

Adapte `ImportDatasetMonthlyMetricsJob` pour mettre à jour la colonne `updated_at` quand la ligne a été modifiée : ie qu'on a mis à jour le nombre de téléchargements ou de vues pour un JDD pour un mois donné.
Ceci permet de vérifier que les lignes anciennes (pas le mois courant) ne sont pas modifiées. Je voulais vérifier cette propriété mais avec l'ancien fonctionne ma requête donnait 0 rows 😅 
```sql
select distinct d.year_month
from dataset_monthly_metrics d
where d.inserted_at != d.updated_at
```
Job mis en place dans cette PR https://github.com/etalab/transport-site/pull/3663

ImportDatasetMonthlyMetricsJob : mise à jour updated_at

---

apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/test/transport_web/controllers/dataset_view_test.exs

Fixes https://github.com/etalab/transport-site/issues/3705
Corrige ce compteur, retire le nombre de ressources communautaires étant donné qu'on a un menu distinct juste en dessous.

Dataset#details : corrige nombre de ressources

---

apps/transport/priv/repo/migrations/20240102144643_dataset_add_not_null.exs
apps/transport/test/support/factory.ex
apps/transport/test/transport/community_resource_cleaner_test.exs
apps/transport/test/transport/import_data_test.exs
apps/transport/test/transport_web/controllers/api/datasets_controller_test.exs
apps/transport/test/transport_web/controllers/api/stats_controller_test.exs
apps/transport/test/transport_web/controllers/backoffice/backoffice_controller_test.exs
apps/transport/test/transport_web/controllers/backoffice/dataset_controller_test.exs
apps/transport/test/transport_web/controllers/dataset_search_test.exs
apps/transport/test/transport_web/controllers/resource_controller_test.exs
apps/transport/test/transport_web/controllers/seo_test.exs

En lien avec https://github.com/etalab/transport-site/issues/3399
Ajoute de contraintes not null pour la table `dataset` sur les colonnes possibles :
- `datagouv_id`
- `custom_title` (attribut propre au PAN)
- `licence`
- `logo`
- `full_logo`
- `slug`
- `tags`
- `datagouv_title`
- `type`
- `frequency`
- `nb_reuses`
- `has_realtime` (généré par le PAN)
- `is_active` (attribut propre au PAN)
J'ai appliqué la migration en local avec les données de production.
> [!NOTE]
> On peut attendre après le 08/01 pour merger, en particulier après https://github.com/etalab/transport-site/issues/3647

Table dataset : ajout de contraintes not null

---

apps/transport/lib/db/resource.ex
apps/transport/test/db/resource_test.exs

Fixes #3723 
Un fait divers, une loi : je rajoute une validation pour éviter le cas cité dans #3723.
Import_data fait appel au changeset de DB.Dataset, qui lui-même fait un cast sur DB.Resource donc fait appel à sa fonction changeset.
Ça marche bien, en tentant d’importer[ ce jeu de données ](https://demo.data.gouv.fr/fr/datasets/gtfs-avec-un-schema-bizarre/)sur Demo, ça donne ça :

Évite les resources avec à la fois un format de donnnées de transport public et un schéma de données

---

apps/transport/client/stylesheets/components/_tooltip.scss
apps/transport/lib/db/dataset_monthly_metric.ex
apps/transport/lib/transport_web/controllers/page_controller.ex
apps/transport/lib/transport_web/templates/page/espace_producteur.html.heex
apps/transport/lib/transport_web/views/page_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/espace-producteurs.po
apps/transport/priv/gettext/espace-producteurs.pot
apps/transport/priv/gettext/fr/LC_MESSAGES/espace-producteurs.po
apps/transport/test/db/dataset_monthly_metric_test.exs
apps/transport/test/transport_web/controllers/page_controller_test.exs
apps/transport/test/transport_web/views/page_view_test.exs

Ajoute les statistiques de téléchargement provenant de l'API data.gouv.fr dans l'Espace Producteur.
Affiche :
- le nombre de téléchargements pour l'année civile entière précédente (2023 pour 2024)
- uniquement pour les jeux de données qui contiennent au moins une ressource hébergée sur data.gouv.fr (les statistiques de téléchargements ne sont pas représentatives en cas d'hébergement ailleurs)
On pourra afficher dans un second temps :
- les statistiques de téléchargements des ressources directement sur la page d'un jeu de données. On ne dispose pas encore de ces données chez nous.
- des détails sur la méthode dont sont obtenus ces chiffres, des graphiques mois par mois, offrir le téléchargement de ces données. On attend un peu le retour de producteurs à cette fonctionnalité.
Voir …

Espace producteur : affichage stats téléchargements

---

apps/transport/lib/db/resource_monthly_metric.ex
apps/transport/lib/jobs/import_dataset_monthly_metrics_job.ex
apps/transport/lib/jobs/import_resource_monthly_metrics_job.ex
apps/transport/priv/repo/migrations/20240117075117_resource_monthly_metrics.exs
apps/transport/test/db/resource_monthly_metric_test.exs
apps/transport/test/support/factory.ex
apps/transport/test/transport/jobs/import_dataset_monthly_metrics_job_test.exs
apps/transport/test/transport/jobs/import_resource_monthly_metrics_job_test.exs
config/runtime.exs

Fixes #3724 
Importe les statistiques de téléchargement des ressources depuis l'API de data.gouv.fr.
Ceci est similaire à ce qui a été fait dans #3663. J'ai suivi la même approche que dans la PR précédente pour les JDDs, j'en ai profité pour effectuer un refactor et extraire des méthodes communes.
L'import est planifié de manière quotidienne et importe les statistiques :
- si le modèle n'a jamais été importé, pour les 24 derniers mois
- si on a déjà importé des statistiques, pour les 3 derniers mois (🆕, ceci n'était le cas dans la précédente PR)
Ce job en local importe ~16 800 lignes pour ~1 300 ressources. On mettra à jour uniquement 3  * 1 300 lignes par jour ensuite.

Import des stats mensuelles data.gouv.fr pour les ressources

---

apps/transport/lib/jobs/new_datagouv_datasets_job.ex
apps/transport/test/transport/jobs/new_datagouv_datasets_job_test.exs

Fixes #3742
Le champ du datetime de création a été modifié dans l'API data.gouv.fr dans #2815 ([code exact](https://github.com/opendatateam/udata/commit/c2539a5f9fd15cec3833e21013c17f3642851e4d#diff-40eddfe27558a331de9feb00ad21869b53b16cdf3c0c89074aefb00047b55211)) et cause un bug dans le job en charge d'identifier les JDDs créés récemment susceptibles d'être référencés sur le PAN.
Cette différence entre `created_at` et `internal.created_at_internal` survient uniquement pour les JDDs moissonnés.
Adapte le code du job en conséquence. Je verrai avec @etalab/transport-bizdev si on a laissé des JDDs de côté à cause de ce bug. EDIT : [liste ici](https://github.com/etalab/transport-site/issues/3742#issuecomment-1907934168)

NewDatagouvDatasetsJob : mise à jour champ date de création

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/transport_web/plugs/custom_secure_browser_headers.ex
apps/transport/lib/transport_web/templates/dataset/details.html.heex
apps/transport/lib/transport_web/templates/dataset/index.html.heex
apps/transport/priv/repo/migrations/20240123133743_dataset_custom_logos_columns.exs
apps/transport/test/transport_web/controllers/dataset_controller_test.exs
config/dev.exs
config/runtime.exs
scripts/custom_logo.exs

Première étape pour https://github.com/etalab/transport-site/issues/3701
Cette PR :
- ajoute 2 nouvelles colonnes dans `dataset` : `custom_logo` et `custom_full_logo` qui contiennent des URLs vers des logos personnalisés. Leurs noms suivent les colonnes `logo` et `full_logo`
- adapte le code pour utiliser le logo provenant de data.gouv.fr ou le logo personnalisé si défini
- les tests correspondants
- un script permettant de générer les logos aux tailles attendues (max 500px pour un logo normal et un thumbnail de 100x100 pixels), indiquant les commandes à effectuer pour upload les logos vers le nouveau bucket créé pour l'occasion et la commande SQL à exécuter
À suivre : adaptation de l'Espace Producteur pour offrir la possibilité aux producteurs d'envoyer un logo personnalisé, qui …

Dataset : ajout de colonnes pour logos personnalisés

---

apps/transport/lib/transport_web/live/gtfs_diff_select_live.ex
apps/transport/lib/transport_web/live/gtfs_diff_select_live.html.heex

Correctif pour:
- https://github.com/etalab/transport-site/issues/3738
C'est un test, il faudra vérifier en production que ça ne fait pas trop crasher le worker.
Je partagerai les résultats sur l'issue linkée plus haut.

Augmentation du seuil de RAM de GTFS-DIFF de 10 à 20MB (expérimental)

---

apps/transport/client/stylesheets/espace_producteur.scss
apps/transport/lib/S3/s3.ex
apps/transport/lib/transport_web/controllers/espace_producteur_controller.ex
apps/transport/lib/transport_web/plugs/custom_secure_browser_headers.ex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/espace_producteur/edit_dataset.html.heex
apps/transport/lib/transport_web/templates/page/espace_producteur.html.heex
apps/transport/lib/transport_web/templates/resource/delete_resource_confirmation.html.heex
apps/transport/lib/transport_web/templates/resource/resources_list.html.heex
apps/transport/lib/transport_web/views/bread_crumbs.ex
apps/transport/lib/transport_web/views/espace_producteur_view.ex
apps/transport/priv/gettext/alert.pot
apps/transport/priv/gettext/en/LC_MESSAGES/alert.po
apps/transport/priv/gettext/en/LC_MESSAGES/espace-producteurs.po
apps/transport/priv/gettext/espace-producteurs.pot
apps/transport/priv/gettext/fr/LC_MESSAGES/alert.po
apps/transport/priv/gettext/fr/LC_MESSAGES/espace-producteurs.po
apps/transport/test/transport_web/controllers/backoffice/backoffice_controller_test.exs
apps/transport/test/transport_web/controllers/espace_producteur_controller_test.exs
config/dev.exs
config/prod.exs
config/runtime.exs
config/test.exs

Fixes #3701
Suite de #3741. Cette PR ajoute la possibilité d'envoyer un logo personnalisé depuis l'Espace Producteur. Ce logo est alors déposé sur un bucket "logos", un e-mail est envoyé à notre équipe pour traiter cette demande à l'aide du script ajouté dans la PR précédente (le script prépare et upload les images sur le bucket).

Espace producteur : édition d'un JDD/logo personnalisé

---

apps/transport/lib/jobs/gtfs_diff_job.ex

Voir:
- https://github.com/etalab/transport-site/issues/3738#issuecomment-1913077010

Augmentation de la durée autorisée de GTFS-Diff (de 5 à 15 minutes)

---

apps/transport/lib/transport_web/templates/espace_producteur/edit_dataset.html.heex

Adapte le HTML pour ajouter un attribut `required` sur l'input permettant d'envoyer un logo personnalisé.

Espace Producteur : ajout attribut required

---

apps/transport/lib/transport_web/endpoint.ex

Fixes #3759 
Cette PR augmente la limite de payload à 200MB pour les requêtes Multipart.
Attention, les requêtes urlencoded et json sont du coup limitées à 8MB, voir https://hexdocs.pm/plug/1.15.2/Plug.Parsers.html : «The default length is 8MB». Vu notre API avec des paramètres très limités, je pense que c’est pas un problème, et même plutôt une bonne chose : quelqu’un qui tente de mettre plus de 8MB de paramètres dans l’URL ou dans la payload JSON de l’API tente très probablement de nous attaquer.
Ça ne règle pas le problème de fond, si on dépasse 200MB en upload de resource alors on a une erreur 500, mais c’est raisonnable comme solution :
- On a un nombre d’événements très limités (10 sur 30 jours)
- La seule resource à dépasser 200MB est le fichier national des aménagements cyclables, …

Augmentation de la limite des requêtes multipart à 200MB

---

apps/transport/lib/jobs/gtfs_diff_job.ex

Voir:
- https://github.com/etalab/transport-site/issues/3738
Le dernier test réalisé par l'utilisateur donnait:
- un time-out visuel
- mais pas de crash du worker derrière (j'ai vérifié dans les logs d'activité)
Donc avec un peu de bol, ça traitera le souci pour cette taille de fichier en tout cas.

Augmentation du timeout gtfs-diff à 30 minutes

---

apps/transport/client/stylesheets/components/_shortlist.scss

Ajuste cette règle CSS utilisée uniquement pour les logos dans la recherche des JDDs. Utile pour les quelques logos personnalisés qui sont donnés en CSS (exemple avec le réseau [SEMO](https://transport.data.gouv.fr/datasets?q=semo)).

Ajuste CSS logo dataset#index

---

apps/transport/lib/db/dataset.ex
apps/transport/priv/repo/migrations/20240212101805_dataset_add_custom_logo_changed_at.exs
apps/transport/test/db/db_dataset_test.exs
apps/transport/test/transport/jobs/custom_logo_conversion_job_test.exs
apps/transport/test/transport_web/controllers/espace_producteur_controller_test.exs

Fixes https://github.com/etalab/transport-site/issues/3774
Ajoute la colonne `custom_logo_changed_at` dans `dataset` et met à jour les valeurs connues (à l'aide des timestamps dans le bucket).

Ajout colonne horodatage pour logos personnalisés

---

apps/transport/lib/jobs/consolidate_lez_job.ex

Suite de #3781, corrige le nom de la ZFE.

ZFE Clermont : correction nom

---

apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/lib/transport_web/templates/dataset/_conversions.html.heex
apps/transport/lib/transport_web/templates/dataset/_resource.html.heex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/lib/transport_web/views/resource_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

En lien avec https://github.com/etalab/transport-site/issues/3739
Implémente les modifications d'UI discutées avec @cyrimorin :
- Légendes pour dernière modification et taux de disponibilité
- Travail sur les boutons : mise en avant de plus de "+ détails"
- Suppression de l'affichage des modes pour les GTFS
- ne plus afficher "visualisation disponible" pour un GTFS avec une conversion GeoJSON ou pour une ressource GeoJSON

Mise à jour de l'UI pour les cartes ressource

---

apps/transport/client/images/icons/olympics.svg
apps/transport/lib/db/dataset.ex
apps/transport/lib/transport_web/controllers/page_controller.ex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/priv/search_custom_messages.yml
apps/transport/test/db/db_dataset_test.exs
apps/transport/test/transport_web/controllers/dataset_search_test.exs

Fixes https://github.com/etalab/transport-site/issues/3790
Ajoute une tuile pour les JOP Paris 2024 sur la page d'accueil. Il faudra indiquer le tag `paris2024` dans le backoffice. Il n'y a pas de suppression automatique du code, on devra revert ça durant l'été/rentrée.

Ajout tuile JOP Paris 2024

---

apps/transport/lib/transport_web/templates/resource/_resources_details.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/validations.pot
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Fixes #3788
Ajoute une statistique indiquant le nombre de "routes" présentes dans le fichier GTFS.
Un peu de refactor des traductions au passage et utilisation des statistiques dans `stats` car les anciens attributs vont être supprimés https://github.com/etalab/transport-validator/pull/194

Détail d'un GTFS : ajouter le nombre de routes

---

apps/transport/lib/jobs/dataset_quality_score.ex
apps/transport/test/transport/jobs/dataset_quality_score_test.exs

Fixes https://github.com/etalab/transport-site/issues/3786
Adapte le calcul du score de disponibilité dans le cas où le JDD a 0 ressources (ou uniquement de la documentation) pour attribuer un score de 0, dénotant qu'un JDD sans ressources est "indisponible".

Score de disponibilité : gère cas avec 0 ressources

---

apps/datagouvfr/lib/datagouvfr/client/datasets.ex
apps/transport/lib/db/contact.ex
apps/transport/lib/db/dataset.ex
apps/transport/lib/db/dataset_follower.ex
apps/transport/lib/jobs/import_dataset_followers_job.ex
apps/transport/priv/repo/migrations/20240311141215_create_dataset_followers.exs
apps/transport/test/db/dataset_follower_test.exs
apps/transport/test/support/factory.ex
apps/transport/test/transport/jobs/import_dataset_followers_job_test.exs
apps/transport/test/transport/jobs/import_dataset_monthly_metrics_job_test.exs
apps/transport/test/transport/jobs/import_resource_monthly_metrics_job_test.exs
config/runtime.exs

Il n'y en a pas vraiment pour le moment et c'est largement à définir car la PR est uniquement du backend. Cette notion est floue sur data.gouv.fr aussi. Mais c'est globalement une notion de suivi/favori/liste de sauvegarde.
Ce que j'envisage ensuite : un utilisateur suite JDD/le met dans ses favoris, il voit cette liste dans l'espace réutilisateurs et ensuite prend des actions sur cet ensemble (notifications, lire les discussions etc).
Une précédente étude sur la volumétrie actuelle des suivis de JDDs https://github.com/etalab/transport-site/pull/3497
- Ajoute une migration et le modèle associé permettant de modéliser le suivi d'un jeu de données (`DatasetFollower`)
- Import des données existantes tous les jours depuis data.gouv.fr
J'ai fait la demande d'un endpoint qui pourra être utile …

Suivi d'un jeu de données et import des JDDs suivis depuis data.gouv.fr

---

apps/shared/lib/wrapper/wrapper_req.ex
scripts/netex-accessibilite.exs

En lien avec:
- #3806
Poke @nlehuby que ça intéressera peut-être.
J'ai souhaité pouvoir avoir une vue d'ensemble de ce qui est dans le fichier (qui fait près de 500MB), et je pense que ça peut être un outil qui aurait du sens à terme en affichage direct sur le PAN pour les visiteurs, dans une déclinaison ou une autre.
Dans le principe général c'est pas très éloigné de la gem netex Ruby d'EnRoute (https://bitbucket.org/enroute-mobi/netex), mais avec des usages potentiellement différents, et directement intégrable dans notre stack.
Le script télécharge le fichier NeTEx accessibilité pointé dans #3806, et l'analyse avec un "streaming parser SAX", pour n'afficher que les éléments de façon indentée et pas plus, et jusqu'à un certain niveau de profondeur, configurable.
Derrière je fais un peu …

Premier script pour "résumer" un gros fichier NeTEx

---

apps/transport/client/javascripts/app.js
apps/transport/client/stylesheets/components/_discussions.scss
apps/transport/lib/transport_web/templates/dataset/_discussion.html.heex
apps/transport/lib/transport_web/views/input_helpers.ex

Fait en CSS avec pour seul javascript un handler défini directement sur l'élément.
Le helper textarea_autoexpand est utilisé pour les discussions pour l'instant.
Le truc est d'empiler dans une grille CSS le textarea est un div dont le contenu sera répliqué du textarea via l'attribut `onInput`. Le changement de contenu du div va déclencher un recalcul de la hauteur, et le placement dans une grille forcera la hauteur du textarea à le suivre.
La hauteur initiale du textarea est conservé à 10rem mais n'est désormais plus qu'un `min-height` pour ne plus la fixer.
J'imagine qu'on pourrait choisir un `max-height` pour ne pas rendre le champs exhubérant.
Fixes #3793.
https://github.com/etalab/transport-site/assets/346377/2e88667e-4c7e-45e3-a5bc-77ed6235fcfe

Discussions: Autoresize des textarea

---

apps/transport/lib/db/dataset.ex
apps/transport/test/transport_web/controllers/dataset_search_test.exs

Fixes #3847
Ajoute un tri par défaut pour les jeux de données sur la recherche, quand on ne spécifie pas l'ordre alphabétique ou ajouté récemment.
Tri par ordre décroissant de la population couverte et par ordre alphabétique en cas d'égalité.
https://github.com/etalab/transport-site/issues/3848 découvert à l'occasion en travaillant sur cette PR

Recherche : tri par défaut déterministe

---

apps/transport/lib/transport_web/templates/dataset/_dataset_scores_chart.html.heex

Fixes #3851
Le graphique des indicateurs peut avoir une taille trop grande malgré des règles CSS ou une spec Vega Lite qui parait prendre ceci en compte.
https://github.com/etalab/transport-site/blob/4698271861462b72ea2eed4c310c301562ad3eee/apps/transport/client/stylesheets/components/_dataset-details.scss#L601-L606
https://github.com/etalab/transport-site/blob/4698271861462b72ea2eed4c310c301562ad3eee/apps/transport/lib/transport_web/controllers/dataset_controller.ex#L82
Toutefois ceci ne semble pas suffisant car le `div` parent n'a pas une largeur fixe. La largeur est connue après le render complet et il arrive que le graphique soit trop grand et déborde.
Cette PR répare ce problème. Le fix que j'ai adopté est peut-être un peu complexe mais je n'ai pas réussi autrement après avoir tenté …

Graphique des indicateurs : améliore responsive

---

apps/transport/test/transport/jobs/new_comments_notification_job_test.exs

Suite de https://github.com/etalab/transport-site/pull/3846
Commentaires relevés lors de la review, le setup de certains jeux de données avait été mal effectué et ne correspondait pas aux commentaires. Met les bonnes valeurs d'attributs aux bons endroits.

NewCommentsNotificationJobTest : répare tests

---

apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/lib/jobs/promote_reuser_space_job.ex
apps/transport/lib/transport_web/controllers/reuser_space_controller.ex
apps/transport/lib/transport_web/live/follow_dataset_live.ex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/email/promote_reuser_space.html.md
apps/transport/lib/transport_web/views/email_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot
apps/transport/test/transport/jobs/promote_reuser_space_job_test.exs
apps/transport/test/transport_web/controllers/reuser_space_controller_test.exs
apps/transport/test/transport_web/live_views/follow_dataset_live_test.exs

Fixes #3859
Apporte les modifications suivantes :
- lors du suivi d'un JDD, s'abonne automatiquement aux notifications liées à ce jeu de données
- s'abonne au suivi quotidien des discussions lors du premier suivi
- affiche le coeur permettant de suivre un JDD pour les personnes non connectées, faisant la promotion de la fonctionnalité
- lorsqu'un utilisateur suit un JDD pour la première fois par le biais du bouton, envoie un e-mail faisant la promotion de l'espace réutilisateur
- ajoute un controller pour l'espace réutilisateur, qui ne fait rien pour le moment (affiche "coming soon")
La fonctionnalité reste visible uniquement par les membres du PAN pour le moment, la partie déconnectée sera donc cachée pour le moment (couvert par des tests précédemment dans …

Améliorations pour l'ajout d'un JDD en favori

---

apps/transport/test/transport/jobs/new_datagouv_datasets_job_test.exs

Quickfix d'un test sensible à la date courante

---

apps/transport/lib/transport_web/views/email_view.ex
apps/transport/test/transport/jobs/promote_reuser_space_job_test.exs

Petit problème en travaillant sur #3864 : le lien vers l'espace réutilisateur était relatif et non complet. Ce n'est pas bon pour un lien présent dans un e-mail.

EmailView : lien absolu vers espace réutilisateur

---

apps/transport/lib/transport/comments_checker.ex
apps/transport/test/transport/comments_checker_test.exs

#3844 a ajouté l'envoi d'une notification aux réutilisateurs concernant les nouvelles discussions.
Il est nécessaire d'adapter `CommentsChecker` pour s'assurer que ceci gère uniquement les producteurs : le scope est tous les datasets sur la plateforme et non seulement les datasets suivis. C'est adapté au PAN, ART etc.
Sans ceci `CommentsChecker` envoie à tout le monde, sans distinguer producteurs et réutilisateurs.

CommentsChecker : gère uniquement les producteurs

---

apps/gbfs/lib/gbfs/controllers/vlille_controller.ex
apps/gbfs/test/gbfs/controllers/vlille_controller_test.exs

Suite de #3874, il y avait une confusion sur les données source. Un JDD avec un scope uniquement Roubaix et l'autre plus global. [Voir Front](https://app.frontapp.com/open/cnv_17srx17a?key=7huWj2JsDfsWLO-0LXVT61DydCK1em-V)

GBFS VLille : mise à jour URL source

---

apps/transport/client/stylesheets/app.scss
apps/transport/client/stylesheets/reuser_space.scss
apps/transport/lib/transport_web/controllers/reuser_space_controller.ex
apps/transport/lib/transport_web/live/discussions_live.ex
apps/transport/lib/transport_web/live/feedback_live.ex
apps/transport/lib/transport_web/live/feedback_live.html.heex
apps/transport/lib/transport_web/live/followed_datasets_live.ex
apps/transport/lib/transport_web/plugs/custom_secure_browser_headers.ex
apps/transport/lib/transport_web/templates/reuser_space/index.html.heex
apps/transport/lib/transport_web/views/bread_crumbs.ex
apps/transport/lib/transport_web/views/input_helpers.ex
apps/transport/lib/transport_web/views/reuser_space_view.ex
apps/transport/lib/transport_web/views/seo_metadata.ex
apps/transport/priv/gettext/en/LC_MESSAGES/reuser-space.po
apps/transport/priv/gettext/en/LC_MESSAGES/seo.po
apps/transport/priv/gettext/fr/LC_MESSAGES/reuser-space.po
apps/transport/priv/gettext/fr/LC_MESSAGES/seo.po
apps/transport/priv/gettext/reuser-space.pot
apps/transport/priv/gettext/seo.pot
apps/transport/test/transport_web/controllers/reuser_space_controller_test.exs
apps/transport/test/transport_web/controllers/seo_test.exs
apps/transport/test/transport_web/live_views/discussions_live_test.exs
apps/transport/test/transport_web/live_views/feedback_live_test.exs
apps/transport/test/transport_web/live_views/follow_dataset_live_test.exs
apps/transport/test/transport_web/live_views/followed_datasets_live_test.exs

En lien avec https://github.com/etalab/transport-site/issues/3803
Réalise une première page d'accueil de l'espace réutilisateur affichant les actions disponibles ("Gérer ses notifications" uniquement pour le moment) et une liste des jeux de données favoris.
Cette PR ajoute un squelette de page et un module permettant d'afficher les JDDs suivis et de les filtrer pour y accéder rapidement.
L'espace réutilisateur reste "caché" et inaccessible par le grand public, la possibilité d'ajouter un JDD en favori étant réservée aux admins pour le moment.
L'accueil de l'espace réutilisateur ne sera pas terminé et rendu disponible après cette PR. Les éléments à venir seront :
- un travail sur le texte
- ajout de contenu explicatif et gestion des _empty states_ en lien avec @cyrilmorin 
- adaptation du …

Première page d'accueil de l'espace réutilisateur

---

apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po

Etrangement, ça fonctionne aussi bien avant qu'après.

Fixer un msgid mal renommé

---

apps/gbfs/lib/gbfs/controllers/vlille_controller.ex
apps/gbfs/test/gbfs/controllers/vlille_controller_test.exs

Suite de #3874
Le type de `station_id` a changé chez le producteur. La spec GBFS indique que l'identifiant doit être une string, ceci produit [des erreurs](https://gbfs-validator.netlify.app/validator?url=https%3A%2F%2Ftransport.data.gouv.fr%2Fgbfs%2Fvlille%2Fgbfs.json) dans notre flux converti où c'est indiqué en entier actuellement.

GBFS VLille : station_id doit être une string

---

apps/transport/lib/transport_web/router.ex
apps/transport/test/transport_web/controllers/reuser_space_controller_test.exs
apps/transport/test/transport_web/live_views/notifications_live_test.exs

Vérifie que la personne est connectée pour accéder à l'espace réutilisateur. Actuellement c'est un prérequis (on récupère un contact et les JDDs suivis), je pense qu'il faudra faire une version logged out afin de découvrir la fonctionnalité mais j'attends que @cyrilmorin (en congés) me partage des éléments d'UI/de contenu.

Espace réutilisateur : middleware auth

---

apps/transport/lib/transport_web/live/followed_datasets_live.ex
apps/transport/test/transport_web/live_views/followed_datasets_live_test.exs

Suite de #3878
Vérifie qu'il est possible de chercher un JDD quand on a une seule catégorie de JDD dans les favoris et que le `select` par type de données est absent.
Le pattern match [était trop contraignant](https://transport-data-gouv-fr.sentry.io/share/issue/5f999be1f4164deb972a3a3449adcdf8/) 🐛.

FollowedDatasetsLive : recherche quand 1 JDD suivi

---

apps/transport/lib/db/notification_subscription.ex
apps/transport/lib/transport_web/live/notifications_live.ex
apps/transport/lib/transport_web/live/notifications_live.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/reuser-space.po
apps/transport/priv/gettext/fr/LC_MESSAGES/reuser-space.po
apps/transport/priv/gettext/reuser-space.pot
apps/transport/test/transport_web/live_views/notifications_live_test.exs

Adapte `NotificationsLive` afin de pouvoir s'inscrire aux notifications générales (non spécifiques à un JDD).
Le motif "article 122 / loi climat résilience" est retiré tant que le décret et l'ensemble des fonctionnalités n'est pas de retour.
Cette inscription se fait uniquement via l'espace réutilisateur.

Espace réutilisateur : inscription aux notifications générales

---

apps/transport/lib/transport/companies.ex
apps/transport/test/transport/companies_test.exs

Fixes #3902
Ajout d'un attribut `mtm_campaign` utile pour la collecte de statistiques pour API Recherche d'Entreprises.

Transport.Companies : ajout mtm_campaign

---

apps/transport/lib/db/notification_subscription.ex
apps/transport/lib/jobs/datasets_switching_climate_resilience_bill_job.ex
apps/transport/lib/jobs/resources_changed_notification_job.ex
apps/transport/lib/transport/data_checker.ex
apps/transport/priv/repo/migrations/20240502134737_notification_subscriptions_migrate_platform_producer.exs
apps/transport/test/transport/data_checker_test.exs
apps/transport/test/transport/jobs/datasets_switching_climate_resilience_bill_job_test.exs
apps/transport/test/transport/jobs/new_dataset_notifications_job_test.exs
apps/transport/test/transport/jobs/periodic_reminder_producers_notification_job_test.exs

En lien avec #3896
Modifie le role à `reuser` pour les abonnements existants aux motifs platform-wide qui avaient précédemment un role à `producer`, l'abonnement ayant été créé depuis le backoffice. https://github.com/etalab/transport-site/pull/3899 ajoute une validation de la cohérence (reason / role) à terme.
Seul le combo `reason=daily_new_comments` et `role=producer` n'est pas migré. Il doit rester ainsi, il y a 2 abonnements existants (le PAN et l'ART). Le code gère bien le cas `producer` et `reuser`
https://github.com/etalab/transport-site/blob/48d10ae88b4df656ef4cfefa4edbbc8c800d2987/apps/transport/lib/transport/comments_checker.ex#L62-L71

NotificationSubscription : migre platform-wide vers reuser

---

apps/transport/lib/db/notification_subscription.ex
apps/transport/lib/jobs/dataset_now_on_nap_notification_job.ex
apps/transport/test/transport/jobs/dataset_now_on_nap_notification_job_test.exs

En lien avec #3896.
Merci @vdegove pour la remarque, ce job prenait toutes les `NotificationSubscriptions`, sans vérifier le role. Cette PR répare ceci en vérifiant qu'on exclut bien les réutilisateurs.

DatasetNowOnNAPNotificationJob : uniquement producer

---

apps/transport/lib/jobs/notification_subscription_producer_job.ex
apps/transport/test/transport/jobs/notification_subscription_producer_job_test.exs

En lien avec #3896
Implémente cette partie.
> Quand quelqu’un passe de réutilisateur à producteur, supprimer ses notifs au lieu de les modifier et recréer toutes les notifs de l’autre rôle
Ce refactor permet d'utiliser `DB.NotificationSubscription.changeset` et gère la différence des motifs entre réutilisateur et producteur (avant on changeait juste le rôle).
La suppression des favoris (ancien réutilisateur qui suit un JDD dont il est producteur désormais) est gérée dans un autre job https://github.com/etalab/transport-site/blob/679085fcc7b73b805f5f33adbdd4ad32c5153e51/apps/transport/lib/jobs/import_dataset_followers_job.ex#L22

NotificationSubscriptionProducerJob : supprime puis recrée les abonnements

---

apps/transport/lib/transport_web/live/discussions_live.ex

Correction d'une erreur JS introduite dans #3909. La syntaxe du commentaire n'est pas bonne comme c'est du JavaScript. Pas facile à spotter car c'est du LiveView et on a un mélange de langages…
Détecté en navigant sur le site web. On n'a pas de Sentry pour le JS actuellement.

DiscussionsLive : répare erreur de syntaxe JS

---

apps/transport/test/build_test.exs
apps/transport/test/support/platform.ex

Voir:
- https://github.com/etalab/transport-site/issues/2520
- https://github.com/jayjun/rambo/pull/13
- https://github.com/jayjun/rambo/issues/23
- https://github.com/jayjun/rambo/issues/21 (bloque une nouvelle release)
Le test qui vérifie la bonne exécution de Rambo échoue en systématique sur Mac M1.
Je le "skippe" (pending) explicitement via cette PR car ça pollue le résultat chez moi.
```
..sh: /Users/thbar/git/transport/transport-site/_build/test/lib/rambo/priv/rambo-macarm: No such file or directory
sh: line 0: exec: /Users/thbar/git/transport/transport-site/_build/test/lib/rambo/priv/rambo-macarm: cannot execute: No such file or directory
1) test rambo rust wrapper compiles and runs (TransportWeb.BuildTest)
apps/transport/test/build_test.exs:30
** (MatchError) no match of right …
```

Skip d'un test qui échoue sur Mac M1

---

apps/transport/lib/transport_web/controllers/page_controller.ex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/page/infos_reutilisateurs.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/reuser-space.po
apps/transport/priv/gettext/fr/LC_MESSAGES/reuser-space.po
apps/transport/priv/gettext/reuser-space.pot
apps/transport/test/transport_web/controllers/page_controller_test.exs

Seconde partie de #3907.
Crée une page "Infos réutilisateurs", similaire à [Infos producteurs](https://transport.data.gouv.fr/infos_producteurs) permettant de présenter l'intérêt de l'espace réutilisateur. Elle sera complétée au fur et à mesure des fonctionnalités disponibles et des éléments donnés par @cyrilmorin.
❓ @cyrilmorin Faut-il rediriger vers cette nouvelle page quand on essaie d'accéder à l'espace réutilisateur en n'étant pas connecté ? Comme ce qui avait été fait demandé dans #3907 pour les producteurs (et implémenté dans #3915)

Ajout page infos_reutilisateurs

---

apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/page/infos_producteurs.html.heex
apps/transport/lib/transport_web/views/page_view.ex
apps/transport/test/transport_web/controllers/espace_producteur_controller_test.exs
apps/transport/test/transport_web/controllers/page_controller_test.exs
apps/transport/test/transport_web/live_views/notifications_live_test.exs

Gère la première partie de #3907, concernant l'Espace producteur.
Lorsque l'utilisateur n'est pas connecté et cherche à accéder à l'Espace producteur (lien envoyé par une notification par exemple), renvoie vers la page [infos producteur](https://transport.data.gouv.fr/infos_producteurs) pour expliquer le concept.
Cette page a du contenu/un bouton qui change en fonction du fait que l'utilisateur soit connecté ou non. Ceci n'a pas été modifié par rapport à la situation précédente (bouton, couleurs ou texte), j'ai simplement ajouté des tests.
https://github.com/etalab/transport-site/assets/295709/f1f26349-996e-4418-9545-fcca3bfee64c
cc @cyrilmorin on peut rediriger directement vers l'Espace producteur après le passage sur data.gouv.fr si tu souhaites. Là on retourne sur "infos producteurs" …

Espace producteur : redirection vers page info quand non connecté

---

apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/client/stylesheets/components/_icons.scss
apps/transport/client/stylesheets/components/_tooltip.scss
apps/transport/lib/transport_web/live/follow_dataset_live.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot
apps/transport/test/transport_web/live_views/follow_dataset_live_test.exs

En lien avec #3908.
Gestion de l'affichage et des interactions des coeurs de suivi de datasets sur la page `dataset#details`.
- Si l'utilisateur est connecté et producteur du JDD (ie membre de l'organisation qui publie le JDD), affichage du coeur en bleu, infobulle d'information et lien vers l'espace producteur dans un nouvel onglet.
- Si l'utilisateur est connecté :
- **Ne suit pas le jeu de données.** Coeur gris, infobulle d'information. Au clic, coeur rouge, infobulle, bandeau d'information et liens vers l'espace réutilisateur dans un nouvel onglet. Inscription à tous les motifs de notification en tant que réutilisateur pour ce JDD. Si première fois que l'action est effectuée, envoi d'un e-mail présentant la fonctionnalité, inscription au suivi quotidien des discussions.
- **Suit le …

Dataset#details : fonctionnement du coeur des favoris

---

apps/transport/client/stylesheets/components/_shortlist.scss
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/templates/dataset/index.html.heex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

En lien avec #3908
Sur la page des résultats de recherche, affiche l'icône de coeur de suivi pour chaque JDD :
- si utilisateur non connecté, l'icône n'est pas affichée
- si l'utilisateur est connecté : coeur bleu si producteur, rouge si suivi et gris sinon

Résultats de recherche : affichage des coeurs de suivi

---

apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/page/infos_reutilisateurs.html.heex
apps/transport/lib/transport_web/views/page_view.ex
apps/transport/test/transport_web/controllers/page_controller_test.exs
apps/transport/test/transport_web/controllers/reuser_space_controller_test.exs
apps/transport/test/transport_web/live_views/notifications_live_test.exs

Dernière partie, fixes #3907
Réalise ce qui avait été promis précédemment https://github.com/etalab/transport-site/pull/3916#issuecomment-2106937768. Quand on essaie d'accéder à l'espace réutilisateur en n'étant pas connecté, redirige vers la page d'informations correspondante. Similaire à #3915 pour les producteurs.

Espace réutilisateur : redirection vers page info quand non connecté

---

apps/transport/lib/jobs/consolidate_bnlc_job.ex
apps/transport/test/transport/jobs/consolidate_bnlc_job_test.exs

Fixes #3925
Le job ne gérait pas les fichiers CSV comportant un BOM (byte order mark) en début de fichier CSV, ce qui est _okay-ish_ pour nous. Survenait avec [Lieux de covoiturage - Département du Calvados](https://www.data.gouv.fr/fr/datasets/lieux-de-covoiturage-departement-du-calvados/).

Consolidation BNLC : gère CSV avec BOM

---

apps/transport/lib/transport_web/session.ex
apps/transport/lib/transport_web/templates/dataset/details.html.heex
apps/transport/lib/transport_web/templates/dataset/index.html.heex

Un rapide refactor visant à utiliser un helper spécifique pour déterminer si on doit afficher des éléments spécifiques à l'espace réutilisateur, que l'on cache pour le moment.
Permet de faire moins d'erreurs, être plus explicite et retrouver les différents endroits à adapter ensuite.

Helper pour déterminer affichage espace réutilisateur

---

apps/transport/lib/db/resource_monthly_metric.ex
apps/transport/lib/jobs/import_dataset_monthly_metrics_job.ex
apps/transport/priv/repo/migrations/20240515113652_add_dataset_datagouv_id_to_resource_monthly_metrics.exs
apps/transport/test/transport/jobs/import_resource_monthly_metrics_job_test.exs

Ajoute le dataset_datagouv_id à l'import de métriques d'une resource depuis l'API de data.gouv.fr.
Pour l'instant la colonne est nullable (pour rétro compatibilité) mais la valeur est attendue par la validation Ecto. Prevoir un script de rattrapage puis ensuite mettre la colonne not null ?
Actuellement la contrainte d'unicité ignore cette nouvelle colonne. L'y inclure quand elle sera remplie ?
* * *
Voir #3931.

dataset_datagouv_id pour resource_metrics

---

apps/transport/priv/repo/migrations/20240515155123_relax_constraint_on_resource_monthly_metrics.exs

La contrainte de clef étrangère était trop ambitieuse et ne peut être garanti à l'import des métriques de resources. Enlevons-là.
Cela est désormais cohérent avec l'autre clef (`resource_datagouv_id`) elle aussi non contrainte.
Follow-up de https://github.com/etalab/transport-site/pull/3935. Voir #3931.

Relax constraint on resource_monthly_metrics

---

apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/controllers/reuser_space_controller.ex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/session.ex
apps/transport/lib/transport_web/templates/dataset/_header_links.html.heex
apps/transport/lib/transport_web/templates/dataset/details.html.heex
apps/transport/priv/gettext/default.pot
apps/transport/priv/gettext/en/LC_MESSAGES/default.po
apps/transport/priv/gettext/fr/LC_MESSAGES/default.po
apps/transport/test/transport_web/controllers/dataset_controller_test.exs
apps/transport/test/transport_web/controllers/reuser_space_controller_test.exs

Fixes #3923
Ajout des liens vers les espaces producteur ou réutilisateur en fonction du contexte (connecté ou pas, producteur, suivi du JDD ou non) conformément à ce qui est décrit dans le ticket.
Le lien "Backoffice" reste présent pour les membres de transport.data.gouv.fr.
> En mode connecté + dataset en favori => redirection dans un nouvel onglet vers la page espace_réutilisateur/dataset (à créer)
cette page n'existe pas encore (@cyrilmorin réfléchit et fera un ticket prochainement), je la crée donc dans le router/controller mais elle ne fait rien pour le moment.
Contexte : connecté, admin et producteur

Page JDD : liens vers espaces utilisateurs

---

apps/transport/lib/transport_web/live/follow_dataset_live.ex
apps/transport/lib/transport_web/templates/layout/_header.html.heex
apps/transport/lib/transport_web/templates/page/infos_producteurs.html.heex
apps/transport/lib/transport_web/templates/page/infos_reutilisateurs.html.heex
apps/transport/test/transport_web/controllers/page_controller_test.exs
apps/transport/test/transport_web/live_views/follow_dataset_live_test.exs

Remplace des `utm_source` vers `utm_campaign`, ce tag est plus approprié pour l'usage qui en est fait. On tente de savoir par quel biais les gens arrivent sur une page : menu, dropdown du menu, clic sur un coeur etc.
[Source](https://buffer.com/library/utm-guide/#happy-utm-tracking)
> The source UTM tag = the referrer (Facebook, Twitter, LinkedIn, YouTube, etc.)
> The medium UTM tag = how the traffic gets to you (for most social media links, this will just be “social”)
> The campaign UTM tag = why the traffic is coming to you (launch, persona, promotion, etc.)

Remplacement utm_source vers utm_campaign

---

scripts/irve_diff.livemd

:warning: merci de ne pas merger @etalab/transport-tech, nous allons faire des tests avec @stephane-pignal 
Voir:
- https://github.com/etalab/schema-irve/issues/61
- https://github.com/etalab/transport-site/issues/3272 dans l'esprit
On a régulièrement besoin de déterminer quelles sont les ressources, points de charges, qui ont disparu de la consolidation, ou évolué. Ce Livebook traite le besoin finalement assez facilement.
"Obviously" ça sera généralisable / transposable à d'autres cas d'agrégations, toutefois l'implémentation reste simple et shipper au plus tôt pour traiter nos cas concrets actuels.
Elle permet aussi de montrer un peu l'usage d'Explorer sur ce type de cas.
J'ajoute suite à échanges avec @stephane-pignal ce Livebook qu'on va tester ensemble et que me donne des résultats …

Ajout d'un Livebook pour comparer des fichiers IRVE

---

restore_db.sh

- quelques quotes reportées par shellcheck
- le shebang est désormais portable (bash n'est pas toujours dans `/bin`)
- les extensions SQL peuvent désormais ne pas être restaurés par le flag `--skip-extensions` (le comportement par défaut est inchangé)
- le prompt qui demande si on doit conserver les jobs Oban inclut un indice classique sur la réponse attendue:
`Do you want to remove already enqueued Oban jobs? [y/N]`

QoL: ajouts au script restore_db

---

apps/transport/test/transport/jobs/warn_user_inactivity_job_test.exs

Evitons de recalculer l'heure courante à chaque insertion pour que le test soit moins sensible à la vitesse d'exécution (notamment en CI).

Test moins sensible au temps qui passe

---

apps/transport/lib/db/notification_subscription.ex
apps/transport/lib/jobs/promote_producer_space_job.ex
apps/transport/lib/transport_web/controllers/session_controller.ex
apps/transport/lib/transport_web/templates/email/promote_producer_space.html.md
apps/transport/test/transport/jobs/promote_producer_space_job_test.exs
apps/transport/test/transport_web/controllers/backoffice/backoffice_controller_test.exs
apps/transport/test/transport_web/controllers/session_controller_test.exs

Dernière partie, fixes #3896.
Quand un producteur se connecte la première fois chez nous avec son compte data.gouv.fr, abonne la personne à toutes les notifications pour les jeux de données que la personne gère. [voir consignes](https://github.com/etalab/transport-site/issues/3896#issuecomment-2098541927).
Cette PR dispatch un job dans `SessionController` quand un contact se connecte la première fois chez nous, ce nouveau job Oban est en charge de déterminer si le contact est producteur ou réutilisateur (rien à faire), créer les abonnements pertinents et envoyer un e-mail souhaitant la bienvenue et présentant l'Espace producteur.
@cyrilmorin doit encore valider le contenu de l'e-mail, le reste de la PR ne changera pas.

Producteurs : inscription aux notifications lors de la 1ère connexion

---

apps/transport/lib/jobs/warn_user_inactivity_job.ex

Le calcul de durée d'inactivité (en jours) est désormais fait sur les dates et non plus les datetime. Ainsi peu importe l'heure à laquelle le job tournera, et éviterait des ambiguïtés de calcul qu'un utilisateur scrupuleux pourrait relever.
Ceci a également le mérite de stabiliser les tests.
Vrai fix de ce que #3945 essayait de corriger.

Meilleur fix pour le calcul d'inactivité

---

.gitignore
restore_db.sh

Nouveau flag `--truncate-jobs` pour automatiquement tronquer les jobs Oban au restore. Le comportement par défaut est inchangé : la question reste posée si le flag n'est pas mis.
Autres changements :
- la gestion d'arguments a été revue pour supporter plus d'options. Le message d'usage est enrichi en conséquence.
- les flags classiques `-h` et `--help` sont ajoutés pour rappeler l'usage.
- helper pour les commandes SQL

restore_db: Option pour tronquer les jobs Oban

---

restore_db.sh

Le comportement par défaut change : désormais les jobs Oban du dump sont supprimés sans interroger l'utilisateur.
Pour conserver les jobs il faut désormais utiliser le flag (optionnel) `--preserve-oban-jobs`.
Autre changement : le `truncate table feedback` aurait dû être `truncate table user_feedback`.

restore_db.sh: supprimons les jobs par défaut

---

apps/transport/lib/db/notification_subscription.ex
apps/transport/lib/jobs/notification_subscription_producer_job.ex
apps/transport/test/transport/jobs/notification_subscription_producer_job_test.exs

Fixes #3943
J'ai revu le code existant pour adapter la valeur de la colonne `source` et l'adapter si jamais l'abonnement a été créé par du code dans le but d'avoir de meilleures statistiques (connaitre la source de création d'un abonnement).

Abonnement aux notifications : valeur champ source quand créé par le système

---

apps/transport/lib/transport_web/plugs/custom_secure_browser_headers.ex
apps/transport/test/transport_web/routing/headers_and_cookies_test.exs

Fixes https://github.com/etalab/transport-deploy/issues/74
Améliore notre CSP en indiquant que le PAN ne peut pas être mis dans une `iframe`. Voir [OWASP - Clickjacking defense](https://cheatsheetseries.owasp.org/cheatsheets/Clickjacking_Defense_Cheat_Sheet.html#defending-with-content-security-policy-csp-frame-ancestors-directive).
Nous avions déjà `x-frame-options: sameorigin` dans notre codebase pour toutes nos réponses. https://github.com/etalab/transport-site/blob/22162d63b100d9a1efd940096fef8613de307555/apps/transport/test/transport_web/routing/headers_and_cookies_test.exs#L12
J'adapte en passant à `DENY`, on ne met pas d'iframe de notre propre site.

Content Security Policy : ajout directive frame ancestors

---

apps/transport/client/javascripts/resource-viz.js

Le format n'est-il pas un meilleur indice que l'URL de la resource ?
Ceci a le mérite d'afficher la visualisation GeoJSON si l'url est formattée différemment, comme dans le cas de la [ZFE Strasbourg](https://transport.data.gouv.fr/datasets/zone-a-faibles-emissions-mobilite/) pour laquelle l'url est au format `https://somewhere.org/path/to/resource/export/geojson`.
Fixes #2301.

Affichage de la carte pour tous les GeoJSONs

---

apps/transport/lib/jobs/periodic_reminder_producers_notification_job.ex
apps/transport/test/transport/jobs/periodic_reminder_producers_notification_job_test.exs

Bug constaté : l'e-mail envoyé listait des producteurs inscrit aux notifications pour les JDDs à tort. On listait les producteurs des jeux de données pour des abonnements à des JDDs en tant que réutilisateur.
J'ai du mal à le phraser de manière simple 😅 Je peux vous partager un exemple d'e-mail reçu avec un contenu inapproprié. Je ne partage pas ici car contient quelques données personnelles.
- utilisateurs A et B
- JDD 1
- utilisateur A n'est pas producteur du JDD 1
- utilisateur A abonné aux notifications pour JDD 1 en tant que réutilisateur
- utilisateur B abonné aux notifications pour JDD 1 en tant que producteur
On envoyait à tort, le texte suivant, à l'utilisateur A :
> Les autres personnes inscrites à ces notifications sont : utilisateur B
Mis en évidence dans le premier commit …

PeriodicReminderProducers : conserve uniquement les JDD abonnés en tant que producteur

---

apps/transport/lib/transport/import_data.ex
apps/transport/test/transport/import_data_test.exs

Il arrive qu'une ressource soit ajoutée à un dataset avec l'URL d'une ressource préexistante. Ceci est malheureux et sans doute un usage détourné de data.gouv.fr mais la réalité est têtue et quand cela se produit des actions correctives manuelles sont requises.
Ce changement vise à résister à un tel recyclage d'URL.
Closes #3976

Import de dataset: résister au recyclage d'URL

---

apps/transport/lib/transport_web/templates/email/new_comments_reuser.html.heex
apps/transport/lib/transport_web/templates/email/new_comments_reuser.html.md
apps/transport/test/transport/jobs/new_comments_notification_job_test.exs

Le rendu markdown d‘une liste de liens est capricieux. Un template html simple fera aussi bien l‘affaire.
Les tests couvrent ce cas désormais.
Closes #3989.

Email : fix liste des datasets avec commentaires

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/transport_web/templates/dataset/details.html.heex
apps/transport/test/transport_web/controllers/dataset_search_test.exs

Closes #3957
Cette PR rajoute un lien dans l’oreille de la page d’un jeu de données sur le nom du producteur, ce lien renvoie à la page de recherche dataset avec un nouveau filtre sur l’organisation (dans l’URL, paramètre GET : `/datasets?organization_id=org_id`). La pagination marche si la liste des jeux de données publiée est longue.
J’ai fait simple, ce lien sur la page d’un jeu de données est le seul moyen d’accéder à cette liste. En particulier, n’ont pas été implémentés :
- La recherche texte libre par organisation, sur la homepage ou la page de résultats de recherche. Si on met le nom d’une organisation, on ne retrouvera (toujours pas) les JDD de cette organisation.
- Un filtre latéral (ce qui aurait impliqué d’avoir une recherche au sein du filtre).
- Une page indexée par les …

Liste les jeux de donnée d’une organisation

---

apps/transport/client/stylesheets/reuser_space.scss
apps/transport/lib/transport_web/live/followed_datasets_live.ex
apps/transport/lib/transport_web/templates/reuser_space/datasets_edit.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/reuser-space.po
apps/transport/priv/gettext/fr/LC_MESSAGES/reuser-space.po
apps/transport/priv/gettext/reuser-space.pot
apps/transport/test/transport_web/controllers/reuser_space_controller_test.exs

Gère une bonne partie des éléments d'améliorations UX décrits dans #3983
À venir dans une PR qui suit : la gestion des notifications pour ce JDD sur la page `reuser_space/datasets_edit`. Ceci requiert une LiveView donc j'ai choisi de découper en 2 PRs.

Espace réutilisateur : améliorations UX

---

apps/transport/lib/transport_web/templates/layout/_header.html.heex

En lien avec #3914
Traite un point qui est déjà certain :
> Ajouter le menu « Espace réutilisateur » sous « Espace producteur » depuis le menu personnel
Ceci reste visiblement uniquement par les membres de notre équipe, pour quelques jours encore, tant que ceci n'est pas mis à disposition du grand public.
Le reste des changements est encore en discussion.

Menu personnel : ajout espace réutilisateur

---

apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

Fixes #4017
Cette erreur survenait quand :
- un utilisateur est connecté
- un JDD est publié par une personne et non une organisation (`dataset.organization_id = nil`)
- cet utilisateur visite la page `dataset#details` pour ce JDD
[🐛 Sentry](https://transport-data-gouv-fr.sentry.io/issues/5528852013/?project=6197733)

Dataset#details : répare erreur 500 quand JDD publié par une personne

---

apps/transport/client/images/icons/validate.svg
apps/transport/client/stylesheets/home.scss
apps/transport/client/stylesheets/main.scss
apps/transport/lib/transport_web/templates/layout/_header.html.heex
apps/transport/lib/transport_web/templates/page/index.html.heex
apps/transport/lib/transport_web/views/layout_view.ex
apps/transport/priv/gettext/default.pot
apps/transport/priv/gettext/en/LC_MESSAGES/default.po
apps/transport/priv/gettext/en/LC_MESSAGES/page-index.po
apps/transport/priv/gettext/fr/LC_MESSAGES/default.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-index.po
apps/transport/priv/gettext/page-index.pot

Fixes #3914
Implémente les changements détaillés dans https://github.com/etalab/transport-site/issues/3914#issuecomment-2181097607
Le bouton pour l'espace réutilisateur reste masqué tant qu'il n'est pas sorti pour le grand public. Tenter d'accéder aux espaces utilisateurs sans être connecté amène sur une landing page d'information, présentant la fonctionnalité et demandant de se connecter.

Modifications accueil et menu

---

apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/lib/transport_web/templates/backoffice/contact/_notification_subscriptions.html.heex
apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.heex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po
apps/transport/test/transport_web/controllers/backoffice/page_controller_test.exs
restore_db.sh

Les abonnements avec le rôle reuser ne sont plus affichés, et l'on a une idée du volume après la liste des producteurs abonnés :
Voir #4009.

Dénombrer les réutilisateurs abonnés à un dataset

---

apps/transport/client/javascripts/explore.js
apps/transport/client/stylesheets/components/_explore.scss

Fixes #4012
Ajuste la couleur du layer des ZFE pour le rendre plus visible. J'ai tenté de jouer avec [`fillOpacity`](https://leafletjs.com/reference.html#path) en passant de 0.2 à 1 mais il n'y avait pas de différence.
J'ai choisi un violet plus foncé.

Carte exploration : couleur layer ZFE

---

apps/transport/client/stylesheets/components/_shortlist.scss
apps/transport/lib/db/repo.ex
apps/transport/lib/transport_web/controllers/pagination_helpers.ex
apps/transport/lib/transport_web/templates/dataset/index.html.heex

Closes #4023 
Cette PR remonte le bloc de liens de la pagination à directement sous la liste de datasets (on ratait facilement la liste à cause du menu à gauche qui faisait scroller).
Elle passe aussi le nombre d’items paginés à 20.
Le PAN a une configuration unique de pagination, cela affecte donc tous les listes paginées suivantes :
- Liste de datasets (recherche)
- Liste de contacts dans le backoffice
- Liste de datasets dans le backoffice
- Liste d’erreurs sur la page de détail d’une resource
- Liste d’erreurs sur la page spécifique de validation (je sais pas si ce template est vraiment utilisé, j’avais vu passer un template inutilisé à un moment)
D’après mes tests manuels, cela n’affecte pas la performance de manière sensible, et le changement de taille de liste est plutôt le …

Passage de la pagination à 20 items et bloc de pagination directement sous la liste

---

apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/session.ex
apps/transport/lib/transport_web/templates/dataset/index.html.heex
apps/transport/priv/gettext/alert.pot
apps/transport/priv/gettext/en/LC_MESSAGES/alert.po
apps/transport/priv/gettext/fr/LC_MESSAGES/alert.po
apps/transport/test/transport_web/controllers/dataset_controller_test.exs
apps/transport/test/transport_web/controllers/reuser_space_controller_test.exs
apps/transport/test/transport_web/session_test.exs
config/runtime.exs

- Rend disponible l'espace réutilisateur pour tout le monde.
- Adapte les quelques tests nécessaires suite à ce changement.
- Ajoute un "kill switch" permettant de fermer rapidement la fonctionnalité en cas de besoin.
Je vais me coordonner avec @cyrilmorin pour la sortie de cette PR, en faisant un tour ensemble avant.

Espace réutilisateur : sortie publique

---

apps/transport/client/stylesheets/components/_discussions.scss
apps/transport/lib/db/contact.ex
apps/transport/lib/transport_web/live/discussions_live.ex
apps/transport/lib/transport_web/templates/dataset/_discussion.html.heex
apps/transport/test/db/contact_test.exs
apps/transport/test/transport_web/live_views/discussions_live_test.exs

Utilise et étend ce qui a été fait dans #3533
Ajoute un badge :label: `transport.data.gouv.fr` pour les membres du PAN qui répondent dans les discussions. Ceci permet de mieux nous identifier.
Cas d'un échange entre PAN et producteur
Réponse d'un membre du PAN pour un JDD que l'on produit (2 badges)

Discussions : ajout badge pour membres du PAN

---

apps/transport/lib/jobs/custom_logo_conversion_job.ex
apps/transport/test/transport/jobs/custom_logo_conversion_job_test.exs

Ajoute un timestamp dans les URLs des logos personnalisés envoyés par les producteurs pour leur de données.
Ceci permet d'éviter un problème de cache de l'image lors de la mise à jour. En effet l'URL précédente était de la forme `https://example.com/:dataset_id.png` avec un cache de plusieurs jours. En cas de remplacement d'un logo qui était déjà personnalisé, le producteur ou les visiteurs peuvent voir l'ancienne version pendant quelques jours.
```
$ curl -I https://transport-data-gouv-fr-logos-prod.cellar-c2.services.clever-cloud.com/60e324396e9514171898339c.png
HTTP/1.1 200 OK
content-length: 3124
accept-ranges: bytes
last-modified: Fri, 05 Jul 2024 06:47:44 GMT
x-rgw-object-type: Normal
ETag: "a67d2a8cea40ab807917b3ae79a4f07c-1"
cache-control: public, max-age=604800
x-amz-request-id: …
```

Logo personnalisé d'un JDD : ajout timestamp dans nom de fichier

---

apps/transport/lib/transport_web/templates/dataset/_banner.html.heex
apps/transport/lib/transport_web/templates/dataset/_custom_message.html.heex
apps/transport/lib/transport_web/templates/dataset/details.html.heex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot
apps/transport/priv/search_custom_messages.yml
apps/transport/test/transport_web/controllers/dataset_controller_test.exs
apps/transport/test/transport_web/controllers/dataset_search_test.exs

Fixes https://github.com/etalab/transport-site/issues/4043. Voir le ticket pour les specs détaillées et les clarifications apportées.
- Ajout d'une bannière sur 2 JDDs parkings ciblés
- Modification description catégorie `private-parking`

Ajout d'une bannière pour annoncer NeTEx parkings

---

apps/transport/lib/db/notification_subscription.ex
apps/transport/lib/jobs/resources_changed_notification_job.ex
apps/transport/lib/transport/notification_reason.ex
apps/transport/test/transport/jobs/resources_changed_notification_job_test.exs

Fixes #4042
Le job et les tests associés faisaient comme si l'abonnement était platform-wide (dataset_id = nil) alors que ce motif est spécifique à un jeu de données.
Étend ce qui a été fait dans #4036 pour avoir un typespec spécifique aux motifs de la plateforme et aux motifs spécifiques aux JDDs.
@vdegove, je pense que tu es la bonne personne pour review ça.

ResourcesChangedNotificationJob : récupérer les bons abonnements

---

apps/transport/lib/transport_web/live/backoffice/custom_tags_live.ex
apps/transport/lib/transport_web/templates/dataset/_banner.html.heex
apps/transport/lib/transport_web/templates/dataset/details.html.heex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot
apps/transport/test/transport_web/controllers/dataset_controller_test.exs
apps/transport/test/transport_web/live_views/custom_tags_live_test.exs

Fixes #4051 
Ajout d'un custom tag `authentification_requise` permettant d'ajouter un bandeau indiquant qu'une authentification est requise pour accéder aux données et que certaines fonctionnalités sur notre plateforme sont indisponibles.

Ajout custom_tag pour authentification requise

---

apps/transport/lib/jobs/consolidate_lez_job.ex
apps/transport/test/transport/jobs/consolidate_lez_job_test.exs

La consolidation ZFE ajoute un champ `publisher` détaillant la collectivité qui publie la donnée et ajoute l'identifiant de la ZFE. Quand le JDD est attaché à une AOM c'est immédiat grâce aux informations en BDD. Quand ce n'est pas rattaché à une AOM, il faut mapper l'organisation data.gouv.fr à des données.
Le nom de l'organisation de Paris a été renommé ("Mairie de Paris" vers "Ville de Paris") et casse la consolidation.
Cette PR répare le bug immédiat, tout en gardant en tête qu'il faudrait avoir un mécanisme plus robuste ou au moins une alerte quand une incohérence est détectée pour éviter de découvrir ça quand on dispatch le job à la main (ce process ne tourne pas automatiquement pour le moment).
Voir [échec de job Oban en prod du …

ConsolidateLEZsJob : adapte publisher pour Ville de Paris

---

apps/transport/lib/transport/import_data.ex

Fixes #4071
Utilise le titre d'une ressource pour déterminer qu'une ressource est en réalité une documentation et non un fichier/API temps réel.
`\b` désigne un [word boundary](https://stackoverflow.com/a/1324756) en regex.

ImportData : utilise titre d'une ressource pour type documentation

---

apps/transport/lib/transport/import_data.ex
apps/transport/test/transport/import_data_test.exs

Nouvelle tentative de corriger #3978, avec cette fois une couverture de test plus solide.
Fixe également #4057 (testé avec un dump de la semaine passée et data.gouv de prod).

Import: Résister au recyclage d'URL de ressources

---

apps/transport/client/javascripts/mapbox-credentials.js

Fixes #4074
Indique la bonne URL d'attribution pour OSM

Corrige attribution OpenStreetMap

---

apps/transport/lib/transport_web/templates/page/espace_producteur.html.heex
apps/transport/lib/transport_web/templates/page/infos_producteurs.html.heex

Adapte le lien utilisé pour indiquer comment publier ses données sur la page "infos producteur" et dans l'espace producteur.
Voir [discussion sur Mattermost](https://mattermost.incubateur.net/betagouv/pl/9c6nctpndfd1pnyqtrn118surc).

Corrige un lien erronné vers la doc

---

ops_tests/ops_tests.exs

Les IPs des loads balancers de Clever Cloud changent https://developers.clever-cloud.com/changelog/2024-06-28-new-ip-list-paris/.
[Voir sur Mattermost](https://mattermost.incubateur.net/betagouv/pl/q5yxxs1uwfg63p6jntk5knzyoa).
Adapte les tests pour refléter les changements effectués dans les enregistrements DNS
- https://github.com/etalab/transport-deploy/commit/ddb0de09651a96093584958c476717d1f7f6c0b3
- https://github.com/etalab/transport-deploy/commit/7f894e8d0a44ba202c49060dc0cbfeef9cf0ad26

OpsTests : mise à jour des IPs de Clever Cloud

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/transport_web/live/backoffice/edit_dataset_live.ex
apps/transport/test/transport_web/controllers/backoffice/page_controller_test.exs

Fixes #4088
Permet de pouvoir éditer un JDD inactif dans le backoffice, dans le but de choisir une nouvelle URL source data.gouv.fr ou de le déréférencer.

Backoffice : pouvoir éditer un JDD inactif

---

apps/transport/lib/transport/import_data.ex
apps/transport/test/support/factory.ex
apps/transport/test/transport/import_data_test.exs
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Suite de #4064, fait une partie de #4069, préalable de #4053.
J’ai fini de tester l’essentiel des routes, il y a quelques trous volontaires :
- Je ne teste pas la route de liste de resources, puisqu’elle sautera dans #4053
- Je ne teste pas l’upload de fichier, trop ennuyant, donc je ne teste que le cas d’une URL remote
- Le cas de mise à jour de resource est très (très) similaire au cas de nouvelle resource (d’ailleurs, c’est la même route de contrôleur, et la même action du client API), donc je ne l’ai pas testée.

Tests manquants sur les éditions de resources

---

apps/transport/priv/gettext/en/LC_MESSAGES/notification_subscription.po
apps/transport/priv/gettext/fr/LC_MESSAGES/notification_subscription.po

Fixes #4079
Ajuste la description du motif `daily_new_comments`.

Notifications réutilisateurs : adapte contenu

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/jobs/import_dataset_followers_job.ex
apps/transport/lib/transport_web/live/discussions_live.ex
apps/transport/priv/repo/migrations/20240726065227_dataset_organization_id_not_null.exs
apps/transport/test/db/db_dataset_test.exs
apps/transport/test/transport_web/controllers/backoffice/page_controller_test.exs
apps/transport/test/transport_web/controllers/dataset_controller_test.exs
apps/transport/test/transport_web/live_views/discussions_live_test.exs

Fixes #4018
Empêche le référencement d'un JDD sans organisation (publié par une personne et non une organisation). Il [n'y a plus de JDD sans organisation en prod](https://github.com/etalab/transport-site/issues/4018#issuecomment-2250339589).
- Ajoute une contrainte not null sur `dataset.organization_id`.
- Ajuste `DB.Dataset.changeset/2`
- Supprime le code et les tests qui géraient la possibilité d'avoir `dataset.organization_id = null`

Dataset : force la présence d'une organisation

---

apps/transport/lib/transport/data_checker.ex
apps/transport/test/transport/data_checker_test.exs

Suite de #4091
L'implémentation n'était pas bonne pour la production, la première clause avec `%{"archived" => nil}` matche en réalité dans le cas d'un JDD sans producteur (owner et organisation) en production. Les tests n'étaient pas représentatifs de cette réalité.
Cette PR tire les conséquences de ceci, écrit un nouveau test pour `dataset_status/1` et fait un refactor pour les réponses HTTP.

DataChecker : répare cas JDD sans producteur

---

apps/transport/lib/transport_web/templates/resource/_negative_stop_duration_issue.html.heex
apps/transport/lib/transport_web/views/resource_view.ex
apps/transport/lib/validators/gtfs_transport_validator.ex
apps/transport/priv/gettext/en/LC_MESSAGES/gtfs-transport-validator.po
apps/transport/priv/gettext/en/LC_MESSAGES/validations-explanations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/gtfs-transport-validator.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations-explanations.po
apps/transport/priv/gettext/gtfs-transport-validator.pot
apps/transport/priv/gettext/validations-explanations.pot

Fixes #4098
Ajoute un nouveau template/description d'erreurs pour une nouvelle règle de validation GTFS.

Validateur GTFS : ajoute erreur NegativeStopDuration

---

apps/transport/priv/repo/migrations/20240730130026_notifications_adjust_foreign_keys.exs
apps/transport/test/db/contact_test.exs
apps/transport/test/db/notification_subscription_test.exs

Fixes #4102
Ajuste la migration initiale pour ne pas lever une exception quand on tente de supprimer un `notification_subscription` ou `contact`, référencé par `notifications`.

Notifications : ajuste clés étrangères pour gérer suppression abonnements et contacts

---

apps/transport/test/test_helper.exs
apps/transport/test/transport/gtfs_rt_test.exs

Fixes #3891
Ajoute un test, avec le tag `:external` (non exécuté en local) vérifiant que le fichier Protobuf GTFS-RT de notre app est bien à la même version que celui publié sur le dépôt source.
En cas de changement on aura un fail de ce test. On pourra alors faire une PR pour le mettre à jour, ou ignorer ce test pendant un temps. https://github.com/etalab/transport-site/issues/3891#issuecomment-2072158178

CI : vérifie que le fichier Protobuf GTFS-RT est bien à jour

---

apps/transport/lib/validators/enroute_chouette_valid_client.ex
apps/transport/test/transport/validators/enroute_chouette_valid_client_test.exs

Le file part du multipart était victime d'un affreux refactoring. (J'avais testé avant le refactoring, bien sûr.)
Ce fix fonctionne (test de bout en bout en local).

Fix le client de l'API enRoute Chouette Valid

---

apps/transport/lib/db/region.ex
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/controllers/page_controller.ex
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

Fixes #4115
Permet d'avoir des titres de catégories de données quand ce n'est pas simplement `type=:type` mais aussi avec des modes ou des tags.
Utilise la configuration des tuiles sur la page d'accueil pour s'assurer de la cohérence entre les paramètres et le titre des données.

Résultats de recherche : uniformise titre de page

---

apps/transport/lib/transport/availability_checker.ex
apps/transport/test/transport/availability_checker_test.exs

Voir:
- #4122
- #3464 (souci similaire, mais actuellement non "traversé" par les ressources que j'ai pu tester)
J'ai implémenté un hot-fix de la manière la moins intrusive possible, en ne touchant pas les options sauf si on est vraiment sur Google Drive.
- Passer à `Req` qui ne présente pas ce problème
- Ouvrir un ticket dans `hackney` pour traiter correctement "303 + GET" (ce qui n'est pas géré actuellement et cause le problème)
```elixir
resources = DB.Resource
|> DB.Repo.all
|> Enum.filter(fn(x) -> x.id == 81575 end)
resources
|> Enum.with_index()
|> Enum.each(fn({r, index}) ->
IO.puts "Processing #{index}/#{resources |> length()}"
url = DB.Resource.download_url(r)
IO.puts url
Transport.AvailabilityChecker.available?(r.format, DB.Resource.download_url(r))
|> IO.inspect
end)
``` …

Correctif sur la disponibilité de la seule ressource hébergée sur Google Drive

---

apps/transport/lib/jobs/resource_history_job.ex
apps/transport/lib/zip.ex
apps/transport/test/transport/jobs/resource_history_job_test.exs
apps/transport/test/zip_test.exs

Fixes #4120
Revoit la méthode pour détecter qu'un fichier local est bien un fichier ZIP. Utilise [la librairie `unzip`](https://hexdocs.pm/unzip/Unzip.html#new/1) pour s'assurer que le fichier sur le disque est bien un ZIP.

ResourceHistoryJob : améliore détection d'un ZIP

---

apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/resource/form.html.heex

Fixes #4132
Répare un lien cassé sur l'espace producteur.
Lors d'un refactor récent, la méthode `:resources_list` a été supprimée du controller mais pas du router https://github.com/etalab/transport-site/pull/4053#discussion_r1725131505 On référençait ainsi cet ancien lien, ce qui causait une erreur 500. Je suis surpris/déçu que Phoenix permette d'avoir des méthodes inexistantes dans un controller alors que c'est référencé dans un router :cry:
Le lien est désormais vers la page d'édition du dataset, ce qui permet de choisir la ressource à éditer.

Espace producteur : mise à jour lien pour modifier une ressource

---

apps/transport/lib/transport_web/plugs/put_locale.ex
apps/transport/test/transport_web/routing/put_locale_test.exs

Fixes #4142
- Vérifie lors d'un changement de locale que celle-ci est bien supportée.
- Ajoute de nombreux tests pour vérifier le bon fonctionnement du plug existant (prise en compte des différentes possibilités de modification de la locale, impact sur la configuration).

PutLocale : vérifie que la locale est bien supportée

---

apps/transport/lib/transport_web/templates/backoffice/contact/_notification_subscriptions.html.heex

Fixes #4146
Ajoute le rôle et la source d'un abonnement plateforme sur la page de détails d'un contact.

Backoffice contacts : affichage role et source pour abonnements plateforme

---

apps/transport/lib/opendatasoft/url_extractor.ex
apps/transport/test/transport/url_extractor_test.exs

En traitant #4149, j'ai (re ?)découvert que `Opendatasoft.UrlExtractor` (le module en charge de trouver des ressources par le biais d'URL présentes dans un export de tableur provenant d'OpenDataSoft) ne trouvait qu'au plus 1 match par ligne.
Si un fichier CSV dispose de plusieurs colonnes qui sont dans notre liste de candidats, seule la première colonne qui matche sera utilisée pour trouver l'URL.
J'ai documenté et testé ce fonctionnement et fait en sorte que ce match soit non sensible à la casse.
J'ai positionné la colonne `url` en premier dans la liste, j'ai constaté que ce nom de colonne était le plus commun quand un producteur renseigne une URL externe, ce qui est ce qu'on cherche en priorité. `fichier` est également très commun mais correspond à un dépôt de fichier sur OpenDataSoft, …

Opendatasoft.UrlExtractor : documente et teste 1 match par ligne

---

apps/transport/lib/validators/enroute_chouette_valid_client.ex
apps/transport/lib/validators/netex_validator.ex
apps/transport/test/transport/validators/enroute_chouette_valid_client_test.exs
apps/transport/test/transport/validators/netex_validator_test.exs

Le validateur d'enRoute peut tomber dans un état incohérent et le statut d'une validation rester en pending éternellement. Ce patch implémente un timeout de notre côté. Il est configuré arbitrairement à 15 minutes pour l'instant.
Voir #4153.

Validateur NeTEx : timeout de 15 minutes

---

apps/transport/lib/validators/enroute_chouette_valid_client.ex
apps/transport/test/transport/validators/enroute_chouette_valid_client_test.exs

A court terme c'est probablement la fonctionnalité la plus utile pour les AOM en attendant qu'on implémente le profil FR correctement.
Voir #4153.

Validateur NeTEx : validation du XSD

---

apps/transport/lib/jobs/new_datagouv_datasets_job.ex
apps/transport/lib/mailer/admin_notifier.ex
apps/transport/test/transport/jobs/new_datagouv_datasets_job_test.exs

Fixes #4159 
Adapte le job en charge de suggérer aux @etalab/transport-bizdev les jeux de données récemment ajoutés sur data.gouv.fr qui pourraient être pertinents à référencer sur le PAN.
- Adapte les règles
- Introduit plusieurs catégories de données, chacune avec ses problèmes règles de pertinence
- Envoi de plusieurs e-mails de JDDs à référencer, en groupant par catégorie de données
- Adapte les tests
- Un peu de refactor
🔜 Le changement d'adresse e-mail destinataire de `deploiement@` à `contact@` sera effectué dans une PR à venir.

NewDatagouvDatasetsJob : e-mail par catégorie de données

---

apps/transport/lib/jobs/new_datagouv_datasets_job.ex
apps/transport/test/transport/jobs/new_datagouv_datasets_job_test.exs
config/runtime.exs
config/test.exs

Suite de #4163
La méthode précédente pour vérifier que les règles avaient des schémas existants ne convenait pas. On en [avait discuté un peu](https://github.com/etalab/transport-site/pull/4163#discussion_r1745403468) mais en réalité au déploiement en production on a une erreur de compilation, à ce stade Cachex, qui est appelé pour la liste des schémas, n'est pas encore démarré.
Stacktrace résultante.
```
2024-09-05T15:33:31.900Z == Compilation error in file lib/jobs/new_datagouv_datasets_job.ex ==
2024-09-05T15:33:31.900Z ** (ArgumentError) errors were found at the given arguments:
2024-09-05T15:33:31.900Z   * 1st argument: the table identifier does not refer to an existing ETS table
2024-09-05T15:33:31.900Z     (stdlib 4.3.1.3) :ets.lookup(:cachex_overseer_table, Shared.Cachex) …
```

NewDatagouvDatasetsJob: check that rules have valid schemas using CRON

---

apps/transport/lib/mailer/admin_notifier.ex
apps/transport/test/transport/data_checker_test.exs
apps/transport/test/transport/jobs/consolidate_bnlc_job_test.exs
apps/transport/test/transport/jobs/datasets_climate_resilience_bill_not_lo_licence_job_test.exs
apps/transport/test/transport/jobs/datasets_without_gtfs_rt_related_resources_notification_job_test.exs
apps/transport/test/transport/jobs/new_datagouv_datasets_job_test.exs
config/config.exs

Les bizdevs ont exprimé leur souhait d'avoir les e-mails de pilotage adressés à `contact@` et non `deploiement@`. Voir #4145 et #4159.
Cette PR change ceci.

E-mails : changement adresse destinataire pour bizdevs

---

apps/transport/lib/jobs/new_datagouv_datasets_job.ex
apps/transport/test/transport/jobs/new_datagouv_datasets_job_test.exs

Lié à #4159 
`<vide>` était interprété comme un tag HTML non existant et non rendu à l'écran [dans Front](https://app.frontapp.com/open/cnv_197ucs9i?key=Yhvgrw_74csEeCpQgjC5zz1_8FWrhrjo) (voir dans "View source").
Change le texte en conséquence.

NewDatagouvDatasetsJob : ajuste information vide

---

apps/transport/lib/validators/netex_validator.ex
apps/transport/test/transport/validators/netex_validator_test.exs

Les autres erreurs de validation sont dégradées en `warning`.
Voir #4153.

Validation NeTEx: seules les erreurs XSD

---

apps/transport/lib/db/notification_subscription.ex
apps/transport/lib/jobs/import_dataset_contact_points_job.ex
apps/transport/test/transport/jobs/import_dataset_contact_points_job_test.exs
config/runtime.exs

Fixes #3897
Cette PR ajoute un job permettant de reprendre les informations des points de contact depuis l'API de data.gouv.fr. Les producteurs peuvent désigner une personne référente pour un JDD sur leur plateforme open data ou depuis data.gouv.fr.
L'objectif est de reprendre cette information et d'inscrire aux notifications producteur pour le JDD.
Ce job réalise ceci pour tout notre catalogue, gère l'ajout/la suppression/le passage d'un contact à un autre.

Import des contact points depuis l'API de data.gouv.fr

---

apps/transport/lib/transport_web/templates/resource/details.html.heex
apps/transport/lib/transport_web/views/resource_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/resource.po
apps/transport/priv/gettext/fr/LC_MESSAGES/resource.po
apps/transport/priv/gettext/resource.pot
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Fixes #4162
- Taille du fichier
- Bouton de téléchargement
- Ajoute un lien vers explore.data.gouv.fr pour ressources pertinentes

Resource#details: link to explore.data.gouv.fr

---

config/dev.exs

En voulant tester des refactorings du validateur GTFS faits dans le cadre de #4153, je me suis pris les pieds dans la config locale. Cette PR corrige ce petit _hiccup_. Il est possible que j'ai loupé quelque chose d'évident.
Il était inutile de redéfinir dans dev.exs, et cette redéfinition supprimait la lecture de l'environnement comme valeur par défaut, rendant ce dernier inopérent.
Il est toujours possible de surcharger dans dev.secret.exs si l'on juge cela nécessaire.

Configuration dev du validator GTFS

---

apps/transport/client/stylesheets/components/_resource-details.scss

Lors de tests de non-régression du validateur GTFS j'ai remarqué que l'affichage des lignes pour la metadata "couverture calendaire" n'était pas assez généreux en largeur.
<details>
<summary>Avant :</summary>
</details>
<details>
<summary>Après :</summary>
</details>

Meilleur affichage de la "couverture calendaire"

---

apps/transport/lib/transport_web/templates/dataset/_resource.html.heex
apps/transport/lib/transport_web/templates/resource/_validation_summary.html.heex
apps/transport/lib/validators/gtfs_transport_validator.ex

Certains commentaires pris en compte sur le validateur NeTEx sont backportés sur le validateur GTFS pour plus tard pouvoir utiliser les deux un peu plus génériquement.
Motivé par #4153.

Unification des APIs des validateurs GTFS & NeTEx

---

apps/transport/lib/validators/netex_validator.ex
apps/transport/priv/gettext/en/LC_MESSAGES/netex-validator.po
apps/transport/priv/gettext/fr/LC_MESSAGES/netex-validator.po
apps/transport/priv/gettext/netex-validator.pot
apps/transport/test/transport/validators/netex_validator_test.exs

A l'occasion de tests manuels, j'ai remis la main sur des cas d'erreurs sans code, scenario que j'avais omis dans des PRs récentes. Cette PR fixe cela.
Voir #4153.

Validateur NeTEx : Support des erreurs sans code

---

apps/transport/lib/transport/data_checker.ex
config/config.exs
config/prod.exs

Fixes #4178
Un warning est visible lors de l'exécution des tests, provenant de `Transport.DataChecker`
```
[warning] Event dropped due to being a duplicate of a previously-captured event.
```
Le warning est visible depuis peu, parce que est Sentry en test mode en `test` (commit https://github.com/etalab/transport-site/commit/344a4d0ddd3daa895de62719cb245ef063c1310c), avant c'était juste silencieux. Mais le warning est intéressant, il dit qu'avec la conf/le code actuel seul le premier event aurait été envoyé. Donc en cas d'erreur d'un appel sur data.gouv.fr on aurait eu 1 seul event comportant le dataset ID et pas les suivants. Le code d'envoi vers Sentry visé est là depuis de nombreux mois.
Il semble qu'il est souhaitable d'envoyer plusieurs événements vers Sentry afin de disposer des …

DataChecker : adapte erreur vers Sentry

---

apps/shared/lib/gbfs_metadata.ex
apps/shared/test/gbfs_metadata_test.exs
apps/transport/test/transport/gbfs_to_geojson_test.exs

Fixes #4208
Ajuste la méthode `Transport.Shared.GBFSMetadata.first_feed/1` pour gérer la payload de `gbfs.json` à partir de la version 3.0 qui ne contient plus de `language`.

GBFSMetadata : ajuste first_feed pour GBFS v3.0

---

apps/transport/lib/transport/gbfs_to_geojson.ex
apps/transport/test/transport/gbfs_to_geojson_test.exs

Fixes #4209
Adapte le code existant pour gérer la différence de valeur pour `station_information.stations[].name` à partir de GBFS 3.0

GbfsToGeoJSON : ajuste station name pour GBFS 3.0

---

apps/transport/client/javascripts/resource-viz.js
apps/transport/lib/transport/gbfs_to_geojson.ex
apps/transport/test/transport/gbfs_to_geojson_test.exs

Fixes #4212
Ajoute un champ `availability` dans la conversion GBFS vers GeoJSON pour gérer le fait que les champs sont nommés différemment selon les versions. Utilise ensuite ce champ dans le code JS.

Transport.GbfsToGeojson : ajout availability

---

apps/transport/lib/jobs/new_datagouv_datasets_job.ex

Certains schémas spécifiés dans la catégorie "Vélo et stationnements" sont invalides. En réalité [c'est un data package](https://schema.data.gouv.fr/etalab/schema-comptage-mobilites/) qui contient 3 schémas, il faut donc spécifier les 3 schémas et non indiquer le nom du data package.
Il y a [du code défensif](https://github.com/etalab/transport-site/blob/5fef8b9af50c5e22c9981989843f5eb36ec41637/apps/transport/lib/jobs/new_datagouv_datasets_job.ex#L81-L91) qui détecte ça, une exception était levée sur Sentry.
[Voir Sentry](https://transport-data-gouv-fr.sentry.io/issues/5818985600/)

NewDatagouvDatasetsJob : corrige liste des schémas

---

apps/transport/lib/transport/history_fetcher.ex
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/dataset/_dataset_resources_history.html.heex
apps/transport/lib/transport_web/templates/dataset/details.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot
apps/transport/test/transport/history_fetcher_test.exs
apps/transport/test/transport_web/controllers/api/datasets_controller_test.exs
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

Fixes #4207 
#4193, le retour. Reprend l'implémentation initiale de #4194 mais limite ceci uniquement à `resource_history` (pas de validations/métadonnées), passe à du streaming pour récupérer les données depuis la base de données et renvoie le résultat en plusieurs chunks HTTP.
Ce changement est fait dans le 2nd commit uniquement pour faciliter la relecture.
Testé avec succès en local sur plusieurs gros JDDs.

Télécharger les détails des ressources historisées en streaming

---

apps/transport/lib/db/contact.ex
apps/transport/lib/jobs/import_dataset_contact_points_job.ex
apps/transport/lib/transport_web/controllers/backoffice/contact_controller.ex
apps/transport/lib/transport_web/controllers/session_controller.ex
apps/transport/priv/repo/migrations/20240926074311_contact_add_creation_source.exs
apps/transport/test/db/contact_test.exs
apps/transport/test/support/factory.ex
apps/transport/test/transport/jobs/import_dataset_contact_points_job_test.exs
apps/transport/test/transport_web/controllers/backoffice/contact_controller_test.exs
apps/transport/test/transport_web/controllers/backoffice/notification_subscription_controller_test.exs
apps/transport/test/transport_web/controllers/session_controller_test.exs

En lien avec #4189
- Ajoute une colonne `creation_source` à la table `contact` pour déterminer la source de création d'un contact.
- Renseigne la valeur de cette colonne pour les enregistrements existants (du mieux possible)
- Adapte le code pour les différentes méthodes de création d'un contact
- Teste et adapte les tests

contact : ajout colonne creation_source

---

apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/templates/dataset/_resource.html.heex
apps/transport/lib/transport_web/templates/dataset/_resource_validation_summary_gtfs.html.heex
apps/transport/lib/transport_web/templates/dataset/_resource_validation_summary_netex.html.heex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/lib/validators/gtfs_transport_validator.ex
apps/transport/lib/validators/netex_validator.ex
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

Follow-up de #4204. Voir #4153.

Validation NeTEx : statistiques dans les cartes de ressources NeTEx d'un dataset

---

apps/transport/test/transport_web/controllers/dataset_controller_test.exs

Cette PR introduit le test associé au hotfix #4233.
Follow-up de #4227.

Dataset : supporter les ressources NeTEx sans validation

---

apps/transport/lib/jobs/consolidate_lez_job.ex
apps/transport/lib/transport_web/live/start_consolidate_job_view.ex
apps/transport/lib/transport_web/templates/backoffice/page/index.html.heex
apps/transport/test/transport/jobs/consolidate_lez_job_test.exs

Fixes #4235
Permet de lancer une consolidation BNZFE depuis le backoffice. Reprend une LiveView existante qui permet de consolider la BNLC et la rend plus générique.

Backoffice : ajout bouton pour consolider BNZFE

---

apps/transport/lib/transport_web/templates/dataset/_resource_validation_summary_netex.html.heex

Comment remarqué dans https://github.com/etalab/transport-site/pull/4227#issuecomment-2391242989, la classe CSS appliquée au résumé des validations interpole directement le niveau de validation maximal et malheureusement la sémantique diffère entre GTFS et NeTEx. Cette PR corrige ceci de façon assez superficielle, à défaut d'uniformiser les codes d'erreurs entre tous les validateurs.
Avant 
Après

NeTEx : Meilleur affichage résumé des erreurs

---

apps/transport/lib/transport_web/controllers/backoffice/contact_controller.ex
apps/transport/test/transport_web/controllers/backoffice/contact_controller_test.exs

Suite de #4244
Gère un bug qui survient avec les données de production (les contacts sont vidés en local), où une liste content `[nil]` n'est pas gérée par la librairie CSV…
[Voir Sentry](https://transport-data-gouv-fr.sentry.io/issues/5968543498/)

Backoffice : encodage de listes pour export de contacts

---

apps/shared/lib/gbfs_metadata.ex
apps/shared/test/gbfs_metadata_test.exs

Fixes #4257
Ajoute des métadonnées sur le type de véhicules présents dans ce flux : vélos, trotinettes, voitures etc

GBFSMetadata : extraction vehicle_types

---

README.md
scripts/README.md
scripts/netex_analyzer.exs
scripts/netex_layout_analyzer.exs

Ce script a servi à [partager une analyse au GT7](https://github.com/etalab/transport-profil-netex-fr/issues/56#issuecomment-2416788728).

Analyse structure fichiers NeTEx existants pour le GT7

---

apps/transport/lib/transport/protobuf/gtfs-realtime.pb.ex
apps/transport/lib/transport/protobuf/gtfs-realtime.proto

[Le CI](https://app.circleci.com/pipelines/github/etalab/transport-site/11176/workflows/59c80088-047b-4020-bae6-c0d781e0710d/jobs/44464) a détecté que le fichier Protobuf GTFS-RT a été mis à jour. https://github.com/google/transit/commit/dadc4485bbfb82a45be519b29ddba4f433f52ba0
Cette PR répercute ce changement.

Mise à jour du fichier Protobuf GTFS-RT

---

apps/transport/lib/transport/application.ex
apps/transport/lib/transport/appsignal_ecto_telemetry.ex
apps/transport/lib/transport/ecto_telemetry.ex

En lien avec:
- #4279
Et vu que c'était peu clair pour moi, je clarifie le code sur les points suivants:
- le handler ne sert en fait qu'à AppSignal (pour l'intégration Ecto) et non à "AppSignal + Ecto" 
- le module ne sert actuellement qu'à AppSignal, le côté dynamique du handler n'a pa été exploité à ce stade, donc je prends note de cet état de fait et je renomme le module pour que ça soit plus clair
Vu que le code correspondant n'est pas testé et pas simple à tester en pratique, j'ai testé en local à la main (dans `handle_event`) avec un `IO.inspect(measurements, IEx.inspect_opts())`, aucun souci détecté, ce qui veut dire que le handler est bien enregistré et fonctionne (point important car ceci n'est pas testé à ma connaissance actuellement).

Clarification du code custom Telemetry AppSignal Ecto

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
apps/transport/lib/transport_web/live/backoffice/custom_tags_live.ex
apps/transport/lib/transport_web/templates/dataset/_banner.html.heex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot
apps/transport/test/transport_web/controllers/api/datasets_controller_test.exs
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

Voir #4275.
Je n'ai pas trouvé d'icone d'avertissement ; en attendant le caractère unicode fait office de substitut.

Datasets expérimentaux

---

apps/transport/lib/transport_web/controllers/resource_controller.ex
apps/transport/lib/validators/validator_selection.ex
apps/transport/test/transport/validators/validator_selection_test.exs
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Actuellement le job est bloquant et sature la queue des validations, bloquant tout le reste et n'utilisant pas la pleine capacité d'enRoute.
Un meilleur fix arrivera dans un second temps.

Temporaire : désactivation validation NeTEx

---

apps/transport/client/javascripts/dataset-map.js
apps/transport/client/javascripts/explore.js
apps/transport/client/javascripts/gtfs.js
apps/transport/client/javascripts/map-config.js
apps/transport/client/javascripts/map-geojson.js
apps/transport/client/javascripts/map.js
apps/transport/client/javascripts/resource-viz.js
apps/transport/client/javascripts/validation-map.js
apps/transport/client/stylesheets/components/_dataset-details.scss

Fixes #4300
Utilise des tuiles IGN en noir et blanc pour plusieurs de nos cartes, sauf carte d'exploration et cartes affichées sur la page statistiques.

Cartes : utilise des tuiles IGN

---

apps/transport/lib/transport_web/plugs/custom_secure_browser_headers.ex

En lien avec #4300 et #4301
J'ai oublié d'autoriser les images provenant du Géoportail IGN dans la CSP…
Il faudrait vraiment que l'on revoit la CSP en local, facile de se faire avoir.

CSP : autorise images venant du Géoportail IGN

---

learning_track.md

Suite à:
- #4287 
- et la bonne remarque de @vdegove (https://github.com/etalab/transport-site/pull/4287#pullrequestreview-2429805896)
je mets quelques billes sur le travail de mise à jour des assets javascript.

Ajout section learning track pour documenter comment mettre à jour les assets javascript

---

apps/transport/lib/transport/import_data.ex
apps/transport/test/transport/import_data_service_test.exs
apps/transport/test/transport/import_data_test.exs
apps/transport/test/transport_web/controllers/backoffice/backoffice_controller_test.exs

En lien avec #4308 / #4309
L'adaptation du code précédente n'était pas suffisante, il faut véritablement écraser la valeur de `resource.type` quand on a détecté que c'est de la documentation.
Je réalise ce changement et je fais des tests bien plus complets.

ImportData : devine le bon type de ressource

---

apps/shared/lib/gbfs_metadata.ex
apps/shared/test/gbfs_metadata_test.exs
apps/transport/lib/transport/gbfs_metadata.ex
apps/transport/lib/transport_web/templates/gbfs_analyzer/index.html.heex
apps/transport/lib/validators/gbfs_validator.ex
apps/transport/priv/gettext/en/LC_MESSAGES/gbfs_analyzer.po
apps/transport/priv/gettext/fr/LC_MESSAGES/gbfs_analyzer.po
apps/transport/priv/gettext/gbfs_analyzer.pot
apps/transport/test/transport/jobs/gbfs_multi_validation_job_test.exs
apps/transport/test/transport/validators/gbfs_validator_test.exs
apps/transport/test/transport_web/controllers/gbfs_analyzer_controller_test.exs

Fixes #4312
Supprime cette clé, désormais non utilisée chez nous et peu utile dans le rapport de validation.

GBFSMetadata : supprimer clé cors_header_value

---

apps/shared/lib/gbfs_metadata.ex
apps/shared/test/fixtures/gbfs/free_bike_status.2.2.json
apps/shared/test/fixtures/gbfs/gbfs.2.2.json
apps/shared/test/fixtures/gbfs/gbfs.3.0.json
apps/shared/test/fixtures/gbfs/station_status.2.2.json
apps/shared/test/fixtures/gbfs/station_status.3.0.json
apps/shared/test/fixtures/gbfs/vehicle_status.3.0.json
apps/shared/test/gbfs_metadata_test.exs
apps/transport/lib/transport/gbfs_to_geojson.ex

Fixes #4258
Calcule des statistiques pour les flux GBFS pour les stations et les véhicules. Le code est adapté pour les différentes versions de GBFS de 1.1 à 3.0.
J'ai exécuté le code sur les différents flux que l'on a chez nous, sans rencontrer d'erreurs.
Il est possible qu'on calcule plus de statistiques plus tard, par exemple distinguer le nombre de véhicules par type (vélo VS trottinette quand un flux comporte les 2) mais il est utile d'envoyer déjà ceci en production, faire un peu de refactor et d'éventuellement ajouter des choses ensuite. On en discutera avec @stephane-pignal.
Une payload complète pour un flux GBFS. La clé ajoutée par cette PR est `stats`
```
%{
cors_header_value: nil,
feed_timestamp_delay: 0,
feeds: ["vehicle_types", "gbfs_versions", "geofencing_zones", …
```

Calcul de statistiques pour les flux GBFS

---

apps/shared/lib/validation/gbfs_validator.ex
apps/shared/test/validation/gbfs_validator_test.exs
apps/transport/lib/transport_web/templates/resource/_errors_warnings_count.html.heex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/test/transport_web/controllers/dataset_controller_test.exs
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Fixes #4296
- Ne stocke pas une validation complète quand le validateur GBFS renvoie un rapport avec les différents champs à `nil`
- Vérifie que les pages `dataset#details` et `resource#details` chargent correctement quand la validation GBFS est `nil`

Gère validation à nil pour flux GBFS

---

apps/shared/lib/gbfs_metadata.ex
apps/shared/test/fixtures/gbfs/station_status.2.2.json

Ignore les données des stations où le nombre de docks ou de véhicules disponibles dans une seule station semble irréaliste (plus de 500).
Ceci permet d'éviter d'avoir des statistiques incohérentes.
Ceci survient par exemple [pour Lime Paris](https://transport.data.gouv.fr/datasets/gbfs-paris), [voir Mattermost](https://mattermost.incubateur.net/betagouv/pl/6agr96dzqtb4dfrhg3ge3bfp3e).
```json
{
"last_updated": 1731763709,
"ttl": 0,
"version": "2.2",
"data": {
"stations": [{
"station_id": "paris",
"num_bikes_available": 9669,
"num_docks_available": 999999,
"is_installed": true,
"is_renting": true,
"is_returning": true,
"last_reported": 1731763709
}]
}
}
```

GBFSMetadata : retire les stations avec données irréalistes

---

apps/transport/lib/transport/gbfs_metadata.ex
apps/transport/test/transport/gbfs_metadata_test.exs

Fixes #4321
Fiabilise la valeur de `types` qui indique si un système a du free floating/des stations.
En effet on constate qu'il existe plusieurs flux avec un flux de station vide ou un flux freefloating avec uniquement des véhicules présents aux stations. Cette PR inspecte le contenu pour assurer une plus grande fiabilité.

GBFSMetadata : fiabiliser le type de système

---

apps/transport/lib/transport/gbfs_metadata.ex
apps/transport/test/fixture/gbfs/station_status.3.0.json
apps/transport/test/transport/gbfs_metadata_test.exs

Fixes https://github.com/etalab/transport-site/issues/4331
Gère le cas des stations virtuelles en GBFS (pas d'infrastructure physique/de docks).
Cette PR :
- ajoute une métrique `nb_virtual_stations`
- adapte le code pour déterminer le type d'un système/de ne pas compter comme `stations` quand des véhicules sont présents dans des stations virtuelles

GBFSMetadata : gère le cas des stations virtuelles

---

apps/transport/lib/jobs/new_datagouv_datasets_job.ex
apps/transport/test/transport/jobs/new_datagouv_datasets_job_test.exs

Fixes #4333
Détecte de manière plus intelligente les JDDs pertinents.
- Gère les pluriels
- Permet de matcher sur les tags avec plusieurs mots
On avait plusieurs tags qui ne pouvaient pas être reconnus avant : `libre service`, `borne de recharge` etc. Ceux contenant des espaces.

NewDatagouvDatasetsJob : gérer JDD non identifiés

---

apps/transport/lib/db/geo_data/geo_data _import.ex
apps/transport/lib/db/geo_data/geo_data_import.ex
apps/transport/lib/jobs/geo_data/base.ex
apps/transport/lib/jobs/geo_data/bnlc_to_geo_data.ex
apps/transport/lib/jobs/geo_data/gbfs_stations_to_geo_data.ex
apps/transport/lib/jobs/geo_data/irve_to_geo_data.ex
apps/transport/lib/jobs/geo_data/lez_to_geo_data.ex
apps/transport/lib/jobs/geo_data/parkings_relais_to_geo_data.ex
apps/transport/priv/repo/migrations/20241120132849_geo_data_import_add_slug.exs
apps/transport/test/transport/jobs/geo_data/bnlc_to_geodata_test.exs
apps/transport/test/transport/jobs/geo_data/gbfs_stations_to_geo_data_test.exs
apps/transport/test/transport/jobs/geo_data/irve_to_geodata_test.exs
apps/transport/test/transport/jobs/geo_data/lez_to_geo_data_test.exs
apps/transport/test/transport/jobs/geo_data/parkings_relais_to_geo_data_test.exs
config/runtime.exs

Première partie de #4324
Cette PR permet :
- l'import de données qui ne sont pas liées obligatoirement à une ressource statique et aux `resource_history`. Ceci est nécessaire car les flux GBFS sont des données temps-réel, non historisées et on souhaite importer plusieurs flux GBFS https://github.com/etalab/transport-site/commit/8078b9bfd655825c9916577f8927b6f04e448e7e
- Un nouveau job `GBFSStationsToGeoData` en charge d'identifier les flux GBFS contenant des stations et d'importer ces données https://github.com/etalab/transport-site/commit/9c1fa4525ba6ae856e13da04c44c7b6f634db705
La partie frontend (afficher les stations sur la carte d'exploration) sera effectuée plus tard, voir #4324

Import des données des stations GBFS dans GeoData

---

apps/transport/lib/mix/tasks/transport/import_aoms.ex

Cette année pas grand chose qui change, juste un petit changement autour du Mans. Un ensemble d’AOMs, qui étaient des communautés de communes en périphérie du Mans, fusionnent en une seule AOM. Elle reprend un reseau_id existant d’une des communautés de communes, le 1293, mais se renomme «Pôle Métropolitain Mobilités Le Mans – Sarthe».
AOM concernées (supprimées) :
- 1283 : CC Maine Coeur de Sarthe, insee_commune_principale: "72024"
- 1285 : CC Le Gesnois Bilurien,   insee_commune_principale: "72329"
- 1288 : CC de la Champagne Conlinoise et du Pays de Sillé, insee_commune_principale: "72334"
- 1292 : CC du Sud Est Manceau, insee_commune_principale: "72058"
- 1294 : CC du Val de Sarthe, insee_commune_principale: "72346"
Cette nouvelle AOM  «Pôle Métropolitain Mobilités Le Mans – Sarthe» …

Mise à jour 2024 des AOM

---

apps/transport/lib/db/dataset.ex
apps/transport/test/transport_web/controllers/dataset_search_test.exs

Fixes #4337
Utilise la date d'ajout sur le PAN pour le tri par "ajouté récemment", ce qui est le fonctionnement plus naturel pour les utilisateurs. `created_at` est une colonne hasardeuse, venant de data.gouv.fr, qui peut avoir des valeurs très étonnantes à cause du moissonnage.
Ajoute des tests pour les tris sur la recherche, ce n'était pas présent pour le moment.

Recherche : tri sur JDD ajoutés récemment

---

apps/transport/lib/db/dataset.ex
apps/transport/test/transport_web/controllers/dataset_search_test.exs

En lien avec #4337
Malheureusement la précédente PR se heurte à la question des quelques valeurs `null` présentes dans la colonne, avant que la colonne n'existe dans la table. https://github.com/etalab/transport-site/pull/4338#issuecomment-2501537923
Cette PR fait en sorte que l'on mette ces JDDs à la fin, et non au début.

Tri des JDDs : null en dernier

---

apps/transport/lib/transport_web/live/backoffice/jobs_live.ex
apps/transport/lib/transport_web/live/backoffice/jobs_live.html.heex
apps/transport/lib/transport_web/live/backoffice/jobs_table_component.ex

Dans le cadre de #4326 j'ai utilisé la fonctionnalité de "snooze" d'Oban, ce qui place certains jobs dans l'état "scheduled_in". En testant davantage cette PR j'ai également constaté que certains jobs en erreurs (état "retryable") n'étaient pas non plus listés.
Pour les jobs "scheduled", la date de prochaine exécution est affichée.
Pour les jobs "retryable", l'erreur et la date de prochaine exécution sont affichées.

Backoffice - jobs : support des états "retryable" et "scheduled"

---

apps/transport/lib/db/contact.ex
apps/transport/lib/db/notification_subscription.ex
apps/transport/lib/jobs/import_dataset_contact_points_job.ex
apps/transport/lib/jobs/import_gbfs_feed_contact_email_job.ex
apps/transport/test/transport/jobs/import_gbfs_feed_contact_point_job_test.exs
config/runtime.exs

Fixes #4339
Cette PR :
- crée un nouveau job `ImportDatasetContactPointsJob` en charge d'identifier les flux GBFS contenant les adresses e-mails des exploitants, crée un contact/trouve un contact, inscrit ce contact aux notifications en tant que producteur pour chaque JDD
- gère le cas où l'adresse/l'exploitant change en supprimant une ancienne configuration puis en créant la nouvelle
- extrait quelques méthodes de `ImportDatasetContactPointsJob` dans `DB.NotificationSubscription` pour les partager entre les 2 jobs
cc @ptitfred je t'ai assign pour la review comme tu avais review le précédent job, peut-être que tu t'en rappelles.

GBFS : inscrire les exploitants aux notifications pour producteurs

---

apps/transport/lib/jobs/import_gbfs_feed_contact_email_job.ex
apps/transport/test/transport/jobs/import_gbfs_feed_contact_point_job_test.exs

Suite de #4344
- Remplit le champ `contact.organization` lorsque l'on crée un contact
- Correction de quelques commentaires

ImportGBFSFeedContactEmailJob : remplit organization pour le contact

---

apps/transport/lib/transport/gbfs_metadata.ex
apps/transport/test/fixture/gbfs/gbfs.2.2.json
apps/transport/test/fixture/gbfs/gbfs.3.0.json
apps/transport/test/fixture/gbfs/station_information.2.2.json
apps/transport/test/fixture/gbfs/station_information.3.0.json
apps/transport/test/fixture/gbfs/station_status.3.0.json
apps/transport/test/transport/gbfs_metadata_test.exs

#4331, le retour.
J'ai été trop vite https://github.com/etalab/transport-site/pull/4332#issuecomment-2501242118 et placé ce champ dans `station_status` alors qu'il est présent dans `station_information`. Repéré en inspectant les statistiques en production et en constatant un 0 partout…
Cette PR répare ceci.

GBFSMetadata : lit station_information.is_virtual_station

---

apps/transport/test/documentation_links_test.exs
apps/transport/test/test_helper.exs
apps/transport/test/transport/gtfs_rt_test.exs

Exécute certains tests uniquement sur CircleCI, uniquement les lundis. Ceci est utile pour des tests que l'on doit exécuter de manière régulière sans que ce soit nécessaire et bloquant.
Les tests concernés sont :
- vérifier que les liens vers la documentation sont bien valides
- que le fichier Protobuf GTFS-RT est bien à jour

Tests exécutés les lundis en CI

---

.circleci/config.yml

Les bénéfices attendus de Dialyzer sont bien maigres rapportés à la frustration causée par les erreurs de CI trop fréquentes. Nous attendrons désormais elixir 1.18 et ses premiers contrôles de type checking.
Cette PR se contente de supprimer dialyzer de la CI. La commande mix et les typespecs sont toujours présents pour ceux que cela intéresse en local.

Farewell Dialyzer

---

README.md

En travaillant sur:
- #4359
- #2425 
le support de CleverCloud m'a indiqué que leur changelog est présent en public, je l'ajoute ici.
J'ai mis un lien vers `.tool-versions` vite fait aussi, qui contient toutes les infos nécessaires pour la maintenance Elixir et OTP.

Ajout changelog CleverCloud et + dans le README

---

README.md
apps/transport/lib/mix/tasks/logs.ex
config/config.exs
config/runtime.exs
docs/upgrade_versions.md
learning_track.md
restore_db.sh

Ref:
- https://github.com/etalab/transport-site/pull/4367#discussion_r1878124598

Correction nommage "Clever Cloud" dans la doc

---

apps/transport/lib/jobs/new_datagouv_datasets_job.ex
apps/transport/test/transport/jobs/new_datagouv_datasets_job_test.exs

Adapte `NewDatagouvDatasetsJob`, le job en charge d'identifier les JDDs récemment publiés sur data.gouv.fr susceptibles d'être pertinents chez nous pour :
- avoir de meilleurs mots clés pour la catégorie des ZFE
- mieux gérer les accents dans les règles, pour éviter de voir indiquer `velo` et `vélo` par exemple

NewDatagouvDatasetsJob : recherche pour ZFE et gestion accents

---

.circleci/config.yml
apps/transport/client/webpack.prod.js

Cette PR met en place du [cache Webpack](https://webpack.js.org/configuration/cache/) pour accéder le job `Compile assets` et la commande `cd ~/transport/apps/transport/client && npm run build`.
On passe d'environ 60 secondes à 4s en CI, soit un gain d'environ 1 minute par build 🥳 
À noter qu'il n'y a pas de risque d'impact en production, on ne package pas (encore ?) les assets JS/CSS/images lors du CI pour une release en production.
[Voir le dernier workflow](https://app.circleci.com/pipelines/github/etalab/transport-site/11596/workflows/c6e8c006-3af8-4abb-a92d-14b48ad95b14/jobs/44906)

CI : cache du build Webpack

---

.circleci/config.yml

Suite de #4375
L'amélioration introduite en cours de PR (cache uniquement en CI et non quand le build est en production) nous amène à la situation suivante :
- le fichier `webpack.prod.js` a été modifié depuis que le cache CircleCI a été créé (la clé du cache étant `js-<< parameters.js_cache_key >>-{{ checksum "apps/transport/client/yarn.lock" }}`)
- webpack ignore le cache préalablement sauvegardé car la configuration webpack a changé
[Un build sur master](https://app.circleci.com/jobs/github/etalab/transport-site/44921) fait apparaitre les logs suivants pour la tâche "Compile assets"
```
<t> [webpack.cache.PackFileCacheStrategy] restore cache container: 58.304911 ms
[webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] /root/transport/apps/transport/client/webpack.prod.js …
```

CircleCI : checksum pour fichiers Webpack et yarn.lock

---

apps/transport/lib/irve/extractor.ex
apps/transport/lib/transport_web/live/backoffice/irve_dashboard_live.ex
apps/transport/lib/transport_web/live/backoffice/irve_dashboard_live.html.heex
apps/transport/test/transport/irve/irve_extractor_test.exs

Cette PR corrige ce bug:
- #4383 
Quand une ressource ne retournait pas HTTP 200, une erreur se produisait qui stoppait la progression. Le code est testé pour ce cas à présent.
Si une ressource est rapportée comme "valide" par data gouv, _mais_ retourne un HTTP différent de 200 (typiquement 404/500), comme ça s'est produit ici, j'affiche à présent `KO` suivi du status HTTP, ce qui permet de filtrer sur ce cas. Vidéo:
https://github.com/user-attachments/assets/4c5e841b-9ae1-47c8-ac59-5de7a6ea88e7

Correctif & amélioration outil de scan IRVE back-office

---

apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/session.ex
apps/transport/lib/transport_web/templates/dataset/_header_links.html.heex
apps/transport/lib/transport_web/templates/dataset/details.html.heex
apps/transport/lib/transport_web/templates/dataset/index.html.heex
apps/transport/lib/transport_web/templates/layout/_header.html.heex
apps/transport/lib/transport_web/templates/page/index.html.heex
apps/transport/priv/gettext/alert.pot
apps/transport/priv/gettext/en/LC_MESSAGES/alert.po
apps/transport/priv/gettext/fr/LC_MESSAGES/alert.po
apps/transport/test/transport_web/controllers/reuser_space_controller_test.exs
apps/transport/test/transport_web/session_test.exs
config/runtime.exs

L'espace réutilisateur est déployé depuis plusieurs mois. On avait du code permettant de désactiver rapidement cette fonctionnalité au lancement, pour corriger d'éventuels bugs ou problèmes de performance.
Ceci ne semble pas nécessaire maintenant, je :broom: donc.

Suppression feature flag espace réutilisateur

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/transport_web/templates/dataset/details.html.heex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/priv/gettext/db-dataset.pot
apps/transport/priv/gettext/en/LC_MESSAGES/db-dataset.po
apps/transport/priv/gettext/fr/LC_MESSAGES/db-dataset.po
apps/transport/test/transport/data_checker_test.exs
apps/transport/test/transport_web/controllers/dataset_controller_test.exs
apps/transport/test/transport_web/controllers/dataset_search_test.exs
apps/transport/test/transport_web/live_views/followed_datasets_live_test.exs

Fixes #4388
- Change le label pour la catégorie `public-transit` : de "Transport public collectif - horaires théoriques" à "Transport public collectif"
- N'affiche pas 2 labels pour les JDDs avec du temps-réel : uniquement "Transport public collectif"
- On garde le titre de la tuile "Transport public collectif - horaires temps réel" sur la page d'accueil et le titre des résultats de la recherche si on clique sur cette tuile
La page d'accueil est laissée telle quelle, seul le titre de la première tuile est modifié pour correspondre au reste, uniquement "Transport public collectif". La question des tuiles pour les autres modes pourra être abordée ultérieurement.
cc @cyrilmorin

Supprimer traduction horaires théoriques

---

apps/transport/lib/transport_web/plugs/router.ex
apps/transport/lib/transport_web/plugs/worker_healthcheck.ex
apps/transport/test/transport_web/plugs/worker_healthcheck_test.exs

Ajoute un plug pour vérifier que notre worker fonctionne correctement.
Le plug répond pour toutes les requêtes HTTP sur le worker, il répond un statut 200 si :
- l'application a été démarrée il y a moins de 20 minutes
- au moins 1 job a été exécuté dans les dernières 60 minutes par Oban
Si ces 2 conditions sont fausses alors le plug répond un statut 503, ce qui causera un redémarrage de l'application par le monitoring de notre hébergeur.
PS : cette branche est déployée [sur prochainement](https://workers.prochainement.transport.data.gouv.fr/) depuis quelques heures

Plug pour vérifier le bon fonctionnement du worker

---

apps/transport/test/transport/jobs/import_gbfs_feed_contact_point_job_test.exs

Fixes #4398
Il me semblait que le code précédent était suffisant pour avoir un tri déterministe mais on a eu au moins une occurence qui prouve le contrainte. Une création des 2 contacts lors de la même milliseconde ?!?
En triant par ID on devrait avoir quelque chose de plus stable, respectant l'ordre d'exécution :
- création du contact dans la phase de setup du test
- exécution du job, qui crée un second contact

Amélioration de la stabilité d'un test

---

apps/transport/lib/validators/validator_selection.ex
config/runtime.exs

Dans la perspective funeste où il nous faille la débrancher (notamment pendant les congés de fin d'année), voici une PR qui introduit la variable d'environnement `DISABLE_NETEX_VALIDATOR`, acceptant une valeur représentant un booléen, donc par convention `true` ou `false`. Par défaut la valeur est fausse. Il s'agit donc davantage d'un kill switch que d'un feature flag.

Feature flag pour la validation NeTEx

---

apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/test/transport_web/views/dataset_view_test.exs

Afficher la carte de la BNLC principale

---

apps/transport/lib/transport_web/plugs/worker_healthcheck.ex

Après le merge, voilà le comportement consolidé:
- chaque appel d'Updown sur le worker lance un calcul de health et affiche le résultat en sortie HTTP
- au même moment, un métrique est envoyé dans AppSignal (avec un seuil qui nous alerte par mail, et moi par PagerDuty à titre de test)
- un état de "health" est calculé : si aucun job n'a tourné dans les 60 dernières minutes, _et_ que l'application tourne au moins depuis 20 minutes (période de grâce pour éviter des redémarrages intempestifs), on considère que l'application n'est pas healthy
- jusque là on ne faisait que retourner un 503 à partir de ça, mais ça ne suffit pas en pratique
- ⚠️ à présent si non healthy (donc après 20 minutes minimum depuis le démarrage, + 60 minutes sans job Oban attempted), je fais un `System.stop()`, qui est …

Hot-fix: shutdown du worker si les jobs ne sont plus traités

---

apps/transport/lib/jobs/workflow.ex

Fixes #4408
Voir le ticket pour la source du problème et les conséquences.
Je n'ai pas réussi à écrire de bons tests en moins de 30 minutes, le challenge est important : dummy Job Oban qui timeout et échanges de messages par le Notifier Oban.
En local j'ai bien reproduit l'erreur, vu la stracktrace qui la causait et vu que c'était correctement géré en exécutant les jobs en local avec le fix présenté ici : encoder la payload, pour gérer le fait qu'on peut avoir une structure ou une chaine de caractères.

Transport.Jobs.Workflow : gérer Oban.TimeoutError

---

apps/transport/lib/jobs/oban_logger.ex
apps/transport/test/transport/jobs/oban_logger_test.exs

En lien avec #4377, #4384, #4408
Ajoute des logs pour Oban, pour aider à diagnostiquer des problèmes en production.
Je suis les [bonnes pratiques](https://hexdocs.pm/oban/preparing_for_production.html#logging) pour la production mais je ne log pas `:job, :start` et `:job, :end` sinon on aurait au moins 120k lignes de logs par jour vu notre volume de jobs exécuté.

Oban : logs des composants importants

---

apps/transport/lib/jobs/new_datagouv_datasets_job.ex
apps/transport/test/transport/jobs/new_datagouv_datasets_job_test.exs

Fixes #4411
Adapte `NewDatagouvDatasetsJob` en charge d'identifier les JDDs pertinents à référencer sur le PAN. Le code précédent était trop laxiste : pour une catégorie "vélos" avec le mot clé "vélo" qui nous intéresse, on aurait dit qu'un JDD avec un tag `developpement-durable` était pertinent.
J'adapte donc la méthode en charge de supprimer les accents (qui supprimait les espaces avant…) et la méthode de matching en fonction de mots-clefs. Un simple `String.contains?` ne suffit pas.

Notification nouveaux JDD : répare matching avec mots-clefs

---

apps/transport/priv/gbfs_operators.csv

Contexte : on a une liste de mapping URLs/opérateur GBFS pour enrichir des métadonnées et un job qui identifie les manques. Voir précédemment https://github.com/etalab/transport-site/pull/4361#pullrequestreview-2489509605
[Voir sur Front](https://app.frontapp.com/open/cnv_19rqbkpi?key=jqe910-na5u2tlBkTswE7NLSx6xRe3pv)

Opérateurs GBFS : ajout URLs Okina pour Ecovélo

---

apps/transport/lib/transport_web/plugs/worker_healthcheck.ex
apps/transport/test/transport_web/plugs/worker_healthcheck_test.exs

Le correctif introduit dans https://github.com/etalab/transport-site/issues/4377 (https://github.com/etalab/transport-site/pull/4405) arrête complètement le programme dans certaines conditions. Or je n'avais pas vu que le plug correspondant est sous tests (https://github.com/etalab/transport-site/pull/4399).
La conséquence est que la suite de test est interrompue au "moment où ce test tourne", et le tout avec un code d'erreur zéro, qui fait que ça ne se remarque que difficilement.
Par conséquent, dans cette PR :
- Je remplace l'appel à `System.stop()` par un raise avec un message clair, uniquement pendant les tests
- Je modifie le test associé, et j'ajoute de la documentation, car ce comportement est important pour le bon fonctionnement de la prod
- Je modifie (y compris en production …

Ne plus stopper la BEAM pendant les tests

---

apps/transport/priv/zfe_ids.csv

[La ZFE de Tours](https://transport.data.gouv.fr/datasets/zone-a-faibles-emissions-zfe-tours-metropole-val-de-loire) est rattachée à l'AOM qui est [un syndicat](https://annuaire-entreprises.data.gouv.fr/entreprise/syndicat-des-mobilites-de-touraine-200085108) et non la métropole. On a la même chose pour la ZFE des [voies spéciales de Lyon](https://transport.data.gouv.fr/datasets/voies-speciales-de-la-zone-a-faibles-emissions-de-la-metropole-de-lyon).
Les données ne correspondant pas, le `zfe_id` est vide pour cette ZFE.
Je mets à jour les données immédiatement et je réfléchis à une meilleure solution long terme pour identifier ces données à corriger.
[Voir sur Front](https://app.frontapp.com/open/msg_2axrh11y?key=StDOYfcpVqUx_y_7_7ZgKEm-uMc-MtQK)

Identifiants ZFE : ajout syndicats pour Tours et Lyon

---

apps/transport/lib/transport/api_cache.ex
apps/transport/lib/transport/application.ex
apps/transport/lib/transport/cache.ex
apps/transport/lib/transport/preemptive_api_cache.ex
apps/transport/lib/transport_web/api/controllers/datasets_controller.ex

Cette PR rajoute un mécanisme pour calculer et remplir automatiquement le contenu du cache pour la réponse de l’endpoint principal `/api/datasets`. 
Ce calcul du cache se fait au lancement de l’application puis toutes les 5 minutes, le cache étant configuré pour expirer au bout de 10 minutes. En théorie donc, aucun utilisateur ne devrait obtenir de résultat non caché sur cet endpoint. J’ai toutefois gardé le fonctionnement précédent par sécurité : si jamais le cache venait à ne pas être rempli, l’appel GET sur `/api/datasets` devrait fonctionner (et re-remplir le cache avec un délai de 10 minutes).
Chez moi ça marche, (mais ce n’est pas testé par des tests en dur), extrait de logs :
```
[info] [api-cache-genserver] Finished populating cache for /api/datasets
[info] GET /api/datasets/ …
```

Cache préemptif pour l’endpoint /api/datasets

---

apps/transport/priv/gbfs_operators.csv

Voir la détection du mapping manquant [sur Front](https://app.frontapp.com/open/cnv_19w2sxzq?key=s6ylqP9LwTC1dEKN7QxIRT4RymHSSPrE)

Opérateurs GBFS : ajout URLs pour Dott

---

apps/transport/lib/validators/gtfs_transport_validator.ex
apps/transport/priv/gettext/en/LC_MESSAGES/gtfs-transport-validator.po
apps/transport/priv/gettext/fr/LC_MESSAGES/gtfs-transport-validator.po
apps/transport/priv/gettext/gtfs-transport-validator.pot

GTFS validator: Fix unusable_trip display

---

apps/transport/lib/transport/telemetry.ex
apps/unlock/lib/controller.ex

En lien avec #4180
Réduit le nombre de lignes de log envoyées vers AppSignal. Actuellement chaque requête sur le proxy.
Exemples de lignes qui ne seront plus envoyées
```
Telemetry event: processing external proxy request for proxy:palmbus-cannes-gtfs-rt-vehicle-position
Proxy response for palmbus-cannes-gtfs-rt-vehicle-position served from cache
```

Proxy GTFS-RT : réduit volume de logs

---

apps/transport/lib/transport_web/controllers/page_controller.ex
apps/transport/test/transport_web/controllers/page_controller_test.exs

On peut avoir des doublons dans https://transport.data.gouv.fr/humans.txt quand il y a des membres de l'équipe qui sont anciens et que leur compte est expiré.
Gère ce cas et ajoute un test.

humans.txt : suppression de doublons

---

apps/transport/lib/transport_web/live/gtfs_diff_select_live.ex
apps/transport/lib/transport_web/live/gtfs_diff_select_live.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/validations.pot

Si on upload 2 fichiers à la fois, l'ordre résultant peut ne pas convenir (ordre alphabétique peu pertinent par exemple).

GTFS diff: bouton pour échanger les fichiers

---

apps/transport/lib/transport/application.ex
apps/transport/lib/transport/preemptive_api_cache.ex
apps/transport/lib/transport/preemptive_base_cache.ex
apps/transport/lib/transport/preemptive_stats_cache.ex
apps/transport/lib/transport_web/api/controllers/stats_controller.ex
apps/transport/lib/transport_web/controllers/stats_controller.ex
apps/transport/test/transport_web/controllers/api/stats_controller_test.exs

Rajoute un cache préemptif sur le modèle du point principal d’API et créé un module générique pour tous les mécanismes similaires à l’avenir.
À comparer à la branche de la PR #4432 sur laquelle elle est basée.

Cache préemptif des statistiques

---

apps/transport/lib/db/resource.ex

Fixes #4448
Voir https://github.com/etalab/transport-site/issues/4448#issuecomment-2664994230
Sans l'utilisation de la colonne `convert_from` on ne peut pas utiliser l'index en place et la requête prend alors 18s au lieu de 80ms.

DB.Resource.get_related_conversion_info : utilise l'index SQL

---

apps/transport/lib/jobs/consolidate_lez_job.ex
apps/transport/priv/zfe_ids.csv
apps/transport/test/transport/jobs/consolidate_lez_job_test.exs

Fixes #4464
Permet de retrouver une organization qui publie la ZFE quand un JDD est rattaché à une AOM ou non. Auparavant dans le second cas on avait une variable qui faisait le mapping alors qu'un semblant de mapping coexistait dans le [fichier CSV zfe_ids.csv](https://github.com/etalab/transport-site/blob/master/apps/transport/priv/zfe_ids.csv).
Cette PR uniformise la méthode pour trouver le nom/code/SIREN d'une ZFE pour se reposer uniquement sur le fichier CSV.

ConsolidateLEZJob : utilisation unique du fichier CSV

---

apps/transport/lib/db/resource_history.ex
apps/transport/lib/db/reuser_improved_data.ex
apps/transport/lib/jobs/resource_history_job.ex
apps/transport/priv/repo/migrations/20250225130151_resource_history_add_reuser_improved_data.exs
apps/transport/priv/repo/migrations/20250305130125_resource_history_nullable_datagouv_id.exs
apps/transport/test/support/factory.ex
apps/transport/test/transport/jobs/resource_history_job_test.exs
config/runtime.exs

En lien avec #4011
Cette PR permet d'historiser des ressources améliorées partagées par les réutilisateurs. Les réutilisateurs partagent une URL vers un GTFS amélioré actuellement, on souhaite historiser cette URL et procéder à la validation de ces resource history.
Le code actuel est adapté pour gérer des `DB.Resource` et `DB.ReuserImprovedData` dans `ResourceHistoryJob` qui est en charge de l'historisation.
L'historisation de ces ressources améliorées est effectuée 2 fois par jour (toutes les 6h pour les ressources statiques classiques).
La validation se fait automatiquement dès qu'on a une ressource history avec un champ `payload.format = 'GTFS'` par le biais du job de workflow.

ResourceHistory job pour ReuserImprovedData

---

apps/transport/lib/jobs/gtfs_diff_job.ex
apps/transport/lib/transport_web/live/gtfs_diff_select_live.ex
apps/transport/lib/transport_web/live/gtfs_diff_select_live/results.ex
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/validations.pot
apps/transport/test/transport/jobs/gtfs_diff_job_test.exs

En cas de GTFS diff depuis des URLs, il est désormais possible de télécharger les fichiers d'origine.
Aperçu :

GTFS diff par URLs : télécharger les sources

---

apps/transport/lib/transport_web/templates/email/producer_with_subscriptions.html.md
apps/transport/lib/transport_web/templates/email/producer_without_subscriptions.html.md
apps/transport/test/transport/jobs/periodic_reminder_producers_notification_job_test.exs

- Indique le pourquoi (rôle producteur)
- Clarifie les autres abonnements (dans le cas où ce n’est pas dans la même organisation, exemple prestataire technique VS AOM).

Amélioration du wording du mail de rappel de notification des producteurs

---

apps/transport/lib/transport/gtfs_diff.ex
apps/transport/lib/transport_web/live/gtfs_diff_select_live/results.ex
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/validations.pot

La notion de profil du GTFS diff concernait toutes les différences,visant à limiter la taille du CSV pour l'affichage dans l'outil. Ceci masquait les ajouts/suppressions de fichiers ou toutes les différences de colonnes des fichiers hors profil. Hors ces différences sont pas nature peu nombreuses.
Cette PR modifie donc le filtre pour ne s'appliquait qu'aux différences liées aux lignes des fichiers hors profil. Cela a pour conséquence de lister tous les fichiers présents dans l'écran de résultats. Un avertissement est ajouté pour les fichiers hors profil pour rappeler que certaines différences peuvent donc ne pas apparaître. Le panneau "Autres fichiers" est supprimé car désormais superflu.
Voir #4460.

GTFS diff : profil uniquement pour les lignes

---

apps/transport/client/stylesheets/components/_gtfs_diff.scss
apps/transport/lib/transport_web/live/gtfs_diff_select_live.ex
apps/transport/lib/transport_web/live/gtfs_diff_select_live/results.ex
apps/transport/test/transport_web/live_views/gtfs_diff_select_live_test.exs

Ça ne teste pas directement la liveview (problèmes avec l'upload) mais ça teste au moins le composant d'affichage des résultats, en anticipation de changements prochains listés dans #4460.
Pour les biens des requêtes Floki des tests, la structure HTML est simplifiée au passage, et un id est introduit pour requêter plus fiablement le contenu du DOM. Ces deux modifications justifient le changement de CSS.

GTFS-diff : Tests de l'écran résultats

---

apps/transport/lib/db/reuse.ex
apps/transport/lib/transport/stats_handler.ex
apps/transport/test/support/factory.ex
apps/transport/test/transport/stats_handler_test.exs

En lien avec #4477, suite de #4478
Stocke des statistiques quotidiennement dans `stats_history` liées aux réutilisations.
```
%{
"reuses::nb_reuses" => 235,
"reuses::sum_metric_discussions" => 60,
"reuses::sum_metric_followers" => 586,
"reuses::sum_metric_views" => 3405602,
"reuses::api" => 14,
"reuses::application" => 160,
"reuses::hardware" => 1,
"reuses::news_article" => 7,
"reuses::paper" => 2,
"reuses::post" => 5,
"reuses::visualization" => 46
}
```

StatsHandler : stocke des statistiques pour les réutilisations

---

.credo.exs

Comme discuté, on retire le check sur les annotations TODO, et on garde sur FIXME, pour que la CI puisse passer au moins sur les premiers.
J’ai aussi retiré un commentaire qui était faux sur la configuration, la syntaxe du fichier de configuration a changé depuis que le fichier a été initialement généré.

Supprime le check sur les annotations TODO dans Credo

---

apps/transport/lib/db/reuse.ex
apps/transport/lib/transport_web/controllers/reuse_controller.ex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/layout/_header.html.heex
apps/transport/lib/transport_web/templates/reuse/index.html.heex
apps/transport/lib/transport_web/views/reuse_view.ex
apps/transport/priv/gettext/default.pot
apps/transport/priv/gettext/en/LC_MESSAGES/default.po
apps/transport/priv/gettext/en/LC_MESSAGES/reuses.po
apps/transport/priv/gettext/fr/LC_MESSAGES/default.po
apps/transport/priv/gettext/fr/LC_MESSAGES/reuses.po
apps/transport/priv/gettext/reuses.pot
apps/transport/test/support/factory.ex
apps/transport/test/transport_web/controllers/reuse_controller_test.exs

Dernière étape de #4477, ajoute une page pour afficher les réutilisations data.gouv.fr des JDDs référencés sur notre plateforme.
La nouvelle page affiche ceci sous forme de cartes et est paginée.

Ajout page pour afficher les réutilisations

---

apps/transport/lib/jobs/dataset_quality_score.ex
apps/transport/test/transport/jobs/dataset_quality_score_test.exs

Fixes #4376
Calcule le score de conformité en prenant en compte les ressources NeTEx et leurs validations avec le validateur d'EnRoute.
Précédemment ces ressources étaient ignorées pour le calcul du score bien que la validation existe.

DatasetComplianceScore : calcul du score pour du NeTEx

---

apps/transport/client/stylesheets/components/_gtfs_diff.scss
apps/transport/lib/transport_web/live/gtfs_diff_explain.ex
apps/transport/lib/transport_web/live/gtfs_diff_select_live/differences.ex
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/validations.pot
apps/transport/test/gtfs_diff_explain_test.exs
apps/transport/test/transport/jobs/dataset_quality_score_test.exs
apps/transport/test/transport_web/live_views/gtfs_diff_select_live_test.exs

Spinoff de #4493 se concentrant sur la mise en page des différences détaillées. Pas de nouveauté métier.
Voir #4460.

GTFS diff : affichage tabulaire des changements

---

apps/transport/client/stylesheets/components/_gtfs_diff.scss
apps/transport/lib/transport_web/live/gtfs_diff_explain.ex
apps/transport/lib/transport_web/live/gtfs_diff_select_live/differences.ex
apps/transport/lib/transport_web/live/gtfs_diff_select_live/gtfs_specification.ex
apps/transport/priv/gettext/en/LC_MESSAGES/gtfs-file-descriptions.po
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/gtfs-file-descriptions.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/gtfs-file-descriptions.pot
apps/transport/priv/gettext/validations.pot
apps/transport/test/gtfs_diff_explain_test.exs

Nouveaux détails de modifications :
- agency_url
- stop's location_type
- type de route
- couleur de ligne;
- trip_headsign
- noms de ligne
Voir #4460.

GTFS diff : davantage de détails des changements

---

apps/transport/client/stylesheets/app.scss
apps/transport/client/stylesheets/reuses.scss
apps/transport/lib/db/reuse.ex
apps/transport/lib/transport_web/controllers/reuse_controller.ex
apps/transport/lib/transport_web/templates/reuse/index.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/reuses.po
apps/transport/priv/gettext/fr/LC_MESSAGES/reuses.po
apps/transport/priv/gettext/reuses.pot
apps/transport/test/db/reuse_test.exs
apps/transport/test/transport_web/controllers/reuse_controller_test.exs

Fixes #4507
Ajoute une barre de recherche à la page de réutilisations afin de chercher par :
- titre de réutilisation
- auteur
- organisation
La recherche est effectuée sans tenir compte de la casse ni des accents.

Page de réutilisations : ajout d'une recherche

---

apps/transport/lib/transport_web/live/gtfs_diff_select_live/results.ex
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/validations.pot

Seule la version française était concernée.
Le lien est déplacé sur l'expression "GTFS modifié" pour alléger le texte.
See #4517.

GTFS-diff: Correction lien téléchargement

---

apps/transport/lib/transport_web/live/gtfs_diff_explain/explanations.ex

La fonction acos() est définie sur l‘intervalle [-1, 1]. L’argument de acos() est le résultat d’un calcul qui est correct mathématiquement mais souffre d’erreurs d’arrondi avec les flottants, ce qui est notre cas ici.
Quand la distance est très très courte, elle peut produire une valeur très proche de 1 et à cause des arrondis dépasser cette valeur et sortir de l’intervalle.
Cette PR s’assure que la valeur est bien comprise dans l’intervalle attendu, au risque d'une inapproximation. Cette inapproximation est négligeable comparées aux erreurs d’arrondi en jeu. A noter également que dans ce cas la distance est tellement faible que ce résultat sera ignoré quoi qu’il en soit.
Fixes #4522.

GTFS-diff, calcul de distance: erreurs d'arrondi

---

apps/transport/lib/transport_web/controllers/reuser_space_controller.ex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/reuser_space/new_token.html.heex
apps/transport/lib/transport_web/templates/reuser_space/settings.html.heex
apps/transport/lib/transport_web/views/bread_crumbs.ex
apps/transport/priv/gettext/en/LC_MESSAGES/reuser-space.po
apps/transport/priv/gettext/fr/LC_MESSAGES/reuser-space.po
apps/transport/priv/gettext/reuser-space.pot
apps/transport/test/transport_web/controllers/reuser_space_controller_test.exs

Ajoute le code nécessaire pour créer un nouveau token (nom et organisation à voir) et les tests associés.
ℹ️ la page des paramètres est toujours accessible uniquement par les membres du PAN.

Espace réutilisateur : créer un nouveau token

---

apps/transport/priv/gbfs_operators.csv

[Voir alerte sur Front](https://app.frontapp.com/open/msg_2c7yni3a?key=XytrR-1DaY9VAmIBHmsCVIqzohoNG6f1)

GBFS : mise à jour opérateur pour Lyon

---

apps/transport/lib/transport_web/controllers/reuser_space_controller.ex
apps/transport/lib/transport_web/templates/reuser_space/new_token.html.heex
apps/transport/test/transport_web/controllers/reuser_space_controller_test.exs

Suite de #4526
Gère les éventuelles erreurs lors de la création d'un token via le formulaire. Ceci peut survenir si quelqu'un manipule le DOM pour retirer des attributs HTML, ce n'est donc pas une situation classique. Les tests prouvent qu'on gère tout de même correctement ce scénario.

Création d'un token : gestion des erreurs

---

apps/transport/lib/transport_web/templates/resource/_gtfs_no_calendar.html.heex
apps/transport/lib/transport_web/views/resource_view.ex
apps/transport/lib/validators/gtfs_transport_validator.ex
apps/transport/priv/gettext/en/LC_MESSAGES/gtfs-transport-validator.po
apps/transport/priv/gettext/en/LC_MESSAGES/validations-explanations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/gtfs-transport-validator.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations-explanations.po
apps/transport/priv/gettext/gtfs-transport-validator.pot
apps/transport/priv/gettext/validations-explanations.pot

En lien avec https://github.com/etalab/transport-validator/pull/218 et https://github.com/etalab/transport-validator/issues/168.
Ajoute une description du nouvel avertissement `NoCalendar` pour la validation GTFS.

Validation GTFS : ajout warning pour NoCalendar

---

apps/transport/client/stylesheets/reuses.scss
apps/transport/lib/transport_web/templates/reuse/index.html.heex

Fixes #4534
Rend le fond des images des réutilisations transparent, bleu auparavant dans le CSS par défaut.

Réutilisations : fond des images transparent

---

apps/transport/lib/validators/gtfs_transport_validator.ex
apps/transport/priv/gettext/en/LC_MESSAGES/gtfs-transport-validator.po
apps/transport/priv/gettext/fr/LC_MESSAGES/gtfs-transport-validator.po
apps/transport/priv/gettext/gtfs-transport-validator.pot

En lien avec https://github.com/etalab/transport-validator/pull/219
Ajoute une traduction pour une nouvelle erreur du validateur GTFS

Traduction pour MissingAgencyId

---

apps/transport/lib/transport_web/api/router.ex

Suite de #4516
Rétablit les plugs comme initialement pour le validateur GTFS transport dans l'API. La suppression de ces plugs ne devait pas présenter un problème important mais il n'y a pas de raison de les supprimer.
Merci @thbar de ta vigilance.

API GTFS transport : adaptation des plugs

---

apps/transport/client/javascripts/explore.js

- l’état initial ignorait les query params
- la websocket n’a pas besoin d’être connectée si on n’affiche pas de GTFS-RT

Corrections carte d’exploration persistente

---

.credo.exs

Je propose de désactiver ce check
```
One `Enum.reject/2` is more efficient than `Enum.reject/2 |> Enum.reject/2`
```
Motivation:
- garder des rejects séparés permet de déplacer / copier coller par "ligne" sans risquer d'introduire un bug (facilite la maintenance / refacto)
- le souci de perf est rarement uniquement lié à ça, et l'absence de check n'empêche pas d'optimiser non plus
Discussion [ici](https://mattermost.incubateur.net/betagouv/pl/nr5agga573yh7q36jf9exxn3co).
Backport de #4492

Suppression du check Credo sur `Enum/reject/2` chainés

---

config/database.exs
config/runtime.exs

Apporte la possibilité de configurer la taille du pool Ecto via une variable d'environnement, `PG_POOL_SIZE`.

Pool size configurable

---

apps/transport/lib/db/dataset.ex
apps/transport/test/db/db_dataset_test.exs

Fixes #4559
Règle le problème de performance pour ces requêtes, utilisées par les statistiques de la page d'accueil. Voir #4006 précédemment.

Utilise les counter cache pour DB.Dataset.count_by_mode

---

apps/transport/lib/transport_web/controllers/explore_controller.ex
apps/transport/lib/transport_web/templates/explore/explore.html.heex
apps/transport/lib/transport_web/templates/layout/_header.html.heex
apps/transport/priv/gettext/default.pot
apps/transport/priv/gettext/en/LC_MESSAGES/default.po
apps/transport/priv/gettext/en/LC_MESSAGES/explore.po
apps/transport/priv/gettext/explore.pot
apps/transport/priv/gettext/fr/LC_MESSAGES/default.po
apps/transport/priv/gettext/fr/LC_MESSAGES/explore.po
apps/transport/test/transport_web/controllers/explore_controller_test.exs

Fixes #4536
- Retravaille les intitulés
- Coche par défaut les différentes couches (au lieu de GTFS-RT uniquement pour commencer)

Carte d'exploration : intitulés et tout cocher

---

config/config.exs

Active l'[intégration avec Oban d'AppSignal](https://docs.appsignal.com/elixir/integrations/oban.html). Les erreurs des jobs sont désactivées (`report_oban_errors: false`) mais on va ajouter [quelques metrics](https://docs.appsignal.com/elixir/integrations/oban.html#metrics).

AppSignal : activation instrumentation Oban

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/jobs/update_counter_cache_job.ex
apps/transport/lib/transport/counter_cache.ex
apps/transport/test/transport/jobs/counter_cache_test.exs
apps/transport/test/transport_web/controllers/dataset_search_test.exs

Utilise le counter cache introduit dans #4006 pour cacher les features d'un GTFS (accessibilité, tarifs etc.) en plus des modes.

Utilise le counter cache pour les features

---

apps/transport/lib/jobs/database_vacuum_job.ex

Ajoute un timeout de 5 minutes au job qui VACUUM 1 fois par semaine. Le timeout par défaut de 15s n'était pas suffisant.
https://github.com/etalab/transport-site/pull/4586 précédemment

DatabaseVacuumJob : spécifie un timeout

---

apps/transport/lib/db/contact.ex
apps/transport/lib/db/default_token.ex
apps/transport/lib/db/token.ex
apps/transport/lib/transport_web/controllers/reuser_space_controller.ex
apps/transport/lib/transport_web/templates/reuser_space/settings.html.heex
apps/transport/lib/transport_web/views/reuser_space_view.ex
apps/transport/priv/repo/migrations/20250603104959_default_token.exs
apps/transport/test/support/factory.ex
apps/transport/test/transport_web/controllers/reuser_space_controller_test.exs

Retravaille #4611 : un token peut être par défaut pour **plusieurs contacts**. Introduit une table `default_token` pour gérer ce cas. Définit les associations nécessaires et met à jour les tests.

Tokens : par défaut pour plusieurs contacts

---

apps/transport/lib/transport_web/templates/reuser_space/new_token.html.heex
apps/transport/lib/transport_web/templates/reuser_space/settings.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/reuser-space.po
apps/transport/priv/gettext/fr/LC_MESSAGES/reuser-space.po
apps/transport/priv/gettext/reuser-space.pot

Ajout de texte pour :
- documenter l'usage lors d'appels à l'API
- documenter qu'il faut créer ou rejoindre une organisation

Tokens : texte de documentation

---

apps/transport/lib/db/resource.ex
apps/transport/lib/db/resource_download.ex
apps/transport/lib/transport_web/controllers/resource_controller.ex
apps/transport/priv/repo/migrations/20250604082439_resource_download.exs
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Cette PR :
- ajoute une table pour stocker des informations sur le téléchargement des ressources
- crée des URLs de téléchargement pour les ressources du PAN `/resources/:id/download?token=xxxxx`
- teste les fonctionnalités ajoutées
Les URLs ne sont pas modifiées dans l'interface/API pour le moment.

Téléchargement avec URLs authentifiées pour ressources PAN

---

apps/transport/lib/transport_web/controllers/reuser_space_controller.ex
apps/transport/test/transport_web/controllers/reuser_space_controller_test.exs

Répare une erreur 500, [voir Sentry](https://transport-data-gouv-fr.sentry.io/issues/6659069923/). 🐛 
Survenait dans la situation suivantes : 2 tokens, t1 et t2, tels que t1 est le token par défaut pour l'utilisateur. On supprime t2. Le code d'avant tentait de remettre t1 en tant que token par défaut alors qu'il l'était déjà.

Suppression token : gère 500

---

apps/transport/lib/transport_web/controllers/dataset_controller.ex

Fixes #4628
2 ressources ont un format `null`, ce qui est considéré comme toujours actif par le filtre des recherches par format quand les JDDs remontent. Les bizdevs vont corriger le format et le code exclut désormais cette situation.

Recherche par format, exclut nil

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/db/resource.ex

Avec la nouvelle catégorie des données routières introduit dans #4633 (parkings + ZFE + données routières), il est nécessaire de revoir l'exclusion de l'historisation des données routières. En effet il est nécessaire d'historiser les données des ZFE et des parkings pour des besoins de consolidation.
Ceci est fait dans cette PR.

Historisation des données routières

---

apps/transport/client/stylesheets/components/_icons.scss

Fixes #4665
Réintroduit du code supprimé dans #4647 qui est en réalité utilisé

CSS icone loi climat et résilience

---

ops_tests/ops_tests.exs

Suite à https://github.com/etalab/transport-site/issues/4147#issuecomment-2996616314, suppression de la vérification de cet enregistrement DNS qui n'existe plus.

ops_tests: suppression de contribuer

---

apps/transport/lib/transport_web/router.ex

Fixes #4499
Au lieu d'avoir un paramètre secret dans l'URL, requiert d'être admin. Cet outil est caché et ne devrait pouvoir être testé que par un dev, en cas de besoin.

GeojsonConversionController: requiert admin

---

.credo.exs
apps/transport/lib/jobs/on_demand_netex_poller_job.ex
apps/transport/lib/transport_web/controllers/resource_controller.ex
apps/transport/lib/transport_web/controllers/validation_controller.ex
apps/transport/lib/transport_web/templates/dataset/_resource_validation_summary_netex.html.heex
apps/transport/lib/transport_web/templates/resource/_netex_validation_errors.html.heex
apps/transport/lib/transport_web/templates/resource/_validation_summary.html.heex
apps/transport/lib/transport_web/templates/resource/gtfs_details.html.heex
apps/transport/lib/transport_web/templates/resource/netex_details.html.heex
apps/transport/lib/transport_web/templates/validation/show_gtfs.html.heex
apps/transport/lib/transport_web/templates/validation/show_netex_v0_1_0.html.heex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/lib/validators/netex/results_adapter.ex
apps/transport/lib/validators/netex/results_adapters/v0_1_0.ex
apps/transport/lib/validators/netex/validator.ex
apps/transport/test/transport/validators/netex/results_adapters/v0_1_0_test.exs
apps/transport/test/transport/validators/netex/validator_test.exs

Cette PR sépare le code de validation (appels d’API enRoute, construction de l’entité MultiValidation, stockage en base, mécanismes de polling et gestion d’erreurs) du code qui sait interpréter les résultats de validation NeTEx.
Cette séparation sera importante pour ensuite faire évoluer la représentation des résultats tout en état capable d’afficher les anciennes validations.
Cette PR introduit notamment l’interface `ResultsAdapter`, abstraction des fonctionnalités d’inspection des résultats (essentiellement utilisées dans les écrans). Cette interface est le compagnon de `Validator`.
Dans cette PR il n’y a donc qu’une implémentation de `ResultsAdapter`, `V0_1_0`, chargée d’inspecter les résultats de validation présents en production à date de cette PR.
Cette PR ne change pas le …

Validation NeTEx : abstraction de l’affichage des résultats

---

apps/transport/lib/jobs/resource_history_job.ex
apps/transport/lib/transport/cache.ex
apps/transport/lib/transport_web/controllers/dataset_controller.ex

En lien avec #4613 et #4502
Met en cache la partie du calcul des ressources historisées pour la page `dataset#details`. Cette requête a été identifiée comme étant consommatrice de ressources et lente.

dataset#details : cache history_resources

---

scripts/irve/stats.exs

Dans la lignée de :
- #4397 qui introduisait l'agrégat brut
- #4492 qui générait l'agrégat chaque nuit et le stocke dans S3
- #4639 qui a modifié le proxy pour servir des fichiers depuis S3
- https://github.com/etalab/transport-proxy-config/pull/145 qui a configuré le proxy
je peux introduire à présent ce script, qui va me servir à suivre les améliorations du code qui ingère et traite les fichiers ici:
- #4715

Script de calcul de petites statistiques sur la consolidation IRVE brute statique

---

apps/transport/client/javascripts/app.js
apps/transport/client/stylesheets/components/_backoffice.scss
apps/transport/lib/db/administrative_division.ex
apps/transport/lib/transport_web/controllers/backoffice/dataset_controller.ex
apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/lib/transport_web/live/backoffice/declarative_spatial_areas_live.ex
apps/transport/lib/transport_web/live/backoffice/edit_dataset_live.ex
apps/transport/lib/transport_web/live/backoffice/edit_dataset_live.html.heex
apps/transport/priv/gettext/administrative_division.pot
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/en/LC_MESSAGES/administrative_division.po
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/administrative_division.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po
apps/transport/test/transport_web/live_views/custom_tags_live_test.exs
apps/transport/test/transport_web/live_views/edit_dataset_live_test.exs

En images :
Ce n’est pas testé, dans l’ensemble le backoffice ne l’est pas beaucoup. À voir si c’est bloquant pour merger.
Graphiquement, il y a une chose de sale : j’ai réutilisé le css d’autocomplete de la homepage, et il y a une phrase de hardcodée dedans (« ou recherchez par lieu »). Ça ne me choque pas pour du backoffice qui est un outil interne utilisé par les chargés de déploiement, mais ça peut se régler.
closes #4353

Edition du territoire couvert déclaré dans le backoffice

---

apps/transport/lib/jobs/on_demand_netex_poller_job.ex
apps/transport/test/transport/jobs/on_demand_netex_poller_job_test.exs

La version n'était pas sauvegardée pour les validations OnDemand. Avoir la version permet d'adapter l'affichage des résultats.

Validation OnDemand: version du validateur NeTEx

---

apps/transport/lib/transport_web/live/backoffice/declarative_spatial_areas_live.ex
apps/transport/lib/transport_web/live/backoffice/edit_dataset_live.ex
apps/transport/lib/transport_web/live/backoffice/edit_dataset_live.html.heex
apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.heex
apps/transport/test/transport_web/live_views/custom_tags_live_test.exs
apps/transport/test/transport_web/live_views/edit_dataset_live_test.exs

En lien avec #4739 : gère les flèches haut et bas pour sélectionner des résultats dans l'autocomplete.

BO territoires : gère flèches haut/bas

---

apps/transport/lib/irve/raw_static_consolidation.ex
apps/transport/test/transport/irve/irve_raw_static_consolidation_test.exs

Après avoir refait une passe de lecture du rapport IRVE nocturne (voir #4715), j'ai vu qu'on pouvait probablement repêcher pas mal de PDC dans le cas suivant : la payload n'est ni une chaîne UTF-8 valide, ni un fichier zip.
Dans la PR présente, je réalise une conversion du "body" de la ressource IRVE si je détecte que ce n'est ni une chaîne UTF-8 valide, ni un fichier ZIP, en supposant que c'est du Latin-1.
J'ai fait cela après avoir été observer les ressources, et constaté que je trouvais effectivement du Latin-1 sur les échantillons que j'ai testé.
En pratique c'est un quick-win qui réduit un peu + l'écart avec data gouv sur le nombre d'identifiants PDC uniques:
```elixir
consolidation-pan.csv: %{
count: 215137,
distinct_count: 113165,
duplicates: 101972
}
consolidation-data-gouv-.csv: …
```

Accroissement nombre de PDC - auto-conversion du Latin-1 vers UTF-8

---

apps/transport/lib/db/contact.ex
apps/transport/lib/db/token.ex
apps/transport/lib/jobs/create_tokens_job.ex
apps/transport/test/transport/jobs/create_tokens_job_test.exs
config/runtime.exs

Cette PR adapte `CreateTokensJob` pour créer un nouveau job en charge de créer un token (et de le mettre par défaut) pour les contacts qui ne sont pas membres d'une organization data.gouv.fr.
Ceci concerne 597 contacts actuellement.
```sql
select id
from contact
where datagouv_user_id is not null and id not in (select contact_id from contacts_organizations)
```
Avoir un token pour ces contacts permettra d'avoir des liens authentifiés pour ces contacts. Les contacts membre d'une organisation auront un token via leur organisation.

CreateTokensJob : création d'un token pour contacts sans org

---

apps/transport/lib/transport_web/views/resource_view.ex

- les catégories ne sont pas cliquables s'il n'y aucune erreur
- les descriptions sont affichées même s'il n'y a pas d'erreur
- les catégories sont désormais séparés par une bordure
Deux screenshots pour illustrer :
* * *
Note: les screenshots incluent les changements de #4774 pour améliorer l'impression générale. Les changements de #4774 ne sont pas visuels.

Validation NeTEx: retravail du résumé des erreurs

---

README.md

ASDF a fait une mise à jour majeure (0.16.0), ils sont passés de scripts bash à un exécutable précompilé, et en ont profité pour changer la syntaxe. J’ai refait une installation clean en local de ASDF, Elixir, Erlang, Node et Yarn, vérifié que tout marche bien, et voici les quelques changements de syntaxe de ASDF.

Mise à jour readme pour nouvelle version de ASDF

---

apps/transport/lib/transport_web/views/resource_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po

Voir https://github.com/etalab/transport-site/issues/4781.
Merci à Tu-Tho Thai pour ses éléments de langage.
En français :
En anglais :

NeTEx: Ajustement textes pour catégorie XSD & le commentaire général

---

apps/transport/client/stylesheets/components/_validation.scss
apps/transport/lib/transport_web/views/resource_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/validations.pot

En cas d'erreurs, pour certaines catégories, nous pouvons afficher des conseils relatifs aux erreurs fréquentes. En espérant que cela évite des allers-retours au support ou que l'AOM ne se décourage.
Ces conseils ne sont pas affichés sur la catégorie est OK.

Conseils à la validation NeTEx

---

apps/transport/lib/transport_web/templates/dataset/details.html.heex

https://github.com/etalab/transport-site/pull/4791 j'ai oublié un renommage dans https://github.com/etalab/transport-site/pull/4791/commits/dc6ec68cf3ad2f8a9ccda24384fbd8e4cbbacb30
Visiblement il n'y a pas de couverture de test sur ce cas… Il faut des "other datasets". Je vais ajouter un test dans une PR à suivre.
[Voir Sentry](https://transport-data-gouv-fr.sentry.io/issues/6852103112/)

Dataset#details : renomme variable

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/test/db/db_dataset_test.exs
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

En lien avec #4796
Utilise les nouveaux territoires pour le bloc "Autres jeux de données". Ajoute des tests sur cette fonctionnalité qui en manquait.

Dataset : utilise les territoires pour les autres jeux de données

---

apps/transport/lib/transport_web/live/backoffice/declarative_spatial_areas_live.ex

Fixes #4778
Ordonne les résultats de recherche du plus grand territoire au plus petit.

BO territoires : tri les résultats de recherche

---

apps/transport/lib/transport_web/live/gtfs_diff_explain/explanations.ex

Il arrive que certaines valeurs de latitude ou longitude ne soient pas trimmées.
Closes #4819.

GTFS-diff: parsing des positions GPS plus résistant

---

apps/shared/lib/wrapper/wrapper_req.ex
apps/transport/lib/enroute/chouette_valid_rulesets_client.ex
apps/transport/test/enroute/chouette_valid_rulesets_client_test.exs
config/config.exs
config/test.exs

Ce client d'API a été implémenté en s'inspirant du CLI officiel ainsi que par essais erreurs. Il est possible qu'il faille plus tard corriger certains détails.

Client d'API pour l'API Rulesets de enRoute Chouette Valid

---

apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/templates/dataset/index.html.heex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/test/transport_web/controllers/dataset_search_test.exs

Retravaille #4825. La recherche par région se fait désormais par code INSEE. Les liens n'avaient pas été ajustés dans la barre des filtres.

Recherche : liens vers régions

---

apps/transport/lib/transport_web/templates/resource/gtfs_details.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/validations.pot

Ajoute un lien vers le validateur MobilityData lorsqu'on ne peut pas valider un GTFS-Flex.

Validation GTFS-Flex : lien vers MobilityData

---

apps/transport/client/stylesheets/reuses.scss
apps/transport/lib/db/reuse.ex
apps/transport/lib/transport_web/templates/reuse/index.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/reuses.po
apps/transport/priv/gettext/fr/LC_MESSAGES/reuses.po
apps/transport/priv/gettext/reuses.pot
apps/transport/test/db/reuse_test.exs
apps/transport/test/transport_web/controllers/reuse_controller_test.exs

Permet de rechercher des réutilisations par type de jeu de données réutilisé.

Réutilisations : recherche par type de JDD

---

apps/transport/lib/db/resource.ex
apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
apps/transport/test/transport_web/controllers/api/datasets_controller_test.exs
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

Fait en sorte que l'URL de téléchargement soit remplacée par l'URL PAN quand on a le :label: d'expérimentation uniquement pour les ressources statiques.
Sinon on avait le cas où un JDD a une ressource temps-réel du proxy, le :label: d'expérimentation et on met une URL en `https://transport.data.gouv.fr/resources/:id/download` qui redirige ensuite vers le proxy. On compte alors les requêtes 2 fois.

DB.Resource.download_url/1 : uniquement ressources statiques

---

apps/transport/lib/transport_web/controllers/resource_controller.ex
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Plutôt que renvoyer une erreur qui pollue AppSignal, renvoyons une page 404 propre.
Comme cela semblait intentionnel à l'origine, il y a peut-être une bonne raison qui m'échappe.

Erreur 404 propre pour resources#details

---

apps/transport/lib/db/resource_history.ex
apps/transport/lib/transport_web/controllers/resource_controller.ex

La requête de chargement des `multi_validation` était appelée plusieurs fois indûment. Ça ne sera sans doute pas révolutionnaire pour les performances mais pourquoi s’en priver ?

Simplification du resource_controller

---

apps/transport/lib/transport_web/templates/resource/_resources_details_gtfs.html.heex

Suite de #4864, les noms des fichiers n'avaient pas été correctement modifiés.

Fares v2 resources#details : correction noms des fichiers

---

apps/transport/lib/transport_web/live/gtfs_diff_explain/explanations.ex
apps/transport/priv/gettext/en/LC_MESSAGES/gtfs-diff.po
apps/transport/priv/gettext/fr/LC_MESSAGES/gtfs-diff.po
apps/transport/priv/gettext/gtfs-diff.pot
apps/transport/test/transport_web/live_views/gtfs_diff_explain_test.exs

Fixes #4860 4860
Dans le GTFS Diff, documente les changements effectués sur `agency_fare_url` et `agency_phone`.

GTFS Diff explanations supplémentaires pour agency.txt
