client/stylesheets/layouts/_footer.scss

Because ```display: block``` is the answer.

Replace inline-block by block

---

client/javascripts/components/discussions/discussions.tag
client/stylesheets/components/_discussions.scss
lib/transport/datagouvfr/client.ex
lib/transport/datagouvfr/client/discussions.ex
lib/transport_web/controllers/discussion_controller.ex
lib/transport_web/router.ex
lib/transport_web/views/discussion_view.ex
priv/gettext/alert.pot
priv/gettext/en/LC_MESSAGES/alert.po
priv/gettext/fr/LC_MESSAGES/alert.po

partial_fix #112 
fixes etalab/transport-datatools-ui#4
Be sure you cherry-pick `ac91a1aef38d34443861134dd05975decabb833b` before
You can add this to any controller
You need to assign
:datagouvfrsite =>Application.get_env(:oauth2,Authentication)[:site])
to the connection
And add
<discussions datasetid="59d503d90b5b3901fed55f91"
datagouvfrsite=<%= @datagouvfrsite %>
posted_on="le"
connected=<%= @current_user != nil %>
respond_comment="Répondre"
post_discussion="Ouvrir une nouvelle discussion"
title="Titre"></discussions>
to the view

Add discussions

---

.circleci/Dockerfile
.circleci/config.yml
elixir_buildpack.config
lib/transport_web/api/views/dataset_view.ex
mix.exs

In order to use ```ExUnit.Callbacks.start_supervised!```, for testing ```GenServer```.

Bump Elixir to v1.6.1

---

client/stylesheets/base/_buttons.scss
lib/transport_web/templates/dataset/details.html.eex

Publish reuse button is now readable

---

client/stylesheets/components/_dataset-details.scss
client/stylesheets/components/_documentation.scss
lib/transport_web/templates/dataset/details.html.eex

Fix responsivity on dataset details page

---

client/javascripts/components/footer/footer-help.tag
client/stylesheets/components/_footer-help.scss
lib/transport_web/templates/layout/_footer.html.eex
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/fr/LC_MESSAGES/default.po
test/transport_web/integrations/contact_test.exs

When the mouse is over the button with the `?` you have this message that appears.

Unroll help message when the mouse is over the help button

---

client/javascripts/components/discussions/discussions.tag
client/stylesheets/components/_discussions.scss

Format the markdown in comments

---

.circleci/config.yml

Errors will be shown in the pull requests,
but if we override them (as it can be an external failure),
it won’t block the deploy.

Deploy even if external tests fail

---

client/javascripts/components/discussions/discussions.tag

Before: `le 2/7/2018, 5:31:49 PM`
After: `le 07/02/2018 à 17:31:49`

Use french date and time formating

---

test/transport_web/solutions/data_reuse/using_map_test.exs

As we're still building the new frontpage, we're disabling this test.
Why? Because map element is not active, and PhantomJS can't reach it.
The cost of making it work is greater than the benefits, as we don't
know yet if we'll keep this layout.

Disable map test

---

README.md
lib/mix/tasks/transport/reset_and_import.ex

As the 3 tasks are always run one after an other, this reduces the work made by hand

Use a single task for importing the data

---

priv/repo/datasets.json

Puisque la métropole a recréé une nouvelle fiche au lieu de la modifier

Update nantes’ id

---

lib/transport/reusable_data/dataset.ex
lib/transport/reusable_data/reusable_data.ex
lib/transport_web/controllers/backoffice_controller.ex
lib/transport_web/controllers/session_controller.ex
lib/transport_web/router.ex
lib/transport_web/templates/backoffice/index.html.eex
lib/transport_web/views/backoffice_view.ex
priv/gettext/alert.pot
priv/gettext/backoffice.pot
priv/gettext/dataset.pot
priv/gettext/en/LC_MESSAGES/alert.po
priv/gettext/en/LC_MESSAGES/backoffice.po
priv/gettext/en/LC_MESSAGES/dataset.po
priv/gettext/en/LC_MESSAGES/page-shortlist.po
priv/gettext/fr/LC_MESSAGES/alert.po
priv/gettext/fr/LC_MESSAGES/backoffice.po
priv/gettext/fr/LC_MESSAGES/dataset.po
priv/gettext/fr/LC_MESSAGES/page-shortlist.po
priv/gettext/page-shortlist.pot
test/transport_web/integrations/backoffice_test.exs

Permet d’ajouter un jeu de données directement depuis le site, sans passer par des PR

Backoffice

---

lib/transport/import_data_service.ex

It will fix the problem for https://transport.data.gouv.fr/datasets/lignes-dautocars-urbains-et-interurbains-de-la-dlva/ where the neptune is imported

Import from data.gouv.fr: the format must contain gtfs, not be equal to

---

lib/transport/reusable_data/dataset.ex
lib/transport_web/templates/backoffice/index.html.eex
priv/gettext/alert.pot
priv/gettext/backoffice.pot
priv/gettext/en/LC_MESSAGES/alert.po
priv/gettext/en/LC_MESSAGES/backoffice.po
priv/gettext/en/LC_MESSAGES/page-shortlist.po
priv/gettext/fr/LC_MESSAGES/alert.po
priv/gettext/fr/LC_MESSAGES/backoffice.po
priv/gettext/fr/LC_MESSAGES/page-shortlist.po
priv/gettext/page-shortlist.pot

Après avoir déployé cette PR il faut lancer cette commande sur mongo:
`db.datasets.update({}, {$set: {"type": "transport-statique"}}, false, true)`
Fixes #401 
Fixes #408

Ajout du champ type sur les datasets

---

client/stylesheets/components/_shortlist.scss
lib/transport_web/templates/dataset/index.html.eex

This is what it looks like
There's still a problem the top pagination that appears before the menu. Maybe we can hid it.

Make CSS responsive on /datasets

---

lib/transport/dataset.ex
lib/transport_web/controllers/dataset_controller.ex
priv/gettext/dataset.pot
priv/gettext/en/LC_MESSAGES/dataset.po
priv/gettext/en/LC_MESSAGES/page-shortlist.po
priv/gettext/fr/LC_MESSAGES/dataset.po
priv/gettext/fr/LC_MESSAGES/page-shortlist.po
priv/gettext/page-shortlist.pot

I think the `@type_to_str` was evaluated at build time, therefore there was no translations…

Fix dataset types translations

---

lib/transport_web/controllers/backoffice/page_controller.ex
lib/transport_web/templates/backoffice/page/index.html.eex
priv/gettext/backoffice.pot
priv/gettext/en/LC_MESSAGES/backoffice.po
priv/gettext/fr/LC_MESSAGES/backoffice.po

Ajoute un lien en bas de la page /backoffice permettant de filtrer les jeux de données périmés

Add outdated datasets filter on /backoffice

---

priv/gettext/fr/LC_MESSAGES/page-index.po

Surtout pour le titre (chili con carne)

Correction des apostrophes

---

config/datagouvfr.exs
lib/datagouvfr/client.ex
lib/datagouvfr/client/resources.ex
lib/datagouvfr/client/reuses.ex
lib/datagouvfr/client/user.ex
lib/datagouvfr/multipart_serializer.ex
lib/transport_web/controllers/resource_controller.ex
lib/transport_web/endpoint.ex
lib/transport_web/router.ex
lib/transport_web/templates/layout/_header.html.eex
lib/transport_web/templates/resource/choose_action.html.eex
lib/transport_web/templates/resource/choose_file.html.eex
lib/transport_web/templates/resource/list.html.eex
lib/transport_web/templates/resource/resources_list.html.eex
lib/transport_web/views/input_helpers.ex
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/en/LC_MESSAGES/page-index.po
priv/gettext/en/LC_MESSAGES/resource.po
priv/gettext/fr/LC_MESSAGES/default.po
priv/gettext/fr/LC_MESSAGES/resource.po
priv/gettext/page-index.pot
priv/gettext/resource.pot

Adds an easier way to update a resource.
There's no direct access to this feature now, we'll do it when we'll be sure of the feature.
You can access to your datasets on this page if you're logged in: /resources/update/datasets
Then you have to choose the resource you want to update:
You can upload a file on the next page
Finally you'll be redirected to the dataset page with a nice message !

Update a resource

---

apps/transport/lib/datagouvfr/client.ex

We don't want it to take the env var at compile time

Fix base_url

---

apps/transport/lib/transport/resource.ex

PS: there was no "transport-statique" in the database (legacy enum)
Closes #717

Validate also long distance coaches

---

apps/transport/lib/datagouvfr/client/datasets.ex
apps/transport/lib/transport/data_checker.ex

Send a email to the team if a dataset is no longer available on data.gouv.fr
Also include in the email the dataset that were inactive but are now again on data.gouv.fr
I have no clue on how to test this :roll_eyes:

send a mail for newly inactive datasets

---

apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/lib/transport_web/templates/dataset/details.html.eex

Use full size logo on datasets/:id:/

---

apps/transport/lib/transport/dataset.ex
apps/transport/priv/gettext/dataset.pot
apps/transport/priv/gettext/en/LC_MESSAGES/dataset.po
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/dataset.po
apps/transport/priv/gettext/validations.pot

to be able to reference https://www.data.gouv.fr/fr/datasets/programme-simplifie-par-saison-iata/ we need a new category "Aerial" (or "Aérien" in french).
feel free to suggest better name as I'm not utterly convinced by the naming

 add aerial type

---

apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot

If the dataset is deactivated we display this error message 
We send a 404 status code but perhaps we should have send a 204...

Handle error message for deactivated datasets

---

apps/transport/client/stylesheets/components/_shortlist.scss
apps/transport/lib/transport_web/templates/dataset/details.html.eex

and in the dataset list, reduce the size of the title
before:
after:
(the change is quite slight)
before:
after:

Add the spatial in dataset

---

apps/transport/lib/transport/aom.ex
apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
apps/transport/priv/repo/migrations/20190910091521_change_siren.exs

now add the siren of the aom in the `/datasets` api:
```js
{
"aom": {
"name": "Brest Métropole",
"siren": "242900314"  // <----------- new field
},
"created_at": "2015-09-21",
"datagouv_id": "55ffbe0888ee387348ccb97d",
"id": "55ffbe0888ee387348ccb97d",
"resources": [ { } ],
"title": "Bibus",
"type": "public-transit",
"updated": "2016-09-14T17:20:28.365+02:00"
}
```
change also the type of the field from integer to string (as it can
starts with a leading '0')
this change is also reflected in the `/aoms` api:
```json
{
"departement": "75",
"forme_juridique": "Etablissement public administratif",
"insee_commune_principale": "75056",
"nom": "Île-de-France Mobilités",
"siren": "217500016"
}
```

change siren to string and add it in /datasets

---

apps/transport/lib/transport_web/templates/stats/index.html.eex

- Harmonisation de la nomenclature "Transports collectif théorique" avec l'expression utilisée en page d'accueil.
- Explicitation de la notion d'AOM.

Corrections mineures sur la page de statistiques

---

apps/transport/lib/transport/data_checker.ex
apps/transport/lib/transport/dataset.ex
apps/transport/lib/transport/resource.ex

False evaluates to true… so we were not sending comments…
@antoine-de Since I cannot connect to the prod server can you run this snippet to send comments to outdated datasets
```elixir
import Ecto.Query
Transport.Dataset \
|> join(:inner, [d], r in Transport.Resource, on: r.dataset_id == d.id) \
|> group_by([d, r], d.id) \
|> having([d, r], fragment("max(?->>'end_date') <= '2019-09-19'", r.metadata)) \
|> Transport.Repo.all() \
|> Enum.filter(& &1.is_active) \
|> Enum.map(fn dataset -> 
IO.inspect(dataset)
Datagouvfr.Client.Discussions.post(dataset.datagouv_id,
"Jeu de données expiré",
"""
Bonjour,
Ce jeu de données est expiré.
Afin qu’il puisse continuer à être utilisé par les différents acteurs, il faut qu’il soit mis à jour prochainement.
L’équipe transport.data.gouv.fr
""", false) …
```

Fix post outdated_comment

---

apps/transport/priv/real_time_providers.csv

fix #840 
pour Saint-Etienne, le portail n'offre pas page non authentifier pour lister l'api, je met du coup un lien vers le portail directement, je vois pas comment faire mieux :(
par contre l'api est un peu chelou, juste 3 endpoints,
* 1 qui te file la liste des stations (mais pas d'acces par id, tu
requetes tout et tu te fais tes maps)
* 1 qui te file la liste des routes sur le même principe
* 1 qui te file un bulk des prochains passage (paginés). par contre sans
le GTFS j'ai l'impression que tu ne fais rien, car pas de trop dans
l'api des routes
Pour Pau je n'ai trouvé aucune info à part https://data.idelis.fr/explore/dataset/api-horaires-de-passage-theorique-et-reel-aux-arrets/information/ qui renvoi vers un lien mort

add realtime for Saint-Etienne

---

apps/transport/lib/transport_web/controllers/resource_controller.ex

a resource can have no validation (the last sentry error was for example for a GBFS resource)
should fix https://sentry.data.gouv.fr/etalab/site/issues/1859616/

fixes sentry 1859616

---

apps/transport/lib/transport_web/controllers/dataset_controller.ex

fixes #684 at least for the dataset page
If data.gouv cannot be queried, we display the dataset page anyway, but
without:
* comments
* reuses
* community ressources
in offline mode the page is like:
I have not found how to setup a timeout with cassette, so I did not test this :roll_eyes:

Display a partial dataset page when datagouv is down

---

apps/transport/lib/transport/dataset.ex
apps/transport/lib/transport/history.ex
apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot

store the content_hash field and use it to tell if the resource is the current one or not.
if it's the current, a tag is added.
furthermore, the resources history are now sorted by date.
This looks like:

Tag the current resource in history

---

apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/templates/error/not_found_error.html.eex
apps/transport/lib/transport_web/views/error_view.ex

now for an invalid dataset url, return a 404 status code, and render the
error via a 404 template
maybe fixes #621, but not sure since the issue lacks a bit of context :stuck_out_tongue_winking_eye: 
```bash
& http HEAD :5000/datasets/pouet
HTTP/1.1 404 Not Found
```
the error page is now:
and before it was:

change the page not found error page

---

apps/transport/lib/transport_web/api/controllers/datasets_controller.ex

close #855
add a publisher field to a dataset object:
```js
{
"aom": {
"name": "Perpignan Méditerranée Métropole",
"siren": "200027183"
},
"created_at": "2018-12-18",
"datagouv_id": "5c18fc4b634f41320c6251e3",
"id": "5c18fc4b634f41320c6251e3",
"publisher": {                          // <-- new field
"organization": "Sankéo"
},
"resources": [
{
"end_calendar_validity": "2019-10-20",
"format": "GTFS",
"start_calendar_validity": "2019-08-23",
"title": "190902.zip",
"updated": "2019-08-23T16:17:08.309+02:00",
"url":
"https://www.data.gouv.fr/fr/datasets/r/00deb486-8d0a-47fd-bda3-0dc012ab4dc4"
}
],
"title": "Sankéo",
"type": "public-transit",
"updated": "2019-08-23T16:17:08.309+02:00"
}
```
I don't know how to test this though :thinking:

add dataset's publisher to api

---

apps/db/lib/db/dataset.ex
apps/transport/lib/transport/history.ex

I though the modification date was enough, but it was not.
This led to dataset (like tisseo) with a **lot** of history (1/day).
I cleaned up the history too.
This PR also add a namespace to the cellar. This way it's easier to test a another bucket (since the bucket names are unique, even accross cellars), just add `CELLAR_NAMESPACE=test` to test on `test_data_history`

check content-hash before backuping

---

apps/transport/lib/transport/import_data.ex

fixes [dlva](https://www.data.gouv.fr/fr/datasets/lignes-dautocars-urbains-et-interurbains-de-la-dlva/) which have 2 resources, and the up to date is not seen in [transport](https://transport.data.gouv.fr/datasets/lignes-dautocars-urbains-et-interurbains-de-la-dlva/) because the format is not found as gtfs
Add also a small improvement on log format

also look at the title to guess if it's a GTFS

---

apps/transport/client/stylesheets/components/_map.scss
apps/transport/lib/transport_web/templates/stats/index.html.eex

Before adding more maps and stats to the `/stats` page, refactor a bit
the css
in full screen it looks like:
and with a smartphone:

better stats css

---

apps/transport/lib/transport_web/controllers/validation_controller.ex

long live the strongly typed language!
The timeout was sent as a header...

fix timeout

---

apps/transport/lib/transport_web/templates/layout/app.html.eex

Since the strike is over (until the next one) I suggest the removal of the banner.
Reverts etalab/transport-site#915

Revert "Add strike banner"

---

apps/db/lib/db/dataset.ex
apps/db/priv/gettext/dataset.pot
apps/db/priv/gettext/en/LC_MESSAGES/dataset.po
apps/db/priv/gettext/fr/LC_MESSAGES/dataset.po
apps/transport/client/images/icons/map.svg
apps/transport/lib/transport_web/templates/page/index.html.eex

fixes #925
Add a type `road-network` to reference road network data.
The main page is now looking like:
I'm not sure about the name `Road network` as it is not car specific, but do we want a car specific names ? I kept `Road network` as it was already referenced as this

make it possible de reference road networks

---

apps/transport/lib/transport/history.ex

There seems to be duplicate in the history (especially in the [tisseo dataset](https://transport.data.gouv.fr/datasets/tisseo-offre-de-transport-gtfs/), but I manually cleaned them.
With this we should never add a duplicate in the history

Fix duplicate in history

---

apps/db/lib/db/resource.ex
apps/transport/lib/transport/import_data.ex

Some datasets have no stable data.gouv.fr url (for example for ODS gtfs
as CSV). In those case we fallback on the real ressource url, this way a
ressource always has an url in the API or the atom feed

fallback on real url when no stable url

---

apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/lib/transport_web/templates/dataset/index.html.eex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot

This way make a bit of advertising to our api.
(and I also added the picto to the other api link in the dataset index page:
)
Note that here I put a direct link to the api whereas in the datasets index the link point to the `/datasets` section of the swagger ui.
I don't think we can poin to `/datasets/{id} in the swagger ui and since there are no parameter to this api, I thought it was enough to add a direct link.
This can be improved when we'll have a `API` page in the web site with
some explanations.

add a link to the /datasets/{id} api in each dataset page

---

apps/db/lib/db/dataset.ex
apps/db/lib/db/resource.ex
apps/db/priv/repo/migrations/20191216144800_add_resource_tags.exs
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/templates/dataset/_resource.html.eex

for the moment we only add the GTFS modes as tags
The tags are searchable via url only for the moment:
http://localhost:5000/datasets?tags[]=tramway&tags[]=bus
and rendered simply in each ressource:

auto discover some tags

---

apps/db/lib/db/dataset.ex
apps/db/priv/repo/migrations/20200110124026_unaccent.exs

change full text search configuration to ignore accents.
The search "Orleans", "chateauroux", "noumea", now gives appropriate results
closes #974

Do not consider accents in search

---

apps/transport/client/stylesheets/components/_shortlist.scss

honestly I'm way over my head on this, but on all chromium based the dataset images are poorly rendered:
(either the company logo or the type pictogram).
I did not found a generic css property to make this right so I used a chromium specify one, but I'm sure there is a better way for this. (any idea @thimy ?)
now it look like (the same in firefox):

fix image size pour chromium

---

.envrc.example
Dockerfile.dev
README.md
docker-compose.yml
docker/database/Dockerfile
docker/database/create_test_db.sh
docker/database/readme.md
docker/database/restore_db.sh
docker_phoenix_startup.sh

Change a bit the readme to ease the on boarding.
* more explicit installation guidelines
* cleanup mock .envrc file and add some comments
* list the main mix commands
* easier docker-compose workflow
I pushed an image with a builtin transport.data.gouv database on [dockerhub](https://hub.docker.com/r/antoinede/transport_data_gouv_dev_database). All the scripts needed to do this have been pushed to `docker/database`. For the moment it's on my account, but I can change this if needed.
Open question:
Can we put the url of the production validator in the example configuration file ? I don't think it's harmful to do so.

Revamp of the readme for easier onboarding process

---

apps/transport/lib/transport_web/api/controllers/aom_controller.ex
apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
apps/transport/lib/transport_web/api/schemas.ex

There were several problems with our openapi endpoint (duplicate names,
invalid parameter definition, and empty name).
Strangely swagger ui had no problem with those, but some other
integration were broken.

Fix OpenAPI spec

---

apps/transport/lib/transport_web/controllers/resource_controller.ex

When a resource was not found
(http://https://transport.data.gouv.fr/resources/<id>) instead of a 404
we were getting a 500.
This error was flooding the logs.

fix 404 as 500

---

apps/db/lib/db/dataset.ex
apps/transport/test/support/database_case.ex

the tests were silently failing because there was no city in the database, but this was hiddent by the wrong implementation of `has_cities` :wink:

fix the association to a region

---

apps/transport/lib/transport/import_data.ex

we shouldn't return nil, but empty list
should fix https://sentry.data.gouv.fr/etalab/site/issues/1873419/

fix associated zone when no zone are available

---

apps/transport/lib/transport_web/templates/page/real_time.html.md
apps/transport/priv/real_time_providers.csv

closes #1016 
* SCNF
It's a bit difficult to reference it correctly, so I added the general page of the SCNF API.
For more concrete links I put navitia documentation since sncf does not have a specific page explaining the API nor documentation
* add a section to reference the GBFS apis and the AF apis

Reference the SNCF and AF Apis

---

apps/transport/lib/transport_web/api/controllers/stats_controller.ex
apps/transport/lib/transport_web/api/router.ex

this was causing 500 errors on /stats/openapi due to some black [magic code generation](https://github.com/etalab/transport-site/blob/master/apps/transport/lib/transport_web/api/controllers/stats_controller.ex#L11:L11):
```
2020-02-11T10:33:01+00:00 (open_api_spex) lib/open_api_spex/path_item.ex:72: OpenApiSpex.PathItem.from_valid_routes/1
2020-02-11T10:33:01+00:00 ** (exit) an exception was raised:
2020-02-11T10:33:01+00:00 ** (UndefinedFunctionError) function https://github.com/etalab/transport-site/blob/master/apps/transport/lib/transport_web/api/controllers/stats_controller.ex#L11:L11)TransportWeb.API.StatsController.bikes_operation/0 is undefined or private 
```

fix openapi for bike sharing api

---

apps/db/priv/repo/migrations/20200212092113_materialized_geographic_view.exs

The old view was causing some performance problem since we did a lot on join on it (and it was dumb since the view has to be create at each time it is queried).
This was causing a quadratic query for example on `/stats/regions` and some timeouts.
Replacing the view by a materialized view fixes all the performance issues

replace the dataset_geographic_view by a materialized view

---

apps/transport/client/stylesheets/main.scss

Lorsque l'on clique sur la petite loupe de la barre de recherche, sur la page de garde, le bouton perd sa marge et le champ de recherche se retrouve collé au bouton.
Ce comportement vient du fichier externe '~template.data.gouv.fr/dist/main.css'

Keep button margin when active

---

apps/db/lib/db/resource.ex
apps/db/priv/gettext/en/LC_MESSAGES/validations.po
apps/db/priv/gettext/fr/LC_MESSAGES/validations.po
apps/db/priv/gettext/validations.pot
apps/transport/client/stylesheets/components/_validation.scss
apps/transport/lib/transport_web/templates/resource/_unloadable_model_issue.html.eex
apps/transport/lib/transport_web/templates/validation/show.html.eex
apps/transport/lib/transport_web/views/resource_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/validations-explanations.po
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations-explanations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/validations-explanations.pot
apps/transport/priv/gettext/validations.pot

change the "unable to load model" cryptic error to "Not compliant to theGTFS specification" (not found better :/)
And add a custom page displaying the file in error if found
The error is still technical but at least the line in problem is displayed making the debug easier.
Note:
It would be better to display the field in error, but due to the fact that the csv can have different number of column than the header we use in the [gtfs structures](https://github.com/rust-transit/gtfs-structure/) project an option (`flexible`) to handle this and that makes the error not directly linked to the field. I think we can see later if we manage to implement this on [rust csv](https://github.com/BurntSushi/rust-csv/)

better display of 'unloadable model' errors 

---

apps/transport/client/javascripts/map-csv.js
apps/transport/client/package.json
apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/client/webpack.config.js
apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot

closes #1047 
Ajout d'une carte qui permet de visualiser le contenu de la ressource la plus récente d'un dataset de covoiturage, si c'est un fichier csv. La carte est sur la page du dataset.

Add a map for csv car sharing datasets

---

apps/transport/client/stylesheets/components/_search.scss
apps/transport/client/stylesheets/components/_shortlist.scss
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/controllers/pagination_helpers.ex
apps/transport/lib/transport_web/templates/dataset/index.html.eex
apps/transport/priv/gettext/en/LC_MESSAGES/errors.po
apps/transport/priv/gettext/en/LC_MESSAGES/page-shortlist.po
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/errors.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-shortlist.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/page-shortlist.pot
apps/transport/priv/gettext/validations.pot

closes #1027 
Affiche un message quand il n'y a pas de données pour une AO / région / commune (mais dans les faits ca n'arrivera que pour une AO)
fixe aussi la page de recherche quand il n'y a pas de données, on affiche maintenant tout le temps la barre latéral
avant: 
aprés:

Affiche un message d'information quand il n'y a pas de données

---

apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/lib/transport_web/templates/backoffice/page/_dataset.html.eex
apps/transport/lib/transport_web/templates/backoffice/page/index.html.eex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po

closes #987 
I did not send an email with the unloadable datasets, for the moment I only added a filter in the backoffice to check them.
I also changed the filters to better see that they are links.
before:
after:
I also added an anchor the not return to the top of the page when using those filters, but to stay on the list of datasets
I also now use the dataset title when `spatial` is empty (and thus renamed the column from `territoire` to `dataset` (not found a better name)) this way we always have a link (non pt dataset might not have a spatial):

Filter unloadable datasets in backoffice

---

apps/transport/client/stylesheets/components/_error.scss
apps/transport/lib/transport_web/controllers/dataset_controller.ex

Pour le moment,
* https://transport.data.gouv.fr/datasets/region/coucou
* https://transport.data.gouv.fr/datasets/aom/coucou
renvoient vers des pages blanches et font des erreurs 500.
On les transforme en 404. Je n'ai pas trouvé d'autre moyen que de faire du try...rescue alors que dans le guide Elixir, ils disent que ce n'est pas une pratique habituelle :man_shrugging: 
Au passage, un peu de css sur la page des 404 :
devient

Eviter les erreurs 500 pour les urls non reconnues

---

apps/transport/client/stylesheets/components/_dataset-details.scss

Juste un petit coup de css pour ne pas que la carte soit rikiki sur mobile.
avant :
apres :

Carte des aires covoiturage compatible avec les écrans mobiles

---

apps/transport/lib/transport_web/controllers/dataset_controller.ex

the condition was reversed, so we were always returning 404 :wink:

fix /dataset/{region|aoms|commune}/:id link

---

apps/transport/client/javascripts/map.js
apps/transport/lib/transport_web/api/controllers/stats_controller.ex

change the bike-sharing map because the city polygons were too small
before:
after:

change bike sharing stats map

---

apps/db/priv/repo/migrations/20200225140241_slug_constraint.exs

ajout d'un index et d'une contrainte d'unicité sur le slug
closes #1073
le cas est super rare, mais on avait un bug si un jdd datagouv était référencé sur transport, puis supprimé et recrée sur datagouv (avec du coup le même slug, mais un id différent), et reréférencé sur transport.
vu que de tt facon on cherche aussi par slug (pour `/dataset/:slug`), je rajoute une contrainte d'unicité sur le slug, comme ca on aura une erreur au référencement directement.

ajout d'une contrainte d'unicité sur le slug

---

apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/templates/dataset/_addresses.html.eex
apps/transport/lib/transport_web/templates/dataset/_realtime.html.eex
apps/transport/lib/transport_web/templates/dataset/index.html.eex
apps/transport/priv/gettext/en/LC_MESSAGES/page-shortlist.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-shortlist.po
apps/transport/priv/gettext/page-shortlist.pot

* les pages de régions/aom/villes gagnent un titre avec le nom de l'ao/region/ville
* la page adresses explique la différence entre la BAN et BANO
* la page du temps réel renvoie vers la doc
Ca donne ca pour les villes/regions/AO
Note: je suis pas convaincu par le titre pour l'AO. Je trouvais que sans la région ca pouvait manquer de contexte, mais la ca fait des titres à rallonge (bon l’exemple d'idfm est particulièrement redondant aussi).
et pour les addresses /  TR:
Pas ultra convaincu en terme de design. Vous en pensez quoi ?

Editorialisation de certaines pages de recherche

---

apps/db/lib/db/place.ex
apps/db/priv/repo/migrations/20200224093551_places_mat_view.exs
apps/transport/lib/transport_web/api/controllers/places_controller.ex
apps/transport/test/support/database_case.ex
apps/transport/test/transport_web/controllers/places_controller_test.exs

use a materialized view for autocomplete instead of multiple unions
This makes it easier to tweak search and more performant mainly by
adding a composite field(indexed_name), cleaned up and indexed for
search.
This makes it possible to search for "ile de france" or "i d f".
We loose some control though, we cannot limit by type not (like asking
for 5 cities, 3 aoms, and 2 regions).
dumb bench or queries using the median of an `ab -n 10`.
(knowing that a huge part is not due to ecto, but it's easier to use
`ab`
than to check the db query time to get some rough estimation)
```markdown
| search        | before                | after  |
| ------------- | --------------------- | ------ |
| montreuil     | 130 ms                | 40 ms  |
| pa            | 110 ms                | 92 ms  |
| a …
```

use a materialized view for search

---

apps/transport/lib/transport_web/controllers/dataset_controller.ex

It let go some user input to the template (when a unknown territory id was used)

XSS vulnerability: remove not needed raw

---

apps/transport/client/javascripts/autocomplete.js

Petites améliorations pour que soit highlighté le bon segment des résultats.
Avant :
Après :
Avant :
Après :
Ca marche toujours avec "i d f" :

Search highlight

---

apps/db/lib/db/dataset.ex
apps/db/priv/repo/migrations/20200311095433_correction_of_dataset_geographic_view.exs
apps/transport/client/javascripts/autocomplete.js

1. Il n'était pas possible d'éditer un dataset qui avait été lié aux zones de datagouv.fr et de le passer en autre chose (jeu de données rattaché  une région par exemple)
2. La materialized view dataset_geographic_view était fausse pour les datasets qui étaient liés aux zones de datagouv.fr. Ce qui touchait en particulier les dataset de vélos.
Par exemple pour les dataset de vélo en Rhones Alpes :
Avant :
Après :
Quelques lignes de code qui m'ont demandé beaucoup d'efforts :D

Correction link dataset regions

---

apps/db/lib/db/resource.ex
apps/transport/lib/transport/import_data.ex
apps/transport/lib/transport/import_data_worker.ex
apps/transport/lib/transport_web/controllers/backoffice/dataset_controller.ex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/backoffice/page/index.html.eex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/backoffice_dataset.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice_dataset.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice_dataset.po

We seem to have some problems with the daily import / validation process.
In order to debug this, this PR adds a new backoffice bouton to only validate all the datasets (without reimporting them, thus speeding the process).
It also adds some logs in the daily import/validation process

Add a backoffice bouton to validate all datasets

---

apps/transport/lib/transport_web/controllers/dataset_controller.ex

commit [4fb8ada3e74a68486ecb77fde1149ff83f](https://github.com/etalab/transport-site/commit/4fb8ada3e74a68486ecb77fde1149ff83fad33bc#diff-1b76c6a5c21bdbb94400c3859d7f3ae7) broke the dataset access by slug, thus breaking url like https://transport.data.gouv.fr/datasets/5defcb1c634f413ad267d96d
This commit fixes it and split it in 2 functions as there is no real reason not to

add back redirect_to_slug_or_404 implementation

---

apps/transport/client/stylesheets/components/_backoffice.scss
apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/lib/transport_web/templates/backoffice/page/_dataset.html.eex
apps/transport/lib/transport_web/templates/backoffice/page/index.html.eex
apps/transport/lib/transport_web/views/backoffice/page_view.ex

closes #1105 
Permettre de trier la table des datasets dans le backoffice par nom ou par date de fin de validité.
Les 2 difficultés rencontrées alors que je ne m'y attendais pas :
- adapter la pagination, car on change de numéro de page, il faut conserver le tri en cours s'il y en a un.
- compatibilité avec les autres filtres. Par exemple si on a sélectionné "jeux de données avec ressources autres", il y a dans la requête un  `select id from ressources where(type==autre)`. Sauf que si je transforme juste en `select id, max(validity_date) from ressources where(type==autre)`, ça ne marche pas car je fais le max des dates de validité sur les ressources de type autre, alors qu'on veut probablement voir les datasets qui ont un type de ressource autre, mais comme date de validité le max sur …

Table triable dans le backoffice

---

apps/db/lib/db/dataset.ex
apps/db/lib/db/resource.ex
apps/db/priv/gettext/dataset.pot
apps/db/priv/gettext/en/LC_MESSAGES/dataset.po
apps/db/priv/gettext/fr/LC_MESSAGES/dataset.po
apps/transport/lib/transport/import_data.ex
apps/transport/lib/transport/import_data_worker.ex
apps/transport/lib/transport_web/controllers/backoffice/dataset_controller.ex
apps/transport/lib/transport_web/templates/backoffice/page/_dataset.html.eex
apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.eex
apps/transport/test/transport_web/controllers/backoffice_controller_test.exs

the reimport of dataset using datagouv's zones was not working because we expected a parameter `use_datagouv_zones` used only in the backoffice.
we thus remove the field use_datagouv_zones in the backoffice since we don't have it while reimporting the datasets and now we consider that we use the datagouv zones if the associated_territory_name is filled
This PR also adds some logs as they were usefull to debug this mess.
Note: I think there is still a problem while computing the sha256, the file stream seems to stop, thus the computed sha is not correct, but this will be for another PR

better handling datagouv zones while reimporting

---

config/config.exs

I forgot to add this file in the last PR :roll_eyes:

fix wrong env var name

---

apps/transport/lib/transport/import_data.ex

I was sure to already have shortened this log :thinking: 
since this function signature was wrong, we often entered the default method catch with an inspect on the geometry

cleanup big log

---

apps/db/lib/db/dataset.ex
apps/transport/test/transport_web/controllers/backoffice_controller_test.exs

This was making it impossible to import datasets already associated to cities in data.gouv as attached to an AOM in transport.

handle empty string for territory

---

apps/transport/lib/transport_web/templates/page/index.html.eex

I don't really understand why, but the old link stoped working, so I put a new one

update slack invitation link

---

apps/db/lib/db/resource.ex
apps/db/priv/repo/migrations/20200429171646_netex_conversion_date.exs
apps/transport/lib/transport/gtfs2netex.ex
config/prod.exs

This NeTEx will be generated through
https://github.com/etalab/gtfs_converter/ using kisio's
[gtfs2netexfr](https://github.com/CanalTP/transit_model/tree/master/gtfs2netexfr).
The NeTEx will be posted asynchronously on data.gouv as a commnunautary
resource.
We store the content_hash of the gtfs that has been used to generate the
netex not to regenerate a new resource needlessly (even if we try to
rewrite the same communautary resource when the GTFS changes).

add a daily task to generate a NeTEx for each GTFS

---

apps/db/lib/db/resource.ex
apps/db/lib/db/validation.ex
apps/db/mix.exs
apps/db/priv/gettext/fr/LC_MESSAGES/validations.po
apps/db/priv/repo/migrations/20200420082026_validation_fields.exs
apps/transport/client/javascripts/map.js
apps/transport/client/stylesheets/components/_stats.scss
apps/transport/lib/transport/import_data.ex
apps/transport/lib/transport/import_data_worker.ex
apps/transport/lib/transport_web/api/controllers/stats_controller.ex
apps/transport/lib/transport_web/api/router.ex
apps/transport/lib/transport_web/controllers/backoffice/dataset_controller.ex
apps/transport/lib/transport_web/controllers/stats_controller.ex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/backoffice/page/index.html.eex
apps/transport/lib/transport_web/templates/stats/index.html.eex

closes #1120
ajout de 2 cartes sur la page /stats :
La carte représente, pour chaque AOM urbaine (que les AO, mais en prenant en compte le jdd régional si présent) la fraîcheur des données, c'est à dire si on trouve 1 jdd GTFS valide sur la date du jour.
Note: dans les stats on a le nombre de jour de péremption du jdd, mais le dégradé ne rend pas grand chose, donc j'ai calé simplement la couleur rouge, que le jdd soit périmé d'un jour ou d'un an.
Je suis preneur de retour si vous pensez que ca vaut le coup de faire mieux.
La carte représente, pour chaque AOM urbaine (que les AO, mais en prenant en compte le jdd régional si présent) le niveau d'erreur max du ou des ressources en cours de validité (on ne prend pas en compte les anciens jdd qui n'auraient pas été remplacé sur coup).
Cette …

Ajout de stat sur la qualitié des données

---

apps/db/lib/db/dataset.ex
apps/transport/client/stylesheets/components/_shortlist.scss
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/templates/dataset/index.html.eex
apps/transport/lib/transport_web/templates/page/index.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/priv/gettext/fr/LC_MESSAGES/page-shortlist.po

Le but est de pouvoir filtrer les résultats par région.
J'ai trouvé que cela n'avait de sens que lorsque l'on est sur la page [de tous les datasets](https://transport.data.gouv.fr/datasets) ou sur la page d'une [région en particulier](https://transport.data.gouv.fr/datasets/region/11) afin de pouvoir passer vers une autre région.
Si l'on est sur une page d'AOM ou de commune, le filtre n’apparaît pas, car à priori tous les datasets sont dans une même région. Et si l'on veut changer de zone géographique, et bien on fait une nouvelle recherche.
Le filtre des régions est compatible avec celui du type de données et du temps réel. Ce qui permet un scénario du type "depuis la page de garde, je sélectionne les datasets vélo partagés, puis sur la page des résultats, je clique sur le nom d'une …

Possibilité de filtrer les résultats de recherche par région

---

apps/db/lib/db/resource.ex

Only consider GTFS as GTFS :wink:
for the moment the
http://localhost:5000/datasets/aires-de-covoiturage-en-france/ resource
is seen as GTFS.
This should make it seen as xlsx.

Only consider GTFS as GTFS

---

apps/db/lib/db/resource.ex
apps/db/lib/db/validation.ex
apps/db/priv/repo/migrations/20200505124346_validation_sha.exs
apps/transport/lib/transport/import_data.ex
apps/transport/lib/transport_web/api/controllers/stats_controller.ex
apps/transport/lib/transport_web/controllers/stats_controller.ex

since the modification dates are not reliable, we store the content hash and revalidate a resource only when this hash has changed

Store the content_hash when validating

---

apps/transport/lib/transport_web/templates/stats/index.html.eex

Le lien vers la base nationale des lieux de covoiturage était cassé dans la page de stats.

fix broken link

---

.gitignore
apps/transport/lib/transport_web/templates/stats/index.html.eex
blog/themes/mediumish/layouts/_default/list.html
blog/themes/mediumish/layouts/_default/single.html

J'avais cassé l'affichage du petit message custom pour les réutilisations lorsque j'avais modifié le nom des tags.

Fix blog custom message

---

apps/db/lib/db/resource.ex
apps/db/lib/db/validation.ex
apps/db/priv/gettext/en/LC_MESSAGES/validations.po
apps/db/priv/gettext/fr/LC_MESSAGES/validations.po
apps/db/priv/gettext/validations.pot
apps/db/priv/repo/migrations/20200603103539_add_metadatas_for_on_the_fly_validations.exs
apps/transport/client/stylesheets/components/_validation.scss
apps/transport/lib/transport_web/controllers/validation_controller.ex
apps/transport/lib/transport_web/templates/resource/_resources_details.html.eex
apps/transport/lib/transport_web/templates/resource/_speed_issue.html.eex
apps/transport/lib/transport_web/templates/resource/_validation_summary.html.eex
apps/transport/lib/transport_web/templates/resource/details.html.eex
apps/transport/lib/transport_web/templates/validation/show.html.eex
apps/transport/priv/gettext/en/LC_MESSAGES/resource.po
apps/transport/priv/gettext/en/LC_MESSAGES/validations-explanations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/resource.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations-explanations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/validations-explanations.pot

Ajout de metadatas dans le rapport de validation à la volée du site.
Et puis petit re-design de la page pour qu'elle ressemble aux autres.
Ajout de la colonne des détails pour les problèmes de vitesse, afin de faire apparaître les messages du validateur.
J'ai essayé de bien découper le commit, donc il sera peut-être plus facile à relire commit par commit.

Better gtfs validation page

---

blog/netlify.toml

Test de fichier de config, afin que les liens sur les sites de previews netlify soient relatifs et non pas absolus (ce qui éviterait de sortir du site de preview au premier clic).
https://gohugo.io/hosting-and-deployment/hosting-on-netlify/

add a netlify deploy config file

---

apps/transport/lib/transport/gtfs_conversions.ex
config/prod.exs

oups, j'avais inversé le booléen en ajoutant le filtre, du coup on ne convertissait aucune données :/
j'ai aussi mis un horaire fixe pour le cron, c'est plus simple à tracer

convertion des ressources officielles

---

apps/db/lib/db/dataset.ex
apps/transport/lib/transport_web.ex
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/lib/transport_web/templates/dataset/index.html.eex
apps/transport/lib/transport_web/templates/layout/app.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/lib/transport_web/views/seo_metadata.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-shortlist.po
apps/transport/priv/gettext/en/LC_MESSAGES/seo.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-shortlist.po
apps/transport/priv/gettext/fr/LC_MESSAGES/seo.po
apps/transport/priv/gettext/page-shortlist.pot
apps/transport/priv/gettext/seo.pot
apps/transport/test/support/database_case.ex
apps/transport/test/transport_web/controllers/seo_test.exs

closes #1184 
pour le moment je n'ai mis qu'un titre spécifique, il faut voir si on veut aussi modifier la `description` de la page.
Je veux bien une relecture attentive sur les fautes de français et d'anglais, vu l'exposition de ces textes :wink:
Pour voir ce que donne les titres, j'ai pushé sur [prochainement](https://prochainement-transport.cleverapps.io/), vous pouvez voir ce que ca donne (sachant que quand on aura amélioré les titres des jdd, ca sera encore mieux :stuck_out_tongue_winking_eye: ):
* [sur la home](https://prochainement-transport.cleverapps.io/)
* [sur la page d'un dataset](https://prochainement-transport.cleverapps.io/datasets/arrets-horaires-et-parcours-theoriques-des-reseaux-naq-bri-nva-m/)
* [sur la page d'un dataset non …

Ajout de titre spécifiques pour un meilleur référencement

---

apps/db/lib/db/dataset.ex
apps/db/lib/db/logs_import.ex
apps/db/priv/repo/migrations/20200622141231_create_import_logs_table.exs
apps/transport/lib/transport/import_data.ex

Création d'une table qui log les imports de datasets, avec un timestamp, un résultat (succes/echec) et un éventuel message d'erreur.
Je pense que ça peut nous servir à debugger, et à afficher sur le site et dans le backoffice la date du dernier import d'un dataset.
Je pensais par la suite faire une table similaire pour les logs des validations, mais je voulais t'en parler avant @antoine-de .

create a log table for import tasks

---

apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/error/not_found_error.html.eex
apps/transport/lib/transport_web/templates/layout/app.html.eex
apps/transport/lib/transport_web/views/layout_view.ex

closes #1228 
* redirection pour les anciens articles de blog
* meilleure gestion des erreurs, il y avait des soucis sur le temps `app.html.eex` qui le rendait impossible à rendre si on était pas passé dans le [pipeline :browser](https://github.com/etalab/transport-site/blob/89b6951dc002b7bb7f3edaa7498021e953e098e1/apps/transport/lib/transport_web/router.ex#L10).
Donc maintenant on a des 404 et non plus des 500

Pas de 500 au lieu de 404

---

apps/db/lib/db/dataset.ex
apps/db/lib/db/resource.ex
apps/db/priv/repo/migrations/20200630154908_original_resource_url.exs
apps/transport/lib/transport/gtfs_conversions.ex
apps/transport/lib/transport/import_data.ex
apps/transport/lib/transport_web/views/resource_view.ex

use the new metadata `transport:original_resource_url` on generated
geojson to match the corresponding GTFS

add a better way to match geojson with gtfs

---

apps/db/lib/db/resource.ex
apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.eex

on ne sauvegardait pas le `content_hash` :cry: 
petits changement aussi sur la page du backoffice présentant les logs:
* on les trie par date, en partant des plus récents
* on les groupe par ressource
Avant:
Aprés:

Correction d'un bug bloquant l'import

---

apps/transport/lib/transport_web/live/commune_field.ex

Il n'était pas très clair dans le backoffice que lorsque l'on veut lier un dataset à une AOM, il ne faut pas rechercher le nom de l'AOM mais le nom d'une des communes faisant partie de l'AOM.

better explanation for backoffice AOM field

---

apps/transport/lib/transport_web/views/dataset_view.ex

Ajout de pictos pour les datasets de type référentiels d'arrêts (un pins de carte comme pour les adresses) et pour les "autres informations"
J'en ai profité pour changer la catégorie du dataset https://transport.data.gouv.fr/datasets/cartographie-openstreetmap-des-gares-sncf-transilien-en-ile-de-france-1/ qui était en autre informations et que j'ai mis en référentiel d'arrêts.

add pictos for stops-ref and informations categories

---

apps/transport/lib/transport/gtfs_conversions.ex
apps/transport/lib/transport_web/controllers/backoffice/dataset_controller.ex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.eex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/backoffice_dataset.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice_dataset.po
apps/transport/priv/gettext/en/LC_MESSAGES/page-index.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice_dataset.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-index.po
apps/transport/priv/gettext/page-index.pot

Permet de lancer la création de resources communautaires (GeoJSON et NeTEx) depuis le backoffice d'un dataset.

Resource conversion from backoffice

---

apps/transport/lib/transport/gtfs_conversions.ex

Les parametres des appels au gtfs_converter n'étaient pas encodés, d'ou des taches qui échouaient si l'on passait comme paramètre une url contenant elle-même des caractères spéciaux, comme &.
Par exemple : https:// convertisseur.transport.data.gouv.fr/gtfs2geojson?url=http:// exs.itiniserev2.cityway.fr/gtfs.aspx?key=OPENDATA **&** operatorCode=CG38 **&** useCache=off&datagouv_id=5bb1caa6634f4136693d9053

encode url parameters for gtfs converter api call

---

apps/transport/client/package.json
apps/transport/client/webpack.config.js

for security reasons.
Nous avons eu une alerte sécurité à cause du package serialize-javascript qui est utilisé par le plugin webpack copy-webpack-plugin. La faille de sécurité est corrigée dans les versions >v6.0.1 du plugin.

update copy-webpack-plugin to latest version

---

apps/db/lib/db/validation.ex
apps/db/priv/repo/migrations/20200818124059_add_geojson_to_validation_data.exs
apps/transport/client/javascripts/validation-map.js
apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/client/webpack.config.js
apps/transport/lib/transport_web/controllers/validation_controller.ex
apps/transport/lib/transport_web/templates/validation/show.html.eex

Pour facilier le debug, la validation à la volée de GTFS inclut maintenant une carte.
https://prochainement-transport.cleverapps.io/validation/99732?issue_type=ExcessiveSpeed#issues
Point à discuter :
- Est-ce une bonne idée de faire un appel synchrone au convertisseur gtfs2geojson ?
- On stocke maintenant en base le geojson de chaque validation. Est-ce que ça prend trop de place ?
- Est-ce qu'on devrait directement intégrer la conversion en geojson au validateur rust plutôt que de faire 2 appels différents (un pour la validation un pour la conversion ?)

Map for validator

---

apps/db/lib/db/dataset.ex

Il y encore des soucis de hash et de validations qui ne veulent pas se lancer :(
Lorsque la tâche quotidienne est lancée, c'est une validation de toutes les ressources qui est demandée.
Par contre lorsque dans le backoffice, on lance une validation, c'est une validation du dataset qui se lance...et qui valide toutes les ressources associées. Je fais ici en sorte que lorsque l'on lance une validation du dataset, ce qui arrive à la création et quand on clique sur valider dans le backoffice, ce soit une validation "forcée". Cela me parait plus logique, car si on clique sur le bouton, à priori c'est qu'on a vraiment envie que les ressources soient validées. Au pire on revalide un peu pour rien.
On avait ici le cas sur https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-tag/ …

Force dataset validation

---

apps/db/test/test_db_dataset.ex

Ajout d'un petit test qui reproduit le scénario qui faisait planter la suppression d'un dataset par Nicolas : le fait que le dataset en question soit le parent_dataset d'une AOM.

add a test on aom foreign key constraints

---

apps/transport/client/stylesheets/components/_dataset-details.scss

for quite a long time we were using a non existent 'template.data.gouv.fr' css class, use the right one
the information were meant to be displayed as
(before:
)

use right css class

---

apps/db/lib/db/dataset.ex
apps/db/lib/db/resource.ex
apps/db/priv/repo/migrations/20200908085058_resource_datagouv_id.exs
apps/transport/lib/opendatasoft/url_extractor.ex
apps/transport/lib/transport/import_data.ex
apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
apps/transport/test/transport/import_data_service_test.exs
apps/transport/test/transport/url_extractor_doc_test.exs

ca permettra de mieux nettoyer les ressources communautaires dans l'api de conversion.
J'en ai profité pour nettoyer et rebrancher certains test unitaires

Ajout de l'id datagouv dans les ressources

---

apps/transport/client/javascripts/dataset-map.js
apps/transport/client/javascripts/map-geojson.js
apps/transport/client/javascripts/map.js
apps/transport/client/javascripts/resource-viz.js
apps/transport/client/javascripts/validation-map.js

https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4
Le fond de carte que nous utilisions n'est plus dispo. Je corrige au moins pour aujourd'hui avec un fond de carte lié à mon compte mapbox.
@l-vincent-l nous informe de l'existence de https://openmaptiles.geo.data.gouv.fr/, mais ce sont des tuiles colorées et vectorielles, ce que leaflet ne gère pas par défaut.

change mapbox map at least temporarily

---

apps/transport/lib/transport_web/templates/page/index.html.eex

Comme les GBFS sont maintenant considérés comme du real time, il faut mettre a jour la requete sur la page de garde pour les horaires de transports en commun real time.
closes #1327

add type public-transit filter

---

apps/transport/lib/transport/import_data.ex

data.gouv.fr a visiblement été bloqué par OpenDataSoft, leur sonde ne
remontent plus correctement si une ressource est dispo ou non. Du coup
on a perdu tout plein de ressources hébérgées sur ODS (genre IDFM,
Nantes, ...)

desactivation temporaire du prefiltre datagouv sur l'indisponibilité

---

apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/test/transport_web/controllers/dataset_view_test.exs

Enum.max_by jette une exception quand la liste est vide, ce qui causait une 500 sur certaines page (comme https://transport.data.gouv.fr/datasets/optymo-velo-en-libre-service/)

Fix crash sur certaines pages de GBFS

---

apps/transport/lib/transport_web/views/dataset_view.ex

when the text cannot be sanitized the sanitizer returns a raw string.
I think in those cases it's better to not sanitize anything.
This was ausing a 500 for the route-500 dataset

fix bug on sanitize

---

apps/transport/lib/transport_web/api/controllers/stats_controller.ex

Voir #1355, la Bretagne était en rouge car nous prenions en compte les ressources non disponibles de [ce dataset](https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh/).
Ces ressources non disponibles sont d'anciennes versions des données "MOBIBREIZHBRET", qui sont sur [data.gouv](https://www.data.gouv.fr/fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh/) mais sont indiquées "non disponibles peut-être temporaire":
On va pour l'instant filtrer les ressources non disponibles pour les exclure de la statistiques (dans le cas présent ça reflètera mieux la qualité réelle de la donnée, qui est en fait bien à jour).
Avant le correctif, la carte qualité ressemblait à ceci:
Après le correctif (qui ne semble …

Correctif statistiques Bretagne (fixes #1355)

---

apps/gbfs/lib/gbfs/controllers/index_controller.ex
apps/gbfs/test/gbfs/controllers/index_controller_test.exs

Avant cette PR, l'[index JSON GBFS](https://transport.data.gouv.fr/gbfs) génère des urls incorrectes car il manque un `/` dans chacune d'entre elles:
* https://transport.data.gouv.fr/gbfsvcub/gbfs.json
* https://transport.data.gouv.fr/gbfsvlille/gbfs.json
* etc...
La PR présente ajoute un test autour de cette génération, et corrige la logique. Les liens doivent devenir:
* https://transport.data.gouv.fr/gbfs/vcub/gbfs.json
* https://transport.data.gouv.fr/gbfs/vlille/gbfs.json
Le test (un peu cracra avec la récupération du port par la config) vérifie que c'est une url complète, et que le chemin est conforme à ce qu'on attend.

Correction hrefs cassées dans l'index GBFS json

---

.gitignore

Le fichier est créé par la CLI de CleverCloud (`clever-tools`), décrite dans https://github.com/etalab/transport-site/blob/learning-track/learning_track.md#read-the-logs-from-the-database.

Git ignore pour configuration CleverCloud CLI

---

apps/gbfs/mix.exs
apps/gbfs/test/gbfs/controllers/index_controller_test.exs
apps/gbfs/test/gbfs/controllers/vcub_controller_test.exs
apps/gbfs/test/support/external_case.ex

Comme vu dans #1351, il est actuellement impossible de lancer les tests de façon isolé sur certaines applications.
Cela rend moins pratique le travail sur ces applications isolées (en plus d'être un code smell comme indiqué dans la codebase). Par exemple on peut vouloir lancer rapidement les tests avec [entr](htetp://entrproject.org) à chaque sauvegarde comme suit, pour itérer beaucoup plus vite :
```
cd apps/gbfs
find lib test | entr -c mix test
```
Dans la présente PR, je corrige les points de couplages qui empêchait de faire ça, mais uniquement sur la partie GBFS pour l'instant (car je bosse dessus et ça me gênait).
Dans le détail:
* GBFS dépend en fait de plusieurs [dépendances externes](https://elixir-lang.org/getting-started/mix-otp/dependencies-and-umbrella-projects.html#external-de …

Correctifs pour le passage en mode umbrella (GBFS uniquement)

---

apps/transport/lib/mix/tasks/transport/import_aom.ex

The association had been broken by a refactoring without me noticing...
I also refactored the query to greatly reduce the number of UPDATE to be done since they are __very__ slow. 
I don't really  nderstand why though (I thought it might be the triggers, but it's slow even when I disabled them...)
This script has been applied to update the production AOM

Repair aom to cities association

---

apps/db/lib/db/dataset.ex
apps/db/lib/db/resource.ex
apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/lib/transport_web/templates/dataset/_resource.html.eex
apps/transport/lib/transport_web/templates/dataset/_resources_container.html.eex
apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/priv/gettext/dataset.pot
apps/transport/priv/gettext/en/LC_MESSAGES/dataset.po
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/dataset.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot

Pour le moment on filtrait les GTFS non dispo (en 404).
Ca permettait de ne pas alourdir les pages comme [celle de la bretagne](https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh) où un seul GTFS est encore la, mais tout plein de GTFS sont encore référencés sur data.gouv (surement un bug de moissonneur).
Le problème c'est que de temps en temps on se retrouve avec des dataset vides (toutes les ressources sont non dispo), sauf les ressources communautaires qui ont été générées quand les ressources étaient ok.
bref ca porte à confusion.
Pour info, il y a 126 ressources non dispo dont  89 GTFS (pour 59 datasets).
Cette PR réaffiche les ressources non dispo, en les marquant comme telle. Je savais pas trop comment faire apparaitre ca, …

Affichage de tous les GTFS, même indisponibles

---

apps/db/lib/db/resource.ex
apps/transport/lib/transport/import_data.ex
config/prod.exs

The import/validate process seems to consume too much memory.
This reduce the memory footprint by not loading in memory all resources
and their validation.
With a dump test on my computer the `maxresident` of `/usr/bin/time`
says that the validate process is now 397_428 compared to 1_836_576
before.
I also changed the time to 4am, this way no user should be impacted if
some stuff slow down

Do not preload all resources / validation while revalidating all

---

apps/transport/lib/transport/validations_cleaner.ex
apps/transport/test/transport/validation_cleaner_test.exs
config/config.exs
config/prod.exs

The manual validations (not linked to a resource) where never cleaned.
This fixes it (and keep 2 month a manuel validation)

Clean old validations

---

apps/db/mix.exs
apps/db/test/db_dataset_test.exs
apps/db/test/support/database_case.ex

Voir #1351, pour le cas de l'application `apps/db` (similaire à #1374).
On peut à présent lancer les tests DB seuls, ce qui est beaucoup plus rapide et ergonomique quand on travaille sur cette partie.

Correction lancement des tests sub-app DB (correctif umbrella)

---

apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot

closes #1377 
J'en profite pour changer le "Autres ressources" sous lequel est listé la ressource de blablacar et le remplacer par "Ressources".
https://transport.data.gouv.fr/datasets/aires-de-covoiturage-en-france/
En effet, "autres ressources" a du sens lorsqu'il y a par exemple des ressources GTFS, et des "autres ressources" (un csv par exemple). Mais lorsque l'on a que un csv, ce "autres ressources" est embrouillant, car on ne sait pas à quoi ce "autre" se rapporte. Je me trompais moi-même en confondant ça avec les ressources communautaires !

Les visualisations carto ne s'appliquent qu'aux ressources officielles

---

apps/db/priv/repo/migrations/20201209152013_add_indices.exs

the stats query was lasting several seconds (~3s) and was slowing the rendering of the /stats page.
Now the stat query is done in ~40ms.

Add indices to speed up stats query

---

apps/transport/test/transport_web/controllers/contact_controller_test.exs
apps/transport/test/transport_web/integrations/contact_test.exs

Après avoir lu la review de @thbar sur ma PR précédente, j'ai compris des petits trucs sur les tests qui m'avaient échappés.
- les tests que j'avais écrits n'étaient pas des tests d'intégration
- j'ai compris comment utiliser le Helper contact_path, je ne sais pas pourquoi je n'avais pas réussi la dernière fois...

Petites modifs dans les tests de la fonction send_mail

---

apps/transport/lib/transport_web/api/controllers/stats_controller.ex

Une petite correction que j'avais oublié de faire avant les vacances : la fonction count_aom_format sert dans la page de stats pour les données de la [carte](https://transport.data.gouv.fr/stats#public-transport-format) qui concerne les formats. Il faut ne compter que les datasets qui sont "actifs" pour avoir de bonnes statistiques. C'est pour cette raison que l'AOM du havre apparait en vert, à cause d'un dataset inactif, et donc invisible sur le reste du site.

Count only active datasets for stats

---

apps/transport/lib/transport/import_data.ex
apps/transport/test/transport/import_data_doc_test.exs
apps/transport/test/transport/import_data_service_test.exs
apps/transport/test/transport/import_data_test.exs

Il y a un bug, par exemple sur le réseau [TAG](https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-tag/).
Sa ressource principale apparait comme indisponible, alors qu'elle est disponible. La ressource est juste dispo via une redirection (HTTP 300), pour le moment tout ce qui n'était pas du 200 était considéré comme non dispo.

Une ressource disponible via une redirection HTTP est quand meme available

---

apps/transport/lib/transport_web/api/controllers/stats_controller.ex

closes #1408
Une manière facile de colorier une carte en vert :)
Précédemment c'est le niveau d'erreur maximal qui déterminait la couleur d'une aom sur la carte de [qualité des données](https://transport.data.gouv.fr/stats#public-transport-quality). C'est maintenant le niveau minimal.
Avant :
Après :

Changer le calcul de la qualité des données pour une AOM

---

apps/db/lib/db/resource.ex
apps/db/priv/gettext/en/LC_MESSAGES/validations.po
apps/db/priv/gettext/fr/LC_MESSAGES/validations.po
apps/db/priv/gettext/validations.pot

Petite faute d'orthographe qui nous empeche d'avoir le type de warning dans le validateur.
https://transport.data.gouv.fr/resources/11876#issues

correct "duplicate" spelling

---

config/config.exs

Dans #1431 j'ai durci la vérification du chargement de `SECRET_KEY_BASE`, toutefois au déploiement la compilation échoue. Je pense que la variable est temporairement non disponible.
On voit pourtant plus haut `Inject SECRET_KEY_BASE`, mais peut-être que le processus plus bas n'en profite pas.
Je reviens juste en arrière, sachant que de toute façon Phoenix lèvera une erreur au boot si la variable n'est pas settée.
```
2021-01-07T19:01:25+01:00 #7 [4/13] RUN mkdir phoenixapp
2021-01-07T19:01:25+01:00 #6 DONE 1.1s
2021-01-07T19:01:26+01:00 #10 [6/13] COPY ./ /phoenixapp
2021-01-07T19:01:26+01:00 #7 DONE 0.3s
2021-01-07T19:01:26+01:00 #8 [5/13] WORKDIR /phoenixapp
2021-01-07T19:01:26+01:00 #8 DONE 0.1s
2021-01-07T19:01:26+01:00 #11 [7/13] RUN mix do deps.get --only prod …
```

Correctif régression SECRET_KEY_BASE

---

apps/transport/lib/transport/import_data.ex

Certains netex ne sont pas bien détectés car avec le format neptume.
pour https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-fluo-grand-est-51-region-grand-est-dga-mobilites
Avant:
Après

detect neptune

---

apps/helpers/lib/hasher.ex

Avant cette PR, l'application tente de télécharger les ressources FTP (qui ne sont pas supportées, voir #1033), et le message d'erreur était peu clair:
```
[error] error while computing content_hash %HTTPoison.Error{id: nil, reason: :nxdomain}
```
Cette PR affiche un message explicite pour tous les protocoles non HTTP/HTTPS, avec un niveau `warn`.
Le but de la PR est d'éviter qu'un développeur se mette à chercher pour rien.

Clarification du log d'erreur lorsqu'on tente de charger une ressource FTP

---

apps/transport/lib/mix/tasks/logs.ex

Attention "beta", il pourrait y avoir des trous dans la raquette.
Actuellement la fonction `clever logs` ne fournit que 1000 lignes de logs (voir https://github.com/CleverCloud/clever-tools/issues/403 et https://github.com/CleverCloud/clever-tools/issues/429).
Ce n'est pas suffisant pour travailler correctement (ex: récupérer les logs d'import de la nuit précédente), et nous ne souhaitons pas pour l'instant utiliser un drain de logs.
En attentant d'avoir autre chose, j'ai porté le script Ruby réalisé avec @antoine-de l'autre jour lors de l'enquête sur #1465 en Elixir, et je l'ai rendu configurable.
La tâche réalise une auto-pagination vérifiée avec dédoublonnage des lignes déjà vues (à défaut de mieux).
```
mix clever.logs --since "2021-01-26T04:00:00Z" --before "2021-01-26T06:00:00Z" …
```

Tâche d'extraction de logs CleverCloud

---

apps/db/lib/db/resource.ex

closes https://github.com/etalab/transport-site/issues/1376
en fait j'ai regroupé les tranports soumis à reservation dans un tag TAD.
Ca ne couvre pour le moment pas tous les cas de TAD (lignes virtuelles, ...) mais j'ai l'impression qu'on pourra les rajouter, et que sinon ca va être trop précis.
On peut aussi mettre un `acronym` pour expliquer, mais en fait c'est pas que des données soumises à reservation sur le principe et je ne sais pas trop si on a vraiment besoin d'expliquer plus que ca

Ajout d'un tag sur le transport à la demande

---

apps/db/priv/repo/migrations/20210126172850_remove_refresh_places_resources_trigger.exs
apps/transport/lib/transport/import_data.ex
config/prod.exs

Comme vu dans #1473 et #1472, avant cette PR, l'import d'un dataset se traduisait par une transaction unique, qui met également à jour chacune de ses N ressources. Pour chaque ressource, le trigger `refresh_places_resources_trigger` est automatiquement appelé.
On a donc une forme de problème de N+1 mais avec un trigger, qui prend entre 500 et 1000 ms. Du coup l'import du dataset peut partir en timeout (> 15 secondes).
Dans cette PR, on désactive le trigger, au profit d'un appel explicite pour rafraîchir la vue matérialisée, et on ne fait ce rafraîchissement qu'après chaque import de dataset (1 fois par dataset, plutôt que 1 fois par ressource du dataset).
Par sécurité j'ai ajouté un cron toutes les heures qui va également rafraîchir la vue matérialisée.
La PR devrait déjà bien aider à …

Remplacement du trigger "refresh_places_resources_trigger"

---

apps/transport/lib/transport_web/controllers/dataset_controller.ex

le fitre par `tag` n’est plus supporté depuis un petit moment mais il restait un truc non desactivé qui faisait planter quand on appelait une route avec le filtre `tag` (inutile maintenant)
https://transport.data.gouv.fr/datasets?tags%5B%5D=bus&region=14 << ca plante maintenant et ca ne plante plus avec le fixe.
la mauvaise nouvelle c’est que quelqu’un a du sauvegarder cette url vu qu’on a eu le soucis en prod (et que ca ne fait pas la même chose que au moment où la personne a sauvegardé l’url), mais vu que ca ne fonctionne pas depuis un petit moment je vote pour fermer les yeux :grin:

remove deprecated `tag` filter handling

---

apps/transport/client/stylesheets/components/_choose_file.scss
apps/transport/client/stylesheets/espace_producteur.scss
apps/transport/client/stylesheets/producteurs.scss
apps/transport/lib/transport_web/templates/page/espace_producteur.html.eex
apps/transport/lib/transport_web/templates/resource/form.html.eex
apps/transport/lib/transport_web/templates/resource/resources_list.html.eex
apps/transport/lib/transport_web/views/bread_crumbs.ex
apps/transport/lib/transport_web/views/page_view.ex
apps/transport/lib/transport_web/views/resource_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/espace-producteurs.po
apps/transport/priv/gettext/en/LC_MESSAGES/resource.po
apps/transport/priv/gettext/espace-producteurs.pot
apps/transport/priv/gettext/fr/LC_MESSAGES/espace-producteurs.po
apps/transport/priv/gettext/fr/LC_MESSAGES/resource.po
apps/transport/priv/gettext/resource.pot

Suivant les recommandations de Aurélie, ajout d'un fil d'Ariane (breadcrumbs) dans l'espace producteur pour mieux s'y retrouver lors de l'ajout ou de la modification de ressources.

Ajout d'un fil d'Ariane dans la mise à jour des ressources (espace producteurs)

---

config/prod.exs

Pour améliorer la tenue en charge de l'application, j'augmente la taille du pool Ecto de 2 à 10.
(Au passage mon éditeur a reformaté le fichier, ce qui rend le diff un peu moins lisible).
Voir #1502 pour les benchmarks.
@fchabouis je vais devoir déployer pour tester en production, car pas de possibilité apparemment de déployer une branche dans notre configuration CleverCloud.
Je pense qu'au final il faudra peut-être ajuster différemment pour `prochainement`, mais je cherche à tester d'abord en privilégiant la production donc je vais merger en l'état.

Augmentation du pool_size de Ecto

---

apps/db/lib/db/dataset.ex
apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot
apps/transport/test/support/factory.ex
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

L'actualité nous a montré que lorsque data.gouv tombe, toutes nos pages de datasets passent en 404.
Ce qui pas nécessaire, puisque nous n'utilisons data.gouv lors de l'affichage d'un dataset que pour les réutilisations et les discussions.

Permettre le fonctionnement de transport en cas de downtime chez data.gouv

---

apps/transport/lib/transport/cache.ex
apps/transport/test/transport/cache_cachex_test.exs

closes #1565 
La fonction cachex.fetch ne prend pas en compte l'option ttl. Il faut donc ajouter un ttl à la main par la suite en cas de commit.
https://github.com/whitfin/cachex/issues/195

Ajout d'un TTL sur le cache de transport

---

apps/gbfs/lib/gbfs/controllers/jcdecaux_controller.ex
apps/gbfs/lib/gbfs/controllers/vcub_controller.ex
apps/gbfs/lib/gbfs/views/error_view.ex
apps/gbfs/test/gbfs/controllers/jcdecaux_test.exs
apps/gbfs/test/gbfs/controllers/vcub_controller_test.exs
apps/helpers/lib/sentry_exception_filter.ex
apps/transport/priv/static/robots.txt
config/config.exs

Voir #1567 il faut réduire le nombre d'évènements.
Je déploie cette PR graduellement sur la production (sans la merger) pour itérer dessus.

Réduction du nombre d'évènements envoyés à Sentry

---

apps/transport/client/stylesheets/main.scss
apps/transport/lib/transport_web/templates/layout/_header.html.eex
apps/transport/priv/gettext/default.pot
apps/transport/priv/gettext/en/LC_MESSAGES/default.po
apps/transport/priv/gettext/fr/LC_MESSAGES/default.po

closes #1551 
J'en profite pour mieux aligner le nom qui etait un peu au dessus des autres éléments de la navigation (a cause du thumbnail de l'utilisateur)
Si le nom n'est pas connu, on affiche juste "Mon compte"

Gestion du header lorsque le nom de l'utilisateur est vide

---

apps/transport/client/.eslintrc
apps/transport/client/javascripts/resource-viz.js
apps/transport/client/package.json
apps/transport/client/webpack.dev.js

Ce qui était parti comme juste une réparation de la carte des IRVE est finalement plus large :
Ce fichier est d'une qualité assez médiocre (pour rester poli), il y a des décalages de colonnes dans tous les sens, des coordonnées qui contiennent tout et n'importe quoi. Ca arrivait meme a faire planter leaflet :)
Deja un premier fix pour remettre la carte sur pieds, ensuite je creuserai comment mieux gérer les erreurs des cartes.
https://transport.data.gouv.fr/datasets/fichier-consolide-des-bornes-de-recharge-pour-vehicules-electriques/
Je me suis rendu compte que ma migration vers webpack 5 avait cassé le code reloading, c'est réparé.
J'ai finalement compris pourquoi je n'arrivais pas à charger le plugin `eslint-plugin-standard` comme indiqué dans la doc depuis le fichier eslintrc : parce …

Réparation de la carte de visualisation des ressources, page dataset

---

apps/transport/client/javascripts/map.js

Voir #1597, la région est passé au vert au complet à présent.
Après suppression du texte spécifique dans la popup, on voit ceci:

Suppression texte spécifique popup concernant l'Isère

---

apps/transport/client/yarn.lock

Le package `is-svg` contient une faille de sécurité remontée ici:
https://github.com/etalab/transport-site/security/dependabot/apps/transport/client/yarn.lock/is-svg/open
J'ai vu qu'en mettant à jour, le package `postcss-svgo` supprime sa dépendance à `is-svg`, ce qui règle l'alerte.

Mise à jour des packages javascript (suppression is-svg)

---

apps/shared/lib/hasher.ex

Ce code n'est plus utilisé depuis #1600.

Suppression de code mort

---

README.md
apps/transport/lib/transport_web/templates/layout/_header.html.eex

J'ai reçu un mail : les pages de status uptime robot sur notre nom de domaine ne sont plus comprises dans le plan gratuit à partir de demain. Apparemment, j'avais déjà reçu un mail le 27 avril, que je n'avais pas vu.
Pour le moment, je mets juste à jour avec l'url qui reste gratuite, puis on pourra se demander si on reste chez eux ou pas.

Mise à jour de la page uptime robot

---

apps/transport/lib/transport/import_data.ex

Patch pour faire en sorte qu'un timeout sur un import donnée ne bloque pas les imports suivants (fix #1626)

---

.circleci/config.yml

Voir https://app.circleci.com/pipelines/github/etalab/transport-site/1515/workflows/44c43865-9683-44c5-a27d-ffd498d7195a/jobs/25774/parallel-runs/0/steps/0-102, je me demande si l'erreur provient d'une restauration partielle du cache mix.

Tentative de réparation du CI

---

mix.lock

Ce répertoire est open-source, mais je ne sais pas s'il est open-contribution :thinking: 
J'essaye et puis on verra bien ! :shrug: 
Voici une petite PR pour résoudre https://github.com/etalab/transport-site/issues/1500 où j'ai simplement mis à jour `libring` pour se débarrasser de l'avertissement de déprécation concernant la stratégie `:simple_one_for_one`.
Dans votre propre base de code, vous n'utilisez jamais cette stratégie, alors j'ai recherché dans le dossier `deps` contenant toutes vos dépendances et j'ai vu que `libring 1.4` utilisait la stratégie `:simple_one_for_one`. Vu que ca faisait longtemps que cette stratégie a été abandonné, je me suis dit que mettre à jour `libring` devrait enlever les avertissements. 
Et c'est le cas ! 
On peut voir …

mise à jour de libring pour résoudre #1500

---

apps/transport/client/stylesheets/components/_backoffice.scss
apps/transport/lib/queries/dashboard_import_count.sql
apps/transport/lib/transport_web/controllers/backoffice/dashboard_controller.ex
apps/transport/lib/transport_web/templates/backoffice/dashboard/index.html.eex
apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.eex
apps/transport/lib/transport_web/views/backoffice/dashboard_view.ex

Ajout de plusieurs couleurs:
- rouge foncé pour crash non géré
- rouge pour uniquement des erreurs
- orange pour mix d'erreurs et de succès
- vert pour full succès
(bon la y'a beaucoup de rouge, mais c'est la base de tests :P)

Ajout d'informations supplémentaires dans le dashboard du backoffice

---

apps/transport/lib/transport/import_data.ex
apps/transport/lib/transport_web/controllers/backoffice/dataset_controller.ex
apps/transport/lib/transport_web/controllers/resource_controller.ex
apps/transport/test/transport/import_data_service_test.exs
apps/transport/test/transport/import_data_test.exs

Cette fonction est celle qui est lancée quotidiennement pour importer les jeux de données venant de data.gouv.fr.
Maintenant qu'elle est mise un minimum sous test, l'idée de cette PR est de la retoucher pour modifier la philosophie de son fonctionnement. 
Étant donné qu'elle lance via `async_stream_nolink` une série de process qui vont chacun importer un jeu de données, le code d'import essaye désormais de faire toutes ses étapes sans se soucier du succès ou de l'échec de celles-ci. En cas de problème, nous laissons le code crasher, et nous avons mis autour de la fonction d'import d'un dataset un `rescue`.
Celui-ci nous permet, en cas de crash de logger l'erreur qui s'est produite, et d'insérer en base un log d'échec.

Refactoring de la fonction import_all_datasets

---

apps/transport/lib/transport/import_data.ex

Il existe dans la table dataset un champ `is_active`. Lorsque ce champ est à `true`, le dataset n'apparait plus dans les résultats de recherche du moteur du site, sa page dédiée est toujours accessible si l'on connait son url, mais elle s'affiche avec un bandeau rouge prévenant que le jeu a été supprimé de datagouv.
[exemple](https://transport.data.gouv.fr/datasets/lignes-regulieres-de-transports-en-pays-de-la-loire-gtfs)
Il y a une tâche qui tourne quotidiennement `inactive_data` et qui détecte quels sont les jeux actifs et inactifs (un jeu inactif est un jeu dont la requête `head` chez data.gouv a retourné une 404). Un jeu peut-être actif, puis inactif, puis redevenir actif (s'il a été supprimé puis recréé sur data.gouv par exemple).
Lors d'un changement de statut (actif => inactif ou …

Ignorer les datasets inactifs lors de l'import quotidien

---

.circleci/config.yml

Je pense (cf #1641) que le cache PLT était restauré à la place du cache de build, à cause de la façon dont j'ai nommé les clés.
J'utilise des noms mieux séparés pour garantir une meilleur isolation entre les deux namespaces de cache.
Il va falloir merger d'abord, et vérifier dans le futur le comportement en gardant #1641 ouvert.

Correctif cache build & PLT (#1641)

---

apps/transport/lib/opendatasoft/url_extractor.ex

Cette PR:
- Corrige le problème rencontré dans #1639 en ajoutant un nouveau nom de colonne supporté dans le code qui sait extraire les "colonnes d'url" des exports OpenDataSoft
- Ajoute un peu de documentation
- Ajoute un test sur ce code (j'ai fait du test-first pour reproduire le souci et documenter)

Correctif import Opendatasoft (#1639)

---

apps/transport/client/javascripts/resource-viz.js
apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex

Suite au commentaire de @Miryad3108 , je règle quelques points concernant la visualisation des gbfs :
- en cas de soucis d'affichage avec un gbfs, on avait une carte vide. Maintenant je supprime la carte en entier.
- il restait la rubrique visualisation dans le menu à gauche de la page dataset en question, je supprime aussi la ligne "visualisation" du menu
- un fichier était reconnu comme étant un gbfs si son url se terminait par "gbfs.json", puisque c'est le nom du fichier décrit dans la spec. On a ici un cas de fichier gbfs.json qui est servi depuis une url qui ne se termine pas comme ça. On peut donc aussi se servir du type de fichier déclaré dans data.gouv (type gbfs)
Ensuite malheureusement, ces fix ne règlent pas le problème du dataset …

mieux gérer la visualisation des gbfs 

---

apps/gbfs/lib/gbfs/controllers/jcdecaux_controller.ex

Il peut arriver que le flux JCDecaux remonte le `last_update` d'une station à `null`. C'est le cas depuis plusieurs jours (voir #1653).
Cette PR rend le code plus défensif par rapport à l'input fourni par l'API JCDecaux, et gère le cas `null` correctement.
L'explication du besoin de diviser par 1000 est ici https://github.com/etalab/transport-site/issues/898 (secondes plutôt que millisecondes).
La sortie était en flottant `1622454039.0` car `x / 1000` donne un flottant. J'ai modifié ce point pour utiliser une division entière.
On note que ce ticket montre bien que "faire proxy" impose un soin plus important: suivi des ops (#1654) et des erreurs, code plus défensif, car en faisant ici une conversion, et en introduisant une erreur à l'intérieur, on crée une indisponibilité là où elle …

Correctif proxy GBFS (arithmetic error)

---

apps/transport/test/test_helper.exs
apps/transport/test/transport/comments_checker_test.exs

Cette petite PR fait en sorte que si on laisse des warnings dans le code des tests de l'application "transport" (celle qu'on touche le plus souvent), le CI bloquera, pour qu'on pense à les enlever.
Voir https://github.com/elixir-lang/elixir/issues/3223#issuecomment-751876927
Je ne vais pas plus loin dans l'exercice, quand on aura migré vers Elixir 1.12 (https://hexdocs.pm/mix/1.12/Mix.Tasks.Test.html), on pourra directement utiliser `mix test --warning-as-errors`.
Je corrige aussi deux warnings qui étaient présent (objectif dépolluer l'output des tests, ce qui sera sympa aussi pour les futurs développeurs).

"warnings as errors" pour les tests transport

---

apps/shared/lib/http_stream_v2.ex
apps/shared/test/http_stream_v2_test.exs
apps/transport/lib/transport/availability_checker.ex
apps/transport/lib/transport/import_data.ex
apps/transport/test/transport/availability_checker_test.exs
apps/transport/test/transport/import_data_test.exs

closes #1665
closes #1538 
L'idée est de supprimer tous les cas particuliers et de traiter toutes les ressources de la même manière : 
- on fait une requête head, en suivant les éventuelles redirections pour voir si la ressources est bien disponible
- en cas de réponse 405 (signifiant que la méthode HEAD n'est pas supportée), on passe au plan B : on fait un GET en streamant la réponse. Dès qu'on a l'information sur le statut de la réponse, on arrête le streaming pour gagner du temps.
Question à laquelle je viens de penser : quid des ressources sur ftp ? (voir #1409)

Correction de la détection des ressources non disponibles

---

apps/db/lib/db/dataset.ex
apps/db/priv/gettext/dataset.pot
apps/db/priv/gettext/en/LC_MESSAGES/dataset.po
apps/db/priv/gettext/fr/LC_MESSAGES/dataset.po
apps/db/priv/repo/migrations/20190130145745_rename_transit_types.exs
apps/db/priv/repo/migrations/20210615132842_charsharing_to_carpooling.exs
apps/transport/lib/transport_web/templates/page/index.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po

Modification "carsharing-area" en "carpooling-area" pour éviter les confusions quand il y aura des données d'autopartage

Modification "carsharing-area" en "carpooling-area"

---

apps/db/priv/repo/migrations/20210622150648_dataset_communes_on_delete.exs
apps/db/test/db_dataset_test.exs
apps/transport/test/support/factory.ex

La table dataset_communes permet de faire une relation many_to_many entre la table dataset et la table communes.
Sauf que lorsque celle-ci a été crée, il y a eu une coquille  dans l'emplacement du on_delete
```
add(:dataset_id, references(:dataset), on_delete: :delete_all)
```
au lieu de 
```
add(:dataset_id, references(:dataset, on_delete: :delete_all))
```
juste la parenthèse qui ferme au mauvais endroit.
Je fais donc ici une migration qui altère la table et qui rajoute le on_delete qui va bien.
Seul petit hic : on ne peut pas altérer une table lorsqu'une view en dépend.
Voir https://stackoverflow.com/questions/62793360/error-cannot-alter-type-of-a-column-used-by-a-view-or-rule-detail-rule-return par exemple.
Je vais donc récupérer le code qui a permis de créer la vue en question, je …

Ajout d'une action on_delete à la table dataset_communes

---

apps/transport/priv/reusers.csv
apps/transport/test/transport/csv_documents_test.exs

J'ai introduit un chemin incorrect suite à un commit non poussé dans #1716.
Cette PR ajoute un test rapide qui détectera ces soucis dès la PR, pour éviter que ça ne se reproduise.

Ajout test détection logos cassés et correctif logo

---

apps/transport/lib/mix/tasks/transport/import_aom.ex
apps/transport/lib/transport/import_aom.ex
apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/backoffice/page/index.html.eex

closes #1727 , #1711, #1710
Je n'ai pas touché au code d'import des AOMs, qui n'est pas testé. De plus, il y a des choses que je trouve étranges dans la manière dont sont liés en base les AOMs et les Datasets, il faudrait peut-être le changer, et ça pourrait avoir des conséquences sur la manière de mettre à jour les AOMs.
Tout ça pour dire que l'import des AOMs était auparavant une Task à lancer depuis mix, ce qui n'était pas très pratique car il fallait se connecter sur le serveur de prod et lancer la ligne de commande. J'ai donc rajouté un bouton dans le backoffice qui permet de mettre à jour les AOMs.

Permettre de lancer la MAJ des AOMs depuis le backoffice

---

apps/transport/lib/transport_web/api/controllers/places_controller.ex

closes #1464, #1520
Je fais un test simple pour rendre la recherche sur le site plus flexible. Si c'est trop couteux en temps de calcul et que les réponses sont lentes, il faudra y réfléchir plus.
Je commence par déployer sur prochainement.
Je trouve les résultats plutôt convaincants, et les requêtes sont vraiment raisonnables. Chapeau à Postgres :) Par exemple si je tape "Auxxerre", on aboutit à 2 requêtes : une première qui ne renvoit rien (basée sur ILIKE), puis une seconde basée sur des trigrammes et la notion de simalarity. L'ensemble de la requête GET se fait en local en 11ms.
On commence par une recherche exacte, basée sur une regex (sans les accents, sans la casse). Tant qu'on trouve des choses, on renvoit les résultats. Si la recherche ne renvoie rien, on fait une deuxième …

Permettre de faire des recherches approximatives dans la barre de recherche

---

apps/transport/client/javascripts/map.js
apps/transport/lib/transport/stats_handler.ex
apps/transport/lib/transport_web/api/controllers/stats_controller.ex
apps/transport/lib/transport_web/api/router.ex
apps/transport/lib/transport_web/templates/page/real_time.html.md
apps/transport/lib/transport_web/templates/stats/index.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/test/transport_web/controllers/stats_controller_test.exs

En renommant la catégorie bike-sharing en bike-scooter-sharing, j'ai oublié la partie statistiques du site.
Cette fois ci j'ai vraiment reporté la modif partout, et j'ai rajouté un (premier) test sur la page de stats.
La carte de stats est réparée.
closes #1735

Fix bike scooter map

---

apps/transport/lib/transport_web/api/controllers/stats_controller.ex

Dans #1748, il a été vu que la carte de disponibilité des horaires théoriques contenait une info incorrecte concernant le nombre de datasets.
Cette PR corrige en fait davantage de points où les datasets inactifs étaient comptabilisés par erreur:
- `nb_datasets` qui est affiché sur la carte mentionnée dans #1748
- `dataset_types`
- `region_features_query`
- `quality_features_query`
Je n'ai :warning: pas traité les points suivants, qui auraient pu l'être, car je n'étais pas sûr de l'impact à ce stade:
- `quality`
- `error_level`
Il serait bon d'avoir un mécanisme plus large, type "global scope" RubyOnRails, ou une vue filtrée par défaut (j'ai vu plusieurs mentions de cette technique pour gérer les "soft delete" avec Ecto), ou au moins une query composée de départ qui serait plus DRY, mais …

Filtre de davantage de datasets inactifs sur les stats (#1748)

---

Dockerfile
apps/transport/lib/transport_web/endpoint.ex
config/prod.exs

closes #1495
Oh zut alors, j'ai passé une bonne partie de la journée à essayer de comprendre pourquoi nos assets n'étaient pas compressés et pourquoi le digest n'était pas ajouté au nom de nos assets, et je vois que la réponse était en fait dans #1495 :sweat_smile: 
Voyons le bon côté des choses : j'ai appris des trucs et je suis arrivé à la même conclusion.
Qui était donc que l'on lançait dans le Dockerfile le `mix phx.digest` avant la phase de build de npm, et que par conséquent, webpack n'avait pas encore fait son travail, et les assets n'étaient pas encore là (voir le dossier priv/static n'existait même pas).
J'en profite pour activer la compression des documents html, via une option dans prod.exs. J'ai fait des tests sur prochainement, on passe de 2.27Mo transférés pour la page …

Compression et digest des static assets

---

apps/transport/lib/transport/import_data.ex
apps/transport/test/fixture/cassettes/client/datasets/sncf.json
apps/transport/test/fixture/cassettes/dataset/dataset-with-multiple-cities-and-country.json.json
apps/transport/test/fixture/cassettes/dataset/dataset-with-multiple-cities.json.json

closes #1790 
On a un problème avec HTTPoison (de Hackney en fait) qui ne gère pas les redirect pour les codes 308. Voir https://github.com/benoitc/hackney/issues/635
Ceci est juste un quick fix : je change l'url que l'on requête sur data.gouv.fr pour éviter d'avoir une 308 en retour et directement une 200. Mais ça ne règle pas le problème de la librairie en dessous, je vais créer une issue pour cela.

Réparation des imports pour les datasets liés à une zone datagouv

---

apps/transport/lib/transport/history/backup.ex
apps/transport/lib/transport/history/fetcher_s3.ex
apps/transport/lib/transport/history/shared.ex
apps/transport/test/transport/history_test.exs
config/config.exs
config/test.exs

Une sécurité supplémentaire pour s'assurer qu'on lit uniquement les objets qui nous appartiennent dans les buckets Cellar de CleverCloud.
Voir https://github.com/etalab/transport_deploy/issues/31 pour les détails

Buckets : lecture des objets de l'organisation uniquement

---

.tool-versions
apps/transport/test/build_test.exs

Les tests présents sous https://github.com/etalab/transport-site/blob/master/apps/transport/test/build_test.exs (introduits cette année) nous ont bien aidé à identifier les versions utilisées (Elixir/Erlang/Node), à être sûr d'utiliser les bonnes versions en dév CI et prod et à les faire converger, ce qui a toujours beaucoup de valeur.
Suite à la mise à jour à 24.0.4 toutefois, j'ai vu que le système ne prévenait pas que le fichier ASDF et le Docker ne pointent pas exactement vers la même version (voir #1810).
En général c'est peu important, car OTP est très généralement bien stable et un numéro de build n'apporte pas d'incompatibilité pénible, toutefois le passage à `24.0.4` était un exemple où il y a un changement important (gestion SSL critique).
Des différences minimes peuvent aussi …

MAJ asdf Erlang 24.0.3 -> 24.0.4 + verrouillage plus complet de la version d'Erlang

---

apps/datagouvfr/lib/datagouvfr/client/api.ex
apps/datagouvfr/lib/datagouvfr/client/community_resources.ex
apps/datagouvfr/test/datagouvfr/client/api_test.exs
apps/datagouvfr/test/datagouvfr/client/community_resources_test.exs
apps/datagouvfr/test/datagouvfr/client/datasets_test.exs
apps/datagouvfr/test/support/data_gouv_api_fixtures.ex
apps/datagouvfr/test/support/mocks.ex
apps/transport/test/transport_web/controllers/nav_test.exs
apps/transport/test/transport_web/controllers/seo_test.exs

Après refacto, la pagination de l'API Data.Gouv.Fr est géré à partir de la propriété "next_page" fournie dans l'enveloppe de la réponse.
👉 Gestion des erreurs dans Datagouvfr.Client.API :
Le stream s'arrête à la première erreur rencontrée
Le dernier élément du stream est un tuple {:error, error} où error contient le détail de l'erreur fournie par l'API.
ex : si la 3e page d'un stream est en erreur, alors le résultat sera
> Datagouvfr.Client.API.stream(resource) |> Enum.to_list()
[
{:ok, page1},
{:ok, page2},
{:erreur, "cannot access resource"} 
]
👉 Gestion des erreurs dans CommunityResources.API :
Le stream s'arrête à la première erreur rencontrée
Retourne le tuple {:error, []} (comportement identique au précédent - avant streaming)

Add the paging feature for Community Resources API.

---

apps/transport/lib/transport_web/views/dataset_view.ex

Fixes https://github.com/etalab/transport-site/issues/1816
Les URLs ont changé suite à la refonte graphique de schema.data.gouv.fr https://github.com/etalab/schema.data.gouv.fr/issues/195

Changement des liens vers schema

---

apps/transport/test/test_helper.exs
apps/transport/test/transport_web/controllers/geojson_conversion_controller_test.exs

Voir #1820 ; ce n'est pas le correctif qu'il faudra à terme (où on voudra par défaut, pouvoir travailler sans ces tests en local, en ayant l'assurance qu'ils tourneront en CI, et en ayant la possibilité de travailler en local avec la version de l'outil que l'on souhaite, compilée en local ou pas), mais ça permettra de remettre au vert les suites de test en local, sans nécessiter de faire tourner l'outil.
Pour vérifier le fonctionnement et simuler un CI local:
```
CI=true mix cmd --app transport mix cmd --app transport mix test test/transport_web/controllers/geojson_conversion_controller_test.exs --color
```
Si on enlève `CI=1`, les tests tourneront à nouveau.

Quick-fix pour exclure les tests nécessitant gtfs-to-geojson (sauf sur le CI)

---

apps/transport/lib/transport_web/templates/backoffice/page/index.html.eex
apps/transport/lib/transport_web/views/bread_crumbs.ex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/en/LC_MESSAGES/espace-producteurs.po
apps/transport/priv/gettext/espace-producteurs.pot
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/espace-producteurs.po

Fixes https://github.com/etalab/transport-site/issues/1739
- Traduction en anglais
- Ajout de chaines en français
- Suppression de doublons
Après ce commit, l'exécution de `mix gettext.extract --merge` ne change aucun fichier.

Mise à jour de traductions manquantes

---

apps/transport/lib/opendatasoft/url_extractor.ex
apps/transport/lib/transport/import_data.ex

Contexte : lorsque des jeux de données sont publiés sur opendatasoft, et qu'ils ne rentrent pas dans leurs cases (très limitées), une pratique courante est de publier un csv qui contient des url vers des ressources (GTFS, NeTEx).
C'est pas du tout pratique pour nous, et c'est pour l'instant quelque chose qu'on essaye en dernier recours lors d'un import : si c'est un jeu public-transit et que tu ne trouves aucune ressource GTFS dedans, alors essaye d'aller en chercher dans les ressources csv.
Cette logique n'était pas implémentée pour les NeTEx, je l'ai donc étendue pour https://transport.data.gouv.fr/datasets/horaires-des-lignes-transilien-1/

Permettre d'importer des ressources Netex depuis un CSV

---

apps/gbfs/lib/gbfs/controllers/vlille_controller.ex
apps/transport/lib/transport_web/controllers/resource_controller.ex

Les logs de tests étaient pollués par plusieurs gros logs de ce type:
```
warning: Elixir.Phoenix.Controller.render/4 with a view is deprecated, see the documentation for render/3 for an alternative
(phoenix 1.5.9) lib/phoenix/controller.ex:763: Phoenix.Controller.render/4
(transport 0.0.1) lib/transport_web/controllers/resource_controller.ex:1: TransportWeb.ResourceController.action/2
(transport 0.0.1) lib/transport_web/controllers/resource_controller.ex:1: TransportWeb.ResourceController.phoenix_controller_pipeline/2
(phoenix 1.5.9) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
(transport 0.0.1) lib/transport_web/router.ex:1: TransportWeb.Router.call/2
(transport 0.0.1) lib/plug/router.ex:280: anonymous fn/4 in TransportWeb.Plugs.Router.dispatch/2
(telemetry 0.4.3) …
```

Correctifs warning Phoenix

---

apps/transport/lib/transport/history/backup.ex
apps/transport/test/transport/history_test.exs

Fixes https://github.com/etalab/transport-site/issues/1893
Voir l'issue pour l'explication du problème

History.Backup : vérifie que meta ne contient pas de _

---

apps/transport/lib/transport/history/backup.ex
apps/transport/test/transport/history_test.exs

Suite de #1880
En vérifiant que mon fix fonctionnait correctement en production, j'ai eu une suprise. J'ai trouvé la source mon problème dans `modification_date`
```elixir
iex > [~N[2015-06-17 23:54:05], ~N[2021-11-01 04:32:48.819059]] |> Enum.max()
~N[2015-06-17 23:54:05]
iex > [~N[2015-06-17 23:54:05], ~N[2021-11-01 04:32:48.819059]] |> Enum.sort(NaiveDateTime) |> Enum.at(-1)
~N[2021-11-01 04:32:48.819059]
```
Bon, [la doc le dit](https://hexdocs.pm/elixir/1.12/NaiveDateTime.html#module-comparing-naive-date-times) mais je trouve ça surprenant.
Bref, voici une correction.

History.Backup: fix tri des dates

---

apps/transport/lib/transport/history/backup.ex

Je me suis encore fait avoir par la comparaison des `NaiveDateTime` comme dans https://github.com/etalab/transport-site/pull/1892...
Le plus triste c'est que la PR précédente ne faisait pas apparaitre le problème car la comparaison des structures est "aléatoire". Je m'en suis rendu compte en vérifiant que le fix fonctionnait correctement en prod [pour un JDD précis](https://transport.data.gouv.fr/datasets/tisseo-offre-de-transport-gtfs/) (ce qui n'est pas le cas à cause de ce bug).
En utilisant les valeurs de production des dates :
```elixir
iex(1)> ~N[2020-08-31 07:10:03.159448] < ~N[2021-11-03 04:34:43.985516]
warning: invalid comparison with struct literal ~N[2020-08-31 07:10:03.159448]. Comparison operators (>, <, >=, <=, min, and max) perform structural and not semantic comparison. …
```

History.Backup : correction comparaison dates

---

apps/transport/lib/opendatasoft/url_extractor.ex
apps/transport/test/transport/url_extractor_doc_test.exs

La PR #1885 a changé le comportement de `get_gtfs_csv_resources` pour le rendre plus strict.
- Avant : toutes les ressources avec des liens distants dont l'URL ne termine pas par `.pdf` ou ne contiennent pas `netex` (non sensible à la casse) sont considérées comme des GTFS
- Après : le nom du fichier doit contenir `gtfs` (non sensible à la casse)
Ceci a eu pour effet de supprimer des ressources de producteurs qui ne nommaient pas leurs fichiers ZIP d'une certaine façon. C'est apparemment commun [dans la région CVL](https://data.centrevaldeloire.fr/explore/dataset/ville-damboise-offre-theorique-mobilite-reseau-urbain/table/).
Reçu par email : 
> J’ai renommé le GTFS en bourges-gtfs.zip. sur notre site open data.
> Ce problème est lié au fait qu’il y a 2 enregistrement dans le jeu de …

UrlExtractor : implémentation legacy pour get_gtfs_csv_resources

---

apps/transport/lib/transport_web/controllers/page_controller.ex
apps/transport/priv/static/robots.txt
apps/transport/test/transport_web/controllers/page_controller_test.exs

Correction de [cette erreur Sentry](https://sentry.io/organizations/betagouv-f7/issues/2586711595/?project=5687467&query=is%3Aunresolved)
- ajout d'un `redirect_path` par défaut
- ajustement du `robots.txt`
- ajout de tests

Ajustement redirect_path pour login

---

apps/transport/lib/transport_web/templates/dataset/_resources_container.html.eex
apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot

closes #1619 
J'en profite pour renommer la section "historique" par "ressources historisées", ce qui me parait plus parlant.
Pour le moment j'ai mis le message uniquement pour les ressources GTFS, car il n'y a qu'elles qu'on historise.

Ajout d'un lien vers la section "ressources historisées"

---

apps/transport/priv/search_custom_messages.yml

Le message affiché correspond à la première catégorie qui match les critères rentrés.
Du coup il faut mettre la catégorie `real-time` avant la catégorie `public-transit` car elle est plus spécifique.
real-time : /datasets?type=public-transit&filter=has_realtime
public-transit : /datasets?type=public-transit

Changer l'ordre des catégories des messages custom

---

apps/transport/lib/transport_web/controllers/validation_controller.ex

Pour je ne sais quelle raison, quelqu'un nous appelle quotidiennement sur l'url de validation des GTFS mais en nous passant un "faux upload" qui s'appelle test_file.txt.
Ca fait des erreurs [Sentry](https://sentry.io/organizations/betagouv-f7/issues/2586794539/events/d1fbda4344f4401395e9ac6c342c5b97/events/?project=5687467&statsPeriod=14d).
Maintenant ça va renvoyer des réponses bad request ([400](https://http.cat/400))

Suppression erreur Sentry

---

apps/transport/lib/transport_web/controllers/resource_controller.ex
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Correction de [cette erreur Sentry](https://sentry.io/organizations/betagouv-f7/issues/2798047776/events/6a9fd4940d574ccc81978b0ed2763e9b/?project=5687467). Les données GBFS ont des métadonnées mais ne sont pas affichées pour le moment sur cette page.
Visiblement on arrive cette page [depuis le controlleur Atom](https://github.com/etalab/transport-site/blob/master/apps/transport/lib/transport_web/controllers/atom_controller.ex), à modifier plus tard, c'est étonnant de linker vers des 404.

Correction erreur 500 resource#details

---

config/runtime.exs

Il manquait un petit `not` sur cette ligne pour que la configuration Oban ne soit pas vide. Dans l'état actuel, le seul moyen de lancer des jobs était de ne PAS démarrer en mode worker.

Répare démarrage worker

---

config/prod.exs

https://github.com/etalab/transport-site/pull/1920 avait rendu cette variable d'environnement obligatoire. Celle-ci est obligatoire au runtime mais non au build et ceci a créé des problèmes sur CleverCloud.
~~Navré.~~ -> edit @thbar aucun souci !

SECRET_KEY_BASE n'est pas une variable requise

---

config/prod.exs

Comme dans #1942. 
Le support CC indique que les variables d'env sont bien disponibles lors du build, mais il faut sûrement [ajuster notre Dockerfile](https://github.com/etalab/transport-site/blob/master/Dockerfile) pour partager des variables d'env lors de la phase de build du container.

fetch_env! vers get_env

---

config/config.exs
config/runtime.exs

Related to https://github.com/etalab/transport-site/issues/1945
Ajout de `APP_ENV` pour distinguer prochainement et la production. J'ai déjà ajouté les variables d'env nécessaires sur CleverCloud.

Ajout APP_ENV en production

---

apps/db/lib/db/resource_history.ex
apps/db/priv/repo/migrations/20211130094242_add_resource_history.exs
apps/db/test/support/factory.ex
apps/transport/lib/jobs/resource_history_job.ex
apps/transport/lib/s3.ex
apps/transport/lib/zip.ex
apps/transport/mix.exs
apps/transport/test/s3_test.exs
apps/transport/test/transport/jobs/resource_history_job_test.exs
apps/transport/test/zip_test.exs
config/config.exs
config/dev.exs
config/prod.exs
config/runtime.exs
config/staging.exs
config/test.exs
mix.lock

See https://github.com/etalab/transport-site/issues/1921
Cette PR ajoute des jobs en charge d'historiser des ressources :
- `Transport.Jobs.ResourceHistoryDispatcherJob` est un job à exécuter de manière régulière, qui ajoute d'autres jobs dans la file de traitement en charge d'historiser les ressources. La liste de ressources à historiser est obtenue à partie d'une requête en base de données.
- `Transport.Jobs.ResourceHistoryJob` est le job en charge d'historiser une ressource. Il doit
----
Les classes notables ajoutées pour faire ce travail
- `Transport.ZipMetaDataExtractor` pour calculer les métadonnées ZIP, repris depuis #1918 
- `Transport.S3` des helpers pour Cellar

Historisation des ressources à l'aide de jobs

---

config/runtime.exs
config/staging.exs

Voir https://mattermost.incubateur.net/betagouv/pl/eteurd1cofya5pe4gi56gioktw et #1951 
Ces commits permettent de tester plusieurs scénarios en staging, pour tenter de reproduire un crash survenu en production le 2021-12-02 en fin de journée.
Au final, cette branche nettoie la configuration dans le fichier runtime.

Branche temporaire investigation

---

apps/transport/lib/jobs/resource_history_job.ex
apps/transport/test/transport/jobs/resource_history_job_test.exs

Ajout de filtres pour les ressources à historiser :
- uniquement les ressources actives
- celles qui sont accessible en HTTP/HTTPS (et non FTP !)

Filtres supplémentaires pour ResourceHistory

---

apps/transport/lib/jobs/resource_history_job.ex
apps/transport/test/transport/jobs/resource_history_job_test.exs

Comme https://github.com/etalab/transport-site/pull/1957, des améliorations soulevées par @fchabouis.
Le client Finch n'a pas cette fonctionnalité, en attendant qu'on stabilise les clients HTTP, j'utilise HTTPoison qui est très présent dans notre code. #1958 #1917

Follow redirects in ResourceHistoryJob

---

README.md

En lien avec:
- #1956
- #1688
J'ai mis à plat les domaines utilisés pour les 3 sous-parties de chaque application, et à l'équerre sur production + staging. Cela permettra d'accéder facilement à LiveDashboard notamment, mais aussi à aller voir facilement l'état d'un service donné.
Je propose de supprimer les custom domains suivants (de CleverCloud), quel est votre avis ?
- `app-$REDACTED$.cleverapps.io` pour toutes les applications
- `prochainement-transport.cleverapps.io` (qui est remplacé par `prochainement.transport.data.gouv.fr`
(Si je le fais, je commencerai par le staging puis la production pour vérifier qu'on n'a pas de surprises, et je demanderai également à CleverCloud si ça peut poser un souci en terme de monitoring ou autre).
L'idée est d'avoir une façon canonique d'accéder aux …

Mise à plat des noms de domaine utilisés

---

apps/transport/lib/jobs/resource_history_job.ex
apps/transport/test/transport/jobs/resource_history_job_test.exs

Gère de potentielles erreurs lorsqu'on essaie de calculer des métadonnées sur un fichier ZIP.
Stacktrace dans Oban
```
** (MatchError) no match of right hand side value: {:error, \"Invalid zip file, missing EOCD record\"}
(transport 0.0.1) lib/zip.ex:10: Transport.ZipMetaDataExtractor.extract!/1
(transport 0.0.1) lib/jobs/resource_history_job.ex:88: Transport.Jobs.ResourceHistoryJob.process_download/2
(transport 0.0.1) lib/jobs/resource_history_job.ex:68: Transport.Jobs.ResourceHistoryJob.perform/1
(oban 2.10.1) lib/oban/queue/executor.ex:218: Oban.Queue.Executor.perform_inline/2
(oban 2.10.1) lib/oban/queue/executor.ex:206: Oban.Queue.Executor.perform_inline/2
(elixir 1.12.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
(elixir 1.12.2) lib/task/supervised.ex:35: …
```

ResourceHistoryJob : gère erreurs ZIP

---

apps/gbfs/lib/gbfs/telemetry.ex
apps/gbfs/lib/page_cache.ex
apps/gbfs/test/gbfs/page_cache_test.exs
apps/transport/lib/transport/telemetry.ex
apps/transport/test/transport/telemetry_test.exs
apps/unlock/test/controllers/unlock_controller_test.exs

Utilise ce qui a été ajouté dans #1925, enregistre des événements afin de connaitre l'utilisation du cache et des ressources externes pour le GBFS.
Cette PR ne contient que l'enregistrement en BDD, je ferai sûrement la partie visualisation backoffice dans la foulée.
Envoie
- `[:gbfs, :request, :internal]` avec le nom du réseau (par exemple `vcub`) dans le cas d'un _cache hit_
- `[:gbfs, :request, :external]` avec le nom du réseau (par exemple `vcub`) dans le cas d'un _cache miss_
On ne prend pas en compte les différentes URLs (gbfs.json vs station_status.json), on s'arrête au niveau du réseau GBFS.

Enregistre Telemetry events pour GBFS

---

apps/transport/lib/jobs/resource_history_job.ex
apps/transport/test/transport/jobs/resource_history_job_test.exs

Fixes https://github.com/etalab/transport-site/issues/1972. Le `is_active` à utiliser est celui du Dataset et non de la Resource, https://github.com/etalab/transport-site/pull/1957 était donc une erreur.

Utilise dataset.is_active pour ResourceHistoryJob

---

apps/gbfs/test/gbfs/page_cache_test.exs
apps/unlock/test/controllers/unlock_controller_test.exs

Le nom des events n'était pas bon dans `page_cache_test`, j'avais indiqué proxy au lieu de gbfs... Donc les handlers n'avaient pas été correctement enlevés.
Cette PR corrige ce problème.

Correction telemetry dans page_cache_test

---

apps/unlock/lib/endpoint.ex
apps/unlock/lib/router.ex

Suite de https://github.com/etalab/transport-site/pull/1995
En réalité le plug était ignoré en production mais pas dans les tests https://github.com/etalab/transport-site/blob/6e4f4103df7c9727fc16edb4a3f861456cf97fd7/apps/transport/lib/transport_web/plugs/router.ex#L9-L13. Je l'ai donc bougé directement dans le router et j'ai confirmé ça en localhost.

Unlock: plug for CORS in the right place

---

apps/transport/lib/transport_web/api/controllers/stats_controller.ex
apps/transport/test/transport_web/controllers/stats_controller_test.exs

Follow up de https://github.com/etalab/transport-site/pull/1993
Il faut s'assurer que les `slugs` sont bien triés dans le même ordre également. Merci @fchabouis.

Vehicles geopoints: order by names and slugs

---

apps/transport/lib/transport_web/templates/page/real_time.html.md

Il y avait une balise cassée sur [cette page](https://transport.data.gouv.fr/real_time) (uniquement la balise de fermeture). Cette PR rétablit un lien vers l'adresse de contact.

Correction lien brisé adresse contact

---

apps/unlock/lib/controller.ex
apps/unlock/test/controllers/unlock_controller_test.exs

Fixes #2006
Ma compréhension du problème avec le code actuel est que si une exception survenait, elle était dans le cache de manière permanente.
Doc: https://hexdocs.pm/cachex/Cachex.html#fetch/4
> A fallback function should return a Tuple consisting of a :commit or :ignore tag and a value. If the Tuple is tagged :commit the value will be placed into the cache and then returned. If tagged :ignore the value will be returned without being written to the cache. **If you return a value which does not fit this structure, it will be assumed that you are committing the value.**
Comme la valeur retournée est `:error`, elle est commit dans le cache.
https://github.com/etalab/transport-site/blob/c069513510b9db7d65e6ea6d9fb1b9f4be6266c5/apps/unlock/lib/controller.ex#L125-L156
Comme l'operation …

Unlock: gère exception dans comp_fn

---

apps/transport/lib/transport_web/live/backoffice/proxy_config_live.ex
apps/transport/lib/transport_web/live/backoffice/proxy_config_live.html.leex
apps/unlock/lib/shared.ex

Affiche le TTL d'une entrée du cache sur la page de suivi du proxy

Ajout TTL proxy config live

---

apps/transport/lib/jobs/oban_logger.ex
apps/transport/lib/jobs/resource_unavailable_job.ex
apps/transport/lib/transport/history/backup.ex
apps/transport/lib/transport_web/controllers/validation_controller.ex

Suppression de plusieurs warnings lors de la compilation.
Il en reste 2
```
warning: Supervisor.Spec.supervisor/2 is deprecated. Use the new child specifications outlined in the Supervisor module instead
Found at 2 locations:
lib/transport/application.ex:31: Transport.Application.start/2
lib/transport/application.ex:32: Transport.Application.start/2
warning: Supervisor.Spec.worker/2 is deprecated. Use the new child specifications outlined in the Supervisor module instead
lib/transport/application.ex:61: Transport.Application.add_scheduler/1
```
que je ne suis pas sûr de pouvoir corriger sans faire d'erreur donc je laisse ceci.

Remove warnings

---

config/config.exs
config/prod.exs

Suite de #1992. La variable `domain_name` ne peut pas leaker d'un fichier à l'autre comme ça.

Set up domain_name in config

---

apps/transport/lib/transport_web/templates/resource/details.html.eex
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Il y avait ce petit cas qui était passé entre les tests, quand il existe un NeTEx associé à une ressource, mais pas de GeoJSON, ça faisait crasher la page.

🪛 Réparation de la page détails des ressources

---

apps/transport/client/javascripts/resource-viz.js

Je m'étais posé la question de pourquoi on avait des villes interdites de circulation partout, cf issue #1990 .
Il s'avère que même si la doc GBFS n'est actuellement [pas très bien rédigée](https://github.com/NABSA/gbfs/issues/361), la règle est quand même claire :  quand des zones de geofencing sont en conflit, la première règle définie a la priorité.
Pour des raisons de clarté, j'avais choisi de toujours faire apparaitre les interdictions au dessus des autorisations, mais ce n'est pas comme ça que sont interprétées les règles, donc j'affiche les règles sur la carte de telle sorte que celle qui s'applique soit celle du dessus (sur laquelle on peut cliquer).
Au passage, j'ai la réponse à ma question initiale, les zones définies par Bird ne semblent pas correctes. Par exemple pour Castres, …

Mettre les calques des GBFS dans le bon ordre

---

apps/db/lib/db/resource.ex

Follow up of #2029
Currently, resources with a JSON schema `schema_name` are validated on the website process and we've seen that this validation can take several seconds when validating large files (we had troubles validating a 305 MB file). Table schema resources are validated using an external web API so they are less affected.
This PR adds a quick fix to skip schema validations for files larger than 10 MB. `filesize` is not filled for all resources at the moment but it's filled for large resources. We'll need to look at validating large files (or everything) on workers.
```sql
select id, url, schema_name, filesize, content_hash
from resource
where schema_name is not null
```

Do not validate large files

---

apps/datagouvfr/lib/datagouvfr/client/reuses.ex
apps/datagouvfr/test/datagouvfr/client/reuses_test.exs
apps/datagouvfr/test/support/data_gouv_api_fixtures.ex

Voir exception https://sentry.io/organizations/betagouv-f7/issues/2590167890/?project=5687467
Il est possible d'avoir une erreur 500 avec le contenu
```
{
"message": "Internal Server Error"
}
```
Cette PR refactor le code existant pour gérer ce cas et rendre plus générique la gestion des erreurs. En lisant `api.ex` et `client.ex` je ne suis même pas sûr qu'il soit possible d'avoir `body` et `reason` avec des atoms en réalité.

Handle another error for datagouv#reuses

---

apps/db/lib/db/resource.ex
apps/db/test/resource_test.exs

This PRs:
- adds a `content_hash` to the `validation` map when validating resources with a schema set. This is similar to what's done for GTFS resources.
- makes sure that validation is skipped if the `content_hash` of a resource with a schema is the same as the previous validation's content hash. Again, similar to what's done for GTFS resources.

Add content hash when validating resources with a schema

---

apps/transport/lib/transport_web/views/resource_view.ex
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Gère l'erreur suivante : https://sentry.io/organizations/betagouv-f7/issues/2912761831/?project=5687467
Ceci survenait pour des ressources GBFS, qui ont un rapport de validation mais pas une liste d'erreurs.
```js
{
"ttl":0,
"feeds":[
"system_information",
"vehicle_types",
"free_bike_status",
"system_pricing_plans",
"geofencing_zones"
],
"types":[
"free_floating"
],
"has_cors":true,
"versions":[
"2.2"
],
"languages":[
"fr"
],
"validation":{
"has_errors":false,
"errors_count":0,
"version_detected":"2.2",
"version_validated":"2.2"
},
"system_details":{
"name":"pony",
"timezone":"Europe/Paris"
},
"is_cors_allowed":true
}
```

Gestion exception dans errors_sample

---

.circleci/config.yml
Dockerfile
Dockerfile.dev
apps/transport/test/build_test.exs

Cette PR rend disponible le binaire de conversion GTFS vers NeTEx. C'est le bout de la chaîne de ces PR:
- https://github.com/etalab/transport-tools/pull/9
- https://github.com/etalab/transport-tools/pull/11
- https://github.com/etalab/transport-tools/pull/12
- https://github.com/etalab/transport-ops/pull/34
- https://github.com/etalab/transport-ops/pull/35
- https://github.com/etalab/transport-ops/pull/36
À considérer comme beta, car:
- https://github.com/etalab/transport-tools/issues/10

Mise à disposition du convertisseur GTFS vers NeTEx

---

apps/datagouvfr/lib/datagouvfr/client.ex
apps/datagouvfr/mix.exs

Enregistre certaines erreurs provenant de datagouv dans Sentry, en particulier quand on a des erreurs OAuth2.
Je n'ai pas pu ajouté un test il n'y a pas de behaviour sur `Datagouvfr.Client.OAuth` ou la lib OAuth.
C'est le même problème que là https://github.com/etalab/transport-site/blob/c71348d127f40ef0abbfe6d44b98cd985dd46e99/apps/transport/test/transport_web/controllers/page_controller_test.exs#L76-L78

Enregistre erreurs datagouv Sentry

---

config/runtime.exs

Ça a dû vous arriver aussi : on lance un webserver en local, il est 12h et paf, 3000 jobs `Transport.Jobs.ResourceUnavailableJob` se retrouvent dans la queue Oban à cause du Cron.
J'ai l'impression que le plus souvent, on n'a pas envie que ces jobs soient lancés automatiquement quand on lance un serveur de dev.
Idem pour la console `iex`, je suis finalement de l'avis de @thbar , on n'a pas envie qu'une session iex en local se mette à traiter des jobs.

Ajustement des settings pour faciliter le travail en local

---

apps/db/lib/db/dataset.ex
apps/db/priv/gettext/dataset.pot
apps/db/priv/gettext/en/LC_MESSAGES/dataset.po
apps/db/priv/gettext/fr/LC_MESSAGES/dataset.po
apps/transport/lib/transport_web/controllers/page_controller.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-index.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-index.po
apps/transport/priv/gettext/page-index.pot
apps/transport/test/transport_web/controllers/dataset_search_test.exs

Une PR de refactor de https://github.com/etalab/transport-site/pull/2030. Lié aussi à #1862 
Suite à cette PR, on avait des incohérences entre le titre d'une tuile sur l'accueil et sur la liste des jeux de données.
Exemple :
- "Transport public collectif - horaires théoriques" sur l'accueil
- "Horaires théoriques de transport public" sur https://transport.data.gouv.fr/datasets?type=public-transit
Cette PR uniformise la source de traduction vers `DB.Dataset.type_to_str`, ce qui simplifie la création des tuiles aussi.

Uniformisation titres par type de Dataset

---

apps/transport/lib/transport_web/templates/page/espace_producteur.html.eex
apps/transport/lib/transport_web/templates/page/infos_producteurs.html.eex
apps/transport/priv/gettext/en/LC_MESSAGES/espace-producteurs.po
apps/transport/priv/gettext/en/LC_MESSAGES/page-producteurs.po
apps/transport/priv/gettext/espace-producteurs.pot
apps/transport/priv/gettext/fr/LC_MESSAGES/espace-producteurs.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-producteurs.po
apps/transport/priv/gettext/page-producteurs.pot

closes https://github.com/etalab/transport-site/issues/2000

Espace producteur : ajout du lien vers validateur GBFS 

---

apps/transport/lib/transport/history/fetcher.ex
config/dev.exs

La suppression de l'implémentation vide de `History.Fetcher` dans https://github.com/etalab/transport-site/pull/2060 était peut-être un peu rapide, c'est bien utile en dev, là où un mock est utile pour les tests.
Cette PR rétablit une implémentation qui ne retourne rien en dev.

Implémentation de dev pour History.Fetcher

---

apps/shared/lib/validation/jsonschema_validator.ex
apps/shared/lib/validation/tableschema_validator.ex

Fixes https://github.com/etalab/transport-site/issues/2085
Stocke au plus 100 erreurs en base de données pour les erreurs de validation de ressources avec des schémas.
On affiche au plus 50 erreurs sur l'interface https://github.com/etalab/transport-site/blob/553aa63b3deddf8cbddaf7e2ca59a1be39318f1a/apps/transport/lib/transport_web/views/resource_view.ex#L110
Pour les ressources avec beaucoup d'erreurs, j'irai lancer une validation forcée depuis le backoffice après avoir déployé cette PR. En effet la validation n'est pas lancée si la ressource distante n'est pas changée. Il y a moins de 10 cas en production
```sql
select dataset_id, jsonb_array_length(metadata->'validation'->'errors')
from resource
where jsonb_array_length(metadata->'validation'->'errors') > 100
```

Limite nombre d'erreurs pour TableSchema et JSONSchema

---

apps/db/lib/db/resource_history.ex

Suite à des 500 sur `GET api/datasets/:dataset_id`, l'application ne savait pas comment sérialiser des `DB.ResourceHistory`.
https://github.com/etalab/transport-site/blob/90b54ea44522bf5bc70f74f4953167128c8200cb/apps/transport/lib/transport_web/api/controllers/datasets_controller.ex#L174

Ajout Jason.Encoder pour ResourceHistory

---

apps/transport/lib/transport_web/templates/dataset/details.html.eex

Un bug étonnant présent visiblement depuis au moins 2 ans : le texte du bouton d'abonnement/désabonnement aux commentaires est inversé.
Démo :
- aller sur https://transport.data.gouv.fr/datasets/trottinettes-montlucon/
- voir le bouton "Se désabonner des discussions ce jeu de données" alors que vous n'êtes pas abonné

Correction texte bouton abonnement aux commentaires

---

apps/transport/lib/transport_web/views/dataset_view.ex

Répare un bug introduit dans #2123
Exception : https://sentry.io/organizations/transport-data-gouv-fr/issues/3024065273/?project=6197733&query=is%3Aunresolved
`resource_metadata` est `nil` et non `%{}`
```
BadMapError :erlang.is_map_key/2
expected a map, got: nil
```

Répare bug has_validity_period?

---

apps/transport/lib/transport_web/templates/dataset/details.html.eex

Retravaille la partie de vue utilisant `has_validity_period?`.
- Utilisation de la `resource_history` dans la boucle et non de la collection
- Si la colonne est présente, il faut dans tous les cas mettre un `<td>`, vide ou non en fonctionne la `ResourceHistory`

Fix DatasetView et has_validity_period?

---

apps/transport/lib/transport_web/templates/dataset/details.html.eex

Le `=` en plus a pour effet de faire un `echo` et donc d'afficher `true` :facepalm:

Réparation syntaxe eex dataset/details

---

apps/transport/client/stylesheets/components/_icons.scss
apps/transport/client/stylesheets/components/_validation.scss
apps/transport/lib/transport_web/live/on_demand_validation_live.html.heex
apps/transport/lib/transport_web/templates/resource/_gtfs_rt_errors_for_severity.html.eex
apps/transport/lib/transport_web/templates/resource/_validation_report.html.eex
apps/transport/lib/transport_web/views/resource_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/validations.pot
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Suite de #2139
Cette PR ajoute l'affichage d'un rapport de validation pour les ressources GTFS-RT qui ont été validées.

Rapport de validation pour GTFS-RT

---

apps/transport/lib/transport_web/plugs/health_check.ex
apps/transport/test/transport_web/routing/health_check_test.exs

En rapport avec:
- #2087
- #1913
On sait à présent que le redémarrage de monitoring CleverCloud n'est pas "trop zélé".
On cherche à présent à confirmer que le souci se présentera même quand la base de données n'est pas sollicitée.
Dans cette PR, je fais évoluer le health-check pour qu'on puisse à la demande contourner la vérification base de données, à l'aide d'un paramètre.
Par défaut 2 checks sont là (`http` et `db`). On peut passer `&db=0` pour ne faire que la partie `http`, qui aura lieu de toute façon.

Évolution du health-check HTTP pour permettre de ne pas vérifier la base de données

---

apps/transport/lib/mailjet/email_host.ex
apps/transport/lib/transport/data_checker.ex
apps/transport/test/transport/data_checker_test.exs
config/runtime.exs

Correctif pour #2154.
J'introduis une notion de "email host name", qu'il faudra utiliser pour chaque utilisation des "routes helpers" pour créer des liens dans les emails.

Correctif pour urls contenus dans les emails

---

apps/transport/priv/gettext/fr/LC_MESSAGES/page-index.po

J'avais changé la casse de ce mot dans https://github.com/etalab/transport-site/pull/2165 et fait la mise à jour "à la main" mais j'ai mal fait ceci dans la partie `fr`. Ceci a pour effet d'avoir une chaîne de caractères non traduite en prod.

Correction casse traduction FR 'Subscribe'

---

apps/transport/lib/transport/import_data.ex
config/prod.exs
config/runtime.exs

Contexte:
- https://github.com/etalab/transport-site/issues/1913
- On a des exceptions dans Sentry la nuit liées au manque de connections via le pool
Dans cette PR:
- je déplace la configuration finale de `prod.exs` (qui affecte prochainement et la production) vers `runtime.exs`
- je configure la taille du pool à 15 au lieu de 6 pour la production uniquement
- ça permet de ne pas aller au passage à contre-courant de https://github.com/etalab/transport-site/issues/1817
- je supprime `pool_timeout` qui n'avait plus d'effet de toute façon
- j'ai augmenté le timeout de validation général, car de temps en temps sur le staging ça saute
Avant d'essayer de tweaker davantage, je vais observer si rien que ça suffit à ne plus avoir de timeouts (voir …

Ajustements sur le pool de base de données (production)

---

.github/.workflows/sentry_release.yml

Fixes https://github.com/etalab/transport-site/issues/2174
J'ai suivi les instructions sur l'action GitHub de Sentry et [l'article de blog](https://blog.sentry.io/2020/07/30/automate-release-management-with-the-sentry-release-github-action)

Ajout GitHub Action pour suivre les déploiements dans Sentry

---

apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/layout/_footer.html.eex

En allant trainer du côté du footer (merci @AntoineAugusti), je me suis rendu compte que le lien vers notre FAQ était cassé.

Lien cassé vers la FAQ

---

apps/transport/lib/transport_web/controllers/page_controller.ex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/layout/_footer.html.eex
apps/transport/lib/transport_web/templates/page/accessibility.html.md
apps/transport/priv/gettext/default.pot
apps/transport/priv/gettext/en/LC_MESSAGES/default.po
apps/transport/priv/gettext/fr/LC_MESSAGES/default.po
apps/transport/test/transport_web/controllers/page_controller_test.exs

Ajoute une page d'accessibilité et un lien "Accessibilité : non conforme" dans le footer.
J'ai suivi les recommandations sur
- https://design.numerique.gouv.fr/outils/exemple-declaration-accessibilite/
- https://design.numerique.gouv.fr/accessibilite-numerique/declaration-accessibilite/

Ajout page accessibilité

---

apps/transport/lib/transport_web/controllers/validation_controller.ex
apps/transport/lib/transport_web/templates/resource/_validation_summary.html.eex
apps/transport/lib/transport_web/templates/resource/gtfs_details.html.eex
apps/transport/lib/transport_web/templates/validation/show.html.eex

Suite à https://github.com/etalab/transport-site/pull/2163, un token a été ajouté aux validations à la demande pour rendre le rapport non public.
Ce query param `token` a été oublié dans les URLs de la validation GTFS pour quand on souhaite filtrer par type de problème ou quand on pagine les erreurs. Cette PR ajoute ce paramètre à ces URLs.

Validation GTFS : ajout token dans pagination

---

apps/shared/lib/hasher.ex
apps/shared/test/hasher_test.exs
apps/transport/lib/jobs/resource_history_job.ex
apps/transport/lib/zip.ex
apps/transport/test/transport/jobs/resource_history_job_test.exs

voir https://mattermost.incubateur.net/betagouv/pl/m1acxa7u5fgjtda416jwzs8s5r
Dans le cas d'une ressource non zip, au lieu de calculer le hash de la resource qu'on vient de télécharger et qu'on s'apprete à historiser, on prend le hash qui est stocké au niveau de la %Resource{}, et qui était à jour lors du dernier import. Mais la ressource a pu changer entre temps, donc on risque de stocker un mauvais hash.

Correction calcul du hash d'une ressource non zip lors de l'historisation

---

apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/lib/transport_web/templates/backoffice/page/index.html.eex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po

Ce filtre et l'identification de telles ressources n'est plus d'actualité.
J'en profite pour indiquer que la ressource existante ne fonctionne pas, il faudrait avoir `count = 0 or cout is null`

Suppression backoffice rt_resource_without_siri_lite

---

apps/transport/lib/transport/stats_handler.ex
apps/transport/lib/transport_web/api/controllers/stats_controller.ex

On commence à avoir des ressources en SIRI, mais quelques endroits du code n'ont pas encore été adaptés pour prendre en compte ces formats en particulier sur `/stats`.

Compte les ressources SIRI

---

apps/transport/priv/search_custom_messages.yml

Ajout de la mention de la page https://transport.data.gouv.fr/real_time

Mention de la page temps réel

---

apps/transport/lib/transport_web/templates/validation/show.html.eex

Suite de https://github.com/etalab/transport-site/pull/2185
Il manque `@conn` ici, [voir l'exception](https://sentry.io/organizations/transport-data-gouv-fr/issues/3102861833/?project=6197733&statsPeriod=14d)

Manque @conn pour resources_details.html

---

apps/transport/lib/transport_web/controllers/validation_controller.ex
apps/transport/test/transport_web/controllers/validation_controller_test.exs

Le champ `DB.Validation.date` pouvait être à `null` pour les validations GTFS-RT quand il y avait une erreur. 
`OnDemandValidationJob` remplit normalement ce champ
https://github.com/etalab/transport-site/blob/350f9824f58068410e9f3818d6c7ffdbb07c15d4/apps/transport/lib/jobs/on_demand_validation_job.ex#L31
mais dans le cas d'un conflit `Oban.Job` (unique par 5 minutes), le job n'est pas exécuté.
Il vaut mieux renseigner ce champ au niveau du controller.

Renseigne date pour validation GTFS-RT

---

apps/transport/lib/transport/availability_checker.ex

closes #2234 
2XX : This class of status codes indicates the action requested by the client was received, understood, and accepted.
Du coup, on peut considérer que toute réponse 2XX signifie que le serveur est opérationnel et que la ressource est bien disponible.

Availability checker : autorise les réponses 2XX

---

apps/transport/lib/transport_web/templates/dataset/_resources_container.html.eex
apps/transport/lib/transport_web/templates/dataset/_reuser_message.html.eex
apps/transport/lib/transport_web/templates/dataset/details.html.eex

Fixes https://github.com/etalab/transport-site/issues/2223
Voir description ici, mais rapidement, [sur ce JDD](https://transport.data.gouv.fr/datasets/simouv-horaires-theoriques-et-temps-reel-de-transport-public-transvilles-valenciennes/) le message est affiché déjà 3 fois après chaque bloc de ressources.
J'ai vérifié que `resources_container` était utilisé uniquement ici.

Affiche message réutilisateur seulement une fois

---

apps/shared/lib/date_time_display.ex
apps/transport/lib/transport_web/live/on_demand_validation_live.ex
apps/transport/lib/transport_web/live/on_demand_validation_live.html.heex

Utilisation de la nouvelle fonction `format_datetime_to_paris` pour avoir quelque chose de plus agréable et modification de celle-ci pour pouvoir afficher de manière optionelle les secondes, utiles pour la validation à la demande (en particulier lors de l'attente du résultat).

Formattage des datetimes pour validation à la demande

---

apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

Fixes #1850 (ouvert depuis longtemps !)
Ajout des champs suivants pour chaque ressource dans l'API :
- filesize
- modes
- features
- schema_name
- schema_version
qui étaient manquants jusqu'à présent. Certains me paraissent très importants pour des intégrations tierces, comme les schémas.
J'ai écrit un premier test (:grimacing:) pour `dataset#by_id` au passage.

Ajout attributs pour ressources dans l'API

---

apps/shared/lib/gbfs_metadata.ex

closes #2151 
On avait une exception dans le try do, mais qui n'était pas du bon type, du coup ça faisait une 500. Maintenant on attrape tout.

Correction d'une erreure 500 sur la validation de certains GBFS

---

apps/db/lib/db/resource.ex
apps/db/priv/repo/migrations/20220321151717_remove_resource_conversion_content_hash.exs
apps/db/priv/repo/migrations/20220321151717_remove_resource_deprecated_fields.exs

Suppresion des champs `is_active` et `conversion_content_hash`.
`is_active` m'a demandé un peu de temps, parce que le champ du même nom pour les Datasets est très largement utilisé partout. Mais celui de resource, je n'ai vu aucune autorisation.

Un peu de ménage dans le schéma de la ressource

---

apps/transport/lib/transport/import_data.ex

Met à jour le `format` des export GeoJSON provenant de ODS en tant que format `geojson` au lieu de `json`. Permet de profiter de https://github.com/etalab/transport-site/pull/2217 et d'avoir un format plus réaliste.
En attente d'une éventuelle correction upstream https://github.com/opendatateam/udata-ods/issues/211 et https://github.com/etalab/data.gouv.fr/issues/632

Exports GeoJSON venant de ODS en tant que geojson

---

apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

Fixes https://github.com/etalab/transport-site/issues/2228
J'ai été surpris de voir que pour les NeTEx il y avait bien des `start_date` mais à `null`.
Exemple
```json
{
"end_date":null,
"has_fares":false,
"has_shapes":false,
"issues_count":{
"ExtraFile":26,
"MissingMandatoryFile":5,
"UnloadableModel":1
},
"lines_count":0,
"modes":[
],
"networks":[
],
"some_stops_need_phone_agency":false,
"some_stops_need_phone_driver":false,
"start_date":null,
"stop_areas_count":0,
"stop_points_count":0
}
```

Gère null pour has_validity_period?

---

apps/transport/lib/transport_web/views/dataset_view.ex

Fixes #2263
J'avais oublié de traiter ce cas dans #2233.

Ressources SIRI dans bloc temps réel uniquement

---

apps/transport/lib/transport/import_data.ex
apps/transport/test/transport/import_data_test.exs

Adapation de `ImportData` pour ne conserver que les ressources avec le schéma ZFE pour la catégorie `low-emission-zones`.
Similaire à ce qui est fait pour `public-transit` mais `get_valid_resources` est un "prefilter" alors que `maybe_filter_resources` est exécuté après avoir construit la ressource.
Le but est de nettoyer [ce JDD](https://transport.data.gouv.fr/datasets/zfe-zone-a-faibles-emissions/) par exemple.

Conserve uniquement ressources avec schéma pour ZFE

---

apps/transport/lib/transport_web/live/on_demand_validation_live.ex
apps/transport/lib/transport_web/live/on_demand_validation_live.html.heex
apps/transport/test/transport_web/controllers/validation_controller_test.exs

Suite de #2242, affichage des informations contenues dans le flux GTFS-RT (entités dans le flux, service alerts si présentes et décodage du flux) sur un résultat de validation à la demande.

Affichage GTFS-RT sur validation à la demande

---

.circleci/config.yml
mix.exs

Je fais tourner `dialyxir` en mode `test`, ainsi on peut faire disparaître la compilation qui existe en mode `dev`, et ne garder que celle en mode `test` dont on a besoin de toute façon.
Il faudra vérifier à l'usage que ça n'introduit pas d'effet de bord.

Réduction de l'usage CircleCI en évitant la compilation "dev"

---

apps/transport/test/transport_web/controllers/atom_controller_test.exs

Fixes #2273
La construction passée du test ne prenait pas en compte qu'il pouvait y avoir +1h ou +2h de décalage par rapport à UTC pour Paris/Europe.

Répare test AtomController lié changement d'heure

---

apps/transport/lib/transport/history_fetcher.ex
apps/transport/test/transport/history_fetcher_test.exs

Utilise ce qui a été fait dans https://github.com/etalab/transport-site/pull/2192
Cette PR prend en compte les `resource_history` qui ont le même `dataset_id` et ne se limite pas que aux mêmes `resource.datagouv_id` (ayant constaté que cette information n'était pas fiable).
L'idée est de donc de "repêcher" des ressources qui étaient en lien avec ce jeu de données mais ne sont plus présentes.
J'ai fait attention à ajouter un index sur `dataset_id` dans `payload` qui est du JSONB.
```
Sort  (cost=1147.91..1148.01 rows=38 width=460)
Sort Key: r2.inserted_at DESC
->  Nested Loop  (cost=0.55..1146.92 rows=38 width=460)
Join Filter: (((r2.datagouv_id)::text = (r1.datagouv_id)::text) OR (((r2.payload ->> 'dataset_id'::text))::bigint = d0.id))
->  Nested Loop  (cost=0.55..35.39 rows=1 width=45) …
```

Historisation : prise en compte des anciennes ressources

---

apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.eex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po

Parce qu'on fait souvent des aller retour entre le backoffice et le site public.

Backoffice : ajout d'un lien permanent vers le site public

---

.formatter.exs
config/config.exs
config/database.exs
config/dev.exs
config/gbfs_validator.exs
config/gtfs_validator.exs
config/test.exs

Je suis régulièrement embêté par ça en travaillant en local, et je m'empêchais de commiter le résultat.
Vu que la configuration est stable ("feature freeze"), on peut le faire tranquillement.
EDIT: on peut ajouter d'autres choses au formateur si ça vous paraît pertinent !

Formattage (sans changement) des fichiers de configuration

---

apps/transport/lib/transport_web/controllers/atom_controller.ex
apps/transport/test/transport_web/controllers/atom_controller_test.exs

Et bien mon fix rapide de #2274 n'aura pas marché très longtemps !
En réalité `AtomController` prend les ressources modifiées lors des 15 derniers jours, on ne pouvait donc pas utiliser une valeur "hardcodée".
Cette PR répare ça.

Répare test format de date sur AtomController

---

config/runtime.exs

Et bien la ligne était partie dans un stash et n'en était jamais ressortie :sweat_smile:

Ajout d'un cron pour le job d'import de la BNLC

---

apps/db/lib/db/resource_unavailability.ex

Après enquête un peu pénible je dois dire 😺 je crois avoir compris l'origine de:
- #2281.
Sur un ordinateur de dév, qui sera en heure française, la fonction `now()` SQL retourne l'heure locale:
```sql
select now(), now() at time zone 'utc'
```
| now                           | timezone                   |
|-------------------------------|----------------------------|
| 2022-04-12 15:43:01.659895+02 | 2022-04-12 13:43:01.659895 |
Or, en production et sur CircleCI, on va être en UTC (donc le problème n'apparaîtra pas).
J'ai l'impression que ça veut peut-être dire que ce test n'est jamais passé en local ?
J'adapte la requête.
En regardant rapidement, je ne vois pas d'autre instance de `now()` en SQL, mais il faudra vérifier.

Correctif tests qui ne plantent qu'en local

---

apps/db/lib/db/resource.ex
apps/db/priv/repo/migrations/20220412131157_add_resource_filetype.exs
apps/transport/lib/transport/import_data.ex
apps/transport/test/transport/import_data_test.exs

En lien avec https://github.com/etalab/transport-site/issues/2308
Sur les bons conseils de @fchabouis j'ajoute la colonne `filetype` pour les ressources provenant de l'API de data.gouv.fr. Ce sera bien utile dans `DatasetView` ensuite.
J'ai fait migration + changement du modèle dans la même PR. On pourrait avoir quelques exceptions lors du déploiement, je trouve que c'est acceptable.

Ajout filetype pour DB.Resource

---

apps/db/lib/db/dataset.ex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/test/transport_web/controllers/dataset_view_test.exs

Fixes https://github.com/etalab/transport-site/issues/2308 utilise ce qui a été fait dans #2319 
Utilise une URL stable pour le bouton "Télécharger" si les fichiers sont hébergés sur data.gouv.fr.

Ajuste URL derrière le bouton Télécharger

---

apps/db/lib/db/resource.ex
apps/db/priv/gettext/en/LC_MESSAGES/validations.po
apps/db/priv/gettext/fr/LC_MESSAGES/validations.po
apps/db/priv/gettext/validations.pot

Suite à https://github.com/etalab/transport-validator/pull/119, j'ai ajouté des messages d'erreurs pour des raisons qui n'étaient pas encore présentes.

Messages d'erreurs supplémentaires pour validateur GTFS

---

apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/test/transport_web/controllers/dataset_view_test.exs
config/config.exs

Fixes #2339
Bison Futé a :
- des URLs en `http://`
- un lien qui redirige vers un directory listing en web (exemple http://tipi.bison-fute.gouv.fr/bison-fute-ouvert/publicationsDIR/Evenementiel-DIR/grt/RRN/)
La combinaison des 2 ne plait pas à notre. En effet, quand on est dans ce cas, notre code essaie de renvoyer le contenu du fichier distant ([voir code](https://github.com/etalab/transport-site/blob/10ada526b16f1e402426eded9acf7387ab9c2de1/apps/transport/lib/transport_web/controllers/resource_controller.ex#L149-L174)).
J'adapte le code pour forcer l'utilisation d'un lien permanent data.gouv.fr, qui lui va rediriger vers le lien final.
On pourrait à terme adapter le code pour avoir une redirection 302 si `content-type: text/html` ?

URL permanente datagouv pour Bison Futé

---

apps/transport/lib/transport/stats_handler.ex
apps/transport/lib/transport_web/templates/stats/index.html.eex
apps/transport/lib/transport_web/views/stats_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/stats.po
apps/transport/priv/gettext/fr/LC_MESSAGES/stats.po
apps/transport/priv/gettext/stats.pot

Fixes #2316
Une prise en compte partielle de ce qui a été décrit dans l'issue, mais qui est déjà une amélioration. Utilise ce qui a été fait dans https://github.com/etalab/transport-site/pull/2248 pour afficher le nombre de flux GTFS-RT diffusant chaque type d'information.
J'ai tenté de faire un truc pas trop moche sans faire de CSS custom ou en changeant totalement l'aspect de cette page.

Stats : compte types de flux GTFS-RT

---

apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/test/transport_web/controllers/dataset_view_test.exs

Suite de https://github.com/etalab/transport-site/pull/2341
En réalité les ressources pour Bison Futé ont un `filetype = remote`, ce qui est logique car c'est bien un lien distant et non un fichier déposé sur datagouv. La PR précédente n'était donc pas suffisante.
J'ai supprimé la contrainte de filetype car ça me semble acceptable de considérer qu'on utilise une URL stable datagouv dès lors que le host est un domaine static de datagouv, ou `tipi.bison-fute.gouv.fr`

Pas de contrainte de filetype pour needs_stable_url?

---

apps/db/lib/db/resource_history.ex
apps/shared/lib/schemas.ex
apps/transport/lib/jobs/backfill/backfill_metadata_validation.ex
apps/transport/test/transport/jobs/backfill/backill_metadata_validation_test.exs

Cette PR est une PR de backfill, qui recalcule les informations de validation de ressources qui ont été historisées avec des informations de validation périmées. C'est dû au fait qu'il n'y avait pas encore https://github.com/etalab/transport-site/pull/2326 et qu'ainsi on historisait un nouveau fichier avec des informations de validation de la version d'avant.
En prod il y a actuellement 155 `ResourceHistory` qui sont concernées
```sql
select rh.payload->'format', r.schema_name, rh.payload->'content_hash', rh.payload->'resource_metadata'->'validation'->'content_hash', rh.payload
from resource_history rh
join resource r on r.datagouv_id = rh.datagouv_id
where rh.payload->'resource_metadata' ? 'validation'
```
C'est un nombre assez faible car actuellement l'historisation comporte des …

Recalcul des données de validation dans l'historisation

---

apps/shared/test/validation/jsonschema_validator_test.exs

Lié à https://github.com/etalab/transport-site/issues/2347
Ajoute un test pour vérifier le comportement de notre validateur JSON Schema vis-à-vis de `dependencies` et `dependentRequired`, lié au fait que notre validateur ne supporte pas les versions 2019 et 2020 pour le moment. https://github.com/jonasschmidt/ex_json_schema/issues/75

Ajout test validateur JSONSchema et dependentRequired

---

apps/transport/lib/transport/stats_handler.ex
apps/transport/test/transport/stats_handler_test.exs

Bug introduit suite à https://github.com/etalab/transport-site/pull/2330
`:gtfs_rt_types` contient une valeur du style
```elixir
[%{count: 60, type: "trip_updates"}, %{count: 44, type: "vehicle_positions"}, %{count: 13, type: "service_alerts"}]
```
et non des nombres, comme les autres clés.
Le processus d'historisation quotidien ne gérait pas cette possibilité, d'où l'apparition [d'une exception](https://sentry.io/organizations/transport-data-gouv-fr/issues/3230559511/?project=6197733&query=is%3Aunresolved).
Je n'avais pas connaissance de cette logique, donc je ne l'avais pas anticipé. Il n'y a malheureusement pas de tests sur cette classe.
Comme un vrai ingénieur, dans `iex -S mix`
```elixir
iex> recompile;Transport.StatsHandler.store_stats()
[debug] QUERY OK db=1.7ms idle=14.1ms
INSERT …
```

Gère gtfs_rt_types pour stockage des stats

---

apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/test/transport_web/controllers/dataset_view_test.exs

Fixes #2366
Prend la suite de https://github.com/etalab/transport-site/pull/2356 et ajoute un menu "Documentation" lorsque le jeu de données contient au moins une ressource avec le type de `documentation`.
Ajuste le code existant pour exclure du nombre de ressources affiché et ajoute une section avec une ancre.

Ajoute menu Documentation sur dataset#details

---

apps/transport/lib/mailjet/client.ex
apps/transport/test/transport/mailjet_client_test.exs
config/dev.exs

Le gros nettoyage de printemps ici:
- https://github.com/etalab/transport-site/pull/2290
incluait un petit souci (`nil` au lieu de `[]` pour les headers envoyés à Hackney) qui résultait en:
- https://github.com/etalab/transport-site/issues/2368
J'ai corrigé et ajouté un test d'intégration un peu plus profond (car le mocking était fait plus haut).
On va réfléchir à des contre-mesures pour détecter ça plus facilement.

Correctif pour régression sur envoi d'email

---

apps/shared/lib/validation/gtfs_validator.ex
apps/shared/test/validation/gtfs_validator_test.exs

Lié à https://github.com/etalab/transport-site/issues/2376
En regardant les erreurs de la validation/validation à la demande, je tombe sur un cas qui ne semble pas être traité par le code existant, le cas de timeout lors de l'appel HTTP au validateur GTFS.
La stacktrace enregistrée est
```
%FunctionClauseError{args: nil, arity: 1, clauses: nil, function: :handle_validation_response, kind: nil, module: Shared.Validation.GtfsValidator}
```
ce qui est assez cryptique. J'ai déjà vu ça dans le backoffice aussi.
La façon de gérer les timeouts avec HTTPoison est assez bancale https://github.com/edgurgel/httpoison/issues/215 mais ma compréhension est que ça devrait être `%HTTPoison.Error{reason: :timeout}`.

Gestion erreur timeout pour validateur GTFS

---

apps/transport/lib/jobs/gtfs_to_netex_converter_job.ex

Fixes https://github.com/etalab/transport-site/issues/2360
Adapte la stratégie de [`backoff`](https://hexdocs.pm/oban/Oban.Worker.html#module-customizing-backoff) pour le job de conversion GTFS vers NeTEx et ajoute un attribut `unique` empêchant d'ajouter des jobs qui sont déjà en attente d'exécution.
La combinaison de l'étalement des nouveaux essais et du caractère unique devrait diminuer la charge.
À noter qu'il est possible de ne pas _retry_ certains jobs du tout https://github.com/etalab/transport-site/issues/2360#issuecomment-1121104830. À voir si on modifie le job ou si on part sur un enregistrement des échecs permanents de jobs dans une base, comme discuté hier à l'oral en point dev.

Stratégie de retry pour SingleGtfsToNetexConverterJob

---

apps/transport/lib/jobs/resource_history_job.ex
apps/transport/test/transport/jobs/resource_history_job_test.exs

Fixes https://github.com/etalab/transport-site/issues/2344
Ajoute `schema_name` et `schema_version` dans `ResourceHistory.payload`. Je n'ai pas fait de backfill, à voir si on en fait plus tard, ou pas ?

Ajoute infos de schéma sur ResourceHistory

---

apps/transport/lib/jobs/resource_history_validation_job.ex
config/runtime.exs

A la vue des statistiques de réponse de notre validateur ces derniers temps, j'essaye de le charger un peu moins pour voir ce que ça donne. Je mets donc une queue pour la validation des ressources history à part avec une concurrence de 1.

Queue de traitement à part pour la validation des ressources history

---

apps/transport/lib/jobs/resource_history_validation_job.ex

J'aimerais donner la priorité à la validation des ressources history récentes, car ce se sont celles qui nous intéressent pour le moment.

Valider les Resources history les plus récentes en premier

---

apps/transport/lib/transport/import_data.ex

Ajuste le code de détection du format GeoJSON dans ImportData, pour traiter un cas spécial dans les ZFE où le fichier "Export au format GeoJSON" ne fonctionne pas car ODS supprime les colonnes qui contient des valeurs à `null`, ce qui rend le fichier invalide.
Le producteur [a publié un fichier alternatif](https://transport.data.gouv.fr/datasets/zfe-m-voies-exceptionnelles), mais le format détecté (ou renseigné) est `a` et non `geojson`.
Sombre histoire, n'est-ce pas ?
Les nombreux tests existants devraient permettre d'assurer un fonctionnement correct.

Ajuste détection du format GeoJSON

---

apps/transport/lib/transport_web/templates/dataset/_dataset_type.html.eex
apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex

Fixes https://github.com/etalab/transport-site/issues/2093
- Ajout d'un lien vers la catégorie associée au jeu de données
- Ajout d'une seconde catégorie, "Transport public collectif - horaires temps réel", uniquement pour les JDD dans `public-transit` ayant des ressources avec du temps réel.

Dataset#details lien vers temps réel transport public

---

apps/transport/lib/db/resource_history.ex
apps/transport/lib/jobs/resource_history_job.ex
apps/transport/priv/repo/migrations/20220523132328_add_resource_history_resource_id.exs
apps/transport/test/transport/jobs/backfill/backill_metadata_validation_test.exs
apps/transport/test/transport/jobs/resource_history_job_test.exs

Lié à https://github.com/etalab/transport-site/issues/2410
Cette PR ajoute une colonne `resource_id` dans la table `resource_history`, dans le but moyen terme de supprimer `datagouv_id`.
Je fais une première PR pour éviter l'effet big bang et commencer dès maintenant à remplir cette nouvelle colonne.

Ajoute resource_id dans ResourceHistory

---

apps/transport/lib/transport_web/templates/dataset/details.html.eex

La section "Documentation" est dupliquée sur les jeux de données, voir https://transport.data.gouv.fr/datasets/evenements-routiers-sur-le-reseau-routier-national-non-concede/
Régression introduite dans https://github.com/etalab/transport-site/pull/2371, pas vu en review malheureusement !

Correction section documentation dupliquée sur dataset#details

---

apps/transport/lib/transport_web/controllers/resource_controller.ex

closes #2417, merci @AntoineAugusti d'avoir remarqué le problème grâce à ton suivi quotidien de la page de Dijon !
J'avais laissé un endroit où l'on allait lire les résultats de la validation V1 pour les GTFS alors que je pensais avoir tout débranché.
Ça s'est vu suite à la mise à jour du validateur GTFS

Incohérence de validation GTFS

---

apps/transport/lib/db/resource.ex
apps/transport/test/db/resource_test.exs

suite à https://github.com/etalab/transport-validator/pull/126 et https://github.com/etalab/transport-validator/pull/129
ça permet d'ajouter des petits tags dans la page détails de la ressource
et aussi de faire des recherches avec ce tag (feature secrète !)
J'ai mis description des correspondances pour la présence d'un fichier pathways.txt, je suis ouvert à la discussion ;)

Ajout de tags "couleurs des routes" et "description des correspondances"

---

apps/transport/lib/db/multi_validation.ex
apps/transport/lib/validators/gtfs_transport_validator.ex
apps/transport/priv/repo/migrations/20220601135310_change-multi-validation-field-name.exs
apps/transport/test/transport/validators/gtfs_transport_validator_test.exs

Grâce à https://github.com/etalab/transport-validator/pull/133, le validateur donne désormais sa version dans les métadonnées de sortie.
J'en profite pour remplir l'information dans la table `multi_validation`.
Je renomme le champ en `validator_version`, je n'avais initialement pas pensé que certains validateurs n'étaient pas appelés via transport-tools.

Ajout de la version du validateur GTFS dans la multi validation

---

apps/transport/client/javascripts/map-geojson.js

La route se met par dessus les autres quand on passe dessus avec la souris
Les popups des lignes et des arrêts contiennent toutes les informations disponibles, et pas seulement les noms
https://user-images.githubusercontent.com/15341118/174118624-b3d2623e-220f-4079-b87b-a4a8f7632c1e.mp4
closes #2450

Amélioration de la carte GTFS

---

apps/transport/lib/transport_web/templates/page/real_time.html.md

L'ancien portail va bientôt disparaitre.

Mise à jour lien API temps réel Air France

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/db/resource.ex
apps/transport/lib/jobs/geo_data/bnlc_to_geo_data.ex
apps/transport/test/transport/jobs/geo_data/bnlc_to_geodata_test.exs

Fixes https://github.com/etalab/transport-site/issues/2480
Le job ne s'exécutait plus suite à l'ajout d'une ressource communautaire sur le jeu de données.
Adapte le code du job pour ne conserver que les ressources "officielles".

Ignore ressources communautaires pour import BNLC

---

apps/transport/lib/transport_web/templates/dataset/details.html.eex

`#dataset-documentation` est pour le moment toujours dans le DOM, même s'il n'y a pas de ressources. Avec la classe `pt-48` ça fait un espace non nécessaire entre du contenu.
Cette PR répare ceci.

Ne pas toujours afficher la section dataset-documentation

---

apps/transport/lib/transport_web/templates/layout/app.html.eex

changement du nom piwik en Matomo.
Suite des erreurs HTML #2429

Update piwik -> Matomo

---

apps/transport/lib/opendatasoft/url_extractor.ex

- Classifie une URL contenant `trip-update` (sans S) comme un `gtfs-rt`
- Filtre (rejette) les URLs qui sont vides dans un CSV (survient [pour Occitanie](https://www.data.gouv.fr/fr/datasets/fichiers-gtfs-de-la-region-occitanie/))

Adaptation détection de contenu depuis ODS

---

apps/transport/lib/transport/data_checker.ex

Fixes https://github.com/etalab/transport-notifications/issues/17, en lien avec #2501.
Une adaptation du texte envoyé en tant qu'e-mail de rappel.

Mise à jour contenu rappel données expirées

---

README.md
apps/transport/lib/opendatasoft/url_extractor.ex
mix.exs

J'avais envie d'avoir une tâche unique qui permette de faire tourner tous les checks faits par le CI avant de pusher une branche et de faire des aller retours inutiles. Je n'ai pas mis dialyzer parce qu'honnêtement il ne trouve quasiment jamais rien et il prend du temps à tourner.
Usage : `mix check_all`

Nouvelle tâche : mix check_all

---

apps/transport/lib/db/resource.ex
apps/transport/lib/jobs/resource_unavailable_job.ex
apps/transport/lib/transport_web/templates/dataset/_community_ressource.html.eex
apps/transport/lib/transport_web/templates/dataset/_resource.html.eex
apps/transport/lib/transport_web/templates/resource/_validation_report.html.eex
apps/transport/lib/transport_web/templates/resource/details.html.eex
apps/transport/lib/transport_web/templates/resource/gtfs_details.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/test/db/resource_test.exs
apps/transport/test/transport/jobs/resource_unavailable_job_test.exs
apps/transport/test/transport_web/controllers/dataset_view_test.exs
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Fixes #2485 
- Déplace `download_url` de `DatasetView` vers `Resource` (et les tests associés)
- Utilise `download_url` au lieu de `url` dans le job en charge de vérifier la disponibilité des ressources
- Remplace `resource.url` par `download_url(@resource)` dans les templates lorsque pertinent

Utilisation URL pertinente pour vérifier la disponibilité

---

apps/transport/lib/transport/import_data.ex
apps/transport/test/transport/import_data_test.exs

Fixes https://github.com/etalab/transport-site/issues/2442
Utilise `resource.datagouv_id` lors de l'import de données pour assurer une meilleure stabilité des identifiants de ressources côté PAN.

Import de données : utilise datagouv_id

---

apps/shared/test/schemas_test.exs
apps/shared/test/support/cache_case.ex
apps/shared/test/validation/jsonschema_validator_test.exs

Suite de #2499, cette fonction était dans un module `.exs` qui n'est pas un endroit approprié. Je la déplace dans `Shared.CacheCase`

Move assert_cache_key_has_ttl

---

apps/shared/lib/gbfs_metadata.ex
apps/shared/test/gbfs_metadata_test.exs

On passe de 
à 
J'ai découvert l'existence de https://hexdocs.pm/ex_unit/ExUnit.CaptureLog.html qui permet justement d'attraper les logs et de ne pas les afficher dans la console, pratique.

Nettoyage des logs de test affichés pour Shared

---

apps/transport/lib/opendatasoft/url_extractor.ex
apps/transport/lib/transport/import_data.ex
apps/transport/test/transport/import_data_test.exs

La logique d'import est légèrement différente pour les ressources ODS : on ne peut les reconnaitre que grâce à leur URL. Il n'est pas possible de se fier au datagouv_id de la ressource, car plusieurs ressources peuvent partager le même dans le cas "ODS"'.
Cette PR traite explicitement la reconnaissance d'une ressource existante lors de l'import de manière différente pour le cas normal et la cas ODS.

Import : traitement plus explicite des ressources ODS

---

apps/gbfs/test/gbfs/controllers/jcdecaux_test.exs
apps/gbfs/test/gbfs/controllers/smoove_controller_test.exs
apps/gbfs/test/gbfs/controllers/vcub_controller_test.exs
apps/gbfs/test/gbfs/page_cache_test.exs

Nettoyage des logs de test affichés pour GBFS

---

apps/datagouvfr/lib/datagouvfr/client/api.ex
apps/datagouvfr/test/datagouvfr/client/community_resources_test.exs

Avant :
Après :
J'en profite pour corriger un bug : le message d'erreur disait qu'on appelait mal la fonction raise, et c'est ça qui faisait un raise :upside_down_face:

Nettoyage des logs de test affichés pour Datagouvfr

---

apps/shared/lib/schemas.ex
apps/transport/lib/jobs/resource_history_job.ex
apps/transport/test/transport/jobs/resource_history_job_test.exs
apps/transport/test/transport_web/controllers/validation_controller_test.exs

Fixes #2504
Cette PR stocke la dernière version publiée d'un schéma lorsqu'une ressource est historisée et qu'elle est associée à un schéma. Ceci est fait dans un champ distinct (`latest_schema_version_to_date`) de ce qui est renseigné dans la ressource, à savoir les champs `schema_(name|version)`.
Cette PR nécessite une adapation du module en charge de la gestion des schémas pour passer des fonctions relatives aux versions des schémas dans la partie Wrapper.

Historisation : stockage de la dernière version d'un schéma

---

apps/transport/mix.exs
apps/transport/test/build_test.exs

Voir #2520, je rétablis la possibilité de travailler avec Rambo en local sur Mac M1 (mon portable).
Avec les contraintes suivantes:
- ça s'appuie sur une PR non mergée dans le projet (mais je verrouille au commit) https://github.com/jayjun/rambo/pull/13
- il ne faut pas que je commite le fichier `mix.lock` car il sera différent
- il y a un bug qui fait que le wrapper Rust ne sera pas compilé si je ne fais pas à la main `mix compile.rambo` (avec éventuellement `MIX_ENV=test`) https://github.com/jayjun/rambo/pull/13#issuecomment-1189194040
Modulo cela, et on peut espérer que ça sera mergé à un moment, ça me permet de re-travailler en local avec des exécutions d'outils, et c'est plus que le bienvenu, vu que ça fait un moment que ça m'empêche de faire certains tests.
J'ajoute au passage un …

Workaround pour Rambo sur Mac M1

---

apps/transport/priv/gettext/fr/LC_MESSAGES/db-dataset.po
apps/transport/test/db/db_dataset_test.exs
apps/transport/test/transport/gtfs_rt_test.exs
apps/transport/test/transport/import_data_test.exs
apps/transport/test/transport/jobs/gtfs_rt_entities_test.exs
apps/transport/test/transport/jobs/gtfs_rt_validation_job_test.exs
apps/transport/test/transport_web/controllers/backoffice/backoffice_controller_test.exs

C'est presque de l'art
J'ai eu des erreurs intermittentes pendant les tests, avec la base de donnée qui n'arrivait pas à suivre le rythme des tests. J'ai l'impression que de ne pas afficher tous ces logs dans la console fait tourner les tests un peu plus vite et que ça peut faire tirer la langue à la base. On va voir si ça se reproduit...

 Nettoyage des logs de test affichés pour Transport :broom: 

---

apps/transport/lib/transport_web/live/backoffice/proxy_config_live.ex
apps/transport/lib/transport_web/live/backoffice/proxy_config_live.html.leex
apps/transport/test/support/live_case.ex
apps/transport/test/transport_web/live_views/gbfs_live_test.exs
apps/transport/test/transport_web/live_views/proxy_config_live_test.exs

Le déploiement de #2459 a créé une petite régression dans le backoffice du proxy, car les éléments de configuration SIRI n'étaient pas intégrés.
Je répare ici et j'ajoute des tests.

Correctif pour le backoffice du proxy

---

apps/transport/lib/transport_web/templates/dataset/_resource_validation_summary.html.heex

Suite à #2532, on a des erreurs 500 sur les pages dataset GBFS, remontées par Sentry.

Réparer les pages des GBFS

---

apps/transport/lib/transport_web/controllers/resource_controller.ex
apps/transport/lib/transport_web/templates/dataset/_resource.html.eex
apps/transport/lib/transport_web/templates/dataset/_resource_validation_summary.html.heex
apps/transport/lib/transport_web/templates/resource/_validation_report.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/lib/transport_web/views/resource_view.ex
apps/transport/test/transport_web/controllers/dataset_controller_test.exs
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Certaines validations se passent mal, et se retrouvent en base avec %{"validation_performed" => false}.
Ce cas n'était pas bien géré pour la page dataset et la page ressource.
Je fais un quick fix, il y aura peut-être moyen de faire mieux par la suite.
Bug introduit par #2532 
[Sentry](https://sentry.io/organizations/transport-data-gouv-fr/issues/3452697255/?environment=prod&project=6197733)

Gestion des validations en performed => false

---

apps/transport/lib/transport_web/templates/dataset/_resources_container.html.eex
apps/transport/lib/transport_web/templates/dataset/_reuser_message.html.eex
apps/transport/lib/transport_web/templates/dataset/details.html.eex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot

Fixes https://github.com/etalab/transport-site/issues/2449
Affiche tout le temps, pour tous les types de données, la section "Documentation" pour inciter les producteurs à publier des ressources de documentation : charte graphique, documents etc.
Je mets un lien vers cette doc https://doc.data.gouv.fr/jeux-de-donnees/publier-un-jeu-de-donnees/#type, à voir si @etalab/transport-bizdev

Section Documentation : affichage incitation à la publication

---

apps/transport/lib/transport_web/templates/dataset/_history_message.html.eex
apps/transport/lib/transport_web/templates/dataset/_resources_container.html.eex
apps/transport/lib/transport_web/templates/dataset/details.html.eex

Fixes #2355
Affiche la mention
> Les versions précédentes des ressources de ce jeu de données sont disponibles dans la section Ressources historisées.
sur toutes les pages d'un jeu de données dès lors que des ressources ont été historisées.
Dans le passé c'était limité aux GTFS et affiché en bas du bloc GTFS. Désormais ce sera après la dernière section présentant des ressources (et avant la section Documentation).

Affiche lien vers ressources historisées dans plus de cas

---

apps/transport/lib/db/resource.ex

Fixes #2569
Pour une raison inconnue, la casse n'était pas bonne dans ce fichier, le L est en minuscule. Partout ailleurs c'est en majuscule.

Répare détection du format SIRI Lite

---

apps/transport/lib/transport_web/templates/dataset/_community_resources.html.eex
apps/transport/lib/transport_web/templates/dataset/details.html.heex

Création d'une sections "Ressources communautaires" dans la liste déroulante à gauche des jeux de données
https://github.com/etalab/transport-site/issues/2559
seconde pr car erreur avec mix dialyzer
première pr :  #2560

Ajout lien nav "ressources communautaires"

---

apps/transport/mix.exs

Suite à #2587 , il faut ajouter explicitement la dépendance à ymlr (voir https://github.com/open-api-spex/open_api_spex/commit/338434a888c3e8ac037f6c36520a13b4d32e6c87)

Ajout explicite de la dépendance ymlr

---

apps/transport/lib/transport/import_data.ex
apps/transport/test/transport/import_data_test.exs

Suite aux changements apportés dans https://github.com/etalab/transport-site/pull/2595, supprime ce qui avait été fait dans #2260.
Pour la catégorie des ZFE, si des ressources n'ont pas de schéma, elles seront moins en évidence.

ImportData : ne pas filtrer ressources pour les ZFE

---

apps/transport/lib/db/multi_validation.ex
apps/transport/lib/transport_web/templates/dataset/_resource.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/test/db/multi_validation_test.exs

Ces dates là
étaient prises dans resource.metadata, mais on veut qu'elles viennent des metadatas associées à la dernière multi_validation.

Ne plus utiliser resource.metadata, 1/X

---

apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/lib/db/resource.ex
apps/transport/lib/transport_web/templates/dataset/_resource.html.eex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/lib/validators/gtfs_transport_validator.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot

Je continue à enlever du code qui utilise resource.metadata dans la page de détail d'un dataset.
Il en reste...

Ne plus utiliser resource.metadata, 3/X 

---

apps/transport/lib/transport_web/templates/dataset/details.html.heex

Répare un bug introduit dans https://github.com/etalab/transport-site/pull/2616, les templates HEEX ne passent pas dans `render_many`.
J'imagine qu'on a pas de tests qui renvoient des discussions (seulement des listes vides ?).

Fix discussions sur dataset suite conversion HEEX

---

apps/transport/lib/transport_web/templates/dataset/_community_resources.html.heex

Similaire à https://github.com/etalab/transport-site/pull/2618
Cette fois j'ai fait une autre recherche, vérifier l'absence de `render_many` pour du HEEX

Fix render many

---

apps/transport/lib/db/dataset.ex
apps/transport/test/transport_web/controllers/dataset_search_test.exs

Lié à https://github.com/etalab/transport-site/issues/2621
Ajoute la possibilité de filter les jeux de données en fonction de leur licence.
Ainsi `https://transport.data.gouv.fr/datasets?licence=licence-ouverte` donnera les jeux de données ayant comme licence la licence ouverte.

Filtre les datasets par licence par le biais de l'URL

---

apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
apps/transport/lib/transport_web/api/schemas.ex
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

Fixes #2622, similaire à la demande dans #2621 : identifier des jeux de données publiés avec une licence spécifique.
Étonné qu'on n'expose pas ce champ encore !

Ajout champ licence pour dataset dans l'API

---

apps/transport/test/transport/jobs/resource_history_job_test.exs

Répare un test qui échoue de temps en temps, [comme ici](https://app.circleci.com/pipelines/github/etalab/transport-site/5226/workflows/1f6f7cdd-3adc-455f-93fa-b896ecbbc6f5/jobs/38389).
```
1) test ResourceHistoryDispatcherJob a simple successful case (Transport.Test.Transport.Jobs.ResourceHistoryJobTest)
apps/transport/test/transport/jobs/resource_history_job_test.exs:31
Assertion with == failed
code:  assert [second_id, first_id] == ids
left:  [133, 125]
right: [125, 133]
stacktrace:
test/transport/jobs/resource_history_job_test.exs:40: (test)
```

Répare un test instable

---

apps/transport/lib/transport_web/live/backoffice/gbfs_live.ex
apps/transport/lib/transport_web/live/backoffice/gbfs_live.html.heex
apps/transport/lib/transport_web/live/backoffice/jobs_live.html.heex
apps/transport/lib/transport_web/live/backoffice/proxy_config_live.ex
apps/transport/lib/transport_web/live/backoffice/proxy_config_live.html.heex
apps/transport/lib/transport_web/live/on_demand_validation_live.ex
apps/transport/lib/transport_web/live/on_demand_validation_live.html.heex
apps/transport/lib/transport_web/live/on_demand_validation_select_live.html.heex

En travaillant sur #2556, je me suis rendu compte (en voulant faire un copier coller de lien vers `js/app.js`) que les différents travaux sur #2538 ont introduit des liens bizarrement formatés (mais qui marchent peut-être quand même).
Du coup dans cette PR :
- Je traite #2402
- Je corrige ces liens formatés curieusement
~~Ce n'est pas finalisé~~ (c'est OK à présent), je voudrais vérifier que je ne casse rien (il y a des `@conn` versus des `@socket` selon les endroits). 
Pour vérifier cela, je me suis demandé si le coverage pourrait détecter quels templates HEEX sont exécutés par les tests (car ces templates sont compilés en fonctions, et au final à terme on devrait pouvoir les voir apparaître dans les rapports de couverture), toutefois j'ai l'impression que ce n'est pas supporté (j'ai …

Nettoyage de liens "/js/app.js"

---

apps/shared/lib/gbfs_metadata.ex
apps/shared/test/gbfs_metadata_test.exs
apps/transport/lib/transport_web/templates/gbfs_analyzer/index.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/gbfs_analyzer.po
apps/transport/priv/gettext/fr/LC_MESSAGES/gbfs_analyzer.po
apps/transport/priv/gettext/gbfs_analyzer.pot
apps/transport/test/transport/jobs/gbfs_multi_validation_job_test.exs
apps/transport/test/transport/validators/gbfs_validator_test.exs

Le rapport actuel mettait "CORS autorisé" si on a * ou "transport.data.gouv.fr", mais les gens qui utilisent le validateur veulent à priori juste savoir si eux peuvent faire des requetes Cross Origin.
Du coup je propose d'afficher le header brut et des laisser tirer leurs conclusions.

Afficher les headers CORS bruts pour la validation GBFS

---

scripts/irve/.gitignore
scripts/irve/irve.exs
scripts/irve/req_custom_cache.exs

En préparant les ateliers IRVE avec @ChristinaLaumond, il nous vient pas mal de questions concrètes sur les données statiques, et on sent bien qu'on va devoir aller comprendre les fichiers sources et les profiler.
Je prépare le terrain en reprenant le principe général de la consolidation (https://github.com/etalab/notebooks/blob/master/irve-v2/consolidation-irve-v2.ipynb) dans un script Elixir, mais sans implémenter une consolidation complète (puisqu'on a acté le principe d'essayer de rester sur la consolidation Python tant que ça suffit et que les besoins ne divergent pas).
Ca pourra servir de base de consolidation v2 si on veut, mais ce n'est pas l'objectif poursuivi pour l'instant.
J'ai pu faire quelque chose d'assez efficient (installation très simple, cache local, rapide), et ça va …

Début de script d'exploitation des IRVE (avant consolidation)

---

apps/transport/lib/transport_web/templates/dataset/_discussion.html.heex

Bug introduit dans https://github.com/etalab/transport-site/pull/2616
L'espace à la fin de `id` empêche le lien de se faire entre l'ancre et le div, permettant l'apparition du formulaire de réponse au clic sur le lien.

Répare identifiant de div pour commentaire sur dataset

---

apps/transport/lib/transport_web/templates/dataset/details.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot

En lien avec https://github.com/etalab/transport-site/issues/2588
- Affiche les 25 dernières ressources historisées
- Ajoute un `rel="nofollow"` pour les liens vers Cellar (peut-être que des robots tentent d'indexer ça et consomment notre bande passante ?!?)

Affiche un message quand on affiche le max de ressources historisées

---

apps/transport/lib/transport_web/templates/resource/_gtfs_rt.html.heex

Retravaille ce qui avait été fait dans https://github.com/etalab/transport-site/pull/2610
La bannière n'est pas suffisamment visible, voir par exemple pour [Bourges](https://transport.data.gouv.fr/resources/79180) actuellement : la bannière n'est affichée que si on clique sur le flux GTFS-RT décodé.

Déplace bannière flux GTFS-RT avec timestamp trop ancien

---

apps/transport/lib/transport_web/plugs/custom_secure_browser_headers.ex

La variable d'environnement vaut `:production` et non pas `:prod`, merci @AntoineAugusti

Correction CSP headers en prod

---

apps/transport/lib/db/resource.ex
apps/transport/test/db/resource_test.exs

Fixes #2656
Relaxe un peu cette règle pour mettre le tag "couleurs des lignes" si >=80% des lignes ont une couleur renseignée.

Tag couleurs des lignes si >= 80%

---

apps/transport/client/javascripts/map-geojson.js
apps/transport/client/javascripts/map.js
apps/transport/client/javascripts/resource-viz.js
apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/client/stylesheets/components/_map-js.scss
apps/transport/test/no_css_inline_style_test.exs

Il en restait dans les fichiers js, pour les légendes de la carte stats et dans le style des popups (carte stats et cartes des GBFS).
J'ai mis à jour le test correspondant (et j'ai changé son nom, car il faut que le nom du fichier se termine par `_test` pour être reconnu comme tel).

Enlever le css inline résiduel

---

apps/transport/lib/transport_web/plugs/custom_secure_browser_headers.ex

Sentry rapport des erreurs de navigateurs qui essaient de télécharger des fonts depuis diverses origines, pour le moment j'autorise tout.
On ne peut pas vraiment restreindre `connect-src`, parce que le site essaie d'affficher une carte dès qu'il voit une ressource geojson, et que ces geojsons peuvent être hébergés sur n'importe quel site d'open data.

CSP : autorise tout pour font-src et connect-src

---

apps/transport/lib/transport/import_data.ex

Fixes #2670
Ajuste la logique de détection des NeTEx pour regarder le format, l'URL, la description, le titre du fichier, comme ce qui est fait pour les GTFS.

Ajuste logique détection NeTEx

---

apps/transport/lib/transport_web/live/on_demand_validation_select_live.ex
apps/transport/lib/transport_web/live/on_demand_validation_select_live.html.heex
apps/transport/test/transport_web/controllers/validation_controller_test.exs

Fixes #2678 
Utilise [`phx-trigger-action`](https://hexdocs.pm/phoenix_live_view/form-bindings.html#submitting-the-form-action-over-http) pour envoyer le formulaire.
Envoie le formulaire dès lors qu'on sélectionne un fichier (le champ qui a changé est disponible dans [`_target`](https://hexdocs.pm/phoenix_live_view/form-bindings.html#javascript-client-specifics))
J'ai tenté de suivre l'exemple donné dans la documentation, avec un event `phx-submit` qui ensuite trigger `phx-trigger-action` sans succès, dommage.

Validation à la demande : submit avec phx-trigger-action

---

apps/transport/lib/transport_web/templates/resource/_resources_details.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot

En lien avec #2581 
Ajout d'un lien vers [notre doc](https://doc.transport.data.gouv.fr/producteurs/operateurs-de-transport-regulier-de-personnes/mise-en-qualite-des-donnees-gtfs) pour les données possibles à modéliser en GTFS.

Données possibles à modéliser en GTFS : lien vers doc

---

apps/transport/lib/transport_web/live/gtfs_diff_select_live.html.heex

Les subtilités de liveview, quand un utilisateur clique sur "download", ça se fait dans la même page et du coup ça réinitialise toute la liveview. En ajout target="_blank" ça évite le problème.

Ajout de target: _blank

---

apps/transport/lib/transport_web/live/on_demand_validation_select_live.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/validations.pot

Suite de https://github.com/etalab/transport-site/pull/2679
Supprime le bouton submit "Valider" lors de l'envoi de fichiers. En effet, si après avoir choisi un fichier l'utilisateur clique sur ce bouton, il obtiendra une erreur 400. Ce comportement a été reporté par e-mail.
Cette PR supprime donc ce bouton dans ce cas, et ajoute une indication comme quoi l'upload est en cours.
https://user-images.githubusercontent.com/295709/193998089-755d36c9-4afd-464a-93c4-0c03855baeeb.mov

Validation à la demande : pas de submit pour fichiers

---

apps/transport/lib/mix/tasks/transport/import_communes.ex
apps/transport/priv/repo/migrations/20221004135750_enable_trigger_refresh_places_commune_trigger.exs

Un erreur dans https://github.com/etalab/transport-site/pull/2665, un trigger n'avait pas été activé à la fin de l'import.
Je ne pense pas que ça crée de problème, surtout que la tache force la mise à jour à la fin et que la table `commune` n'a pas changé depuis.

Import communes : enable trigger ne doit pas désactiver un trigger

---

apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/test/transport_web/controllers/dataset_search_test.exs

Il n'y avait pas de garde fous dans les requêtes du moteur de recherche pour éviter la présence de résultats dupliqués.
Je rajoute des `distinct` et je mets à jour un test.

Suppression des résultats dupliqués dans le moteur de recherche

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/jobs/gtfs_rt_entities.ex
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/controllers/resource_controller.ex
apps/transport/lib/transport_web/templates/dataset/_resource.html.heex
apps/transport/lib/transport_web/templates/resource/details.html.heex
apps/transport/test/transport_web/controllers/dataset_controller_test.exs
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Dans la suite de #2683 
Maintenant que les gtfs_rt_entities sont sauvegardées proprement en base dans la table `resource_metadata`, je débranche les pages datasets et resources qui allaient encore lire dans les champs de la table `resource` directement, pour les brancher aux `resources_metadata`. Ca se fait plus facilement que ce que je craignais :relieved: 
Reste à faire :

Pages ressources et datasets : brancher les flux gtfs sur resource_metadata

---

apps/transport/lib/transport_web/views/dataset_view.ex

Les liens de pagination sont actuellement mauvais quand il y a un filtre en place avec une AOM ou une région, les filtres passés en query params ne sont pas conservés.
Ainsi https://transport.data.gouv.fr/datasets/region/2?q=auvergne (qui contient un `?q`), est perdu dans les liens vers les autres pages en bas de page. Ceci se retrouve aussi avec `features` / `modes` etc.
Cette PR répare ceci. J'ai l'impression de refaire ce qui existe dans [pagination_helper](https://github.com/etalab/transport-site/blob/master/apps/transport/lib/transport_web/controllers/pagination_helpers.ex) mais j'ai pas réussi à réutiliser du code, si vous voyez une opportunité.

Répare pagination quand filtré par AOM ou Région

---

apps/transport/lib/transport/import_data.ex

Suite à https://github.com/etalab/transport-site/pull/2696, certaines ressources GTFS ont vu leur format indiqué comme `gtfs-rt` par erreur.
Cette PR robustifie à nouveau la détection de formats.
Voir [Sentry](https://sentry.io/organizations/transport-data-gouv-fr/issues/3661173939/?environment=prod&project=6197733&query=is%3Aunresolved), [Mattermost](https://mattermost.incubateur.net/betagouv/pl/b37b1tps3jgh3cqn5wyziurcxc)

Meilleure détection GTFS / GTFS-RT

---

apps/transport/lib/jobs/remove_history_job.ex
apps/transport/test/transport/jobs/remove_history_job_test.exs

Retravaille https://github.com/etalab/transport-site/pull/2700 pour effectuer la suppression en 2 temps :
- indiquer ce qui doit être supprimé
- lancer des jobs de suppression, qui tournent au fur et à mesure de manière récursive
Le problème est qu'en production certains jobs passent en timeout, car il y a des milliers d'objets à supprimer pour certains JDD.
```sql
select *
from resource_history
where payload ? 'mark_for_deletion'
```
retourne 12k lignes actuellement, montrant le nombre important de lignes à supprimer en BDD, mais surtout sur Cellar.
|dataset_id|count|
|--- | ---|
|752 | 2876|
|508 | 2031|
|567 | 1899|
|751 | 1439|
|131 | 1356|
|231 | 1356|
|759 | 661|
|250 | 584|

RemoveHistoryJob : suppression en 2 temps

---

apps/transport/lib/db/resource_metadata.ex
apps/transport/lib/transport/stats_handler.ex
apps/transport/test/transport/stats_handler_test.exs

Retravaille le stockage de statistiques de flux GTFS-RT, qui avait été effectué dans https://github.com/etalab/transport-site/pull/2352, pour utiliser désormais `DB.ResourceMetadata.features` comme introduit dans https://github.com/etalab/transport-site/pull/2683

Adapte stockage stats pour GTFS-RT

---

apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/lib/transport_web/templates/dataset/_resource.html.heex
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

Suite de #2693
Compte les types de flux GTFS-RT par ressource, et non par dataset. Évite d'afficher l'ensemble des différents flux pour toutes les ressources d'un dataset.

Compte les entités GTFS-RT par ressource

---

apps/transport/lib/transport_web/controllers/page_controller.ex
apps/transport/lib/transport_web/templates/stats/index.html.heex
apps/transport/test/support/database_case.ex
apps/transport/test/transport_web/controllers/stats_controller_test.exs

Le format des stats a changé suite à #2706, ce qui fait crasher la page. [Voir Sentry](https://sentry.io/organizations/transport-data-gouv-fr/issues/3665664039/?environment=prod&project=6197733&query=is%3Aunresolved#exception).
Je répare et j'ajoute un test basique pour charger la page `/stats`.

Page stats : répare affichage stats flux GTFS-RT

---

apps/transport/lib/transport_web/live/gtfs_beta_diff.ex
apps/transport/lib/transport_web/live/gtfs_diff_select_live.ex

* augmentation de la taille max des GTFS à 4Mo
* avoir un mode fallback quand un fichier est trouvé dans une archive et pour lequelle on n'a pas renseigné de primary key => pas de diff, toute modification de ligne revient à supprimer + ajouter la ligne.
* bug : quand une nouvelle colonne est ajoutée dans un fichier, on ne détectait pas la modification des lignes modifiées
* plus explicite : quand on fichier est ajouté, on liste les headers de ce fichier en tant que créations de colonnes.
Pour l'instant le code n'est pas testé, j'attendais de voir si on avait beaucoup de retours sur le format et qu'il risquait de changer ou pas.

Gtfs diff : quelques fix et améliorations

---

apps/transport/lib/transport_web/controllers/page_controller.ex
apps/transport/lib/transport_web/templates/page/index.html.heex

On avait des chiffres mis directement dans la vue auparavant, ceux-ci ne sont plus bons suite à l'import des AOMs millésime 2022.

Page d'accueil : compter régions et AOMs

---

apps/transport/lib/jobs/gtfs_rt_entities.ex
apps/transport/test/transport/jobs/gtfs_rt_entities_test.exs

Depuis que ceci est stocké dans `DB.ResourceMetadata` dans https://github.com/etalab/transport-site/pull/2693 et que le code a été adapté, on peut supprimer cette partie.

GTFSRTEntitiesJob : ne plus stocker dans resource.metadata

---

apps/transport/lib/jobs/new_dataset_job.ex
apps/transport/lib/transport/data_checker.ex
apps/transport/lib/transport/notifications.ex
apps/transport/lib/transport_web/controllers/backoffice/dataset_controller.ex
apps/transport/test/transport/data_checker_test.exs
apps/transport/test/transport/jobs/consolidate_lez_job_test.exs
apps/transport/test/transport/jobs/new_dataset_job_test.exs
apps/transport/test/transport/notifications_test.exs
apps/transport/test/transport_web/controllers/backoffice/backoffice_controller_test.exs
config/notifications-config.sample.yml

Retravaille les notifications pour ajouter un motif permettant d'avoir une liste d'adresses e-mails intéressées par l'ajout de jeux de données.
Envoie ces notifications lorsqu'un jeu de données est ajouté depuis le backoffice.

Envoi de notifications lors de l'ajout d'un jeu de données

---

apps/shared/lib/date_time_display.ex

See [Sentry issue](https://sentry.io/organizations/transport-data-gouv-fr/issues/3706252664/?environment=prod&project=6197733&query=is%3Aunresolved&referrer=issue-stream)
On this fine Sunday morning, I had a chance to discover and read the [Timex.AmbiguousDateTime](https://hexdocs.pm/timex/Timex.AmbiguousDateTime.html) page.
Discovered because at 3am in Europe/Paris, we went back to 2am today.
```elixir
"2022-10-30T02:03:54.322000" |> Timex.parse!("{ISO:Extended}") |> Timex.Timezone.convert("Europe/Paris")
#<Ambiguous(#DateTime<2022-10-30 02:03:54.322000+02:00 CEST Europe/Paris> ~ #DateTime<2022-10-30 02:03:54.322000+01:00 CET Europe/Paris>)>
```
This is documented as [Ambiguity #2 - Times with more than one valid timezone](https://hexdocs.pm/timex/Timex.AmbiguousDateTime.html#module-ambig …

Handle AmbiguousDateTime for convert_to_paris_time

---

apps/transport/lib/transport/data_checker.ex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/test/transport/data_checker_test.exs
apps/transport/test/transport_web/views/error_view_test.exs
config/config.exs

Petite amélioration suite à https://github.com/etalab/transport-site/pull/2740
- Tri par catégorie de données
- Utilisation du titre du PAN et non de data.gouv.fr
- Ajout du type de données dans l'e-mail
cc @cyrilmorin

Nouveaux JDD : ajout catégorie de données, titre custom

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/transport/data_checker.ex
apps/transport/test/transport/data_checker_test.exs

Retravaille la méthode utilisée pour trouver les jeux de données avec un GTFS expirant à une date précise pour utiliser la multi-validation et `DB.ResourceMetadata`.

Utilise la multi-validation pour GTFS expirant à une date

---

apps/transport/lib/jobs/consolidate_lez_job.ex
apps/transport/priv/zfe_ids.csv
apps/transport/test/transport/jobs/consolidate_lez_job_test.exs

Diverses améliorations liées à la consolidation ZFE :
- oubli d'une clause `limit`, qui pose problème si une resource a plusieurs historisation + validation sans erreurs (on a alors plusieurs résultats sans `limit`)
- données de ZFE manquantes pour Toulouse (le [JDD](https://transport.data.gouv.fr/datasets/perimetre-zone-a-faibles-emissions-mobilite-zfem) n'est plus rattaché à l'AOM de Toulouse et l'entité principale de la ZFE n'est pas Toulouse Métropole)

Améliorations consolidation ZFE

---

apps/transport/lib/siri_queries.ex
apps/transport/test/transport/siri_queries_test.exs
mix.exs
mix.lock

Pour préparer mon travail sur :
- #2741 (la partie requête "à paramètres" en particulier)
je modifie dans cette PR la façon de générer les requêtes SIRI, pour ne plus utiliser une interpolation de chaîne, et à la place nous appuyer sur l'API de `Saxy`. Le but premier est d'éviter de risquer de former du XML mal formé lorsqu'on va injecter des éléments saisis par un utilisateur extérieur.
J'ai mis par ailleurs le générateur de requêtes sous tests, pour me faciliter ce refactoring, et faciliter les suivants (ex: mise en commun d'éléments partagés, ou correctifs).
Au passage j'ai corrigé quelques points dans les templates:
- suppression de références à "IDF" dans les requêtes
- suppression de namespaces non nécessaires
Je partirai de cette branche pour travailler sur la deuxième itération du …

Construction des requêtes SIRI par "XML builder"

---

apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
scripts/api_datasets_check.exs

Voir:
- #2752
Je supprime une partie de la donnée sortante côté API qui pose problème, car je n'ai pas pour l'instant le temps matériel pour investiguer correctement.
Cela permet de corriger les nombreux appels en 500 (26% de datasets) sur l'API, en attendant mieux.
:warning: Je vais déployer directement sur la production sans merger. Il sera préférable de remplacer cela par un correctif propre lundi !

Fix temporaire et incomplet pour #2752

---

apps/transport/lib/db/resource_history.ex
apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
apps/transport/test/transport_web/controllers/api/datasets_controller_test.exs

J'ai réécrit certains passages du controller dataset de l'API.
La différence principale, c'est que je m'appuie sur des proloads nestés, ce qui simplifie la gestion des données de validation.
J'ai essayé de jouer avec les requêtes génériques pour les assouplir et permettre de faire des left joins, mais je n'ai pas réussi !
On pourra en discuter si vous avez des idées. Mais si j'utilise des lateral_join, je ne sais faire que du join `inner`. Si je join sur des subqueries, je ne peux plus preloader, car on ne peut pas preloader quelque chose qui vient d'une subquery.
Du coup je m'en suis tenu à revoir le code du controller et à rajouter un test qui échouait avant cette PR.

Refacto dataset controller de l'API

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/db/resource.ex
apps/transport/lib/transport_web/templates/resource/_validate_gtfs_rt_now.html.heex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Suppression/refactor de quelques méthodes utilisant les métadonnées stockées directement dans les ressources.
J'en profite pour afficher un message explicite d'erreur pour les ressources GTFS-RT quand on ne peut pas déterminer automatiquement quel fichier GTFS utiliser.

Suppression méthodes utilisant métadonnées des ressources

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/jobs/dataset_now_licence_ouverte_job.ex
apps/transport/lib/transport/notifications.ex
apps/transport/test/db/db_dataset_test.exs
apps/transport/test/transport/jobs/dataset_now_licence_ouverte_job_test.exs
apps/transport/test/transport/notifications_test.exs
config/notifications-config.sample.yml

Similaire à #2740
Cette PR regarde quand un jeu de données est modifié, détecte quand on passe d'une licence non LO à LO puis envoi un e-mail en utilisant le système de notifications. On introduit une nouvelle raison de notifications `:dataset_now_licence_ouverte`.

Envoi d'e-mails lorsqu'un jeu de données passe en licence ouverte

---

apps/transport/lib/jobs/workflow.ex
config/runtime.exs

Pour l'instant les workflow sont dans la queue par défaut, qui est limitée à 2 jobs à la fois.
Donc si 2 workflow sont traités, ils bloquent la queue, et plus aucun autre job ne peut tourner, ce qui empeche le workflow de finir...embouteillage garanti.
Merci @AntoineAugusti d'avoir repéré l'embouteillage !

workflow : queue dédiée

---

apps/transport/lib/transport/import_data.ex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/priv/gettext/dataset.pot
apps/transport/priv/gettext/en/LC_MESSAGES/dataset.po
apps/transport/priv/gettext/fr/LC_MESSAGES/dataset.po
apps/transport/priv/repo/migrations/20221110101806_rename_mobility_license.exs
apps/transport/test/db/db_dataset_test.exs

Fixes #2765
On retrouve encore quelques occurences de "license" mais qui ont leur place
- `license` dans les réponses de l'API data.gouv.fr pour les JDD
- "ODbL license" qui correspond à l'appelation officielle

Mobility License to Mobility Licence

---

apps/transport/lib/jobs/resource_unavailable_job.ex

Ajoute un paramètre `unique` pour ce job pour éviter un blast de jobs dans le cas où Oban a été congestionné.
Je mets à 9 minutes car ça peut être exécuté toutes les 10 minutes.
https://github.com/etalab/transport-site/blob/ec61255fd3ac4c3cf1bdfe993969d35847427f02/config/runtime.exs#L106
[`Oban.insert_all` ne regarde pas le `unique`](https://github.com/etalab/transport-site/pull/2773), je passe donc à `Oban.insert!`

Ajout unique pour ResourceUnavailableJob

---

.circleci/config.yml
.tool-versions
Dockerfile
Dockerfile.dev

Voir:
- https://github.com/etalab/transport-ops/releases/tag/elixir-1.14.1-erlang-24.3.4.6-ubuntu-focal-20211006-transport-tools-1.0.5
Désolé au passage pour @AntoineAugusti chez qui je sais que ça rame particulièrement pour la partie compilation Erlang, mais j'avais déjà commis ma boulette.

Mise à jour transport-tools (couleurs), Elixir et Erlang (mineures)

---

apps/transport/lib/transport_web/templates/dataset/details.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot

Fixes #2772
Remplace "Producteur de la donnée" par "Données publiées par".

Adapte label producteur de la donnée

---

apps/transport/lib/jobs/backfill/backfill_data_conversion_netex_filesize.ex
apps/transport/lib/jobs/gtfs_generic_converter.ex
apps/transport/test/transport/jobs/backfill/backfill_data_conversion_netex_filesize_test.exs
apps/transport/test/transport/jobs/single_gtfs_to_geojson_converter_job_test.exs
apps/transport/test/transport/jobs/single_gtfs_to_netex_converter_job_test.exs

Fixes #2134
- Répare le calcul de la taille du fichier dans le job
- Ajoute un job de backfill
Lancer le job de backfill avec
```elixir
import Ecto.Query
id = (from dc in DB.DataConversion, where: dc.convert_from == "GTFS" and dc.convert_to == "NeTEx", select: min(dc.id)) |> DB.Repo.one!()
%{"data_conversion_id" => id, "backfill" => true} |> Transport.Jobs.Backfill.DataConversionNeTExFilesize.new() |> Oban.insert!()
```

Correction de la taille des fichiers des conversions GTFS > NeTEx

---

apps/transport/lib/transport_web/templates/resource/_invalid_shape_id_issue.html.heex
apps/transport/lib/transport_web/templates/resource/_speed_issue.html.heex
apps/transport/lib/transport_web/templates/resource/_unused_shape_issue.html.heex
apps/transport/lib/transport_web/views/resource_view.ex
apps/transport/lib/validators/gtfs_transport_validator.ex
apps/transport/priv/gettext/en/LC_MESSAGES/gtfs-transport-validator.po
apps/transport/priv/gettext/en/LC_MESSAGES/validations-explanations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/gtfs-transport-validator.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations-explanations.po
apps/transport/priv/gettext/gtfs-transport-validator.pot
apps/transport/priv/gettext/validations-explanations.pot

closes #2548 
Fait suite à https://github.com/etalab/transport-validator/pull/148
Cette PR rajoute le code qui permet d'afficher joliment ces 2 nouvelles issues
remarque : la colonne détails va être remplie grâce à https://github.com/etalab/transport-validator/pull/149

Prise en compte de 2 nouvelles issues du validateur

---

apps/transport/lib/db/resource.ex
apps/transport/lib/db/resource_metadata.ex
apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
apps/transport/test/transport_web/controllers/api/datasets_controller_test.exs

Suite à la demande de l'ART de rajouter cette information à notre API. 
Je ne suis pas particulièrement content du code que je trouve trop compliqué. C'est le même que la dernière fois.
Le problème ici étant que les métadonnées des gtfs-rt sont directement rattachées aux ressources, et non pas à des resource history. De plus il faut observer plusieurs métadonnées de la ressource pour aggréger les entités vues au cours des 7 derniers jours, ce qui rajoutte de la complexité.
J'ai rajouté un test pour me rassurer.

Ajouter les entités gtfs-rt dans l'API en tant que features

---

apps/transport/lib/transport_web/templates/resource/_resources_details.html.heex
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Petit bug introduit dans #2785, le cas `nil` n'est pas géré correctement et cause [quelques exceptions](https://sentry.io/organizations/transport-data-gouv-fr/issues/3747513153/activity/?project=6197733)

Gère nil pour networks_start_end_dates

---

apps/transport/client/stylesheets/home.scss
apps/transport/lib/transport_web/templates/page/index.html.heex

Ajout du lien vers la documentation spécifique dans la partie "Données à venir"
Image (au hover)

Lien vers la doc du schéma de comptage des mobilités

---

apps/transport/lib/transport/import_data.ex

L'import de ce [dataset](https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs) échouait à cause d'une sombre histoire de cas `nil` non géré. Je connais des gens qui diraient que ça ne serait jamais arrivé en R**t.
Voir les problèmes d'import [ici](https://transport.data.gouv.fr/backoffice/datasets/38/edit#imports_history).

Réparation de l'import du dataset 38 (cityway)

---

apps/transport/lib/transport/data_checker.ex
apps/transport/lib/transport/import_data.ex

Pour le moment, si un dataset est moissoné sur ODS ET que l'identifiant de ce dataset sur ODS contient un nom de format, par exemple "gtfs-rt", cette chaine de caractère se retrouve dans l'url de la ressource. En conséquence, transport se trompe et essaye d'importer une ressource ODS de type json ou csv en tant que ressource non ODS et cela fait échouer l'import.
C'est ce qui nous arrive avec https://transport.data.gouv.fr/datasets/gtfs-et-gtfs-rt-reseau-tao-2022-orleans-metropole
Je rajoute donc une protection du pauvre en vérifiant le nom du fichier pour détecter ce cas.

fix import tordu ODS

---

apps/transport/lib/transport/import_data.ex
apps/transport/test/transport/import_data_test.exs

Adapte l'import de données pour détecter des ressources de documentation pour le type `public-transit` qui ne retient que certains types de ressources.
Le premier cas d'usage est [pour le JDD de Lille](https://www.data.gouv.fr/fr/datasets/localisation-des-arrets-ilevia-bus-metro-et-tram-gtfs-pictogrammes-du-reseau-ilevia/) qui comporte un PDF avec des logos sur datagouv et pas sur le PAN.

ImportData: détection de documentation pour public-transit

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/db/resource.ex
apps/transport/test/db/db_dataset_test.exs
apps/transport/test/support/factory.ex
apps/transport/test/transport/validation_cleaner_test.exs
apps/transport/test/transport_web/controllers/dataset_search_test.exs

Allez, c'est le grand saut, je supprime le champ `modes` de `DB.Resource`. Maintenant toutes les informations concernant les modes sont stockées dans des `ResourceMetadata`.
Pour l'instant je ne fais pas la migration associée, parce que si ça se passe mal je veux pouvoir revenir en arrière facilement.
lié à #2390

Suppression de resource.modes

---

apps/transport/lib/db/resource.ex
apps/transport/lib/transport_web/templates/resource/_resources_details.html.heex
apps/transport/test/db/resource_test.exs
apps/transport/test/transport/validation_cleaner_test.exs
apps/transport/test/transport_web/controllers/dataset_search_test.exs

Celui là je m'attendais à un gros morceau, en fait il était déjà presque plus utilisé :relieved: 
Par contre vu que le mot `features` est utilisé partout, j'ai du tout scanner manuellement pour vérifier qu'on n'utilisait plus ce champ.
lié à #2390

Suppression de resource.features

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/transport/import_data.ex
apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/lib/transport_web/templates/backoffice/page/index.html.heex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po
apps/transport/priv/repo/migrations/20221129131631_dataset_add_archived_at_field.exs

En lien avec https://github.com/etalab/transport-site/issues/2793
- Ajoute un nouveau champ `archived_at` contenant la date d'archivage dans data.gouv.fr
- Ajoute un nouveau filtre dans le backoffice pour identifier les JDD actuellement archivés

Dataset : stockage date d'archivage

---

apps/transport/lib/transport/import_data.ex

Certaines ressources nommées "Documentation NeTEx" avec `type = 'documentation'` ont été mal détectées par le script d'import et se voient attribuées le format `NeTEx`.
Exemple [sur le JDD IDFM](https://transport.data.gouv.fr/datasets/horaires-prevus-sur-les-lignes-de-transport-en-commun-dile-de-france-gtfs-datahub) où on retrouve ces ressources dans la section NeTEx et documentation.

ImportData: ajuste détection pour ressources documentation

---

apps/transport/lib/jobs/resource_unavailable_job.ex
apps/transport/lib/transport/availability_checker.ex
apps/transport/lib/transport/import_data.ex
apps/transport/test/transport/availability_checker_test.exs
apps/transport/test/transport/jobs/resource_unavailable_job_test.exs

Fixes #2818
Pour les ressources SIRI, faire une requête `GET` et autoriser les réponses 2XX ou une 401 car l'authentification est classique.
On pourrait à terme aller plus loin et tester en s'authentifiant, pour le moment on n'a pas ces informations. Ce fix est immédiatement utile pour [les SIRI d'IDFM](https://transport.data.gouv.fr/datasets/horaires-prevus-sur-les-lignes-de-transport-en-commun-dile-de-france-gtfs-datahub#dataset-resources).

Test de disponibilité différencié pour ressources SIRI

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/transport_web/templates/dataset/details.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

Fixes https://github.com/etalab/transport-site/issues/2793
Dernière étape liée à cette issue : afficher une bannière lorsqu'un jeu de donnée a été archivé sur data.gouv.fr. Informe les réutilisateurs que les données peuvent ne pas être fiables et donne une indication claire aux bizdevs.
Répare en même temps le code qui permet d'afficher la bannière indiquant qu'un jeu de données a été supprimé.

Ajout bannière si le jeu de données est archivé

---

apps/transport/lib/jobs/geo_data/bnlc_to_geo_data.ex
apps/transport/lib/transport_web/api/controllers/geo_query_controller.ex
apps/transport/lib/transport_web/controllers/explore_controller.ex
apps/transport/lib/transport_web/templates/explore/explore.html.heex
apps/transport/lib/transport_web/templates/layout/_header.html.heex
apps/transport/priv/gettext/default.pot
apps/transport/priv/gettext/en/LC_MESSAGES/default.po
apps/transport/priv/gettext/fr/LC_MESSAGES/default.po
apps/transport/priv/gettext/fr/LC_MESSAGES/explore.po
apps/transport/test/transport_web/controllers/api/geo_query_controller_test.exs
apps/transport/test/transport_web/controllers/explore_controller_test.exs

J'ai été un peu trop vite dans https://github.com/etalab/transport-site/pull/2723
Je refactor le code pour utiliser `relevant_dataset` dans les jobs de `GeoData` dans `ExploreController` et `GeoQueryController` pour être certain de parler du même jeu de données à chaque endroit.
Je change aussi le titre du menu dans le header.

GeoQueryController : utilise dataset utilisé dans les jobs

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/transport/data_checker.ex
apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/test/transport/data_checker_test.exs

Suite de https://github.com/etalab/transport-site/pull/2797 et #2816
- Envoi un e-mail unique pour JDD supprimés, réapparus et archivés
- Ajout d'un lien vers le backoffice pour les JDD archivés

DataChecker : envoi d'un unique e-mail pour JDD supprimés et archivés

---

apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

Met à jour le code `DatasetController#details` pour gérer un possible changement de slug d'un jeu de données sur data.gouv.fr. Quand ceci survient, d'anciennes URLs du PAN enregistrées précédemment ne sont plus valides (car le slug a changé). De même si le slug change sur data.gouv.fr le nouveau slug ne sera fonctionnel qu'après un import.
Cette PR améliore la situation en mettant à jour le slug à partir de l'API de data.gouv.fr. Le maintien des anciennes URLs est assuré par le fait que l'API de data.gouv.fr redirige lorsqu'on utilise un précédent slug.
Je rajoute des tests pour les cas supportés mais non testés (redirections en utilisant l'identifiant en base de données et le `datagouv_id`).

Dataset#details : gère changement de slug et redirections

---

apps/transport/client/stylesheets/components/_validation.scss
apps/transport/lib/transport_web/templates/resource/_download_availability.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot

Suite à https://github.com/etalab/transport-site/pull/2821, je retravaille les explications des tests de disponibilité pour clarifier le traitement différencié des ressources SIRI.

Améliore les explications des tests de disponibilité

---

apps/transport/lib/transport_web/controllers/validation_controller.ex
apps/transport/lib/transport_web/live/on_demand_validation_select_live.ex
apps/transport/lib/transport_web/live/on_demand_validation_select_live.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/validations.pot
apps/transport/test/transport_web/controllers/validation_controller_test.exs

Adapte la page de validation à la demande pour inclure un texte de présentation pour le NeTEx.

Validation à la demande NeTEx : ajoute texte explicatif

---

apps/transport/lib/transport_web/templates/dataset/details.html.heex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
apps/transport/priv/gettext/page-dataset-details.pot
apps/transport/test/transport_web/controllers/dataset_controller_test.exs
apps/transport/test/transport_web/controllers/dataset_view_test.exs

- Regroupe les GTFS et NeTEx au sein d'une même section "Données théoriques". Les GTFS seront placés avant les NeTEx (et triés par ordre de validité)
- Renomme la section "Ressources temps réel" en "Flux temps réel" (contient GTFS-RT, SIRI, SIRI-Lite)

Dataset#details : regroupe GTFS et NeTEx

---

apps/transport/lib/transport/import_data.ex

Fixes #2835
Ce type n'était pas géré, les autres méthodes sont moins strictes sur les types et ont généralement un "catch-all" renvoyant `false`.

ImportData : gère nil pour is_documentation?

---

apps/transport/lib/transport_web/controllers/backoffice/broken_urls_controller.ex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/backoffice/broken_urls/index.html.heex
apps/transport/lib/transport_web/templates/backoffice/page/index.html.heex
apps/transport/lib/transport_web/views/backoffice/broken_urls_view.ex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po
apps/transport/test/support/factory.ex
apps/transport/test/transport_web/controllers/backoffice/broken_urls_controller_test.exs

Suite à #2827 , je fais une première requête qui détecte quand dans un dataset, une url disparait et une autre apparait simultanément et je met le résultat dans une page du backoffice pour commencer à jouer avec.
Je vais déployer sur prochainement pour voir ce que ça donne.
L'url est `/backoffice/broken-urls`, pour prochainement ce sera [ici](https://prochainement.transport.data.gouv.fr/backoffice/broken-urls).

Page de backoffice pour les URLs cassées

---

apps/transport/lib/transport_web/templates/resource/details.html.heex
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Il n'est pas nécessaire d'afficher un rapport de validation sur `resource#details` pour [une ressource de documentation](https://transport.data.gouv.fr/resources/80098)

Pas de rapport de validation pour type documentation

---

apps/transport/lib/transport_web/views/dataset_view.ex

Utilise une URL plus neutre pour le lien de référence de la licence mobilités

Adaptation URL pour Licence mobilités

---

apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/lib/transport_web/templates/resource/details.html.heex
apps/transport/lib/transport_web/templates/resource/gtfs_details.html.heex
apps/transport/lib/transport_web/views/resource_view.ex
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Fixes #2842, voir détails dans l'issue.
Exemple d'UI avec une description assez longue.

Affichage de la description des ressources

---

apps/transport/lib/jobs/dataset_history_job.ex
apps/transport/priv/repo/migrations/20221208083708_add_indexes_resource.exs
apps/transport/test/transport/jobs/dataset_history_job_test.exs

J'ai mis du temps à comprendre le problème. Ce n'était pas tant une question d'indexation que de left joins à répétition.
Je faisais 4 LEFT joins : 
- dataset <> resources
- resources <> resources_history
- resources <> multi_validation
- resources <> resource_metadata
On se retrouve donc avec un résultat qui a nb_resources * nb_resources_history * nb_validations * nb_metadata
Par exemple pour le dataset 612, on a 3 ressources, 37 resources history, 1458 metadata, 323 multi validations.
Ca commence à faire beaucoup de lignes, puis on fait un distinct final la dessus, mais à ce moment l'indexation des tables ne sert plus à rien. D'ou un gros tri qui prend du temps.
L'idée est donc de preloader une query pour les metadata qui se charge de n'attraper que les metadata les plus récentes. On …

Dataset history : rendre la query plus rapide

---

apps/transport/lib/transport_web/controllers/page_controller.ex

Suite à la demande formulée ici https://github.com/etalab/transport-site/pull/2849#issuecomment-1346296085
> possible que la tuile apparaisse entre "stationnement vélo" et "données routières" ?
cc @Benoit-MINT

Arrange l'ordre tuile comptage des mobilités

---

apps/transport/client/stylesheets/components/_dataset-details.scss
apps/transport/lib/transport_web/templates/dataset/_community_resources.html.heex
apps/transport/lib/transport_web/templates/dataset/_history_message.html.heex
apps/transport/lib/transport_web/templates/dataset/_resources_container.html.heex
apps/transport/lib/transport_web/templates/dataset/_reuser_message.html.heex

Fixes #2585
- Passe le texte "Des versions précédentes des ressources de ce jeu de données sont disponibles dans la section Ressources historisées." de noir à gris
- Sépare les ressources et la partie "inviter à déclarer une réutilisation"/"Ressources communautaires" par une fine bordure (il y avait déjà un tag `hr` mais invisible)
- Passe le titre "Ressources communautaires" en `h2` comme les autres titres

Uniformise les messages d'infos sur la page de JDD

---

apps/transport/lib/transport_web/api/router.ex
apps/transport/lib/transport_web/redirect.ex
apps/transport/lib/transport_web/router.ex

En lien avec https://github.com/etalab/transport-site/issues/1814
Répare ["Missing Anti-clickjacking Header"](https://dashlord.mte.incubateur.net/dashlord/report/aHR0cHM6Ly90cmFuc3BvcnQuZGF0YS5nb3V2LmZy/zap.html#10020). Ce header était présent sur la quasi exclusivité des pages, le Swagger avait un traitement particulier.
Répare au passage https://github.com/etalab/transport-site/issues/1851 en introduisant une redirection sur `/api`.

Ajout de headers de sécurité pour Swagger

---

apps/transport/lib/jobs/geo_data/base.ex

Vu en production sur la BNLC.
```
(ArgumentError) errors were found at the given arguments:
* 1st argument: not a textual representation of a float
:erlang.binary_to_float(\"50.6062355590429\\r\\n\")
```
alors que le fichier est considéré valide par Validata.

BaseGeoData : amélioration du parsing de floats

---

apps/transport/lib/transport_web/templates/resource/_validate_gtfs_rt_now.html.heex

Vu sur le JDD de Lille : 1 GTFS disponible, 1 GTFS indisponible, le bandeau disant qu'on ne peut pas déterminer le GTFS à utiliser est affiché alors que le validateur ne regarde que les ressources disponibles et à jour.

Bouton validation GTFS-RT : conserve uniquement les GTFS disponibles

---

apps/transport/lib/transport_web/plugs/put_locale.ex
apps/transport/lib/transport_web/router.ex
apps/transport/test/transport_web/routing/put_locale_test.exs

Fixes #2240
Utilise le [header HTTP `accept-language`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) en plus des autres paramètres pour déterminer la langue à utiliser.

Meilleure détection préférence de langue

---

apps/transport/lib/db/multi_validation.ex
apps/transport/lib/transport_web/controllers/resource_controller.ex
apps/transport/lib/transport_web/templates/resource/_gtfs_rt_previous_validations_details.html.heex
apps/transport/lib/transport_web/templates/resource/_validation_report.html.heex
apps/transport/lib/transport_web/templates/resource/_validation_report_gtfs_rt.html.heex
apps/transport/lib/transport_web/templates/resource/details.html.heex
apps/transport/lib/transport_web/views/resource_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/validations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations.po
apps/transport/priv/gettext/validations.pot
apps/transport/test/db/multi_validation_test.exs
apps/transport/test/transport_web/controllers/resource_controller_test.exs

Affiche, sur la page de détails d'une ressource GTFS-RT, un récapitulatif des rapports de validation au cours des 30 derniers jours.

GTFS-RT : affiche le détail des erreurs au cours des 30 derniers jours

---

config/runtime.exs

Fixes https://github.com/etalab/transport-site/issues/2075
Ajoute le plugin [Lifeline](https://hexdocs.pm/oban/Oban.Plugins.Lifeline.html) qui permet de remettre des jobs en `available` alors qu'ils sont en `executing` depuis un certain temps.
> The Lifeline plugin periodically rescues orphaned jobs, i.e. jobs that are stuck in the executing state because the node was shut down before the job could finish. Rescuing is purely based on time, rather than any heuristic about the job's expected execution time or whether the node is still alive.

Oban : ajout du plugin Lifeline

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/lib/transport_web/templates/backoffice/page/_dataset.html.heex
apps/transport/lib/transport_web/templates/backoffice/page/index.html.heex
apps/transport/lib/transport_web/views/backoffice/page_view.ex
apps/transport/lib/transport_web/views/dataset_view.ex
apps/transport/test/support/factory.ex
apps/transport/test/transport_web/controllers/backoffice/page_controller_test.exs

Le coquin de `end_date` n'a pas dit son dernier mot, il en reste dans le backoffice dans la colonne "fin de validité" qui est en bonus utilisable pour trier les datasets...
J'en profite pour réparer un bug : certaines pages du backoffice faisaient des 500, par exemple : https://transport.data.gouv.fr/backoffice?dir=asc&order_by=end_date&q=gtfs#backoffice-datasets-table
je rajoute un test sur un des filtres du BO.

Se débarasser du end_date dans le backoffice

---

apps/transport/lib/jobs/dataset_history_job.ex
apps/transport/test/transport/jobs/dataset_history_job_test.exs

ça faisait planter les jobs d'historiser un dataset sans ressource.

Fix : historisation des datasets sans resource

---

apps/transport/lib/jobs/archive_metrics_job.ex
apps/transport/test/transport/jobs/archive_metrics_job_test.exs
config/runtime.exs

Fixes #2877
Ajoute un job quotidien en charge d'archiver les `DB.Metrics` après 90 jours.
On garde une seule ligne par jour, event et target en faisant la somme des événements.

Réduit le nombre de DB.Metrics après 3 mois

---

apps/transport/lib/db/dataset.ex

Répare [cette erreur Sentry](https://sentry.io/organizations/transport-data-gouv-fr/issues/3017325701/?environment=prod&project=6197733&query=is%3Aunresolved&referrer=issue-stream) où il y a surement des personnes qui mettent le query param `modes=` ce qui n'est pas accepté.
Je n'ai pas trouvé comment une utilisation classique arrivait à ces URLs.

Recherche JDD : ajout guard pour modes

---

apps/transport/lib/jobs/archive_metrics_job.ex
apps/transport/test/transport/jobs/archive_metrics_job_test.exs

Suite de https://github.com/etalab/transport-site/pull/2879
Le job de dispatch renvoyait toutes les dates < 3 mois, même si ces enregistrements avaient déjà été passés à la journée au lieu de l'heure.
Cette PR retourne uniquement les dates pertinentes pour éviter de recalculer des choses qui sont déjà archivées (c'était très rapide, mais ça fait quand même [300 jobs par jour](https://transport.data.gouv.fr/backoffice/jobs?worker=ArchiveMetricsJob) inutiles dès à présent)

ArchiveMetricsJob : ne pas recalculer ce qui n'est pas nécessaire

---

config/runtime.exs

Une tentative de résolution du problème que l'on a constaté sur Oban : certains jobs (des Workflow pour le moment) restent en `available`.
Je tente un correctif indiqué dans les issues en attendant la sortie d'un commit.

Oban: TCP keepalive

---

apps/transport/lib/transport/data_checker.ex
apps/transport/test/transport/data_checker_test.exs

Lié à #2887
Ajout de logging pour essayer de déterminer la cause du problème. Je n'ai rien trouvé en lisant le code ou en l'exécutant en local plusieurs fois, mon hypothèse est donc un problème temporaire de l'API data.gouv.fr.

DataChecker - état d'un JDD : ajout de logging Sentry

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/db/resource.ex
apps/transport/lib/jobs/resource_history_job.ex
apps/transport/lib/transport/import_data.ex
apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
apps/transport/lib/transport_web/api/schemas.ex
apps/transport/test/transport/jobs/resource_history_job_test.exs
apps/transport/test/transport_web/controllers/api/datasets_controller_test.exs

Cette information est maintenant stockée au niveau des ressources history. Historiquement on se servait de ce champ pour décider si on validait (V1) une ressource lors de l'import.
La bonne nouvelle, c'est que ça va grandement accélérer les imports, car on téléchargeait systématiquement la ressource lors de l'import pour calculer son hash. Ce n'est plus nécessaire.

Suppression du champ content_hash de la ressource

---

apps/transport/lib/transport_web/live/gtfs_diff_select_live.ex

Bug remonté par Tu-Tho Thai lors de l'utilisation du GTFS Diff.
Assez marrant l'erreur arrivait parce que la liveview attrapait un message venant d'un autre process (d'historisation des ressources) et que cela faisait planter la liveview. Tu-Tho a dû faire son test quand des taches d'historisations étaient en train d'être traitées par le worker !
L'erreur [Sentry](https://sentry.io/organizations/transport-data-gouv-fr/issues/3850504329/?project=6197733&query=is%3Aunresolved+gtfs_diff&referrer=issue-stream&statsPeriod=14d)

Fix Gtfs Diff

---

apps/transport/lib/transport_web/templates/resource/_missing_id_issue.html.heex
apps/transport/lib/transport_web/templates/resource/_missing_name_issue.html.heex
apps/transport/lib/transport_web/views/resource_view.ex
apps/transport/priv/gettext/en/LC_MESSAGES/validations-explanations.po
apps/transport/priv/gettext/fr/LC_MESSAGES/validations-explanations.po
apps/transport/priv/gettext/validations-explanations.pot

Fixes #2905
Améliore le rendu de validation pour 2 types d'errreurs : `MissingId` et `MissingName`. Auparavant le template utilisé était le template générique, qui donne peu d'informations.
Le validateur donne assez peu de détails pour donner de meilleurs indications (pas de nom de fichier ou de ligne dans le fichier)
```json
{
"severity":"Error",
"object_id":"",
"issue_type":"MissingId",
"object_name":"",
"object_type":"Agency",
"related_objects":[]
}
```
On pourrait envisager l'ajout du numéro de ligne pour `MissingId`, une prochaine fois ? :wink: La structure n'existe pas dans le validateur.

Validation GTFS : ajout nouveaux templates d'erreurs

---

apps/transport/lib/db/dataset_history.ex
apps/transport/lib/transport_web/controllers/dataset_controller.ex
apps/transport/priv/repo/migrations/20230111115335_add_index_dataset_history_slug.exs
apps/transport/test/db/dataset_history_test.exs
apps/transport/test/transport_web/controllers/dataset_controller_test.exs

En lien avec #2913 et suite de https://github.com/etalab/transport-site/pull/2826#pullrequestreview-1202574142, @fchabouis tu l'avais bien dit.
> Peut-être que prochainement on pourra aller chercher ce slug nous même pour éviter l'appel à data.gouv, mais c'est déjà beaucoup mieux comme ça 🙏
Utilise `DB.DatasetHistory` pour tenter de trouver le dataset actuel pour un ancien slug, si jamais on ne trouve pas un dataset immédiatement (par slug, datagouv_id ou id).
On garde le fallback à l'API de data.gouv.fr en dernier recours.

Dataset#details : utilise DatasetHistory pour rediriger depuis un ancien slug

---

apps/datagouvfr/lib/datagouvfr/client/api.ex
apps/datagouvfr/test/datagouvfr/client/api_test.exs
apps/transport/lib/transport/data_checker.ex
apps/transport/test/transport/data_checker_test.exs

Fixes #2887
Cette issue avait été fermée mais le problème est de retour, mais avec des logs cette fois https://github.com/etalab/transport-site/issues/2887#issuecomment-1378364617
Cette PR :
- permet de réessayer jusqu'à 3 fois les requêtes vers l'API data.gouv.fr en cas de timeout
- ajoute un mécanisme de sécurité empêchant de désactiver plus de 10% des JDD d'un coup (en cas de grosse panique côté API datagouv)
J'ai partagé ce problème récent [avec l'équipe datagouv](https://mattermost.incubateur.net/betagouv/pl/jkshojrwnjya7y8exampdj5aiy)

API data.gouv.fr : retry en cas de timeout

---

apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/layout/_footer.html.heex
apps/transport/priv/gettext/default.pot
apps/transport/priv/gettext/en/LC_MESSAGES/default.po
apps/transport/priv/gettext/fr/LC_MESSAGES/default.po
apps/transport/test/transport_web/controllers/page_controller_test.exs

Lien vers la page de budget dans le footer.
La PR sur beta.gouv.fr a déjà été faites https://github.com/betagouv/beta.gouv.fr/pull/12885
Je fais une page `/budget`, commune à pas mal de produits beta.gouv.fr, qui redirige.

Ajout page budget dans footer

---

apps/transport/lib/jobs/multi_validation_with_error_notification_job.ex
apps/transport/test/transport/jobs/multi_validation_with_error_notification_job_test.exs

Corrige le travail effectué dans https://github.com/etalab/transport-site/pull/2909, lié à https://github.com/etalab/transport-site/issues/2903
En réalité dans `multi_validation` seule la colonne `resource_history_id` est renseignée quand une validation est effectuée sur une historisation, et non la colonne `resource_id` (utilisée elle pour une validation temps réel).
Mon code et mes tests ne représentaient pas la réalité, ce qui a causé des erreurs [en prod](https://transport.data.gouv.fr/backoffice/jobs?worker=notifi) (voir jobs `discarded`).
```
(KeyError) key :dataset not found in: nil. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
(transport 0.0.1) lib/jobs/multi_validation_with_error_notification_job.ex:93: anonymous fn/1 in …
```

MultiValidationWithErrorNotificationJob : utilise resource_history

---

apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.heex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po
apps/transport/test/transport_web/controllers/backoffice/page_controller_test.exs

Suite au travail récent d'enregistrement des notifications envoyées en base de données, affiche cette information dans le backoffice, lors de l'édition d'un jeu de données.
J'ai corrigé la mauvaise traduction visible dans https://github.com/etalab/transport-site/pull/2936/commits/439b154964ef2e766b42acab6ea900deba6d2741

Backoffice : affichage des notifications envoyées

---

apps/transport/lib/db/dataset.ex
apps/transport/test/transport_web/controllers/dataset_search_test.exs

Fixes #2938
Si on cherche des jeux de données pour une région (`/datasets/region/:id`), mettre en premiers résultats les jeux de données associés à la région, puis les autres.

Améliore ordre des datasets lors d'une recherche par région

---

apps/transport/lib/db/notification.ex
apps/transport/lib/jobs/dataset_now_licence_ouverte_job.ex
apps/transport/lib/jobs/multi_validation_with_error_notification_job.ex
apps/transport/lib/jobs/new_dataset_notifications_job.ex
apps/transport/lib/jobs/resource_unavailable_notification_job.ex
apps/transport/lib/transport/data_checker.ex

Un peu de refactor pour éviter d'avoir du `DB.Notification.changeset` partout.

Ajout méthode insert! pour DB.Notification

---

apps/transport/client/javascripts/explore.js
apps/transport/client/stylesheets/components/_explore.scss
apps/transport/lib/transport_web/api/controllers/geo_query_controller.ex
apps/transport/lib/transport_web/controllers/explore_controller.ex
apps/transport/lib/transport_web/templates/explore/explore.html.heex
apps/transport/priv/gettext/en/LC_MESSAGES/explore.po
apps/transport/priv/gettext/explore.pot
apps/transport/priv/gettext/fr/LC_MESSAGES/explore.po
apps/transport/test/transport_web/controllers/api/geo_query_controller_test.exs
apps/transport/test/transport_web/controllers/explore_controller_test.exs

Suite de https://github.com/etalab/transport-site/pull/2943
Je récupère les données dans `geo_query` et j'affiche ceci sur la carte d'exploration.

Affichage des aires des ZFE sur la carte d'exploration

---

apps/transport/lib/validators/jsonschema_validata_json_validator.ex
apps/transport/test/transport/validators/jsonschema_validata_json_test.exs

on stockait pour l'instant des rapports de validation en text (la sortie par défaut), je passe en json.

Validateur JSON schema validata : json output

---

apps/transport/lib/transport/data_checker.ex

Voir:
- #2947 
Ce test échouait sur toutes les PR ce matin, alors j'ai été voir. 
Il s'agissait au final d'une question d'ordre des requêtes HTTP reçues par les mocks.
Je stabilise l'ordre avec un tri, à voir si ça ne pose pas de problème "métier" ?

Correctif test fragile bien embêtant

---

apps/transport/client/stylesheets/components/_notification.scss
apps/transport/lib/db/breaking_news.ex
apps/transport/lib/transport_web/controllers/page_controller.ex
apps/transport/lib/transport_web/templates/backoffice/breaking_news/index.html.heex
apps/transport/lib/transport_web/templates/layout/_breaking_news.html.heex
apps/transport/lib/transport_web/templates/layout/app.html.heex
apps/transport/lib/transport_web/views/layout_view.ex
apps/transport/test/transport_web/controllers/breaking_news_controller_test.exs

Ajoute la possibilité d'utiliser du Markdown lors de la rédaction de breaking news, et uniquement pour ça.
Utile pour @etalab/transport-bizdev prochainement, avec la mise en ligne du sondage à destination des utilisateurs où indiquer un lien sera très utile.

Possibilité d'utiliser du Markdown pour les breaking news

---

apps/transport/lib/transport/companies.ex
apps/transport/mix.exs
apps/transport/test/transport/companies_test.exs
mix.lock

Je prépare un client HTTP pour rechercher des entreprises en utilisant SIREN ou SIRET, utile plus tard pour les changements à venir sur le backoffice.

Ajout client HTTP pour API Recherche d'Entreprises

---

apps/transport/lib/db/notification.ex
apps/transport/priv/repo/migrations/20230124110826_notification_change_dataset_on_delete_behavior.exs
apps/transport/priv/repo/migrations/20230124110826_notifications_change_dataset_on_delete_behavior.exs
apps/transport/priv/repo/migrations/20230125145703_notifications_add_dataset_datagouv_id.exs
apps/transport/test/db/notification_test.exs
apps/transport/test/support/factory.ex
apps/transport/test/transport/jobs/multi_validation_with_error_notification_job_test.exs
apps/transport/test/transport/jobs/resource_unavailable_notification_job_test.exs
apps/transport/test/transport_web/controllers/backoffice/page_controller_test.exs

Voir [sur Sentry](https://sentry.io/organizations/transport-data-gouv-fr/issues/3893732231/?environment=prod&project=6197733&referrer=issue-stream), fixes #2950 
Avec la structure de base de données actuelle, il n'est pas possible de supprimer un jeu de données si des notifications sont liées à celui-ci.
Cette PR fait en sorte que la ligne soit conservée (pour des besoins statistiques), mais le `dataset_id` passera à `null`.
Comme suggéré par @fchabouis, j'ajoute une colonne supplémentaire dans les notifications `dataset_datagouv_id` pour garder une trace en cas de suppression du dataset

Migration on delete pour notifications.dataset_id

---

docs/scaleway/bucket_lifecycle_configuration_production.json
docs/scaleway/bucket_lifecycle_configuration_staging.json

Corrige la configuration de bucket lifecycle pour les buckets chez Scaleway.
De manière étrange, seul le bucket de staging avait une mauvaise configuration appliquée, le bucket de prod avait bien la configuration sans préfixe. La conf avec `"prefix": "*"` ne fonctionne pas car elle ne prend en compte que les objets/dossiers qui commencent par `*` et non `*` en tant que glob.
J'ai remplacé la configuration avec
```
aws --endpoint-url "https://s3.fr-par.scw.cloud" --region fr-par s3api put-bucket-lifecycle-configuration --lifecycle-configuration file://policy.json --bucket transport-staging-backups
```
et vérifié la bonne prise en compte en CLI + UI.
```
$ aws --endpoint-url "https://s3.fr-par.scw.cloud" --region fr-par s3api get-bucket-lifecycle-configuration --bucket …
```

Scaleway : correction configuration bucket lifecycle

---

Dockerfile

En cherchant à aller vérifier un point pour:
- #2028 
j'ai eu besoin d'aller vérifier l'état en direct (en tout cas je me suis posé la question), ce que je ne pouvais pas faire tant que :
- #1384 
n'était pas traité.
J'ai pas mal fouillé et simplifié le problème, et noté tout ce que j'ai appris.
Au final: l'ironie est que la capacité était déjà là (via un cookie par défaut, cohérent entre iex et phoenix), mais qu'on n'avait pas compris que c'était le cas.
Je peux aujourd'hui lire les clés Cachex en direct sur prochainement:
```
❯ clever ssh --alias staging-site
Erlang/OTP 24 [erts-12.3.2.6] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [jit]
iex(node@XYZ)2> Cachex.keys(:transport)
{:ok, ["home-index-stats"]}
```
À discuter avec @fchabouis demain avant un déploiement en …

Capacité à se connecter à l'instance Elixir en cours d'exécution

---

apps/transport/lib/db/dataset.ex
apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.heex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po
apps/transport/test/db/db_dataset_test.exs

closes https://github.com/etalab/transport-site/issues/2912
Permet de se rendre compte si une ressource n'est pas historisée depuis longtemps, ou si elle n'a jamais été historisée.

Ajout d'informations sur l'historisation dans le BO

---

apps/datagouvfr/lib/datagouvfr/client/datasets.ex
apps/transport/client/stylesheets/components/_backoffice.scss
apps/transport/lib/db/dataset.ex
apps/transport/lib/transport_web/live/backoffice/edit_dataset_live.ex
apps/transport/priv/gettext/backoffice.pot
apps/transport/priv/gettext/db-dataset.pot
apps/transport/priv/gettext/en/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/en/LC_MESSAGES/db-dataset.po
apps/transport/priv/gettext/fr/LC_MESSAGES/backoffice.po
apps/transport/priv/gettext/fr/LC_MESSAGES/db-dataset.po
apps/transport/priv/repo/migrations/20230202090645_add_dataset_organization_type.exs
apps/transport/test/db/db_dataset_test.exs
apps/transport/test/transport_web/controllers/backoffice/dataset_controller_test.exs
apps/transport/test/transport_web/live_views/edit_dataset_live_test.exs

Après discussion avec les bizdevs, ce champ va être rempli dataset par dataset, il n'y a pas de notion d'organisation qui aurait toujours le même type pour tout les datasets (on n'était pas sûr que cette hypothèse soit toujours vraie). Techniquement c'est donc plus simple, il suffit de rajouter un champ dans la table `dataset`.
Je n'ai pas mis de restrictions sur les valeurs du champ en base, juste de le changeset, car ça va forcément bouger.

Backoffice : Ajout du champ "type d'organisation"

---

apps/transport/lib/transport_web/controllers/page_controller.ex
apps/transport/test/transport_web/controllers/page_controller_test.exs

Fixes #2967
On avait une erreur 500 sur l'espace producteur quand une erreur survenait lors d'une tentative de récupération de jeux de données depuis data.gouv.fr.
```
FunctionClauseError Sentry.Event.transform_exception/2
```
on passait en fait un tuple `{:error, _}` ce qui ne correspond à ce qu'attend Sentry.
Cette PR répare ce bug, on pourra au moins savoir quel était le problème. Étant donné que le problème a été reporté par la métropole de Lyon, je dirais que l'erreur originale est un timeout de l'API qui ne retourne pas tous les nombreux jeux de données en moins de 5s. On verra !
Testé aussi en local en me mettant un mauvais token OAuth

Espace producteur : répare erreur 500 lors d'une exception

---

apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex

Améliore ce qui a été fait dans https://github.com/etalab/transport-site/pull/2936.
Les notifications envoyées n'étaient pas triées dans l'ordre "descendant", ce qui peut donner induire en erreur.
Voir par exemple en prod [sur cette page](https://transport.data.gouv.fr/backoffice/datasets/146/edit).

Backoffice : tri des notifications envoyées

---

scripts/siri/siri_check.exs

Pour tester un flux en dehors du requêteur (qui passe par le serveur et peut donc être soumis à restriction IP sans qu'on le voit), j'ai réparé le script de requête.

Réparation check SIRI

---

apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/test/transport_web/controllers/backoffice/page_controller_test.exs

Retour de https://github.com/etalab/transport-site/pull/2979.
`Enum.group_by` ne conserve pas l'ordre de tri https://github.com/etalab/transport-site/pull/2979#issuecomment-1438606971, je fais donc un truc plus sérieux et j'ajoute un test pour me (et vous) prouver que c'est correct !

Fix tri des notifications envoyées dans backoffice

---

apps/shared/lib/schemas.ex
apps/shared/test/fixtures/schemas.json

Fixes #2985
Ignore les datapackages qui sont présents sur [`schemas.json`](https://schema.data.gouv.fr/schemas.json). Ce ne sont pas de "vrais" schémas et en conséquence ils sont affichés sur des pages comme `/validation`, ce qui n'est pas un comportement souhaité.
Si on souhaite les utiliser directement plus tard on pourra voir pour ne pas les exclure aussi "haut" dans les traitements.

Schemas : ignore les datapackage

---

apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/test/transport_web/controllers/backoffice/page_controller_test.exs

Suite de #2984, c'est un running gag, j'ai honte.
J'avais mis [dans l'ordre `:asc`](https://github.com/etalab/transport-site/pull/2984/files#diff-3e31a2789fd376e9999ec27f69a3952a19c1a5825f21c93c639d714392e38f69R199) et on veut l'inverse.
Bref !

Tri ordre *descendant* des notifications

---

.dialyzer_ignore.exs
apps/transport/client/stylesheets/main.scss
apps/transport/lib/db/contact.ex
apps/transport/lib/db/dataset.ex
apps/transport/lib/db/notification.ex
apps/transport/lib/db/notification_subscription.ex
apps/transport/lib/transport_web/controllers/backoffice/contact_controller.ex
apps/transport/lib/transport_web/controllers/backoffice/notification_subscription_controller.ex
apps/transport/lib/transport_web/controllers/backoffice/page_controller.ex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/backoffice/contact/_notification_subscriptions.html.heex
apps/transport/lib/transport_web/templates/backoffice/contact/form.html.heex
apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.heex
apps/transport/lib/transport_web/views/backoffice/contact_view.ex
apps/transport/lib/transport_web/views/backoffice/page_view.ex
apps/transport/priv/repo/migrations/20230220102200_add_notification_subscription.exs
apps/transport/test/support/factory.ex
apps/transport/test/transport_web/controllers/backoffice/contact_controller_test.exs
apps/transport/test/transport_web/controllers/backoffice/notification_subscription_controller_test.exs

Suite de https://github.com/etalab/transport-site/pull/2965
Cette PR (un peu grosse, désolé 🙈) ajoute la possibilité d'inscrire des contacts à des motifs de notifications depuis le backoffice.
Ce qui est inclut :
- ajout de la table et du modèle `notification_subscriptions`
- ajout de `TransportWeb.Backoffice.NotificationSubscriptionController` qui gère la création et la suppression d'abonnements à des notifications
- mise à jour de `dataset#edit` et `contact#edit` pour créer et supprimer des abonnements aux notifications en prenant comme référence un JDD ou un contact
- mise à jour du code existant pour charger les abonnements aux notifications dans les situations pertinentes
Le code HEEX est assez lourd car il y a des tableaux à générer, avec les bons boutons pour avoir des actions de …

Ajout d'abonnements à des notifications

---

apps/transport/client/stylesheets/home.scss
apps/transport/lib/transport_web/controllers/page_controller.ex
apps/transport/lib/transport_web/router.ex
apps/transport/lib/transport_web/templates/layout/_header.html.heex
apps/transport/lib/transport_web/templates/page/index.html.heex
apps/transport/lib/transport_web/templates/page/missions.html.md
apps/transport/lib/transport_web/templates/stats/index.html.heex
apps/transport/priv/gettext/default.pot
apps/transport/priv/gettext/en/LC_MESSAGES/default.po
apps/transport/priv/gettext/en/LC_MESSAGES/page-index.po
apps/transport/priv/gettext/fr/LC_MESSAGES/default.po
apps/transport/priv/gettext/fr/LC_MESSAGES/page-index.po
apps/transport/priv/gettext/page-index.pot
apps/transport/test/transport_web/controllers/page_controller_test.exs

Reprise de la [Fiche produit du PAN](https://docs.google.com/document/d/1Iw1HsnVBjbQmYOvifnL63ydy4nK5nBF9khh7HvWwb_o/edit) écrite par @Benoit-MINT pour valoriser les missions menées par le PAN.
La page est en Markdown dans le code, elle reste donc facilement modifiable.

Ajout d'une page décrivant les missions du PAN
